### ISSUE TITLE
Revisión documentación Argo v1 - Primera etapa

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#1]
Se requiere realizar la revisión de la documentación disponible del sistema Argo v1, para comprender el funcionamiento y los diferentes roles y módulos que tiene el sistema actual.

**Sub Tareas**

- [x] Revisión manual de usuario [MANUAL DE USUARIO DE GESTIÓN DEL SISTEMA DE GESTIÓN CONTRACTUAL - ARGO](https://ti.udistrital.edu.co/sites/default/files/documentacion/2021-02/INS%20SISTEMA%20ARGO.pdf
- [x] Identificar los módulos y roles involucrados en el actual sistema.

**Criterios de aceptación**

- [x] Listar los roles y módulos del sistema Argo v1

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Comentario en el issue con la lista de módulos y roles identificados en la revisión de la documentación.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Sistema ARGO

1. **Módulo de Gestión de Compras**

A este módulo sólo tienen permiso de acceso las personas autorizadas de la Sección de Compras. En dónde podrán:

- Registrar una orden

Se registra una nueva orden, ya sea de compra o de servicios, llenando un formulario con información muy especifica del contrato, solicitante y supervisor, contratista, presupuesto, objetivo y justificación del contrato, entre otros.

- Consultar y modificar una orden

Después de un filtro de búsqueda se pueden consultar, modificar o eliminar elementos o servicios de una orden NO suscrita, así como descargar documento de la orden en formato PDF y suscribir una o varias ordenes deseadas a la vez. 

- Registrar elementos y servicios en una orden

Después de un filtro de búsqueda se pueden cargar elementos y servicios que se deseen agregar a la orden seleccionada llenando un formulario, y ya sea de manera individual por medio de un formulario de la página, o de manera masiva por medio de un formato Excel suministrado por la misma, se cargan los elementos y/o servicios deseados.

- Gestión de contratos de orden de compra y servicios suscritos

Después de un filtro de búsqueda se podrán ver las ordenes previamente suscritas pero que todavía no se encuentran en ejecución por no poseer acta de inicio, y se podrán realizar las acciones de consultar su información, descargar documento de la orden en formato PDF, registrar Acta de inicio, registrar RP y CDP, y por último cancelar el contrato.

- Consultar contratos por vigencia

Después de un filtro de búsqueda que exige la vigencia y el estado de los contratos a buscar, se mostrará la lista de estos y se podrá consultar la información de la orden y descargar documento de la orden en formato PDF.


2. **Módulo de Gestión Contractual**

A este módulo sólo tienen permiso de acceso las personas autorizadas de la Oficina Asesora Jurídica y el IDEXUD. En dónde podrán:

- Registrar un contrato

Se registra un nuevo contrato llenando un formulario con información muy especifica del tipo de compromiso, tipo de contrato, garantías, solicitante y supervisor, contratista, presupuesto, objetivo y justificación del contrato, entre otros.

- Actualizar un contrato

Después de un filtro de búsqueda se pueden consultar, actualizar datos de un contrato NO suscrito, así como descargar documento del contrato en formato PDF, suscribir uno o varios contratos deseadas a la vez y modificar o eliminar elementos pertenecientes al contrato.

- Registrar elementos a un contrato

Después de un filtro de búsqueda se pueden cargar elementos y servicios que se deseen agregar a la orden seleccionada llenando un formulario, y ya sea de manera individual por medio de un formulario de la página, o de manera masiva por medio de un formato Excel suministrado por la misma, se cargan los elementos y/o servicios deseados.

- Gestión de contratos suscritos

Después de un filtro de búsqueda se podrán ver los contratos previamente suscritos pero que todavía no se encuentran en ejecución por no poseer acta de inicio, y se podrán realizar las acciones de consultar su información, descargar documento de la orden en formato PDF, registrar Acta de inicio, registrar RP y CDP, y por último cancelar el contrato.

- Consultar contratos por vigencia

Después de un filtro de búsqueda que exige la vigencia y el estado de los contratos a buscar, se mostrará la lista de estos y se podrá consultar la información del contrato y descargar documento del contrato en formato PDF.

- Gestión modificaciones a contratos suscritos 

Después de un filtro de búsqueda se mostrará la lista con los contratos en dónde se podrá consultar la información del contrato y modificar su información solo bajo una justificación.


3. **Módulo de Gestión de pólizas**

A este módulo sólo tienen permiso de acceso las personas autorizadas de la Sección de Compras, la Oficina Asesora Jurídica y el IDEXUD. En dónde podrán:

- Gestión de pólizas a contratos suscritos

Después de un filtro de búsqueda se mostrará un listado con los contratos y/o ordenes NO suscritas solicitadas y se podrá consultar su información, registrar, modificar, cambiar estado  y gestión de amparos de la póliza, y descargar documento de la orden o contrato en formato PDF.

4. **Módulo de reportes**

A este módulo sólo tienen permiso de acceso las personas autorizadas de la Sección de Compras, la Oficina Asesora Jurídica y el IDEXUD. En dónde podrán:

Todos los reportes se podrán exportar en el formato seleccionado (XLS, XLSX o PDF) después de definir ciertos parámetros de visualización esenciales para su creación.

- Reporte de contratistas (presupuesto)
- Reporte de contratos cancelados
- Reporte general de contratos dinámico
- Reporte general de contratos estático 
- Reporte contractual
- Reporte contratistas
- Reporte interventoría
- Reporte localización
- Reporte de supervisores
