### ISSUE TITLE
Construir diagrama de flujo módulo gestión compras y gestión novedades según requerimientos del cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#10]
Se requiere realizar el 

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buenas tardes,

Se desarrolla un diagrama de flujo inicial de los procesos de registro de contrato y registro de pólizas en los módulos Gestión Contractual y Gestión de Pólizas respectivamente en el sistema actual de Argo.

**Flujograma de proceso registro de contrato en Argo V1 modulo Gestión Contractual**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/18691b06-a680-49cf-be21-4b466e211ddc)


**Flujograma de proceso registro de pólizas en Argo V1 modulo Gestión de Pólizas** 
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/1b81c5b5-6942-4b09-98dd-c45e47ee2d2a)

**Link OneDrive flujograma módulos (Gestión Contractual y Gestión de Pólizas)**
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EbB2eQKWw2xArqd_-novOOMBMycTvYzelsXrY1ckXNuaig?e=UFxz8L

Cordial saludo.

**Comment by jcmurilloa** [comment]
Hola Carlos Julian, te agradezco agregar estas evidencias en el issue correspondiente, que es el relacionado con la gestión contractual y de pólizas.

**Comment by cjgonzalezp** [comment]
Buenos días Julián,

Pido disculpas se me cruzo la información de la issue, te informo que el desarrollo de la actividad fue cargada nuevamente en la issue correspondiente #7 para tu revisión.

Saludos.

**Comment by cjgonzalezp** [comment]
Buenos días,

1. Se desarrolla investigación sobre los diferentes flujogramas de procesos desarrollados para el módulo de novedades los cuales relaciono a continuación:

**Flujograma Novedad de Reinicio**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/020c1643-5b20-46be-9e21-30c43f49aa32)

**Flujograma Novedad de Terminación Anticipada**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/8252cbe2-84ee-4ebc-a95d-36abd5c3c7bc)

**Flujograma Novedad Adición y Prorroga**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/71001c1d-4bd6-4a23-9f45-357f55906815)

**Flujograma Novedad de Cesión**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/d884216c-7c17-490b-a1a8-63e30216657c)

**Flujograma Novedad de Suspensión** 
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/f468d28b-ae9c-4229-992e-71ec21ca38ea)

Relaciono link donde se encuentran los anteriores flujogramas del módulo novedades en OneDrive:
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Es-0eLqD90RBmDJiDVo47twBvms7f6N2wfUxuT8_RAv4Gg?e=78ZtsW


2. El Diagrama para el módulo de gestión de compra se completará el día miércoles 15 de mayo posterior a capacitación del módulo el día 14 de mayo

Saludos.

**Comment by jcmurilloa** [comment]
Perfecto Carlos Julian, pendiente la realización del flujo de gestión de compras, según los requerimientos levantados en la sesión del 14 de mayo.

**Comment by cjgonzalezp** [comment]
Buen día,

De acuerdo con la capacitación de ARGO desarrollada el día 15 de mayo se elabora diagrama de flujo del módulo de gestión de compras y teniendo en cuenta los requerimientos del cliente

Diagrama de flujo Proceso Registro Órdenes de Compra y Servicios Modulo Gestión de Compras ARGO V2
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/921a3db2-75d0-4368-9140-20b7db6ff141)

Adjunto link donde se encuentra guardado el archivo en OneDrive del proyecto correspondiente
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsTyLCE3MAJGiEluHJ1P5hcB7WXrIE7oOmrf6vBRsR_wVA?e=ImDSCA


Cordial saludo.

**Comment by jcmurilloa** [comment]
Muy buen trabajo Carlos Julian!
