### ISSUE TITLE
Ajuste modelo de datos de Gestión contractual - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#100]
Se requiere realizar los ajustes que surgieron de la Issue #93.

- Ajustes en contrato_arrendamiento
> - cambiar _plaza_administracion_ por _plazo_administracion_
- Ajustes en estado_contrato
>- Remover campo vigencia
>- Remover campo numero_contrato
>- Ajustar nombre campo de referencia de _contrato_general_ 
>- usuario_id cambiar tipo string a number 
- Ajustes en convenio
>- Ajustar nombre campo de referencia de _contrato_general_
>- Ajuste en el campo de nombre_convenio por solo nombre y cambiar tipo.
- Ajustes en contratista
>- Ajustar nombre campo de referencia de _contrato_general_ 
- Ajustes en cdp
>- Ajustar nombre campo de referencia de _contrato_general_
- Ajustes en clausula y paragrafo
>- Ajustar tipo de dato del campo _descripcion_ 
- Ajustes en estado_contrato o contrato_general
>- Campo de numero de contrato o consecutivo necesario para contrato suscrito y contrato cancelado. 

Ajuste tipo de datos de campos paramétricos de:
![image](https://github.com/user-attachments/assets/9bcf6c8b-638e-4789-8d36-46167438ad71)
![image](https://github.com/user-attachments/assets/fd58c0ed-68a6-47e0-b103-bad24635249d)
![image](https://github.com/user-attachments/assets/ca866c4e-e74d-4e9a-b94b-f6924a89a221)
![image](https://github.com/user-attachments/assets/069a2cfb-2816-4b73-82fc-823ffad4123c)

Agregar por favor, las notas para los campos o colecciones cuya información viene de un sistema externo, por ejemplo, los datos del contratista vienen de Ágora, los de presupuesto (cdp) de Sicapital.

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
- Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
WIP



![Image](https://github.com/user-attachments/assets/ff35226f-6cd1-4d3c-8f59-eeab1547bbe3)



TODO: Ajuste tipo de datos de campos paramétricos.

**Comment by mau-oati** [comment]
Existen dudas con los campos paramétricos, debido a que la database original se guardan como strings, se esperaría guardar como numbers, sin embargo muchos enpoints actuales retornan información de id de parámetros como strings y esperan como params también un string. Por esta razón, no es claro si debemos seguir los. lineamientos actuales de string o mover todo hacia number.

**Comment by edwargl7** [comment]
Se debe confirmar si el id de unidad ejecutora en la migración al ERP cambia a numérico o seguirá usando "01" y "02". Y los demás campos que en la migración al nuevo ARGO cambian las referencias a la fuente de datos

**Comment by edwargl7** [comment]
Se presenta el modelo de datos actualizado y cubriendo las observaciones dadas por DBA en un anterior revisión, pendiente la revisión del mapeo de los campos comentados por @mau-oati . Buen trabajo.
