### ISSUE TITLE
Implementación microcliente gestión de Póliza - Registro

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#101]
Se requiere realizar la implementación del módulo de registro de pólizas asociado a un contrato siguiendo el [Mockup Registrar Póliza](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EX8eWggXnGBFqimRBTnrQ5cBXaFZjEEoBCMCDurv6bd2Gw?e=xqmBK3)

**Sub Tareas**

- [x] Implementación formulario de registro de póliza.

**Criterios de aceptación**

- [x] Documentación de la visualización correcta de la vista de registro de pólizas.

**Requerimientos**

No aplica

**Material de apoyo**
- Vista del registro de Póliza.
![image](https://github.com/user-attachments/assets/60f9c733-234f-411b-8fa3-ccc06634f66f)
![image](https://github.com/user-attachments/assets/7e41971a-b735-4287-abd9-95d0402af1bd)

**Especificaciones técnicas**
1. Repositorio microcliente [poliza_mf](https://github.com/udistrital/poliza_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- Arquitectura de aplicaciones - Microclientes (https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se construye la base incial y el formulario básico para el registro de pólizas.
Se requiere revisar más adelante: validaciones de negocio e integrar con parámetros y api mids para obtener la información correcta.




https://github.com/user-attachments/assets/164858db-e0f4-4698-9d82-d20d05434084

**Comment by edwargl7** [comment]
Cuenta con el estilo adicional en la agrupación de cada sección del formulario y la documentación del README del repositorio. Bien documentada la Issue. Se resuelve el PR. Muy buen trabajo.

**Observaciones**
- Revisar columnas (valor, fecha inicial y fecha final) en la sección de amparos. 
- Remover archivo _.editorconfig_.
- Ajuste para permitir decimales en el campo de suficiencia de los amparos.
