### ISSUE TITLE
Implementación microcliente gestión de Actas de inicio - Registro

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#102]
Se requiere realizar la implementación del módulo de registro de actas de inicio asociado a un contrato siguiendo el [Mockup Registrar Actas de Inicio](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EVM7vgBYKTtGpdkdjTIs5wwBbPokc3naNoOWYpUdfYgk-A?e=d0cd4I)

**Sub Tareas**

- [x] Implementación formulario de registro de acta de inicio.

**Criterios de aceptación**

- [x] Documentación de la visualización correcta de la vista de registro de actas.

**Requerimientos**

No aplica

**Material de apoyo**
- Vista módulo registro de Acta de Inicio
![image](https://github.com/user-attachments/assets/814a1fbf-9b66-407a-b56f-832de6230c2b)

**Especificaciones técnicas**
1. Repositorio microcliente [acta_inicio_mf](https://github.com/udistrital/acta_inicio_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- Arquitectura de aplicaciones - Microclientes (https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Se realizó el commit inicial con toda la creación de la estructura del microcliente siguiendo los lineamientos respectivos.

**Comment by Lau2ri** [comment]
Queda lista la vista del modulo de **_Registrar actas de inicio_**.

https://github.com/user-attachments/assets/58b486e9-6203-4701-9440-ade99f5d3976

![Image](https://github.com/user-attachments/assets/a22d5902-cbe5-43b6-8740-a19e943fa37d)

**Comment by edwargl7** [comment]
Buen trabajo, puedes realizar los PR del root y mf de actas por favor @Lau2ri .

Pendiente revisar con @cjgonzalezp los campos requeridos para este formulario.

**Comment by edwargl7** [comment]
Se revisa el código y se resuelven los PR. Se recomienda remover archivo .editorconfig.
