### ISSUE TITLE
Implementación vista de Consulta de contratos microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#103]
Se requiere realizar la implementación del módulo de la vista de consulta del microcliente de gestión contractual basado en el [Mockup Consultar Contrato](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EYWnZavErKtDjy0JAgMeW30BYKpX2xs-kAAy2qMVidD6Pw?e=etKGG1). 
Se debe implementar gráficamente el panel de búsqueda.

![image](https://github.com/user-attachments/assets/f26bf436-e29c-4330-91b5-78b47ac4f709)

**Sub Tareas**

- [x] Implementación campos de búsqueda basado en el Mockup.
- [x] Integración campo _Vigencia_.
- [x] Registro tipo de persona _Natural_ y _Jurídica_ en parámetros CRUD.
- [x] Integración campo Tipo de Persona.

**Criterios de aceptación**

- [x] Documentación de la visualización correcta de la vista de consulta de contratos.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microcliente [gestion_contractual_compras_contrato_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- Arquitectura de aplicaciones - Microclientes (https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se crea el modulo de consulta de contratos y se hace la modificación en el root para poder acceder a éste mediante la ruta http://localhost:4200/consultar-contrato.

![Captura de pantalla 2024-08-13 235918](https://github.com/user-attachments/assets/315216f9-71a2-4881-a43b-0b07ea69476f)

**Comment by edwargl7** [comment]
Pendiente revisar en que agrupación de parametros_crud se deben crear los registros de tipo persona.

**Comment by edwargl7** [comment]
Para los registros de tipo de persona podemos usar el area_tipo _**"Gestión Contractual"**_ de id 25. Tipo de parámetro crear "Tipo persona" y en parámetro agregar "Natural" y "Jurídica".

**Comment by Lau2ri** [comment]
Se realizó el registro de tipo de persona Natural y Jurídica en parámetros CRUD.

<img src="https://github.com/user-attachments/assets/64d185c0-588f-4021-bbe9-9cb13f37c51e" width="490">

**Comment by Lau2ri** [comment]
Se realiza la correcta integración de los campos Vigencia y Tipo Persona, además de acomodar la interfaz para que se asemeje al Mockup del mismo:

https://github.com/user-attachments/assets/6c1eeab1-ded5-4e86-bb18-e74a5a3c9a23

![Image](https://github.com/user-attachments/assets/440e3d97-ca66-4013-8087-be8fcd893037)

**Comment by edwargl7** [comment]
Muy buen trabajo, cumple con las integraciones solicitadas. Ya puedes realizar el PR por favor @Lau2ri .

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelven los PR del microcliente root y gestion_contractual_compras_contrato.
