### ISSUE TITLE
Implementación control de escenarios microcliente de gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#104]
Se requiere realizar la implementación complementaria para manejar errores en peticiones que puedan no ser alcanzadas o en la visualización del spinner que le permita al usuario identificar que se encuentra en proceso alguna petición.

**Sub Tareas**

- [x] Implementación de [progress-spinner](https://material.angular.io/components/progress-spinner/overview).
- [x] Implementación de modales de alerta en caso de presentarse fallos en las peticiones de las integraciones implementadas.

**Escenarios de pruebas**
- [x] Error en consulta a parametros_crud.
- [x] Error en consulta de contratista en proveedores_mid.
- [x] Error en consulta de información presupuestal en presupuesto_contractual_mid.

**Criterios de aceptación**

- [x] Documentación de la implementación requerida y pruebas realizadas.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microcliente [gestion_contractual_compras_contrato_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- Arquitectura de aplicaciones - Microclientes (https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se incian pruebas locales de spinner.

**Comment by mau-oati** [comment]
En caso de tener el endpoint abajo, se obtendrá un error en una sweet alert:

<img src="https://github.com/user-attachments/assets/ac7bf396-3078-4c9b-8f2f-1c9307cff270" width="500" />

**Comment by mau-oati** [comment]
En caso de tener un error interno, se obtendrá un error en una sweet alert:

<img src="https://github.com/user-attachments/assets/629f6120-d323-47c0-8c15-4a6edf18c2a4" width="500" />

**Comment by mau-oati** [comment]
Se inician pruebas locales del progress spinner. Se están revisando flujos de carga incial.

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/7466d28f-4f00-4d07-9c83-84fa1077ba78

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/5190180a-2ebc-4521-9488-ff97a2120cd3

**Comment by edwargl7** [comment]
Muy buen trabajo, se aborda ajuste de visualización del spinner. Se resuelve el PR.
