### ISSUE TITLE
Ajuste modelo de datos de pólizas y amparos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#105]
Se requiere realizar el ajuste del modelo de datos de Pólizas y Amparos requerido para la creación del microservicio CRUD que se encargue del almacenamiento de estos datos de un contrato. Se debe tomar como partida el último modelo que contempla estas tablas  en la Issue #100.
Tener presente el modelo actual para la migración.
![image](https://github.com/user-attachments/assets/c297bbad-f841-40e7-9e5d-6aeb0aadf919)

**Sub Tareas**

- [ ] Ajustar los campos de referencia a fuentes externas.
- [ ] Dado que se implementará en un microservicio diferente al CORE de ARGO se debe establecer el tipo de base de datos apropiado para estos datos.
- [ ] La relación de referencia entre amparo y póliza no es obligatoria dado que se crea en el flujo primero el amparo sin póliza (registro de contrato) y se asocia al llegar al registro de póliza.
- [ ] Aclarar el uso del campo tipo valor y unidad amparo.
- [x] Agregar campo que almacene el valor del amparo basado en el Mockup de registro de Póliza.

**Criterios de aceptación**

- [ ] Modelo de datos siguiendo los lineamientos.

**Requerimientos**

No aplica

**Material de apoyo**
- Vista de Registro de Póliza.
![image](https://github.com/user-attachments/assets/87af50ff-3288-411f-aa1c-c59594860e0e)
- Tablas empleadas en el sistema actual.
![Image](https://github.com/user-attachments/assets/4172b877-ea27-4ee7-9339-369b312734b1)
![Image](https://github.com/user-attachments/assets/12a5dc7e-ae9d-4e3d-9f04-426507d78d16)

**Lineamientos Modelos de datos**
- Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Pendiente ejemplo de datos registrados en el modelo actual solicitado por @mau-oati .

**Comment by mau-oati** [comment]
No se tiene muy claro si **amparo_contrato** guarda información distinta a amparo_poliza.
Las relaciones quedan simplificadas en el modelo propuesto:

![Image](https://github.com/user-attachments/assets/b9ae8cec-4810-4f3b-8e5f-1a0a87ade157)

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/89f82dae-e87d-44c2-a5cc-57bf9a161245)
![image](https://github.com/user-attachments/assets/dcb64f9c-2794-413b-9a81-337c58b48302)
![image](https://github.com/user-attachments/assets/9bde1085-b4ed-4256-84ce-390fc86d9582)

**Comment by edwargl7** [comment]
[poliza_202408150758.csv](https://github.com/user-attachments/files/16625363/poliza_202408150758.csv)
[amparo_poliza_202408150759.csv](https://github.com/user-attachments/files/16625366/amparo_poliza_202408150759.csv)
Registro asociado amparo_contrato
![image](https://github.com/user-attachments/assets/a8aac46c-a34d-421e-be22-820c0cc89623)
![image](https://github.com/user-attachments/assets/68bd7673-6a78-43c2-8297-843d05dc6623)

Las pólizas asociadas a estos registros no tienen registros en amparo_contrato
![image](https://github.com/user-attachments/assets/eb3959e2-25d3-45ba-aa96-bf1dd9eecb8f)

**Comment by edwargl7** [comment]
Del modelo propuesto pendiente ajustar tipo de dato de entidad_aseguradora_id, en pólizas y nombre del campo de referencia a contrato general.
De ampara agregar campo de valor y nombre del campo de referencia a contrato general.

Se debe evaluar con ayuda de funcionamiento la forma de migrar el campo usuario dado que en el sistema actual es un string compuesto por el tipo de documento y número de documento de identidad.
En el nuevo sistema será la referencia a terceros.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/766529eb-a0fb-4073-976f-675d47acaa05)

**Comment by edwargl7** [comment]
Se observan los ajustes de los campos nuevos y nombres de los campos de cada tabla.

**Observaciones**
- Revisión modelo tipo no relacional.
- Campo fecha_inicio, fecha_fin, valor del amparo no son obligatorios dado que el amparo se registra primero al crear el registro del contrato.
- Campo descripción del amparo cambiarlo a opcional en el modelo de datos, podría agregarse la restricción desde el microcliente.
- Agregar número de póliza a póliza.
- La referencia de póliza en amparo es opcional dado que el amparo se registra primero al crear el registro del contrato.
