### ISSUE TITLE
Diseñar mockup de vista del flujo de aprobación de submódulo Gestión de pólizas

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#107]
Se requiere realizar el diseño de vista del flujo de aprobación de submódulo Gestión de pólizas

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipos SoS.
- [x] Realizar ajustes según comentarios del equipo.
- [x] Presentar al cliente el mockup definitivo.

**Criterios de aceptación**

- [x] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño del mockup para el flujo de aprobación y firma del acta de aprobación de póliza en el sistema ARGO V2.

![Image](https://github.com/user-attachments/assets/86b78b6a-def7-4df6-8f5a-758bcc332e36)


Saludos.

**Comment by jcmurilloa** [comment]
Buen avance @cjgonzalezp, revisaremos los detalles en el próximo Review!

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza desarrollo del diseño de mockup del flujo de aprobación del submódulo de pólizas.

**Enlace archivo guardado en OneDrive en el proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuPCWLOJsQFPpAGekdxLO-oBAxm2b5LnyKpkR6k0k7ZUyQ?e=91KjbR

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente únicamente mostrar al cliente para aprobación.
