### ISSUE TITLE
Ajuste modelo de datos cláusulas y parágrafos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#108]
Se requiere realizar la revisión y ajustes al modelo de datos de datos cláusulas y parágrafos basado en el modelo propuesto en la Issue #78.

**Sub Tareas**

- [ ] Revisión en conjunto y ajustes al modelo de datos propuesto.

**Criterios de aceptación**

- [ ] Diseño de modelo de datos que cumpla con los lineamientos.

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
- Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)
- Lineamientos [Modelos de Datos en Mongo](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/lineamientos_mongo.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
De la reunión que se llevo a cabo el día de hoy para realizar la revisión en conjunto y así ajustar el modelo de datos de cláusulas y parágrafos para que se acomode a las funcionalidades requeridas se obtuvo el siguiente modelo:

![Captura de pantalla 2024-08-20 160034](https://github.com/user-attachments/assets/d503fbb8-4cf7-437b-90a3-08eb4e02aa04)

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/207c1963-e37d-4cda-9f85-7d0b52a5a9a4)

**Comment by Lau2ri** [comment]
De la segunda reunión que se llevo a cabo el día de hoy se obtuvo el siguiente modelo:

![Captura de pantalla 2024-08-22 223725](https://github.com/user-attachments/assets/91ecc3d6-95de-4599-abc0-cb2d7709557e)

**Comment by edwargl7** [comment]
Posibles cambios:

- Agregar colección de referencia para el microcliente (plantilla) con versionado
1. Enfoque uno (compartir referencia a predeterminado o plantilla).
> - campo tipo_contrato_id (paramteros_crud).
> - campos de versionado (versión, versión actual, vigencia?)
> - campo orden_clausula_id
> - campo orden_paragrafo_ids[] (orden_paragrafo solo pertenece a cada cláusula pero no pertenece a ningún contrato ni plantilla si no que es referenciado desde el que lo requiere)
> - clausula_contrato tendría una estructura similar sin el versionado, ni tipo_contrato y almacena las referencias a orden_cláusula y orden_parágrafo
2. Enfoque de insertado de orden_clausula y orden_paragrafo (múltiples) por contrato sin importar que sea la misma predefinición (plantilla).
> - campo tipo_contrato_id (paramteros_crud).
> - campos de versionado (versión, versión actual, vigencia?)
> - campo orden_clausula_id
> - cada registro de orden_paragrafo conoce a que contrato o plantilla pertenece caso similar para orden_clausula


> [!NOTE]
> Revisar el uso de nombre en orden_clausula y orden_paragrafo

**Comment by edwargl7** [comment]
Se toma la opción 2 que brinda una implementación más limpia y evita agregar lógica robusta en el microcliente para validar cambios, se realizaría para cada contrato sin importar si se basa en la estructura predefinida para cada tipo de contrato un nuevo registro de orden_clausula y los respectivos orden_paragrafo asociados a dicho contrato.

**Comment by edwargl7** [comment]
Para el caso que la cláusula no tenga parágrafos no se realiza registro de orden parágrafo.

**Comment by Lau2ri** [comment]
Modelo ajustado:
![image](https://github.com/user-attachments/assets/8ee05b9b-511c-4351-85be-58af3f3f16f8)

**Comment by edwargl7** [comment]
Se finaliza el diseño del modelo de datos, se puede presentar a DBA.
