### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión requerimientos con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#11]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se define telefónicamente con la jefe de oficina de contratación Diana Pirachican, espacio de reunión para el levantamiento de requerimientos sesión #2 del sistema ARGO en su Versión 2.0

Detalle Reunión:
Fecha: 14 de mayo 2024
Hora: 2:00 a 3:00 pm
Sede: Piaba - Presencial Oficina Contratación 


Saludos,

**Comment by cjgonzalezp** [comment]
Buen día Julian,

Se realiza reunión de levantamiento de requerimientos con al oficina de contratación el día 14 de mayo de 2024 en horario de 2:00 pm a 3:30 pm. En el transcurso del día Jueves 16 de mayo se terminara de documentar el acta de reunión correspondiente para revisión, aprobación y recolección de firmas de los participantes.


Cordial saludo.

**Comment by cjgonzalezp** [comment]
Buen día,

Se documenta reunión bajo el **acta 027/2024 levantamiento requerimientos** y se almacena en la carpeta correspondiente al proyecto en OneDrive. Queda pendiente la recolección de firmas de los asistentes a la reunión.

**Adjunto link del acta almacenada en la carpeta de OneDrive**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnXB423KgghOsaBuCXHE7AEB8kNJSlVqC2YhvoDJWQeHOQ?e=leoNdb

**Link grabación sesión**
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cjgonzalezp_udistrital_edu_co/EY39W1UEP11Lrb4q3A5I6gUBV2c1J8YUD8D8PIp1CBVRsw?e=meylbg&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


Cordial saludo.

**Comment by jcmurilloa** [comment]
Muy buen trabajo Carlos Julian, realice unas pequeñas modificaciones al documento, el acta cuenta con VoBo para recolección de firmas.

**Comment by cjgonzalezp** [comment]
Buen día,

Se recolectan firmas de los participantes presentes en la reunión realizada el pasado 14 de mayo de 2024.

**Adjunto link del documento cargado en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnXB423KgghOsaBuCXHE7AEB8kNJSlVqC2YhvoDJWQeHOQ?e=d4rGDG


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo Cristian Julian!
