### ISSUE TITLE
Ajuste modelo de datos de pólizas y amparos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#110]
Se requiere realizar los ajustes mencionados en la Issue #105.

**Sub Tareas**

- [x] Ajuste campo fecha_inicio, fecha_fin, valor del amparo no son obligatorios dado que el amparo se registra primero al crear el registro del contrato.
- [x] Ajuste campo descripción del amparo cambiarlo a opcional en el modelo de datos.
- [x] Agregar número de póliza a póliza.
- [x] La referencia de póliza en amparo es opcional dado que el amparo se registra primero al crear el registro del contrato.

**Criterios de aceptación**

- [x] Modelo de datos ajustado.

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
- Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/f204e14f-0323-4e25-8721-1eac81b143fa)

**Comment by edwargl7** [comment]
Cambio numero_poliza a string.
Reemplazar poliza_id y amparo_id por id.
Pendiente revisar el uso de estado en póliza en el modelo actual (pregunta para funcionamiento).
Campo tipo_valor_amparo_id cambiar tipo de dato, y consulta para funcionamiento lista a la que están asociados en el sistema actual (unidad_amparo -> suficiencia, amparo -> , tipo_valor_amparo -> % o SMLV).

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/c425ae17-08c6-4a9b-8bd4-6651d3de9b96" width="450" />

**Comment by edwargl7** [comment]
Revisar con @cjgonzalezp la vigencia del amparo.
![image](https://github.com/user-attachments/assets/69eb8b57-02fb-4897-a089-b57f3e2da6fd)
tipo_valor_amparo y unidad_amparo en el sistema actual se asocian al mismo valor.
![image](https://github.com/user-attachments/assets/2ec05132-6d2f-4ef2-a040-fbbd9e755370)

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/36d680d7-9b6c-4929-a113-f965de9ac0d4)

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/80f742f6-f380-4d91-a2c3-a1644bdb9b78)

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/ead3ce10-9520-4537-9319-4c398c38021c)

**Comment by edwargl7** [comment]
[acta_apro_poliza_345.pdf](https://github.com/user-attachments/files/16721269/acta_apro_poliza_345.pdf)

**Comment by edwargl7** [comment]
Se contrasta la información con la base de datos y se observa que el campo unidad amparo almacena el valor de la suficiencia.
![image](https://github.com/user-attachments/assets/0315588b-e3ad-40f5-9127-44904c0ce4a9)
![image](https://github.com/user-attachments/assets/6ddf1686-34b4-47d4-a8de-c4bcc30fb160)
Se realiza reemplazo en base de datos y se observa la diferencia en el porcentaje

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/00efe8a4-4af8-473e-b921-6487489a6f52)

**Comment by edwargl7** [comment]
Ajustes requeridos antes de la presentación.
![image](https://github.com/user-attachments/assets/1a076f44-464e-4485-85da-4b21f5f2a2e9)
Tener presente la estructura que se maneja para el modelo relacional y la notación para campos obligatorios, pk y fk.

![image](https://github.com/user-attachments/assets/ab63d7b4-3139-4008-bee4-30427846c5f6)
Referencias a otras BD o sistemas.

- Póliza
> - descripcion campo opcional
> - usuario_legacy tipo varchar para soportar la migración del sistema actual
> - usuario_id para referencia a terceros crud y añadir nota que indique la referencia de este campo a terceros como lo indican los lineamientos
- Amparo_poliza
> - amparo_id obligatorio
> - Cambiar tipo de suficiencia a flotante/decimal -> numeric
> - Eliminar campo unidad_amparo
> - valor tipo flotante/decimal -> numeric


**Equivalencia entre modelo de datos**
Modelo actual | Modelo propuesto

| amparo_contrato  | amparo_poliza |
| ------------- | ------------- |
| vigencia  | descripcion  |
| tipo_amparo  | amparo_id  |
| suficiencia  | suficiencia  |
| numero_contrato  | contrato_general_id  |
| vigencia_contrato  | contrato_general_id |

| amparo_poliza  | amparo_poliza |
| ------------- | ------------- |
| poliza  | poliza_id  |
| estado  | activo  |
| fecha_inicio  | fecha_inicio |
| fecha_fin  | fecha_final  |
| unidad_amparo  | suficiencia |
| amparo  | amparo_id |
| tipo_valor_amparo  | tipo_valor_amparo_id |

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/5f51e14b-4eaa-4540-b10d-b32485961893)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/d0e065da-1bc4-4884-b95f-75dd350a15aa)

**Comment by edwargl7** [comment]
Se realizan los ajustes finales, ya se tiene la versión final para la presentación del modelo.
