### ISSUE TITLE
Diseño Modelo de datos ordenador

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#112]
Se requiere realizar el análisis y diseño del modelo de datos del ordenador contemplando la migración de registros de la base de datos actual. Actualmente la gestión de ordenadores se encuentra en el módulo paramétrico, se debe revisar el flujo de datos entre SICAPITAL y ARGO actualmente para el registro de ordenadores y como manejar el registro de ordenador encargado solicitado por el usuario para el registro de un contrato.

**Sub Tareas**

- [x] Revisión modelo de datos actual que almacena los ordenadores.
- [x] Revisión módulo paramétrico del ARGO actual, campos requeridos.
- [x] Revisión campos requeridos del ordenador en el contrato (ids de referencia).
- [ ] Manejo de ordenador encargado para el sistema actual.

**Criterios de aceptación**

- [x] Documentación de la Issue con el modelo de datos propuesto y factores a tener presente en la migración.

**Requerimientos**

No aplica

**Material de apoyo**
- [argo_desarrollo](https://github.com/udistrital/argo_desarrollo)

**Lineamientos Modelos de datos**
- Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
````
            case "ordenadorGasto" :

                $cadenaSql = " SELECT ORG_IDENTIFICADOR, ORG_ORDENADOR_GASTO FROM SICAARKA.ORDENADORES_GASTO ";
                $cadenaSql.=" WHERE ORG_ESTADO='A' ";
```

```
            case "informacion_ordenador" :
                $cadenaSql = " 	SELECT  ORG_NOMBRE,  ORG_IDENTIFICACION ";
                $cadenaSql .= " FROM SICAARKA.ORDENADORES_GASTO  ";
                $cadenaSql .= " WHERE ORG_IDENTIFICADOR = $variable and ORG_ESTADO = 'A'";
```

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/9e02e0b0-578e-409d-b883-d58a345087ba)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/c23071d5-8f91-4947-80c4-b5e56641b3ba)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/f6fb7c12-c7f6-4b63-8f6e-12a5696b64ed)

**Comment by edwargl7** [comment]
Se solicita por parte de @mau-oati registros de ejemplos de ordenadores en contrato para tener un caso de ejemplo para complementar el modelo diseñado.

Pregunta para funcionamiento, si se requiere un ordenador encargado, ese registro debe existir como ordenador también en Sicapital?
Cuál debe ser la fuente de esos funcionarios que el abogado podría consultar para tomar el ordenador encargado cuando dicha actualización no se encuentre realizada en el sistema.

**Comment by edwargl7** [comment]
Se debe abordar en otra Issue el complemento del análisis requerido para la construcción del modelo de datos de gestión de Ordenadores.
