### ISSUE TITLE
División del Cliente Argo v1 en Microfrontends - Microcliente Gestión de Pólizas PT1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#12]
Se requiere realizar el diseño para dividir el sistema Argo v1 en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI.  Incluir pólizas y amparos.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

- [x] Análisis del sistema Argo v1 microcliente de Gestión Pólizas
- [x] Crear diagrama de componentes de la arquitectura para Argo v2.
- [x] Listado de funcionalidades de cada microcliente basado en las funciones conocidas en el manual de usuario revisado en las tareas realizadas en el Sprint 0.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de componentes con la división clara el sistema en múltiples microclientes.
- [ ] Listado de funcionalidades que componen cada microcliente.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se inició el diagramado borrador en Draw.io, segmentando por dominios los microservicios y sus repectivos clientes. WIP.

**Comment by mau-oati** [comment]
**Primer prototipo de propuesta**


![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/a38fcb1f-a4d6-4434-a35b-bfebe7507eda)

**Comment by edwargl7** [comment]
Buen día,

Agregar por favor el componente de amparos al módulo de pólizas. Muchas gracias.

**Comment by mau-oati** [comment]
![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/0f0d276e-6d64-46a5-854e-238c11d0bc9b)

**Comment by mau-oati** [comment]
| Modulo             | Micro Clientes                 | Funcionalidades       |
|--------------------|--------------------------------|-----------------------|
| Gestión de Polizas | Gestión de Contratos Suscritos | Consultar Contrato    |
|                    |                                |                       |
|                    | Gestión de Contratistas        | Consultar Contratista |
|                    |                                |                       |
|                    | Gestión de Pólizas             | Registrar Póliza      |
|                    |                                | Modificar Póliza      |
|                    |                                | Manejo de Estado      |
|                    |                                |                       |
|                    | Gestión de Amparos             | Registro de Amparos   |
|                    |                                | Generar Documento     |

**Comment by edwargl7** [comment]
Excelente trabajo. Agregar lista de funcionalidades a la carpeta de documentos v2 por favor.
