### ISSUE TITLE
Implementación vista de documentos microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#121]
Se requiere realizar la implementación del paso 9 para la carga de documentos basado en la lista de registros de parámetros y la vista de visualización de documentos que adicional a la lista de documentos de carga se incluye la previsualización de la minuta.

**Paso 9**
![image](https://github.com/user-attachments/assets/6668d73e-9a3b-41f2-bbf1-459c22baad50)

**Vista visualización documentos**
![image](https://github.com/user-attachments/assets/4a21f7e2-2b83-42fd-a78c-75b5bcbad7b6)

**Sub Tareas**

- [x] Implementación vista para cargar documentos (paso 9) con integración de parámetros crud.
- [x] Implementación vista de visualización de documentos.

**Criterios de aceptación**

- [x] Documentación de la implementación en la Issue. 

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se creó el nuevo paso 9 para cargar los documentos del contratista, la función de cargar un archivo pdf funciona correctamente, sin embargo a la hora de visualizar el documento recién cargado este no se muestra por un error en políticas de seguridad:

<img src="https://github.com/user-attachments/assets/a679accc-3ea1-4902-a092-b1be78d49d41" width=500>

Se intentaron varias soluciones, entre ellas abrir el visualizador de pdf en una nueva ventana y tratar de desactivar ciertas políticas con etiquetas meta en el index.html, ninguna resultando exitosa por lo que se deduce que las políticas están configuradas desde el lado del servidor y no me es posible modificarlas.

https://github.com/user-attachments/assets/a7318a65-171f-4a34-8d41-58621de11fd9

![Image](https://github.com/user-attachments/assets/f200e896-d3ba-4d40-92cf-55345d5184ca)
