### ISSUE TITLE
División del Cliente Argo v1 en Microfrontends - Microcliente Gestión orden PT1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#13]
Se requiere realizar la planeación y estructuración para dividir el sistema Argo v1 en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI.

Esta tarea contempla el módulo de Gestión de orden (creación, edición y suscripción sin incluir pólizas ni acta de inicio).

Tener presente que para la versión 2 de ARGO se debe tener presente agregar más de un supervisor.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

- [x] Análisis del sistema Argo v1 microcliente de Gestión Orden
- [x] Crear diagrama de componentes de la arquitectura para Argo v2.
- [x] Listado de funcionalidades de cada microcliente basado en las funciones conocidas en el manual de usuario revisado en las tareas realizadas en el Sprint 0.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de componentes con la división clara el sistema en múltiples microclientes.
- [x] Listado de funcionalidades que componen cada microcliente.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
**Duda:** Respecto a esta tarea - Las ordenes en ARGO, por lo que he visto en la documentaci'on son una abstracci'on de todo (contrato, compras, polizas), puede ser que lo est'e entendiendo mal. Porque no tenemos un modulo Ordenes (tenemos Contratro, Compra, Polizas, Novedades).

**Comment by mau-oati** [comment]
**Primera propuesta borrador:**

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/5a365628-6c79-4130-861a-0875831ed27c)

**Comment by edwargl7** [comment]
Excelente trabajo, muy bien adelantado en el diagrama la identificación de los microservicios requeridos por cada microfrontend.
En el siguiente sprint abarcaremos los microservicios y el modelo de datos. Para finalmente llegar al diagrama completo de microfrontend y microservicios requeridos (microservicios existentes y transversales, y los del core de ARGO).

**Comment by edwargl7** [comment]
Agregar listado de funcionalidades de cada microclientes por favor. Ejemplo:
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/6599d5cb-5296-43f0-bf7a-e22217be9e7a)

**Comment by edwargl7** [comment]
Pendiente agregar la lista de funcionalidades @mau-oati .

**Comment by mau-oati** [comment]
| Modulo                     | Micro Clientes                 | Funcionalidades     |
|----------------------------|--------------------------------|---------------------|
| **Gestión de Orden de Compra** | Gestión de Órdenes             | Registrar Órdenes   |
|                            |                                | Consultar Órdenes   |
|                            |                                | Registrar Elementos |
|                            |                                |                     |
|                            | Gestión de Contrato de Órdenes | Consultar Contrato  |
|                            |                                | Generar Documento   |
|                            |                                | Consulta de Pólizas |
|                            |                                | Consulta RP         |
|                            |                                | Cancelar Contrato   |

**Comment by edwargl7** [comment]
Excelente trabajo, agregar lista de funcionalidades a la carpeta de documentos v2. Muchas gracias
