### ISSUE TITLE
Implementación pruebas de integración microservicio de gestión de cláusulas y parágrafos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#131]
Se requiere realizar la implementación de pruebas de integración en el microservicio de [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud)

**Sub Tareas**

- [x] Implementar pruebas de integración en cláusula CRUD.
- [x] Implementar pruebas de integración en parágrafo CRUD.
- [x] Implementar pruebas de integración en orden cláusula CRUD.
- [x] Implementar pruebas de integración en orden parágrafo CRUD.
- [x] Implementar pruebas de integración en plantilla tipo contrato CRUD.

**Criterios de aceptación**

- [x] Documentación de Issue con los resultados de las pruebas implementadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Archivo Excel  con el registro de todas las pruebas de integración:
[Pruebas locales integracion microservicio Clausulas y Paragrafos.xlsx](https://github.com/user-attachments/files/16924906/Pruebas.locales.integracion.microservicio.Clausulas.y.Paragrafos.xlsx)

![Image](https://github.com/user-attachments/assets/b26614dc-354b-4532-8608-50bab22297db)
