### ISSUE TITLE
Ajustes microservicio de gestión de cláusulas y parágrafos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#133]
Se requiere realizar ajustes a la implementación del microservicio de gestión de cláusulas y parágrafos abordado en la Issue #122. Principalmente relacionados con los lineamientos de Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)

**Sub Tareas**

- [x] Ajuste nombres de endpoints a plural y reemplazar "_" por "-".
- [x] Cambio de tipo de dato usado en la respuesta de los endpoints de string a integer.
- [x] Implementación endpoint de consulta de estructura de cláusulas y parágrafos por id del contrato (contrato general), que aborden los métodos GET, POST y PUT.
- [x] Implementación endpoint Health Check.
- [x] Agregar a los endpoints tipo GET ALL los query params query, limit, offset, sort y order.
- [x] Agregar al endpoint tipo GET ALL de Plantilla tipo contrato campo Metadata tipo JSON adicional en el formato de respuesta en el mismo nivel de Status, Data, ... Dentro de este nuevo campo se debe agregar el total de registros basado en el filtro aplicado a la consulta (esto con el fin de complementar el paginado realizado con limit y offset).
- [x] Pruebas funcionales de todos los endpoints (dado ajustes en respuestas y controladores).

**Criterios de aceptación**

- [x] Ajustes a la implementación realizada en la Issue #122.
- [x] Completar la implementación adicional (endpoints nuevos y query params).

**Requerimientos**

No aplica

**Material de apoyo**
- Estructura de respuesta endpoint de plantilla tipo contrato
```json
{
   "Success":true,
   "Status":"200",
   "Message":"Request successful",
   "Data":[
      {
         "_id":"66dceb93074c3859ba040084",
         "version":4,
         "version_actual":false,
         "tipo_contrato_id":0,
         "orden_clausula_id":null,
         "orden_paragrafo_ids":[
            {
               "_id":"66dcd99c65aae7d6dc3571db",
               "paragrafo_ids":[
                  "66dcc6aac3357bfa77e68f02"
               ],
               "contrato_id":"66dcd99c65aae7d6dc357151",
               "clausula_id":"66dcc6aac3357bfa77e68f02",
               "fecha_creacion":"2024-09-07T22:54:20.796Z",
               "fecha_modificacion":"2024-09-07T23:49:11.414Z",
               "__v":0
            },
            {
               "_id":"66dce7528e30c0e0f824e8a3",
               "paragrafo_ids":[
                  "66dcc6aac3357bfa77e68f02"
               ],
               "contrato_id":"66dcd99c65aae7d6dc354387",
               "clausula_id":"66dcc6aac3357bfa77e68f02",
               "fecha_creacion":"2024-09-07T23:52:50.666Z",
               "fecha_modificacion":"2024-09-07T23:54:53.097Z",
               "__v":0
            }
         ],
         "fecha_creacion":"2024-09-08T00:10:59.513Z",
         "fecha_modificacion":"2024-09-08T00:14:56.280Z",
         "__v":0
      }
   ]
}
```

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Creación Endpoint de Contratos
Falta por revisar y confirmar su correcta funcionalidad en diferentes casos de éxito y de fallo.

<img src="https://github.com/user-attachments/assets/0b500869-f84c-4df1-8d22-330d28f72da6" width=400>

Ejemplo GET:

<img src="https://github.com/user-attachments/assets/ccfe8f65-1e38-4f2d-be49-caf90d4425e3" width=400>

### Creación de campo Metadata en respuesta de GET ALL de Plantilla_tipo_contrato:
https://github.com/user-attachments/assets/1fad063a-692c-4453-ad3c-c4d5015d1fe8

![Image](https://github.com/user-attachments/assets/4699ab81-b45a-41a7-8f56-36e3192e8471)

**Comment by Lau2ri** [comment]
## Pruebas funcionales:

### Filtros y ajustes generales:
https://github.com/user-attachments/assets/3b4a29f9-3547-4763-aeae-19536343b73b

![Image](https://github.com/user-attachments/assets/547c3273-b4c3-48ab-b1ca-479fbfa24ccb)

### Funcionalidad endpoint Contratos:
https://github.com/user-attachments/assets/ae958e92-7380-4b74-a30d-6fd5e9b47fb1

![Image](https://github.com/user-attachments/assets/53d1153a-b09c-4482-b09f-2c31770a7e4d)

https://github.com/user-attachments/assets/f0160c10-7d4f-401e-aaa3-da7bfd5d8dc9

![Image](https://github.com/user-attachments/assets/e75b3230-91e1-42c4-b92f-27ca7f1bc48b)
