### ISSUE TITLE
Implementación endpoint de consulta de contratos de un contratista en microservicio Proveedores MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#138]
Se requiere realizar la implementación de un endpoint que permita consultar los contratos de un proveedor aplicando filtros como estado, unidad ejecutora. Con el fin de identificar si el contratista al momento de registrarse un nuevo contrato ya cuenta con un contrato en curso.

**Sub Tareas**

- [x] Implementación endpoint que permita consultar contratos en el ARGO actual y el ARGO nuevo. Se debe filtrar por vigencia, la vigencia es un campo de entrada en el microservicio proporcionado por el microcliente.
- [x] Implementación para retornar la información del contratista (endpoint actual) junto con la información de los contratos de la vigencia solicitada.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de la implementación del nuevo endpoint y resultado de pruebas.

**Material de apoyo**
- Repositorio microcliente [proveedores_mid](https://github.com/udistrital/proveedores_mid)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se añade a la consulta del proveedor los datos adicionales de los contratos que este pueda tener y sus respectivos datos, ésta consulta sólo traerá los contratos que el proveedor tenga vigentes.

![Captura de pantalla 2024-10-24 202558](https://github.com/user-attachments/assets/bef10494-c512-4404-94a2-dc756be73be1)

**Comment by edwargl7** [comment]
Se está ajustando el endpoint del ambiente de pruebas dado que genera error, se integra con el del ambiente de producción.
Dentro de los ajustes que se están realizando en la query se observa que la validación la realiza contra la fecha actual teniendo presente el mes. Se validará con el arquitecto los cambios y en un siguiente sprint se realizará la prueba funcional y de integración con el endpoint ajustado.

**Comment by edwargl7** [comment]
Se revisa la implementación, dado que el endpoint actualmente integrado en esta Issue solo suministra información para persona natural se puede refactorizar para aclarar este resultado en las funciones implementadas.
![Image](https://github.com/user-attachments/assets/e0b5a654-4ad1-41ea-846c-815245a93747)
![Image](https://github.com/user-attachments/assets/990fc836-b68a-4632-8734-88b60c86c11f)
