### ISSUE TITLE
División del Cliente Argo v1 en Microfrontends - Microcliente Gestión actas de inicio PT1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#14]
Se requiere realizar la planeación y estructuración para dividir el sistema Argo v1 en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI. 

Esta tarea contempla el módulo de Gestión Actas de inicio.

Tener presente que para la versión 2 de ARGO se debe tener presente agregar más de un supervisor.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

- [x] Análisis del sistema Argo v1 microcliente de Gestión Actas de inicio
- [x] Crear diagrama de componentes de la arquitectura para Argo v2.
- [ ] Listado de funcionalidades de cada microcliente basado en las funciones conocidas en el manual de usuario revisado en las tareas realizadas en el Sprint 0.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [ ] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de componentes con la división clara el sistema en múltiples microclientes.
- [ ] Listado de funcionalidades que componen cada microcliente.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Primer borrador
Propuesta diagrama gestión actas de inicio:

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/df745f40-0e34-4526-813f-42b1bbd186ef" width="550" >

**Comment by edwargl7** [comment]
Buen día,

Excelente trabajo, es clara las dependencias entre los componentes y las funcionalidades de cada uno.

Agregar por favor la lista de funcionalidades de cada microservicios. Ejemplo:
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/e1df37e6-65c4-4210-83e7-f31dbe925043)

**Comment by Lau2ri** [comment]
### Tabla de funcionalidades
A continuación se presenta la tabla de funcionalidades correspondiente a los módulos funcionario y gestión contractual.

![Image](https://github.com/udistrital/argo_documentacion/assets/133523053/128964c8-95a2-434c-8e2e-0f1a227b53c8)

**Comment by Lau2ri** [comment]
En el Módulo de Funcionario, se mueve la funcionalidad "Actualizar actas de inicio" de la sección de Gestión actas de novedades a la sección de Gestión actas de inicio.

![Image](https://github.com/udistrital/argo_documentacion/assets/133523053/7d1afc24-c312-478b-8190-9230b06eca4a)

**Comment by edwargl7** [comment]
Muchas gracias. Se da por terminada la tarea.
