### ISSUE TITLE
Integración microservicio de cláusulas y parágrafos con microcliente de gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#140]
Se requiere realizar la integración en el microcliente de [gestión contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) y el microservicio CRUD [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud). Además, se requiere completar la funcionalidad del paso de cláusulas y parágrafos relacionado al registro del mismo y enumeración de cláusulas usando un valor quemado en el MF de contrato para realizar las pruebas necesarias (posteriormente al definirse e implementarse el crud se reemplazará por el valor correcto).

**Sub Tareas**

- [x] Registro de estructura predefinida basado en un contrato CPS.
- [x] Implementación numeración de cláusulas en el MF (registrar en parametros_crud como nombre en ordinal y código y order el valor en entero).
- [x] Implementación registro de orden parágrafos y cláusulas asociados a un contrato (con valor de contrato quemado por el momento).
- [x] Implementación almacenamiento de parágrafos nuevos (con valor de contrato quemado por el momento).
- [x] Implementación almacenamiento de cláusulas nuevas (con valor de contrato quemado por el momento).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de avances y resultados pruebas funcionales.

**Requerimientos**

- Issue #142 

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realizan ajustes para que la interfaz quede de acuerdo con el mockup, además se integra con parametros_crud para obtener la numeración de la enumeración de las clausulas.

https://github.com/user-attachments/assets/ebcbf5fa-6f83-4e44-9bbc-510197b34757

![Image](https://github.com/user-attachments/assets/55ab622d-52e6-4b31-a8aa-412d30c78b54)

Se inició también la integración con clausulas_paragrafos_crud, pero no se ha terminado de comprobar su funcionalidad.

**Comment by Lau2ri** [comment]
Se realiza el registro de estructura predefinida basado en un contrato CPS en la BD

https://github.com/user-attachments/assets/a20ca3d9-6afc-449d-9f89-c175391a705a

![Image](https://github.com/user-attachments/assets/67ab601c-a255-4eb5-933a-0adf48914c17)

**Comment by Lau2ri** [comment]
Se realiza la integración con clausulas y parágrafos para mostrar el registro realizado de plantilla tipo contrato basado en un contrato CPS.

https://github.com/user-attachments/assets/1d0deb90-49e6-44b7-b487-269ddfb9d6d7

![Image](https://github.com/user-attachments/assets/c4dccc81-5013-467d-924a-8658549c311c)
