### ISSUE TITLE
Generación de plantillas para parametrización de contratos según su tipo Parte II

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#143]
Se requiere realizar el diseño de las plantillas para parametrización de contratos según su tipo

**Sub Tareas**

- [x] Realizar la investigación según cada tipo de contrato.
- [x] Proyectar las diferentes plantillas.
- [x] Exponer al equipo SoS.
- [x] Exponer al cliente.

**Criterios de aceptación**

- [x] Plantillas construídas y aprobadas equipos SoS y cliente.
- [x] Plantillas documentadas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Están pendientes las plantillas de las minutas generales que se utilizaran desde la oficina de extensión IDEXUD que están pendientes de compartirlas por parte del IDEXUD.

Por favor dejar las revisiones de las plantillas para un siguiente sprint.


Saludos.

**Comment by jcmurilloa** [comment]
Con esta información clara, podemos finalizar issue y programar una nueva al momento en que se cuente con el insumo por parte del IDEXUD. Buen trabajo @cjgonzalezp!
