### ISSUE TITLE
División del sistema en Microservicios - Gestión contractual - Gestión orden compras y servicios - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#15]
Se requiere realizar el diseño de los microservicios de ARGO, de tal forma que cada uno sea independiente, autosuficiente y escalable. El objetivo es lograr desacoplar las funcionalidades del sistema y descentralizar los servicios teniendo presente el concepto de microservicios.

Tener presente los servicios existentes que se pueden integrar:

- [terceros_crud](https://github.com/udistrital/terceros_crud) nos permite obtener la información de los usuarios de la Universidad
- [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid) y [documentos_crud](https://github.com/udistrital/documentos_crud) que nos permiten almacenar y gestionar soportes de archivos en diferentes formatos.
- [parametros_crud](https://github.com/udistrital/parametros_crud) cuenta con el CRUD en el que podemos registrar los datos paramétricos.

**Material de apoyo**
- [División del sistema en Microservicios](https://github.com/udistrital/planeacion_cliente/issues/803)

**Sub Tareas**

- [ ] Creación del diagrama de componentes de la arquitectura propuesta para el sistema Argo - Módulos Gestión contractual y orden compras y servicios.
- [ ] Listado de microservicios y principales funcionalidades.

**Criterios de aceptación**

- [ ] El diagrama muestra la división clara del sistema ARGO v1 en múltiples microservicios de los módulos Gestión contractual y orden compras y servicios, incluir los servicios existentes mencionados y los nuevos requeridos para la nueva versión de ARGO.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Diagrama de microservicios.
- [ ] Archivo subido a la carpeta de documentación con la lista de microservicios y principal funcionamiento.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Agregada a la carpeta de ARGO las grabaciones de las capacitaciones del sistema actual para tener presente e identificar el impacto en el módulo de gestión contractual y orden de compras y servicios.

**Comment by Lau2ri** [comment]
### Boceto v1 - División del sistema en Microservicios

![ARGO-Microservicios Gestión contractual y ordenes drawio](https://github.com/udistrital/argo_documentacion/assets/133523053/f89069fb-c33e-4edd-aee4-a5a00c582b59)

Para verlo mejor se adjunta el archivo draw.io a continuación: https://drive.google.com/file/d/1EZdCWDhC_zdefNretdiviIeV12-rq6BG/view?usp=sharing, el diagrama presentado se encuentra en la página "Microservicios Gestión contractual y ordenes".

**Comment by edwargl7** [comment]
Muy buen análisis de este módulo y las dependencias a otros servicios. En una segunda parte analizaremos cuales son las posibles dependencias de consumo de datos de otros servicios sobre el actual sistema de ARGO y se realizarán los ajustes pertinentes a este diagrama.
