### ISSUE TITLE
Integración microservicio CRUD gestión contractual para la vista de consulta del microcliente

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#150]
Se requiere realizar la integración del endpoint de consulta de contratos que cuenta con unos ajustes en la Issue #191. Por lo que es necesario actualizar el endpoint de consulta en el microservicio [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid) que permita enviar los query params.
![Image](https://github.com/user-attachments/assets/875dddd2-9ccb-48b6-b029-dbac586fef7d)

**Sub Tareas**

- [x] Actualización controlador del microservicio MID para envío de query params que permitan realizar las consultas requeridas en la vista de consulta.
- [ ] Implementación de consulta por estado en el controlador del microservicio MID (puede combinarse con el query params de la primera subtarea).
- [ ] Implementación de consulta por contratista en el controlador del microservicio MID (puede combinarse con el query params de la primera subtarea).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se ajustó la integración con el CRUD y retorna una tabla con todos los contratos.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/8bea0464-7efe-4716-842e-f1d7b89bd09c)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/b942f37e-e854-4049-9932-5c3f077e325f)
- Consulta por Vigencia:
![Image](https://github.com/user-attachments/assets/c6addf3a-014c-4f72-b5ff-45031d965916)

La implementación de la tabla paginada tomó más tiempo de lo esperado. Hubo que re estructurar las respuestas del mid para obtener la metadata, agregar un nuevo endpoint que obtuviera los contratos en general con los parámetros resueltos y agregar el campo de estado a la respuesta general.

TODO: Filtro por contratista y por estado.

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelven los dos PR y se crea tarea para continuación.
