### ISSUE TITLE
Integración registro cláusulas por contrato en microcliente gestión contractual y microservicio cláusulas y parágrafos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#151]
Se requiere realizar la implementación del registro de cláusulas y parágrafos asociados al contrato. Completar la integración de registro de cláusulas y parágrafos nuevos (Issue #140).
También se requiere implementar la lógica al momento de eliminar un parágrafo o cláusula para el contrato. Al momento de eliminar una cláusula se debe eliminar los parágrafos asociados siempre y cuando los dos no sean predeterminados, con el fin de eliminar solamente lo relacionado a ese contrato.

**Sub Tareas**

- [x] Implementar consulta de plantilla por tipo de contrato cuando el contrato no cuente con registros de orden de cláusulas y parágrafos (contratos nuevos), de lo contrarío se visualizará las cláusulas y parágrafos asociados al contrato.
- [x] Implementación registro de contrato mediante orden cláusula y orden parágrafo (los contratos no tienen versionamiento).
- [x] Implementación almacenamiento de parágrafos nuevos (con valor de contrato quemado por el momento).
- [x] Implementación almacenamiento de cláusulas nuevas (con valor de contrato quemado por el momento).
- [x] Implementación actualización de orden parágrafo cuando se elimine un parágrafo (eliminando lógicamente el parágrafo si no es predeterminado).
- [x] Implementación actualización de orden cláusula y parágrafo cuando se elimine una cláusula (eliminación lógica de la cláusula no predeterminada y parágrafos no predeterminados).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
- Microcliente [gestión contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) 
- Microservicio CRUD [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se consiguió implementar las siguientes dos tareas:
- Implementar consulta de plantilla por tipo de contrato cuando el contrato no cuente con registros de orden de cláusulas y parágrafos (contratos nuevos), de lo contrarío se visualizará las cláusulas y parágrafos asociados al contrato.
- Implementación actualización de orden cláusula y parágrafo cuando se elimine una cláusula (eliminación lógica de la cláusula no predeterminada y parágrafos no predeterminados).

Y se logró parcialmente la siguiente tarea, ya que se realiza el registro de una nueva orden clausula, pero no se realiza el registro de nuevos orden parágrafo.

- Implementación registro de contrato mediante orden cláusula y orden parágrafo

https://github.com/user-attachments/assets/667a8e06-ff99-445f-b209-858cdebb1d5c

![Image](https://github.com/user-attachments/assets/09424f02-5dbd-48ca-8cfb-5743a5897150)

Las demás tareas quedan pendientes, aunque estén implementadas parcialmente, no muestran un correcto funcionamiento.
