### ISSUE TITLE
Definición validaciones contratista y CDP

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#153]
Se requiere realizar la validación con funcionamiento y el abogado de las validaciones requeridas para la asignación del contratista y las validaciones requeridas en el CDP.

**Sub Tareas**

- [x] Validaciones del contratista (contratos vigentes por unidad ejecutora o en general) y demás criterios a tener presentes.
- [x] Criterios en la consulta de CDP.

**Criterios de aceptación**

- [x] Definición de criterios.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se crea documento con la definición de validaciones que debe tener en cuenta el sistema ARGO V2 para el registro de contratos.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Parametrizaciones/[Documentos](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Parametrizaciones/Documentos?csf=1&web=1&e=TZ6Hyo)?csf=1&web=1&e=TZ6Hyo

Saludos.
