### ISSUE TITLE
Implementación consulta de plantilla y contrato microservicio CRUD cláusulas y parágrafos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#155]
Se requiere continuar con la implementación de la consulta de plantillas y parágrafos con las consultas construidas en la Issue #152 Que permitan optimizar la cantidad de peticiones realizadas para entregar la estructura requerida.

**Sub Tareas**

- [x] Implementación del ajuste al consultar la plantilla actual para un tipo de contrato.
- [x] Pruebas funcionales consulta de plantilla.
- [x] Implementación del ajuste al consultar las cláusulas y parágrafos (orden) de un contrato.
- [x] Pruebas funcionales consulta de un contrato.
- [x] Pruebas funcionales adicionales.

**Escenarios de pruebas**
- [x] Prueba registrando más de un contrato con diferente cantidad de cláusulas y parágrafos.

**Criterios de aceptación**

- [x] Documentación de la implementación y resultados de las pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones Técnicas**
- Ejemplo estructura de respuesta de consulta de plantilla activa para un tipo de contrato.
```json
{
    "Success": true,
    "Status": "200",
    "Message": "Request successful",
    "Data": {
        "_id": "66dceb93074c3859ba040084",
        "version": 4,
        "version_actual": true,
        "tipo_contrato_id": 10,
        "clausulas": [
            {
                "_id": "f6dcd99c65aae7d6dc3571db",
                "order": 1,
                "nombre": "XY",
                "descripcion": "z",
                "paragrafos": []
            },
            {
                "_id": "a4dcd99c65aae7d6dc3571df",
                "order": 1,
                "nombre": "XY",
                "descripcion": "z",
                "paragrafos": [
                    {
                        "_id": "66dcd99c65aae7d6dc3571db",
                        "order": 1,
                        "nombre": "ab",
                        "descripcion": "wer"
                    }
                ]
            }
        ],
        "fecha_creacion": "2024-09-08T00:10:59.513Z",
        "fecha_modificacion": "2024-09-08T00:14:56.280Z"
    }
}
```

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se logró obtener la respuesta deseada a través de la consola de MongoDB con el primer query de Plantilla tipo contrato, pero los otros dos querys de orden clausula y orden parágrafo continúan sin dar respuesta en MongoDB. 

https://github.com/user-attachments/assets/f6100051-13fc-4b36-af5b-df58ceb526ec

![Image](https://github.com/user-attachments/assets/17f16981-35f0-4a14-9a78-eb23b583296d)

**Comment by Lau2ri** [comment]
Se consigue por medio de la query creada, con unas cuantas modificaciones, hacer la consulta exitosamente y con el formato solicitado haciendo uso del Aggregate de Mongo.

Fue necesario crear funciones de mapeo que permiten reorganizar eficientemente los datos en la estructura jerárquica que se requería, facilitando la asociación entre cláusulas y sus parágrafos correspondientes.

https://github.com/user-attachments/assets/de66d828-b9dd-4b04-94b1-c56902d5d4d7

![Image](https://github.com/user-attachments/assets/82e9b006-f581-4335-83df-748cb87a1b9c)

**Comment by Lau2ri** [comment]
Se resuelven los problemas encontrados y ya se muestra una correcta funcionalidad en las tres consultas:

https://github.com/user-attachments/assets/f775df63-41ea-4142-acf8-307f1c6b801e

![Image](https://github.com/user-attachments/assets/89d7b08a-e008-4da0-8231-d7407d605ea1)
