### ISSUE TITLE
Implementación de validaciones paso de cláusulas y parágrafo en microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#159]
Se requiere realizar la implementación en el microcliente de la validación de la utilización de la enumeración de cláusulas sin que se realicen saltos.

**Sub Tareas**

- [x] Implementación validación de enumeración de cláusulas sin que se realicen saltos, es decir, que el usuario por error asigne la cláusula primera, segunda, cuarta y quinta, saltando de esta forma la tercera al no elegirla.
- [x] Implementación modal de error por consulta de tipo de contrato sin plantilla.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas funcionales.

**Requerimientos**

- Mockup de modales Issue #158.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Implementación de modales de alerta acorde a los diseños de los mockups dados.
Para caso de error por consulta de tipo de contrato sin plantilla:

<img src="https://github.com/user-attachments/assets/c22dbe7b-4ec3-4626-97cb-d1dd84705a58" width=400>

Para casos de agregar, eliminar y guardar cláusulas y parágrafos: 

https://github.com/user-attachments/assets/f8d891be-4f0a-449e-95f8-9c20e63ad51d

![Image](https://github.com/user-attachments/assets/866a7aa9-9154-4a38-b269-644592e7501b)

**Comment by Lau2ri** [comment]
###  Implementación validación de enumeración de cláusulas sin que se permitan saltos ni tampoco enumeración repetida:

https://github.com/user-attachments/assets/c4ecfc52-2d96-4a2a-9a16-7ddbbe9c9b69

![Image](https://github.com/user-attachments/assets/e412bd42-93ef-40c1-8501-30fbd00934c8)
