### ISSUE TITLE
Actualizar el flujo del modulo contractual según requerimientos cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#16]
Se requiere actualizar el flujo del modulo contractual según requerimientos cliente

**Sub Tareas**

- [x] Generar las modificaciones según requerimientos del cliente para la nueva versión

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se actualiza diagrama de flujo del módulo de gestión contractual según los requerimientos iniciales del cliente.

**Diagrama de proceso registro contrato CPS y Póliza ARGO V2**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/de38f441-a95d-452b-a7f6-9a23304fec0e)

**Formulario de registro contrato ARGO V2**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/0158201f-8ee7-408f-a512-c92fc6d096ac)

**Formulario de registro póliza ARGO V2**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/16244a6d-2b8f-4f7b-b331-45ae67e52bc9)

**Adjunto link de los archivos cargados en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsTyLCE3MAJGiEluHJ1P5hcB7WXrIE7oOmrf6vBRsR_wVA?e=aJ3wie

Gracias y quedo atento a comentarios

Cordial saludo.

**Comment by jcmurilloa** [comment]
Muy buen trabajo Carlos!
