### ISSUE TITLE
Pruebas funcionales paso cláusulas y parágrafos microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#160]
Se requiere requiere realizar las pruebas funcionales completas al paso de cláusulas y parágrafos que validen el funcionamiento en conjunto de cada una de las implementaciones realizadas.

**Sub Tareas**

- [x] Validación funcionalidad completa del paso de cláusulas y parágrafos, registrando dos contratos y validando al consultar un tercero nuevo (sin registros de cláusulas y parágrafos) que visualice la plantilla basada en el tipo.

**Criterios de aceptación**

- [x] Documentación de los resultados de pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Creación de Ordenes para nuevo contrato sin edición:

https://github.com/user-attachments/assets/2baa0586-b2b7-4bc8-83da-b99511d33636

![Image](https://github.com/user-attachments/assets/bfe982c6-a0a3-4b91-b30e-a90a86fc859a)

### Creación de Ordenes para nuevo contrato con edición, pero sin agregación o eliminación:


https://github.com/user-attachments/assets/7c6c702c-08ed-4d60-885f-e63674148606

![Image](https://github.com/user-attachments/assets/00f72ca4-c3ff-4a47-b592-d7fd47d0edd5)

### Creación de Ordenes para nuevo contrato con edición, agregación y eliminación:


https://github.com/user-attachments/assets/69ba8960-0930-4239-9964-d3a57c893a82

![Image](https://github.com/user-attachments/assets/4dba5100-8863-4125-b38a-78bb546444fc)
