### ISSUE TITLE
Integración registro cláusulas por contrato en microcliente gestión contractual y microservicio cláusulas y parágrafos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#162]
Se requiere continuar con la integración implementada en la Issue #151. 

**Sub Tareas**

- [x] Implementación almacenamiento de parágrafos nuevos (con valor de contrato quemado por el momento).
- [x] Implementación almacenamiento de cláusulas nuevas (con valor de contrato quemado por el momento).
- [x] Implementación actualización de orden parágrafo cuando se elimine un parágrafo (eliminando lógicamente el parágrafo si no es predeterminado).
- [x] Pruebas funcionales

**Criterios de aceptación**

- [x] Documentación de avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
- Microcliente [gestión contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) 
- Microservicio CRUD [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza un avance en dónde ya se guardan registros de clausulas y parágrafos nuevos, además de crear un Orden Clausula para un contrato id nuevo con sus respectivos Orden Parágrafos nuevos.

https://github.com/user-attachments/assets/594875c9-03ad-4780-ad70-697b10fc2e32

![Image](https://github.com/user-attachments/assets/37be1e3f-bfba-44f8-bdfc-a5630e238451)
