### ISSUE TITLE
Integración registro cláusulas por contrato en microcliente gestión contractual y microservicio cláusulas y parágrafos - Parte 3

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#165]
Se requiere continuar con la integración implementada en la Issue #162.

**Sub Tareas**

- [x]  Implementación actualización de orden parágrafo cuando se elimine un parágrafo (eliminando lógicamente el parágrafo si no es predeterminado).
- [x] Implementación registro de contrato mediante orden cláusula y orden parágrafo (los contratos no tienen versionamiento).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Implementación de lógica para eliminar lógicamente las clausulas y paragrafos cuando estas son NO predeterminadas, se observa que se remueven correctamente de su respectivo Orden Clausulas y Orden Paragrafos (cuando hay más de un paragrafo), sin embargo, para los Orden Paragrafos que sólo poseen un paragrafo_id y éste es eliminado todavía falla en realizar tal actualización ¿Se debería dejar un array de paragrafo_ids vacío?

https://github.com/user-attachments/assets/4b5625a5-4ba8-4a91-bdbf-742b392aae77

![Image](https://github.com/user-attachments/assets/f5bdc995-468d-4267-a238-af2b9ebc8b8c)

**Comment by Lau2ri** [comment]
En cuanto al registro de un contrato nuevo mediante Orden clausulas y Orden paragrafos, funciona correctamente la creación de un nuevo Orden clausulas, además del registro de nuevas clausulas editadas en el proceso, sin embargo con los paragrafos se registran los nuevos, pero ocurre un error en la creación de nuevos Orden paragrafos. Se sigue revisando este problema.

https://github.com/user-attachments/assets/2de17b5f-0a04-448d-99f8-527b4dbe525a

![Image](https://github.com/user-attachments/assets/3e8b3ed0-5e64-42d1-a88f-fdb851840d7d)

**Comment by Lau2ri** [comment]
Creación de Ordenes para nuevos contratos:

https://github.com/user-attachments/assets/c9964ce6-a5f5-430b-8f76-6b5605c1e88d

![Image](https://github.com/user-attachments/assets/a4d27879-3036-4f43-8145-4d0edbd5790a)
