### ISSUE TITLE
Adición campos de auditoría microservicio de cláusulas y parágrafos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#169]
Se requiere realizar la adición de los campos activo a las colecciones de orden cláusula y orden parágrafo para una eliminación lógica que permita mantener registros que puedan ser utilizados para la auditoría de cambios y un soporte eficiente. Validación realizada con DBA e infraestructura, donde se sugiere adicionar también dos campos de "creado_por" y "actualizado_por" a cada colección de este microservicio que permita almacenar adicionalmente el id del usuario que efectúa estos cambios.

**Sub Tareas**

- [x] Actualización modelo de datos.
- [x] Actualización README con modelo actualizado y drawio.
- [x] Agregar campo activo en orden cláusula y parágrafo.
- [x] Agregar campos nuevos a cada colección del microservicio (creado_por, actualizado_por).
- [x] Actualizar implementación de eliminación lógica con los nuevos campos.
- [x] Actualización implementación almacenado para contrato.
- [x] Ajuste integración microcliente.
- [ ] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Repositorios**
- [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf)
- [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud)

**Material Apoyo**

Definición almacenado de cláusulas y parágrafos por contrato:
1. Registro orden cláusulas y parágrafo basado en la plantilla original al momento del primer guardado (copia de la plantilla).
2. Si el usuario agregar parágrafos a una cláusula existente y guardar en la misma cláusula, se debe crear el registro del nuevo parágrafo no predeterminado y dicho id nuevo asociarse al orden parágrafo de dicha cláusula.
2.1. Si el usuario edita el mismo parágrafo agregado en el punto 2, se debe realizar una petición PUT para actualizar el mismo parágrafo sin crearse uno nuevo (dado que ese parágrafo no es predeterminado).
2.2. Si el usuario elimina esa cláusula se debe hacer la eliminación lógica del orden parágrafo de dicha cláusula y eliminar el id de la lista de ids de orden cláusula, adicional, se debe eliminar lógicamente el parágrafo no predeterminado.
3. Si se agrega una nueva cláusula, se debe crear la nueva cláusula no predeterminada y asociarse en orden cláusula al contrato.
3.1. Si se agregan parágrafos, estos serán no predeterminados, por lo que se crean los registros en parágrafos y se asocian a dicha cláusula en orden parágrafo.
3.2. Si se elimina la nueva cláusula, se debe realizar la eliminación del id de orden cláusula y la eliminación lógica de orden parágrafo, cláusula y parágrafo.

Nota: Mantener la funcionalidad separada gracias al botón que permite guardar cambios por cada cláusula debe mantener organizado los ids de orden cláusula y se centra en cada orden parágrafo de cada cláusula respectiva.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza la actualización de los campos nuevos en el crud de cada colección y se comprueba su correcto funcionamiento:

### General:

https://github.com/user-attachments/assets/f42737cc-50af-4419-9238-c14aa4c66631

![Image](https://github.com/user-attachments/assets/0c47d0a3-1243-4c5c-a282-6cbf530e7e82)

### Creación:

https://github.com/user-attachments/assets/26164b2b-6e21-4192-8f5f-a8f10b3a7f85

![Image](https://github.com/user-attachments/assets/d85fd36b-7ee7-4b1b-ae35-ee27b4ba89f2)

### Eliminación lógica:

https://github.com/user-attachments/assets/68747cb6-9478-40f2-aba3-cd6c4dd1cd76

![Image](https://github.com/user-attachments/assets/502cbe8b-b821-4a66-a117-e312ffbaeba9)

**Comment by Lau2ri** [comment]
Creación de nuevo contrato al momento de cargarlo por primera vez:

https://github.com/user-attachments/assets/9a48c52d-e4d0-4d8d-8550-00bbc4fabed7

Además de esto se actualizaron los métodos **_post_** y **_put_** del endpoint de **contrato** para adaptarse a los nuevos campos y se volvió a crear todo el contrato de prueba en la base local de Mongo con los campos actualizados.

**Comment by Lau2ri** [comment]
# Pruebas de casos de uso y correcciones necesarias

## Casos de uso exitosos:

✅ Carga de contrato existente
✅ Carga de plantilla y creación de nuevo contrato
✅ Eliminación de cláusulas:
  - Predeterminadas:
    • Remoción de ID del orden de cláusulas
    • Eliminación correcta de parágrafos anidados
  - No predeterminadas:
    • Remoción de ID del orden de cláusulas
    • Actualización del estado activo a falso
    • Eliminación correcta de parágrafos anidados
    
✅ Eliminación de parágrafos:
  - Predeterminados:
    • Remoción de ID del orden de parágrafos
    • Cambio de estado activo a falso si es el último
  - No predeterminados:
    • Remoción de ID del orden de parágrafos
    • Actualización del estado activo a falso
    • Cambio de estado activo a falso si es el último

✅ Guardado de cláusulas editadas:
  - No predeterminadas: Actualización del registro existente
  - Predeterminadas:
    • Creación de nuevo registro con campo predeterminado en falso
    • Actualización del orden de cláusulas con el nuevo ID

✅ Creación de nueva cláusula:
  - Nuevo registro con campo predeterminado en falso
  - Actualización del orden de cláusulas añadiendo el nuevo ID

✅ Guardado de parágrafos editados:
  - No predeterminados: Actualización del registro existente
  - Predeterminados:
    • Creación de nuevo registro con campo predeterminado en falso
    • Actualización del orden de parágrafos con el nuevo ID

✅ Creación de nuevo párrafo:
  - En cláusula sin parágrafos previos:
    • Nuevo registro con campo predeterminado en falso
    • Creación del orden de parágrafos con el nuevo ID
  - En cláusula con parágrafos previos:
    • Nuevo registro con campo predeterminado en falso
    • Actualización del orden de parágrafos añadiendo el nuevo ID

## Fallos detectados y correcciones necesarias:

❗ Detección errónea de modificaciones:
  - La descripción de las cláusulas siempre se detecta como modificada
  - Consecuencias:
    • Creación innecesaria de copias de cláusulas no modificadas
    • Duplicación de registros de cláusulas al crear/editar parágrafos sin modificación de la cláusula
    • Comportamiento replicado en parágrafos, generando copias innecesarias

❗ Actualización de nombres de parágrafos:
  - Al tomar la decisión de nombrar los paragrafos (PARÁGRAFO, PARÁGRAFO PRIMERO, etc) se evidencia un caso de uso en el que si se elimina un parágrafo de un grupo mayor a 1, se realiza su eliminación de manera correcta, pero la actualización de nombres no se evidenciará en base (parágrafo primero eliminado, entonces parágrafo segundo pasaría a ser primero en interfaz, pero en base parágrafo segundo sigue siendo parágrafo segundo) ya que para verse reflejados habría que actualizar paragrafos predeterminados.

**Comment by edwargl7** [comment]
Muy buena la documentación y casos aplicados.

**Observaciones**
- Eliminación de parágrafos:
Se menciona "Cambio de estado activo a falso si es el último" para parágrafo predeterminado, los parágrafos predeterminados desde el módulo de registro de plan no pueden desactivarse. Si el cambio mencionado se refiere a orden parágrafo, se encuentra correctamente aplicado.
- Detección errónea de modificaciones. Se revisará en la planning la solución requerida para evitar la duplicación siempre (cláusulas y parágrafo).
- Actualización de nombres de parágrafos. Dado que en el requerimiento el abogado no requiere ni tiene la posibilidad de cambiar el orden de los parágrafos ni de elegir el número del parágrafo se puede dejar en cada parágrafo un nombre genérico o sin nombre en caso de no ser obligatorio y la lógica de nombrado según el orden que tengan ser utilizada en el renderizado de la minuta. Esto dado que el nombrado de los parágrafos puede variar según el caso de cada contrato, principalmente cuando se elimina uno como lo comentas en el caso de prueba, que para la plantilla se conserva el nombre basado en la numeración, pero para el contrato por eliminar alguno ya puede cambiar, y al ser compartidos esto implica que no podemos cambiarles el nombre a los no predeterminados.
