### ISSUE TITLE
Diseño modelo de base de datos - Gestión contractual y orden de compras y servicios - parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#17]
Se requiere realizar el diseño inicial del modelo de base de datos basado en las tareas previas del sprint 0 y sprint 1, en las que se identificaron los microclientes y se observaron parte de los formularios con los campos principales en el diligenciamiento de los módulos de gestión contractual y orden de compras y servicios. Estos cuentan con similitudes en los datos requeridos para el registro, por lo tanto, se busca en esta primer etapa tener presente la similitud para crear un modelo que permita reutilizar este diseño.

Tener presente los servicios existentes que se pueden integrar:

- [terceros_crud](https://github.com/udistrital/terceros_crud) nos permite obtener la información de los usuarios de la Universidad
- [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid) y [documentos_crud](https://github.com/udistrital/documentos_crud) que nos permiten almacenar y gestionar soportes de archivos en diferentes formatos.
- [parametros_crud](https://github.com/udistrital/parametros_crud) cuenta con el CRUD en el que podemos registrar los datos paramétricos.

**Material de apoyo**
- [Modelo de Datos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Especificaciones técnicas**

1. Se debe crear el modelo de base de datos teniendo presente la división de los microclientes, que dan la base para la separación en microservicios.

**Sub Tareas**

- [ ] Diseño de diagrama con el modelo de datos de cada microservicio basado en los microclientes.

**Criterios de aceptación**

- [ ] Diagrama con el modelo de base de datos de cada microservicio partiendo de la división de microclientes.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Diagrama del modelo de base de datos almacenado en la carpeta de documentación de ARGO.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Agregada a la carpeta de ARGO las grabaciones de las capacitaciones del sistema actual para tener presente e identificar el impacto en el módulo de gestión contractual y orden de compras y servicios.

**Comment by mau-oati** [comment]
Basado en las novedades de la semana, se re ajustó la tarea para que el objetivo sea clarificar los posibles MS y sus orígenes de datos.

**Comment by mau-oati** [comment]
![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/52d25436-492e-4e18-aa3e-a227ad190435)

**Comment by edwargl7** [comment]
Buen trabajo, subir diagrama a la carpeta por favor. En una siguiente etapa se ampliará en más detalle el modelo de datos una vez identificados los cambios que se puedan hacer y que no afecten a otros sistemas, dado que se han identificado sistemas que consumen información de ARGO, por lo que modificar el sistema puede afectar a otros. Se procede a realizar una revisión detallada para identificar los cambios y módulos independientes y el plan a seguir con los módulos que suministren información a otros sistemas.

Dentro de los evidenciados hasta el momento se tienen:

1. Supervisores -> Cumplidos, novedades
2. Acta de inicio (fechas) -> Titan
