### ISSUE TITLE
Registro información presupuestal en microcliente gestión contratos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#170]
Se requiere realizar la implementación para el registro de la información del paso 2 del registro de contrato (sin ordenador) integrando el microservicio MID y CRUD. Adicionalmente, la información obtenida del CDP debe organizarse y presentarse en el paso 5. Implementando la selección en caso de tener más  de un CDP.
![image](https://github.com/user-attachments/assets/62ae8604-fe1a-459e-a6a8-14ecbb983012)
![image](https://github.com/user-attachments/assets/6e148af1-cd0d-4aae-b6e0-9d14e208a210)

Vista para más de un CDP.
![image](https://github.com/user-attachments/assets/0c7d3553-9d40-4381-8fa9-f50a7d89604e)

**Sub Tareas**

- [x] Integración microcliente y microservicios con la información del paso 2.
- [x] Distribución de información relacionada al CDP en el paso 5.
- [x] Implementación ajustes microcliente para selección y ajustes en caso de contar con más de un CDP.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Dudas: 
En el paso 2, el ordenador del gasto se obtiene desde parámetros crud?

**Comment by mau-oati** [comment]
Se encuentran limitantes para mantener la idea original del modal, por la naturaleza del paso de datos que maneja Angular, lo que acomplejaría el componente y sobrecargaría la carga y proceso de los datos en cada modal.
Luego de las pruebas se consideró mas adecuado trabajar con un accordeon. 

![Image](https://github.com/user-attachments/assets/7aa74736-d978-4d0a-af30-80e3aae4c0d3)

**Comment by mau-oati** [comment]
De modo que la información se muestre con un toggle que mostrar o ocultar, en la misma página donde se está editando.

**Comment by mau-oati** [comment]
Se inician pruebas de manejo por acordeones para completar la tarea.

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/844817d2-1a4a-4cc9-8238-58fcffea0608

**Comment by mau-oati** [comment]
Se usaron los campos:
- Justificación
- Descripción
- Observaciones

Pues el objeto CDP solo cuenta con estas propiedades:
```json
{
	"cdp": {
		"vigencia": "2024",
		"descripcion": "Cesantías",
		"rubro_interno": "1234",
		"estado": "APROBADA",
		"justificacion": "LA FACULTAD....",
		"id_sol_cdp": "3325",
		"nombre_dependencia": "FACULTAD",
		"fecha_registro": "2024-07-05T00:00:00.000+00:00",
		"observaciones": "SUELDO BÁSICO",
		"numero_disponibilidad": "2314",
		"num_sol_adq": "4874",
		"valor_contratacion": "2085261868",
		"estadocdp": "VIGENTE-AGOTADO"
	}
}
```

**Comment by edwargl7** [comment]
Se revisará el endpoint de CDP para complementar la información requerida para el paso de Obligaciones del contrato.
Muy buena implementación y manejo de la funcionalidad para la diferente cantidad de CDP seleccionados. Se revisará con @cjgonzalezp la funcionalidad documentada.

Se debe revisar si se afecta que según el caso se muestre el paso de especificaciones técnicas.
![image](https://github.com/user-attachments/assets/52f9ac35-ed43-499b-b79b-18b1d2128301)

**Comment by jcmurilloa** [comment]
Por favor tener presente la vista de múltiples CDP para el rol de abogado de contratación, con el fin de permitir mayor funcionalidad en este apartado.
