### ISSUE TITLE
Creación de historias de usuario de Registro de contrato - parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#171]
Se requiere realizar la documentación de las historias de usuario para el módulo de registro de contratos, pólizas y acta de inicio desde el rol del abogado.

**Sub Tareas**

- [x] Documentación de las historias de usuario para el módulo de registro de contratos pólizas y acta de inicio desde el rol del abogado.

**Criterios de aceptación**

- [x] Documentación de las historias de usuario para el módulo de registro de contratos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día

Se avanza en la documentación del formato HU para el submódulo registro de contrato - rol abogado.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Formatos%20HU/HU-%20Historia%20de%20Usuario%20Subm%C3%B3dulo%20Registro%20Contrato.xlsx?d=wf1e84efe67cb4070a092f5a0a6e4d42a&csf=1&web=1&e=OjYsrW

Saludos.

**Comment by jcmurilloa** [comment]
My buen avance @cjgonzalezp, en el review evaluaremos pólizas y actas de inicio para el seiguiente sprint.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza parte dos de la creación y documentación del formato HU registro de contrato.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Formatos%20HU/HU-%20Historia%20de%20Usuario%20Subm%C3%B3dulo%20Registro%20Contrato.xlsx?d=wf1e84efe67cb4070a092f5a0a6e4d42a&csf=1&web=1&e=59gR65


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, continuaremos en el siguiente sprint la parte final
