### ISSUE TITLE
Ajustes despliegue microcliente gestión contractual ambiente pruebas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#172]
Se requiere realizar el ajuste y apoyo en el despliegue del microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf)

**Sub Tareas**

- [x] Ajustes requeridos durante el despliegue.

**Criterios de aceptación**

- [x] Referencia commits de ajustes aplicados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se hacen ajustes del tamaño del size y ajustes del package.json. Se revisan formas de optimizar la librería quill.

**Comment by mau-oati** [comment]
Se están validando pruebas locales de manejo de rutas, y formas de importar menos elementos de Quill para recudir los tamaños de los compilados. Se sigue revisando.

**Comment by edwargl7** [comment]
Pendiente comentarios revisados en la planning para poder finalizar la Issue.

**Comment by mau-oati** [comment]
Se revisaron estrategias de Lazy loading y segmentación de rutas. Luego de las pruebas no hubo mejora, se confirmó que el tamaño es por el uso de las librerías externas como Quill y SweetAlert. Se revisan estrategias con otras librerías para el caso de Quill con el fin de reducir el tamaño.

**Comment by edwargl7** [comment]
Se finaliza la Issue. Se continuará la revisión posteriormente. Muchas gracias.
