### ISSUE TITLE
Integración CDP y estado contrato microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#174]
Se requiere realizar el registro del estado a "Por suscribir" al momento de registrar el contrato. También se requiere la integración del registro del CDP(s).

**Sub Tareas**

- [x] Registro del estado al momento de crear el contrato.
- [x] Integración registro de información de CPD o CDPs asociados al contrato.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Tipo de parámetro para estados 137
Estado POR SUSCRIBIR - 6773

**Comment by mau-oati** [comment]
### Guardado de CDPs:
![Image](https://github.com/user-attachments/assets/5dc04973-ce11-46a9-aa76-eacc6f5672b2)


### Implementación Inicial de estado:

![Image](https://github.com/user-attachments/assets/81e8922e-b5cb-45aa-b76c-c0f5ca3d37af)

![Image](https://github.com/user-attachments/assets/9d134b33-369d-47db-9c97-b3c4f339d263)

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR. Se podría cambiar la consulta del estado.
De 
```
parametro?query=Id:' + environment.ESTADO_POR_SUSCRIBIR + '&limit=0
```
Por 
```
parametro/environment.ESTADO_POR_SUSCRIBIR
```
![image](https://github.com/user-attachments/assets/cdacc8e6-928a-4824-b2a1-2cba40372de2)
