### ISSUE TITLE
Integración cláusula reversión de saldos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#175]
Se requiere realizar la implementación para la asignación de una cláusula nueva especifica para el caso de reversión de saldos en el paso de información presupuestal.
![image](https://github.com/user-attachments/assets/4f624912-f573-4ea3-82b1-06bfd8ba27d5)

**Sub Tareas**

- [x] Revisión cambios en la descripción de cláusulas y parágrafos para evitar duplicación sin cambios (relacionada a la Issue #169  Detección errónea de modificaciones)
- [x] Creación de variable para validación de cláusula adicional.
- [x] Implementación en el CRUD agregando campo de reversion_saldo de tipo booleano a la colección de plantillas endpoint POST, GET plantilla por tipo de contrato.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se exploran distintas posibilidades de por qué el editor de texto enriquecido implementado está detectando cambios incorrectamente (siempre marca como modificado aunque no haya cambios reales) y sus posibles soluciones:

### 1. Eventos de inicialización confundidos con cambios reales

**Problema**
El editor Quill puede estar emitiendo eventos de cambio durante la carga inicial del contenido, lo que hace que el sistema interprete esta carga inicial como una modificación del usuario.

**Solución**
Implementar un sistema de tracking del valor inicial y un flag de inicialización. Esto permite comparar los cambios subsecuentes contra el valor original real, ignorando los eventos de carga inicial.

### 2. Normalización automática del HTML

**Problema**
Quill realiza normalizaciones automáticas del HTML (añadiendo/eliminando espacios en blanco, normalizando etiquetas, etc.). Esto puede hacer que contenido visualmente idéntico sea técnicamente diferente a nivel de string.

**Solución**
Implementar una función de normalización personalizada que procese tanto el contenido inicial como los cambios posteriores de la misma manera, permitiendo comparaciones más precisas y evitando falsos positivos por diferencias en el formato HTML.

### 3. Frecuencia excesiva de eventos de cambio

**Problema**
El editor puede estar emitiendo eventos de cambio con demasiada frecuencia, lo que dificulta determinar cuándo ha ocurrido un cambio significativo real.

**Solución**
Implementar técnicas de debounce y distinctUntilChanged para reducir la frecuencia de eventos y asegurar que solo se procesen cambios significativos. Esto ayuda a filtrar micro-cambios que no representan modificaciones reales del contenido.

### 4. Manejo incorrecto del estado del formulario

**Problema**
El componente padre puede estar interpretando incorrectamente el estado del formulario o no estar manejando adecuadamente las propiedades dirty/pristine.

**Solución**
Asegurar un manejo apropiado del estado del formulario en el componente padre, utilizando las propiedades correctas de Angular Forms para detectar cambios reales y verificar el estado del formulario antes de procesar las actualizaciones.

**Comment by Lau2ri** [comment]
Se ajusta el componente del editor para que detecte los cambios del texto correctamente comparándolo con el estado inicial del mismo, esto soluciona el problema de detección errónea de cambios:


https://github.com/user-attachments/assets/e47aba68-f7c4-415e-b8fb-46a6647b0e2c

![Image](https://github.com/user-attachments/assets/0dc75c37-20a4-4db7-844c-1ea38a0101b4)

Esto  me permite ajustar el botón y poder dejarlo deshabilitado todo el tiempo y sólo habilitarlo cuando el usuario haga un cambio en el texto:


https://github.com/user-attachments/assets/f95d8ca8-b3fb-4918-82f9-d8b2f268cebe

![Image](https://github.com/user-attachments/assets/5e8a74f5-2291-4e2f-9541-fedaeebc3199)

Además se ajusta el nombrado de los parágrafos como se había comentado en el planning de esta semana, dejando en base de datos a todos los parágrafos con el nombre "PARÁGRAFO." sin cambiarlo ni enumerarlo en ningún momento, pero en la interfaz el usuario si podrá visualizarlos enumerados para que sea más cómodo:


https://github.com/user-attachments/assets/b65235ba-1997-45cf-b347-b7d65ce67254

![Image](https://github.com/user-attachments/assets/4eee7b37-9e51-449e-86a9-4ae3fcbf6387)

Por último, ya se creó la nueva plantilla (con el nuevo campo reversion_saldo) que contiene un orden parágrafo diferente que la plantilla original asociado a la cláusula de "Valor del contrato.", para este caso particular el original tiene un solo parágrafo, y para la segunda plantilla entonces tiene un orden parágrafo con 2 parágrafos añadiendo el parágrafo adicional:

<img src="https://github.com/user-attachments/assets/5e5f690c-cd29-49a8-915a-c6fa9169d047" width=400>

**Comment by Lau2ri** [comment]
### Pruebas funcionales endpoint:

https://github.com/user-attachments/assets/2efdfca5-5d7c-4283-ac41-42ed8f96d330

![Image](https://github.com/user-attachments/assets/e3bdaf69-512a-4380-80ad-61b6c38b08e2)

### Pruebas funcionales microcliente:

https://github.com/user-attachments/assets/324ab0b2-bf1e-44ed-b872-30c576497883

![Image](https://github.com/user-attachments/assets/fcc67cd7-75a1-4e69-b311-18b847d38f78)

**Comment by edwargl7** [comment]
Muy buen desarrollo y documentación, se revisará el PR antes de pasar la tarea a review. Muchas gracias.

**Comment by Lau2ri** [comment]
Se valida la revisión que quedó pendiente de si el botón de guardar se habilitaba al agregar parágrafos y cláusulas nuevos, se procede con los PR.

https://github.com/user-attachments/assets/ff8b6483-a170-48a3-9505-669df808ffb9

**Comment by edwargl7** [comment]
Muy buen trabajo. Control de cambios propuesto permite un muy buen manejo para el usuario. Documentación completa.
