### ISSUE TITLE
Integración manejo de contratista según tipo de persona microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#176]
Se requiere realizar la implementación del manejo del contratista según el contrato que tenga en la vigencia y el tipo de persona.

**Sub Tareas**

- [x] Integración consulta de contratos por vigencia.
- [x] Implementación modales según sea el caso.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Basado en la consulta que realiza el endpoint se observa que la query valida contra la fecha de la consulta y la fecha fin del contrato que si es mayor o igual a la fecha fin si retorna el contrato por documento de identidad.
Por lo tanto, 
- se plantea validar que si es persona natural y tiene un contrato se muestra el siguiente modal.
- Este modal nunca se mostrará para persona diferente a persona natural
![image](https://github.com/user-attachments/assets/9affdae5-2d27-4793-b819-51b8db7cc585)

- Este modal no se observa que pueda ocurrir para persona natural dado que si ya se finalizó el contrato no traerá nada.
- Para persona diferente a persona natural si pueda ocurrir este caso, por lo tanto, se mostrará de la siguiente forma los contratos que tenga activos:
1178 - En Ejecución
1198 - En Ejecución
![image](https://github.com/user-attachments/assets/50053d0b-48b2-4e19-bd75-b6e582e08ec2)

FYI: @Lau2ri

**Comment by Lau2ri** [comment]
Se añade el modal en caso de que la consulta retorne un contratista con un contrato vigente, debido a que no se posee el número de identificación de una persona de tipo jurídica que posea contratos vigentes, no se puede realizar esta prueba, sin embargo la estructura para esta validación quedó creada y debería funcionar exactamente igual que para una persona natural:

https://github.com/user-attachments/assets/14a3c644-f6a1-40ca-aea5-0610bbc742d8

![Image](https://github.com/user-attachments/assets/71377e78-467c-4ff6-9721-7ef46beb1365)

**Comment by edwargl7** [comment]
Buena implementación, para la prueba se observa correctamente el comportamiento esperado. 
Se revisará con @cjgonzalezp si es requerido mostrar la información del contrato en la información del contratista directamente, dado que el modal presenta dicha información.
![Image](https://github.com/user-attachments/assets/eba4bf47-93cf-41bb-8bff-1c0635d4b13c)

Se realiza la revisión con el arquitecto y se observa que para persona jurídica en Producción los contratos diferentes a CPS no cuentan con estado finalizado, tampoco acta de inicio, ni manejo de novedades por lo que de ser necesario se podría consultar por vigencia, pero al no contar con un proceso de finalización del contrato, se plantea calcular la fecha de finalización del contrato tomando la fecha de suscripción más el plazo, sin embargo, como no cuentan con un estado de ejecución podría no necesariamente calcularse de esta forma la fecha fin correcta de dicho contrato. Se requiere el apoyo de @cjgonzalezp para validar el manejo requerido para poder efectuar la validación de dicha información o si el flujo es diferente no se mostraría ningún modal para persona jurídica.
