### ISSUE TITLE
Creación de historias de usuario de legalización e inicio de ejecución de contrato

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#177]
Se requiere realizar la documentación de las historias de usuario para el módulo de pólizas y acta de inicio desde los diferentes roles.

**Sub Tareas**

- [x] Documentación de las historias de usuario para el módulo de registro de pólizas y acta de inicio.

**Criterios de aceptación**

- [x] Documentación de las historias de usuario para el módulo de registro de contratos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la creación del documento HU para los submódulos pólizas y acta de inicio.

**Enlace documentos guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Formatos%20HU?csf=1&web=1&e=BZmTkf


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la documentación del formato HU para los submódulos registro y consulta de pólizas y registro de actas de inicio.

**Enlace documentos guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Formatos%20HU?csf=1&web=1&e=jYfM7W


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente exponer estos formatos al usuario al momento de exponer el sistema.
