### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de muestra de avance del sistema con funcionamiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#178]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de muestra de avance del sistema con funcionamiento

**Sub Tareas**

- [x] Concertar reunión con funcionamiento.
- [x] Desarrollar la reunión con funcionamiento.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se programa reunión con Funcionamiento -OATI para la presentación de avances del sistema ARGO V2 el día miércoles 30 de octubre de 2024 hora: 2:00 pm.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se proyecta acta de reunión de la presentación de avances del sistema ARGO V2 al equipo de funcionamiento de la OATI. Agradezco tus comentarios y visto bueno para proceder a recolectar las firmas de los presentes.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20-%20Presentaci%C3%B3n%20avances%20ARGO%20V2?csf=1&web=1&e=HqM6Bt


Saludos.

**Comment by jcmurilloa** [comment]
Acta revisada y con VoBo para recolección de firmas.

**Comment by cjgonzalezp** [comment]
Buen día,

Se da por finalizada la issue con la recolección de firmas de todos los presentes en la reunión bajo el acta a continuación guardada en la carpeta del proyecto.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2** 
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsX_q8tqZh9LopYxEV_30x4BCNS87FX08U6ucDPzN_MaRA?e=WAqm5U

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp
