### ISSUE TITLE
Diseño, implementación módulo acta de inicio

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#179]
Se requiere realizar el diseño del modelo de datos de acta de inicio contemplando la migración de los datos del ARGO actual. Implementar el CRUD para el registro de actas.
![image](https://github.com/user-attachments/assets/087355b9-914c-4566-9c39-602557529ac8)

**Sub Tareas**

- [x] Diseño tabla en el modelo de datos CORE teniendo presente los lineamientos de modelo relacional.
- [x] Implementación CRUD para actas de inicio en el microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud)
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación diseño, avances implementación y resultados pruebas funcionales.

**Material de apoyo**
- Mockup de acta de inicio (registro de acta de inicio).
![image](https://github.com/user-attachments/assets/993a716c-76d1-4e71-9fce-f0092c1cf893)
- Modelo de datos sistema actual.
![udistrital - argo-modelo-datos-core](https://github.com/user-attachments/assets/4c4b5925-d12d-4283-82f7-e62e4299ecc8)
- Modelo de datos CORE nuevo ARGO
![modelo_propuesta_relacional](https://github.com/user-attachments/assets/ae754870-a5aa-45b6-8170-f4aa056ea23a)
- Repositorio microservicio CRUD
[gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud)
- Repositorio microcliente [acta_inicio_mf](https://github.com/udistrital/acta_inicio_mf)
- Repositorio microcliente root [gestion_contractual_root_mf](https://github.com/udistrital/gestion_contractual_root_mf)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
_Realizando inicio de entorno de desarrollo para gestion de issue_ :arrows_clockwise:

**Comment by EliSLopezM** [comment]
## Propuesta del modelo sobre "acta_inicio"

![image](https://github.com/user-attachments/assets/c0f85acc-d3ec-44c1-b449-6f5738eb9177)

**Comment by EliSLopezM** [comment]
## Correcion del modelo "acta_inicio"

![image](https://github.com/user-attachments/assets/835d6e23-3ef9-4bc2-84ab-10446713f969)

**Comment by EliSLopezM** [comment]
_Validando y Gestionando base de datos local y variables de entorno para corregir funcionamiento inicial del desarrollo_

**Comment by edwargl7** [comment]
Ejemplo de script de creación de base de datos, tener presente los campos activo, fecha_creacion y fecha_modificacion deben estar siempre al final de la creación de cada tabla.
También es requerido agregar la descripción de cada campo. https://github.com/udistrital/usuario_rol_crud/blob/develop/database/scripts/20240626_001109_creacion_tablas.up.sql

**Comment by EliSLopezM** [comment]
## Documentacion de la base sobre la interacion con la nueva tabla "acta_inicio"

[Documento sobre la creacion de la base de datos](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EXyJtd7Fd9lFpqDSF75YpQ0BByWd0qw0ptaKoG8iN4ihdw?e=eA077T)

**Comment by edwargl7** [comment]
Se realiza la revisión de la implementación, se puede generar el PR (necesario bajar cambios de develop antes de solicitar el PR). Por favor actualizar el swagger y agregar las pruebas funcionales del controlador implementado.

**Comment by EliSLopezM** [comment]
## Pruebas Swagger

* GET obtener actas de inicio:

![image](https://github.com/user-attachments/assets/79e9e617-3cd7-4211-939c-cea004148444)

* GET acta por id

![image](https://github.com/user-attachments/assets/a448749c-26e9-4b69-a23b-8c5e3948b3f4)

**Comment by EliSLopezM** [comment]
## Complementacion pruebas swagger

* POST creacion de un acta

![image](https://github.com/user-attachments/assets/cbc71040-2940-48f8-ae3f-27465456707f)

![image](https://github.com/user-attachments/assets/00f173aa-b822-469f-a858-e4e20d993de3)


* PUT actualizacion de acta

![image](https://github.com/user-attachments/assets/1e76d0b9-1a1e-4879-9418-21b3c1818589)

![image](https://github.com/user-attachments/assets/2a6007bf-0e1c-4cc6-a97d-8770846cc848)


* GET general o especifico 

![image](https://github.com/user-attachments/assets/478882ce-1e7e-4165-8c54-02c63d585c13)

![image](https://github.com/user-attachments/assets/90cac94a-1b91-4714-8e8d-d580dee60143)


* DELETE cambia ele stadoa ctivo a false

![image](https://github.com/user-attachments/assets/da58b78a-8e28-4c17-9533-7140ef8fd573)

**Comment by edwargl7** [comment]
Buen trabajo, se aprueban los cambios pero se deben resolver conflictos en el PR. Se resolverá el PR después de la presentación.
