### ISSUE TITLE
Preparación presentación estado actual ARGO v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#180]
Se requiere realizar la configuración de los microservicios para la presentación a funcionamiento del estado actual de ARGO v2.

**Sub Tareas**

- [x] Configuración de microservicios para presentación.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se agenda para revisión a las 4 con @mau-oati y @cjgonzalezp

**Comment by mau-oati** [comment]
Video Avance:

https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EbLmYD9-rzFDvkONHUguDdYBwiaAgJWKRxKHL1YyVFeb2A?e=G1XpyH

**Comment by edwargl7** [comment]
Se revisa el diagrama de arquitectura de ARGO v2 como posible para agregar a la presentación.
Issue #136 diseñado por @Lau2ri 
![image](https://github.com/user-attachments/assets/356c815f-3cc8-45b1-82c2-2d833d950098)

**Comment by cjgonzalezp** [comment]
Buen día,

Se crea presentación de los avances, cambios y novedades del desarrollo del sistema ARGO V2.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:p:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/ARGO%20-%20Avances%20y%20Novedades.pptx?d=wfa86186d5f1f495ab7283ba79b3e2616&csf=1&web=1&e=DBeyrG


Saludos.

**Comment by edwargl7** [comment]
Se finaliza la Issue. Muy buena preparación.
