### ISSUE TITLE
Integración endpoint de consulta de contratos proveedor persona natural - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#181]
Se requiere realizar el ajuste en la integración de la consulta de contratos de un proveedor, dado que se realizó el ajuste de la consulta. Esta consulta retorna los contratos de persona natural, en un rango de un año atrás de la fecha de consulta, trayendo de esta forma los contratos y el estado, por lo que se hace necesario validar que no cuente con contrato en ejecución para generar la alerta, si cuenta con estados Por Suscribir, Suscrito o Legalizado se debe presentar al abogado el detalle del contrato.

**Sub Tareas**

- [x] Implementación e integración validación proveedor persona natural (emplear variables de entorno con notación Legacy).
- [x] Pruebas funcionales.
- [x] Implementar pruebas de integración endpoint consulta de contratos del proveedor.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se actualizan las pruebas de integración a los cambios agregados al endpoint y se realiza el test correctamente:

![image](https://github.com/user-attachments/assets/d1f17968-3672-4b7b-afb9-ec96c72c512c)

**Comment by Lau2ri** [comment]
Se realizan las pruebas con un contratista con contrato en estado "En ejecución", debido a que no se tiene un id de contratista que tenga contratos en otro estado distinto, no se pueden probar éstas otras validaciones, sin embargo, la lógica para ello quedó creada y en teoría debería funcionar como se espera:

https://github.com/user-attachments/assets/d5fe018a-cadd-41ca-9722-f9f83895dd68

![Image](https://github.com/user-attachments/assets/e652500e-3d48-46af-a229-e7ae9e017d48)

**Comment by edwargl7** [comment]
Se va a realizar la modificación de datos en la base de datos de ambiente de pruebas para poder replicar el caso de una persona natural con contratos en estado diferente a En ejecución, Finalizado y Cancelado.

**Comment by edwargl7** [comment]
Muy buen trabajo, se crea y resuelve el PR. Se podría agregar el número de contrato que se encuentra en ejecución.
