### ISSUE TITLE
Ajustes en los microclientes error CORS

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#182]
Se requiere realizar la revisión del error "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." generado al acceder a la ruta del microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).

**Sub Tareas**

- [x] Revisión y ajustes por error de CORs.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación resultado de pruebas funcionales.

**Material de apoyo**
- Repositorio [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf)
- Repositorio [gestion_contractual_root_mf](https://github.com/udistrital/gestion_contractual_root_mf)
- Repositorio guía para ajustes de CORS [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [Ajustes despligue mf](https://github.com/udistrital/sga_cliente_calendario_academico_mf/commit/acea3a89d0cc1bbc29d24d2e1101cbe6a71e9cb9)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Error  a Revisar: 

![image](https://github.com/user-attachments/assets/fddfd84a-5b6c-45c3-b5b5-56cdd91bf1c9)

Revisando en la versión desplegada, se rendereiza correctamente el registro:

https://pruebasargomicroclientes.portaloas.udistrital.edu.co/contratos/registrar

![image](https://github.com/user-attachments/assets/037ae0df-3149-470c-91bc-97d5701e22a6)

El error de CORS aparece esporádicamente, pero no parece ser un problema principal. Se encuentran errores como:


- **Ubicaciones crud retorna 403**:
```
GET https://autenticacion.portaloas.udistrital.edu.co/apioas/ubicaciones_crud/v2/lugar?query=TipoLugarId:1&limit=0 403 (Forbidden)
```

- **Parágrafos-cláusulas - Sin url desplegada**:
```
http://localhost:8080/plantilla-tipo-contratos/tipo-contrato/1?query=reversion_saldo:false'
```

- **CDP - Sin url desplegada**:
```
http://localhost:3118/cdps/numeros-disponibilidad?vigencia=2024&unidadEjecutora=01'
```

- **Proveedores - Sin url desplegada**:
```
http://localhost:3000/contratistas?id='
```

**Comment by edwargl7** [comment]
Identificado el error con el arquitecto, se requiere la revisión con infraestructura. Se puede finalizar esta Issue. Muchas gracias.
