### ISSUE TITLE
Implementación query params contrato general - microservicio gestion_contractual_crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#183]
Se requiere realizar la implementación de los query params (query, fields, sortby, order, limit) al controlador getAll de contrato general [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud). Requeridos para la integración de la vista de consulta de contrato.

Ejemplo estructura respuesta:
```json
{
   "Metadata":"metadata",
   "Success":"success",
   "Status":"statusCode",
   "Message":"message",
   "Data":"data"
}
```

**Sub Tareas**

- [x] Implementación query params (query, fields, sortby, order, limit).
- [x] Implementación campo Metadata que complemente el paginado permita retornar cuantos registros bajo el criterio de búsqueda existen.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultado pruebas funcionales.

**Material de apoyo**
![image](https://github.com/user-attachments/assets/25f641c1-e344-4570-a00e-f429b4f6ed51)
![image](https://github.com/user-attachments/assets/d0b4fc57-0e73-46dd-8a4c-814509817e89)
![image](https://github.com/user-attachments/assets/1ade8ac9-64f1-4514-9fa1-77a762c3d133)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se inician pruebas locales de manejo de params.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/87e338c3-e7c4-447b-8659-ec4d887d957c)

Se completan pruebas de order, limit y offset.

**Comment by mau-oati** [comment]
Si embargo sigo resolviendo problemas con el campo field y query que desajustan la consulta cuando no se envían parámetros.

**Comment by edwargl7** [comment]
Muy buen trabajo, se complementa la consulta de Metadata en el siguiente sprint.
