### ISSUE TITLE
Integración datos contratista con microservicio gestion_contractual_crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#184]
Se requiere realizar la integración del microcliente con el microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud) para registrar el contratista asociado al contrato.

**Sub Tareas**

- [x] Integración microservicio gestion_contractual_crud endpoint de registro de contratista.
- [x] Pruebas funcionales. 

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
## Pruebas funcionales de integración con el microservicio gestion_contractual_crud para el registro del contratista:

https://github.com/user-attachments/assets/d811b641-947f-4756-86f8-585f6a1ba314

![Image](https://github.com/user-attachments/assets/1f57b7c5-b155-43b1-b4e2-85d5d91c083d)

![Image](https://github.com/user-attachments/assets/a6f4478c-0c4b-490c-9a57-e922fc0e1381)

**Comment by edwargl7** [comment]
Muy buen trabajo, revisar el controlador presentado porque no retorna el campo contrato_general_id del contratista registrado al contrato, se observa correctamente en https://github.com/udistrital/gestion_contractual_crud/blob/feature/info-presupuestal/src/contratista/entities/contratista.entity.ts.
