### ISSUE TITLE
Integración microservicio con el microcliente - Actas de inicio

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#185]
Se requiere realizar la integración del microservicio para el registro de las actas de inicio asociado al id de contrato (usar un id quemado en el microcliente).

**Sub Tareas**

- [x] Ajuste campo user_legacy a usuario_legacy para mantener el mismo nombre de campo de la tabla de contrato general.
- [x] Implementación integración tercero id del usuario que realiza el registro del acta de inicio.
- [x] Integración microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud) para registro de acta de inicio con [acta_inicio_mf](https://github.com/udistrital/acta_inicio_mf).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se compartirá un ejemplo para obtener el id del usuario por el momento sin cifrar el dato obtenido.

**Comment by EliSLopezM** [comment]
Se ajusto el campo user_legacy a usuario_legado para mantener el mismo nombre de campo de la tabla de contrato-general y la tabla acta-inicio en la abse de datos y en [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud).

```postgres
ALTER TABLE acta_inicio RENAME COLUMN user_legado TO usuario_legado;
ALTER TABLE contrato_general RENAME COLUMN usuario_legacy TO usuario_legado;
```

**Comment by edwargl7** [comment]
Te puedes guiar de https://github.com/udistrital/gestion_contractual_mf/tree/develop/src/app para los servicios.

**Comment by EliSLopezM** [comment]
## Estado actual

![image](https://github.com/user-attachments/assets/acd58ef5-b9ce-4013-9c24-a5515bdf5c3a)
![image](https://github.com/user-attachments/assets/931a801f-75fa-4a06-8539-6d182ac8fdf6)

Al realizar la integracion del servicio user, se encuentra que al querer guardar el id del usuario al momento de registrar el acta de inicio se guarda un valor nulo, locaul se esta corrigiendo este comportamiento 

Adicional a esto durante las pruebas la integracion de  [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud) para registro de acta de inicio con [acta_inicio_mf](https://github.com/udistrital/acta_inicio_mf), se realiza de manera correcta solo en los campso de esta tabla, los cuales son ( usuario_legado, descripcion, fecha_inicio, fecha_fin)

**Comment by EliSLopezM** [comment]
## Estado de tarea 

Se corrigio la tare actual sobre el id del usuario, la cual se realizo las pruebas con el usuairo "utest01", debido a que el usuario "utestvice" no tiene guarda el id del localStorage, debido a que no tiene el campo (perdona_id)

![image](https://github.com/user-attachments/assets/88ecd906-34e7-4c8d-8efb-7d1f26b185c0)


Como final se muestra pruebas del envio de post a [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud), con los campos de id del usuario, fecha de inicio y terminacion

**Comment by edwargl7** [comment]
Buena implementación, posteriormente se cambiará el manejo de excepciones usando snackbar por modales. Cuenta con la implementación tomada de SGA para manejo de datos del tercero que es muy útil para las siguientes integraciones.
