### ISSUE TITLE
Implementación metadata para consulta de contratos en microservicio CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#191]
Se requiere completar la implementación del campo metadata combinado con los diferentes filtros query params que permita obtener los datos complementarios requeridos para el manejo de tablas y paginación.

**Sub Tareas**

- [x] Implementación campo Metadata con conteo según los filtros aplicados.
- [x] Integración cambios PR [microservicio CRUD 3](https://github.com/udistrital/gestion_contractual_crud/pull/3).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/c95169f1-cf74-4cc7-8b37-2f90ec9e2721)

**Comment by mau-oati** [comment]
Se están revisando pruebas locales.

**Comment by mau-oati** [comment]
Pruebas:
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/emrianoa_udistrital_edu_co/ERhnzfcYsCxAun8JVYHYqHQBcK7ZkHf5pTeDF_oREBDD9Q?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=jzadwk

**Comment by edwargl7** [comment]
Muy buena implementación y complemento de metadatos.
Revisar porque el campo de búsqueda query se maneja con JSON.
Se requiere resolver conflicto para mezclar cambios.
![image](https://github.com/user-attachments/assets/31f21fa9-7b26-4f2b-b4ed-e808e058a814)

**Comment by edwargl7** [comment]
Resuelto PR, muchas gracias.
