### ISSUE TITLE
Implementación manejo de pasos según criterio - ocultar/mostrar paso - microcliente gestión contractual mf

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#192]
Se requiere realizar la implementación en el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf) para manejar el paso de especificaciones técnicas y garantías según corresponda.

**Especificaciones técnicas**
La visualización del step especificaciones técnicas en el registro de contrato solo aplica si se elige tipo de compromiso _Orden_.

**Garantías**
Aplica si se elige tipo de compromiso _Orden_, se muestra si se selecciona en el paso 1 (Información de Contrato) el campo _Aplica Póliza_.
![Image](https://github.com/user-attachments/assets/7d4c601f-3514-4f7c-ab5b-035fb8db740e)
![Image](https://github.com/user-attachments/assets/4e244dea-8b70-48d2-9864-441cde6ece47)

**Sub Tareas**

- [x] Implementación manejo del paso especificaciones técnicas.
- [x] Implementación manejo del paso garantías.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se incia revisión para el control de los pasos que se pueden ver o no en el stepper.

**Comment by mau-oati** [comment]
El proceso está más complejo de lo esperado, pues el comportamiento del Stepper es por default estático. Al querer un borrador dinámico, debemos incluir algunos eventos y manejo más complejo.

**Comment by mau-oati** [comment]
Validaciones iniciales de Especificaciones Tecnicas:

![Image](https://github.com/user-attachments/assets/ac06ab9b-fecb-4f07-9e1d-497b520ccc94)
![Image](https://github.com/user-attachments/assets/41c77dc8-4ddd-462d-9ec9-fced66e7ad05)

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/c3097006-ae47-4185-897f-9a37e6c1bc71

**Comment by edwargl7** [comment]
Muy buena implementación y documentación, se resuelve el PR.
