### ISSUE TITLE
Implementar campo de no edición de cláusulas y parágrafos - microservicio cláusulas CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#193]
Se requiere agregar un campo "es_editable" a cláusulas y parágrafos para que los registros predeterminados puedan ser controlados, dado que existen cláusulas y parágrafos que no deben ser editados en el paso de cláusulas y parágrafos por el abogado, ya sea porque dichos campos son diligenciados con datos recolectados en pasos anteriores, o porque el contenido de la cláusula o parágrafo hace parte de una parametrización que no debe ser alterada.
Implementación en el microservicio [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud) y microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).

**Nota:** Este campo solo será asignado en la creación predefinida, las nuevas cláusulas y parágrafos agregadas por el abogado por defecto será true.

**Sub Tareas**

- [x] Agregar campo nuevo en la tabla de cláusula y parágrafo del modelo de datos.
- [x] Implementar nuevo campo en los controladores de cláusulas y parágrafos, por defecto true.
- [x] Actualizar controlador de consulta de plantilla del contrato para que retorne este nuevo campo en cada cláusula y parágrafo.
- [x] Pruebas funcionales microservicio.
- [x] Implementación en el microcliente para mostrar campos de cláusula (título y descripción) solo lectura.
- [x] Implementación para ocultar el botón de eliminación de cláusula cuando "es_editable" es falso.
- [x] Implementación en el microcliente para mostrar campo de parágrafo (descripción) solo lectura.
- [x] Implementación para ocultar el botón de eliminación de parágrafo cuando "es_editable" es falso.
- [x] Pruebas funcionales microcliente.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza la implementación del nuevo campo en los controladores de cláusulas y parágrafos, por defecto true:

https://github.com/user-attachments/assets/d444a414-2ee9-48f5-b091-432beccabe91

![Image](https://github.com/user-attachments/assets/10c8b4ed-f5d5-421f-a2ff-d4b25557a385)

Y se actualiza el controlador de consulta de plantilla por tipo de contrato para que retorne este nuevo campo en cada cláusula y parágrafo:

https://github.com/user-attachments/assets/cd938c1d-75d4-42cf-8331-ff1cdf89f96f

![Image](https://github.com/user-attachments/assets/43af7788-5059-4ea7-9c98-f591385fc187)

**Comment by Lau2ri** [comment]
Se realiza:

✔️ La implementación para mostrar campos de cláusula solo lectura.
✔️ La implementación para ocultar el botón de eliminación de cláusula cuando "es_editable" es falso.
✔️ La implementación para mostrar campo de parágrafo solo lectura.
✔️ La implementación para ocultar el botón de eliminación de parágrafo cuando "es_editable" es falso.

https://github.com/user-attachments/assets/0c479787-72a2-4105-a510-b37b1481dfe9

![Image](https://github.com/user-attachments/assets/6a9b1dcf-ba90-4458-9f3e-286787334a2d)

**Comment by edwargl7** [comment]
Muy buena implementación, se observa actualizado correctamente el modelo de datos. Resueltos PR del microservicio y del microcliente.
Pendiente en los ajustes de estilos, el estilo para los campos deshabilitados que sean más visibles.
