### ISSUE TITLE
Integración OIKOS paso Información Solicitante y Supervisor - microcliente gestión contractual MF

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#194]
Se requiere realizar la integración de OIKOS con el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf) en el paso Información Solicitante y Supervisor.

![image](https://github.com/user-attachments/assets/369896eb-56ce-4fb8-babd-f686ee2aa8df)

**Sub Tareas**

- [x] Reorganizar el orden de los campos en **Solicitante**, dado que debe seleccionarse primero la sede.
- [x] Reorganización **Lugar de Ejecución**, para mantener los selectores según el grupo de información seleccionada.
- [x] Integración selector de SEDE en las secciones _Solicitante_ y _Lugar de ejecución_ con la consulta (Crear variable de entorno para el filtro TipoEspacioFisicoId -> Asociado a consulta de SEDE):
```
/espacio_fisico?query=TipoEspacioFisicoId:38,Activo:true&fields=Id,Nombre&sortby=nombre&order=asc&limit=0
```
- [x] Revisión consulta de dependencias filtradas por sede:
```
/asignacion_espacio_fisico_dependencia?query=EspacioFisicoId:{espacio_fisico_id},Activo:true&fields=Id,DependenciaId&limit=0
```
Ejemplo:
```
/asignacion_espacio_fisico_dependencia?query=EspacioFisicoId:20,Activo:true&fields=Id,DependenciaId&limit=0
```
- [x] Dado que la consulta retorna las dependencias sin orden alfabético y no se puede establecer el filtro dado que el nombre de dependencia es un campo anidado se requiere reestructurar la respuesta implementando un nuevo endpoint en [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid) que retorne una estructura simple de dependencias de la sede consultada ordenadas por el nombre.
![Image](https://github.com/user-attachments/assets/116b6bb7-edc4-4552-bff4-e0a3740c915d)
 
- [x] Integración selector DEPENDENCIAS en las secciones _Solicitante_ y _Lugar de ejecución_ con la consulta implementada en la subtarea anterior.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se requiere revisar el vinculo de Ciudad con Sede

**Comment by mau-oati** [comment]
Revisiones iniciales del endpoint de oikos.

**Comment by mau-oati** [comment]
Se ajustó el orden de los campos, y se completó ajuste de objeto para retornar alfabéticamente , se inician pruebas con el mid.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/bbffd17d-ccc4-4ac6-a73b-06e329586848)

![Image](https://github.com/user-attachments/assets/3e64b96e-77c0-4d1c-832b-87bad180d3f0)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/20e46917-63cd-417c-99c7-aa1eee3e3ab8)

Pruebas con MF

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/a19fb919-885f-4ac3-853e-99bd68c33892

**Comment by edwargl7** [comment]
Muy buen trabajo, se revisa de donde obtener las direcciones de las sedes. Se resuelven los PR.
