### ISSUE TITLE
Implementación endpoints consulta ordenador y supervisor microservicio MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#195]
Se requiere realizar la implementación de los endpoints requeridos para asociar el ordenador y supervisor al microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).
El análisis realizado con apoyo de funcionamiento establece que es requerido consumir los datos del ARGO actual, por lo tanto, se requiere realizar la implementación base, dado que posteriormente se requiere realizar el mapeo de dependencia y sede, la cual complementará la lógica en el microservicio MID.

Ejemplo error generado en ARGO actual cuando no se encuentra información relacionada a la dependencia y sede.
![image](https://github.com/user-attachments/assets/52417737-699b-4af2-b18f-93e5e4a3de32)

Implementar en el microservicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)

**Sub Tareas**

- [x] Implementación consulta de supervisores.
```
/supervisor_contrato?query=Estado:true
```
Ejemplo parámetros adicionales:
```
/supervisor_contrato?query=Estado:true,SedeSupervisor:FICC,DependenciaSupervisor:DEP14
```
- [x] Implementación consulta de ordenadores.
```
/ordenadores?query=Estado:true
```
Ejemplo parámetros adicionales:
```
/ordenadores?query=Estado:true,RolId:1
```
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Ajustando el microservicio de "ordenadores_supervisores_contratacion_mid" sobre los datos que se estan consumiendo necesarios del sistema ARGO, sobre la lógica relacionada con las sedes y dependencias.

**Comment by edwargl7** [comment]
Buen día,

Por favor documentar la Issue con la implementación realizada @EliSLopezM para finalizar el sprint.

**Comment by EliSLopezM** [comment]
## Conclusion de issue 

El código cumple con la mayor parte de los requisitos de la issue:

* La estructura de los Endpoints implementa correctamente con los parámetros de consulta solicitados.
* Los controladores y Servicios están configurados de acuerdo a los parámetros indicados en la issue.
* Con las pruebas básicas existen archivos de prueba para los controladores y servicios, aunque podrían expandirse para cubrir casos con parámetros adicionales y mas especificos 

## Recomendaciones Finales

* Expandir las Pruebas, agrega pruebas que simulen las solicitudes completas con diferentes combinaciones de parámetros (Estado, SedeSupervisor, DependenciaSupervisor, RolId), para verificar la data traida
* Las pruebas de integración (si es posible): Realiza pruebas de integración para verificar el comportamiento completo del microservicio MID en su interacción con el sistema ARGO, para verificar su funcionamiento en el codigo implementado de [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf) y [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)

**Comment by edwargl7** [comment]
Aprobada la implementación y completada correctamente. Muchas gracias.
