### ISSUE TITLE
Implementación cláusula aplica póliza - microservicio cláusulas CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#196]
Se requiere realizar el análisis e implementación para el caso en el que puede o no aplicar póliza, según la selección cambia el contenido de la cláusula de garantías. Esta posibilidad de elegir solo aplica para los contratos tipo de compromiso _Orden_.

**Sub Tareas**

- [x] Implementación manejo de cláusula según criterio de selección.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza la creación de 4 plantillas para los cuatro casos según los criterios de selección (reversión saldos y aplica póliza) y así para la plantilla llamada se crea el contrato según dichos criterios:

https://github.com/user-attachments/assets/6d8e4318-adda-4bb9-97be-215a178081a4

![Image](https://github.com/user-attachments/assets/692e97ac-d395-4876-b2d0-f7e3089fb544)

Se va a revisar el porqué al crear el contrato a partir de las plantillas con aplica_poliza en falso, la clausula queda al final (29) de la lista y no en su lugar (12).

**Comment by Lau2ri** [comment]
Se soluciona el problema de orden de la clausula de garantías, que resultaba ser un error en la consulta de la plantilla lo que hacía que la clausula quedara al final. 

https://github.com/user-attachments/assets/ba1372d6-0ba5-4aa4-8b84-151d59da43c4

![Image](https://github.com/user-attachments/assets/1739c1a3-fc54-498d-ac9e-a95148be9b3c)

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelven los dos PR.
