### ISSUE TITLE
Gestionar la actualización de procedimientos y flujos ante el SIGUD

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#197]
Se requiere realizar la actualización de procedimientos y flujos ante el SIGUD

**Sub Tareas**

- [x] Adelantar contacto para generación de requerimiento de aprobación en contratación
- [x] Generar el seguimiento a la actualización de procedimientos y flujos en el SIGUD
- [x] Adelantar contacto para la actualización de procedimientos y flujos en el SIGUD 

**Criterios de aceptación**

- [x] Envío ante el SIGUD de requerimientos de actualización.
- [x] Procedimientos y flujos aprobados por el SIGUD.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.

**Comment by cjgonzalezp** [comment]
Buen día,

Se agendó reunión con cliente el 14 de noviembre para definir la implementación de unos submódulos del ARGO actual y adicional de revisarán los diagramas y procedimientos que se deben actualizar en el SIGUD.

**documentos a revisar con el cliente para posible actualización en SIGUD**
GC-PR-013 Elaboración y revisión
GC-PR-013 CRP y Pólizas
GC-PR-013 Acta de inicio y custodia del contrato
GC-PR-013-FR-044, Acta de Aprobación de Póliza
GC-PR-013-FR-045, Acta de Inicio de Contrato de Interventoría
GC-PR-013-FR-046, Acta de Inicio de Contrato de Obra
GC-PR-013-FR-047, Acta de Inicio CPS Y OPS
GC-PR-013-FR-049, Solicitud Préstamo de Contratos
GC-PR-013-FR-051, Acta de Inicio Contratos de Compraventa


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

En cuanto a la actualización de diagramas cargados en SIGUD se revisaron los siguientes procesos: 

- GC-PR-013 Elaboración y revisión 
- GC-PR-013 CRP y Pólizas 
- GC-PR-013 Acta de inicio y custodia del contrato 

Los diagramas serán revisados por Beatriz Montenegro en conjunto con la Oficina de Planeación y el Analista del proyecto ARGO V2 para su actualización. El analista Julián dará apoyo y seguimiento para cumplir con el objetivo de actualizar estos diagramas en el SIGUD. 

Por otro lado, se revisaron los formatos de actas de inicio de los diferentes tipos de contrato, se confirma que no requieren actualización y se seguirán usando los formatos actuales, los cuales se tendrán en cuenta en la implementación en la versión 2 del sistema ARGO.  

- GC-PR-013 Acta de inicio y custodia del contrato 
- GC-PR-013-FR-044, Acta de Aprobación de Póliza 
- GC-PR-013-FR-045, Acta de Inicio de Contrato de Interventoría
- GC-PR-013-FR-046, Acta de Inicio de Contrato de Obra
- GC-PR-013-FR-047, Acta de Inicio CPS Y OPS
- GC-PR-013-FR-049, Solicitud Préstamo de Contratos
- GC-PR-013-FR-051, Acta de Inicio Contratos de Compraventa 


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, estaremos atentos al avance de esta actualización
