### ISSUE TITLE
Implementación registro de ordenador en el microservicio crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#198]
Se cambia el alcance de la Issue en la que se requiere el ajuste en el microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud) para el registro de la información del ordenador del sistema actual de ARGO el cual centraliza la información requerida para el nuevo ARGO.

**Sub Tareas**

- [x] Actualización modelo de datos.
- [x] Creación CRUD de ordenador en el microservicio.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y pruebas funcionales.

**Requerimientos**

NA

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realizan correcciones menores de la base para comenzar con la implementación de los endpoints.

**Comment by edwargl7** [comment]
Luego de una revisión con funcionamiento se requiere realizar unos cambios en el registro del ordenador que permita registrar más datos a los propuestos actualmente en el modelo de ARGO v2.
![image](https://github.com/user-attachments/assets/0029eee5-2e1b-4559-8b08-8d37cb12beb0)
Los cambios requeridos son:

Agregar una tabla adicional que almacene la información del ordenador y remover el campo ordenador_id de a tabla de contrato_general.

La nueva tabla debe almacenar:
- tercero_id (ID del ordenador en tercero consultado por documento de identidad para obtenerlo).
- ordenador_argo_id (ID del registro de ordenadores de ARGO v1)
- ordenador_sikarca_id (ID almacenado en ARGO v1 referenciando SIKARCA)
- resolución
- documento_identidad (documento ordenador obtenido de ARGO v1)
- cargo_id
- activo
- fecha_creacion
- fecha_modificacion

![image](https://github.com/user-attachments/assets/da70310d-fbbc-4e80-ad48-e3df8308ab9e)

**Comment by Lau2ri** [comment]
Se realiza la actualización del modelo de datos creando la tabla nueva de ordenadores (a la derecha): 

![image](https://github.com/user-attachments/assets/01f2f51b-49f3-4ee0-8c16-365e275b17b2)

**Comment by Lau2ri** [comment]
El crud de ordenadores es creado den Gestión contractual crud, pero debido a un error desconocido las pruebas fallan, así que quedan pendientes:

![image](https://github.com/user-attachments/assets/7f5cf5dd-b7e9-4821-932b-a96aebbc9a61)

**Comment by edwargl7** [comment]
Se completa la implementación, por favor revisar el fallo y completar las pruebas funcionales.
