### ISSUE TITLE
Ajustes de estilos e integración paso de garantías

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#199]
Se requiere realizar ajustes en el paso de garantías que permita eliminar cualquier amparo y no solamente el último. Además, de realizar ajustes en los estilos.

![image](https://github.com/user-attachments/assets/711199af-76ab-4fea-8272-0e0cd29b1144)

**Sub Tareas**

- [x] Ajustes en la funcionalidad de eliminación.
- [x] Ajustes de estilos.
- [ ] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/8bec3ab4-b3aa-4573-b8d2-84a7816b2713)
![Image](https://github.com/user-attachments/assets/a9494047-6dcb-464e-a6c1-3b80c6ae39b5)

**Comment by edwargl7** [comment]
No requiere tantos ajustes dado que fueron aplicados unos para la presentanción a funcionamiento.
