### ISSUE TITLE
Revisión documentación Argo v1 - Primera etapa

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#2]
Se requiere realizar la revisión de la documentación disponible del sistema Argo v1, para comprender el funcionamiento y los diferentes roles y módulos que tiene el sistema actual.

**Sub Tareas**

- [x] Revisión manual de usuario [MANUAL DE USUARIO DE GESTIÓN DEL SISTEMA DE GESTIÓN CONTRACTUAL - ARGO](https://ti.udistrital.edu.co/sites/default/files/documentacion/2021-02/INS%20SISTEMA%20ARGO.pdf
- [x] Identificar los módulos y roles involucrados en el actual sistema.

**Criterios de aceptación**

- [x] Listar los roles y módulos del sistema Argo v1

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Comentario en el issue con la lista de módulos y roles identificados en la revisión de la documentación.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
**Entidades**:  Órdenes, Contrato, Solicitante, Supervisor, Contratista, CDP, Ordenador de Gasto, Bienes, Servicios.


### - Módulo de Gestión de Compras

**Rol**: Personas autorizadas de la Sección de Compras. 

**Acciones**: 

- Registrar una orden (Compra u orden de servicio).

- Consultar y modificar una orden.

- Registrar elementos y servicios en una orden

- Gestión de contratos de orden de compra y servicios suscritos

- Consultar contratos por vigencia 


### - Módulo de Gestión Contractual

**Rol**: Personas autorizadas de la Oficina Asesora Jurídica y el IDEXUD.

**Acciones**: 

- Registrar un contrato

- Actualizar un contrato

- Registrar elementos a un contrato

- Gestión de contratos suscritos

- Consultar contratos por vigencia

- Gestión modificaciones a contratos suscritos 


### - Módulo de Gestión de pólizas

**Rol**: Personas autorizadas de la Sección de Compras, la Oficina Asesora Jurídica y el IDEXUD. 

**Acciones**: 

- Gestión de pólizas a contratos suscritos

### - Módulo de reportes

**Rol**: Personas autorizadas de la Sección de Compras, la Oficina Asesora Jurídica y el IDEXUD. 

**Acciones**:

Generación de Reportes:

1. Reporte de contratistas (presupuesto)
2. Reporte de contratos cancelados
3. Reporte general de contratos dinámico
4. Reporte general de contratos estático 
5. Reporte contractual
6. Reporte contratistas
7. Reporte interventoria
8. Reporte localización
9. Reporte de supervisores

**Comment by edwargl7** [comment]
Excelente trabajo.
