### ISSUE TITLE
Revisión dependencias de datos del módulo de Gestión Contractual - Dependencia de y sobre ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#20]
Se requiere realizar el análisis detallado sobre cada uno de los datos requeridos en el módulo de Gestión Contractual, identificando que campos son consumidos o se deben consumir de otros servicios y también identificar que datos registrados en ARGO son consumidos por otros servicios.

Esto con el fin de ver la viabilidad de:

1. Unificar el módulo de Gestión Contractual con el módulo de Orden de compras y servicios.
2. Diseñar e implementar un microservicio para la gestión de estos módulos con una base de datos diferente a la base de datos actual, sin afectar otros sistemas.

Para esto se debe crear una tabla con la lista de los campos requeridos en el registro de Contratos en estos módulos identificando las similitudes entre los dos módulos, el consumo de otros servicios para poder realizar el registro y que servicios requieren de estos datos.

**Sub Tareas**

- [x] Registrar todos los campos de los formularios de registro de contrato de los módulos de Gestión Contractual.
- [x] Revisión y registro de cada campo si su fuente es de otro sistema basado en el sistema actual ARGO apoyado con la base de datos del sistema actual. [Ver diagrama en la carpeta de ARGO](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EbS_rdklkDxDo33gYLJ79nkBqGjhDXQgrGdWLDvdNe1k6Q?e=qrdEBS).
- [x] Identificar cuales campos son consumidos por otros sistemas (tarea que se realizará con el apoyo de otros equipos).
- [x] Revisión de similitud en los campos de los dos módulos.

**Criterios de aceptación**

- [x] Lista de campos de los formularios de los módulos de Gestión contractual en los que se especifique si la fuente es de otro sistema y si es fuente para otro sistema.

**Requerimientos**

- [ ] Usuario del ambiente de pruebas de ARGO.
- [x] Modelo de datos del sistema actual de ARGO.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Evidenciar el avance progresivo en cada sub tarea.
- [x] Listado de campos de los formularios de los módulos de Gestión contractual que especifiquen la dependencia de otros sistemas, tanto que sean consumidos por ARGO como desde otros sistemas.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Enlace del archivo donde podemos agregar los avances de esta Issue [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBcCUIhWwEqT5dYoDnjk1ZcQ?e=eAaliN). Muchas gracias.

**Comment by Lau2ri** [comment]
Se empieza a revisar la documentación y material de apoyo pertinente para comenzar con la tarea en forma.

**Comment by edwargl7** [comment]
Por el momento no se tiene usuario en ambiente de pruebas, se debe trabajar con el material disponible (manuales y capacitaciones).

**Comment by Lau2ri** [comment]
Se termina la revisión documental, del material de apoyo y de las grabaciones de capacitación sobre el sistema Argo para comenzar con el llenado de la tabla.

**Comment by Lau2ri** [comment]
Se completó gran parte de la tabla requerida, sin embargo aún quedan unos pocos módulos por terminar de llenar.

**Comment by Lau2ri** [comment]
Se termina de completar toda la sección de Gestión contractual, añadiendo la gestión de contratos suscritos y (por encima) la gestión de elementos y servicios.

![image](https://github.com/udistrital/argo_documentacion/assets/133523053/980a42cd-37b9-45a6-ac9e-e5c893408bf0)

**Comment by edwargl7** [comment]
Se realiza la revisión preliminar en la que se observa una clara y correcta agrupación y reorganización de los submódulos y los campos respectivos a cada formulario y elementos agrupados por cada submódulo. Las columnas faltantes de origen de los datos se abordaran con la tercera capacitación necesaria para una identificación más clara de estos. Muy buen trabajado.
