### ISSUE TITLE
Integración cláusulas con información del contrato - microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#200]
Se requiere realizar el registro de las cláusulas para cada tipo de contrato y la identificación de la fuente de datos requerida para cada cláusula que toma parcial o totalmente los datos del contrato (pasos previos del registro del contrato). 

**Sub Tareas**

- [x] Registro de cláusulas de cada tipo de contrato (registro local, almacenar las peticiones para el ambiente de prueba).
- [x] Identificación de la fuente de datos de cada variable requerida en cada cláusula (tomar el campo del JSON de respuesta del microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud)).
- [x] Identificación de campo que requieren un formato diferente a la fuente.
- [x] Implementación función de formato moneda en [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid).
- [x] Pruebas funcionales en el microcliente de cada tipo de cláusula registrada.

**Criterios de aceptación**

- [x] Documentación avances registro de cláusulas por tipo de contrato.
- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Material de apoyo**
- [Diseño de contratos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Elj4ywUkhIZNhCNu6uk40TwB3jBZ2Yx9INBpmjm762EOjA?e=SaZvBI)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se decide realizar el registro de las plantillas de los contratos de una vez en el ambiente de pruebas, y ya se realizaron los registros de las siguientes plantillas (con sus respectivas clausulas, paragrafos, orden clausulas y orden paragrafos):

### - Contrato de Prestación de Servicios (1)
- Plantilla con: ✔️Aplica Póliza y ✔️Reversión de saldos
- Plantilla con: ✔️Aplica Póliza y ❌sin Reversión de saldos

### - Contrato de Prestación de Servicios Profesionales y Apoyo a la Gestión (2)
- Plantilla con: ✔️Aplica Póliza y ✔️Reversión de saldos
- Plantilla con: ✔️Aplica Póliza y ❌sin Reversión de saldos

### - Contrato de Orden de Servicio (3)
- Plantilla con: ✔️Aplica Póliza y ✔️Reversión de saldos
- Plantilla con: ✔️Aplica Póliza y ❌Sin Reversión de saldos
- Plantilla con: ❌No Aplica Póliza y ✔️Reversión de saldos
- Plantilla con: ❌ No Aplica Póliza y ❌Sin Reversión de saldos


https://github.com/user-attachments/assets/f3948172-e8e8-4eaf-a330-7cdf0ea76f97

![Image](https://github.com/user-attachments/assets/5ea40208-e20c-4653-9086-2a62612c232e)

**Comment by Lau2ri** [comment]
# Identificación de la fuente de datos de cada variable requerida en las cláusula
Las ❌ significan que no tengo claro de dónde puede provenir el dato y que no viene de Gestión contractual crud.
## Contrato de Prestación de Servicios y de Prestación de Servicios Profesionales y Apoyo a la Gestión:
- **Cláusula primera:** {{objeto}} proviene de Sicapital o Sofia
- **Cláusula segunda:** {{actividades}} proviene de Sicapital o Sofia
- **Cláusula tercera:** 
    * {{valorPesos}} proviene de Gestión contractual crud /contratos-generales **en números**, en letras habría que transformarlo.
    * {{numero_cdp_id}} proviene de Gestión contractual crud /cdp
    * {{vigencia_cdp}} proviene de Gestión contractual crud /cdp
    * {{rubro_cdp}} ❌
- **Cláusula sexta:** 
   * {{plazoEjecucion}} proviene de Gestión contractual crud /contratos-generales
   * {{unidadEjecutoraId}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula vigésimo tercera:** {{supervisor}} ❌ :memo: se consultará mediante el servicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)
- **Cláusula vigésimo novena:**
   * {{ciudad_id}} proviene de Gestión contractual crud /lugares-ejecucion
 
### Formatos especiales:
- **Cláusula décimo segunda:** _Tabla_ de amparos
- **Cláusula vigésimo novena:** _Día de la semana y fecha_ actual en la que se crea la minuta

## Contrato Orden de Servicio y Orden de Compra:
- **Cláusula primera:** 
   * {{objeto}} proviene de Sicapital
   * {{especificaciones_tecnicas}} (sólo si aplica) proviene de Sicapital (APLICA SI SE CARGAN EN EL PASO DE ESP TEC) :memo: se almacena en en ms [especificacion-tecnica](https://github.com/udistrital/gestion_contractual_crud/tree/develop/src/especificacion-tecnica)
- **Cláusula segunda:** {{valorPesos}} proviene de Gestión contractual crud /contratos-generales **en números**, en letras habría que transformarlo.
- **Cláusula tercera:** {{modoPago}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula cuarta:**
   * {{numero_cdp_id}} proviene de Gestión contractual crud /cdp
   * {{vigencia_cdp}} proviene de Gestión contractual crud /cdp
   * {{rubro_cdp}} ❌
- **Cláusula quinta:** 
   * {{plazoEjecucion}} proviene de Gestión contractual crud /contratos-generales
   * {{unidadEjecutoraId}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula sexta:** {{supervisor}} ❌ :memo: se consultará mediante el servicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)
- **Cláusula vigésimo tercera:**
   * {{ciudad_id}} proviene de Gestión contractual crud /lugares-ejecucion

### Formatos especiales:
- **Cláusula séptima:** _Tabla_ de amparos (sólo si aplica)

## Contrato de Obra:
- **Cláusula primera:** {{objeto}} proviene de Sicapital o Sofia
- **Cláusula segunda:** {{actividades}} proviene de Sicapital o Sofia
- **Cláusula tercera:** 
    * {{valorPesos}} proviene de Gestión contractual crud /contratos-generales **en números**, en letras habría que transformarlo.
    * {{numero_cdp_id}} proviene de Gestión contractual crud /cdp
    * {{vigencia_cdp}} proviene de Gestión contractual crud /cdp
    * {{rubro_cdp}} ❌
- **Cláusula quinta:** 
   * {{plazoEjecucion}} proviene de Gestión contractual crud /contratos-generales
   * {{unidadEjecutoraId}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula séptima:** {{supervisor}} ❌ :memo: se consultará mediante el servicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)
- **Cláusula decima:**
   * {{ciudad_id}} proviene de Gestión contractual crud /lugares-ejecucion

### Formatos especiales:
- **Cláusula sexta:** _Tabla_ de amparos (sólo si aplica)
- **Cláusula decima:** _Día de la semana y fecha_ actual en la que se crea la minuta

## Contrato de Arrendamiento:
- **Cláusula primera:** 
   * {{nombre_arrendador}} ❌ Ágora (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid) - representante legal
   * {{nit_arrendador}} ❌ Ágora (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid) - representante legal
- **Cláusula segunda:** {{objeto}} proviene de Sicapital :memo: mediante el ms [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid)
   * parágrafo: {{direccion_arriendo}} ❌
- **Cláusula cuarta:** 
    * {{valorPesos}} proviene de Gestión contractual crud /contratos-generales **en números**, en letras habría que transformarlo.
    * {{numero_cdp_id}} proviene de Gestión contractual crud /cdp
    * {{vigencia_cdp}} proviene de Gestión contractual crud /cdp
    * {{rubro_cdp}} ❌
- **Cláusula quinta:** {{modoPago}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula séptima:** 
   * {{plazoEjecucion}} proviene de Gestión contractual crud /contratos-generales
   * {{unidadEjecutoraId}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula vigésimo novena:** {{supervisor}} ❌ :memo: se consultará mediante el servicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)
- **Cláusula trigésimo segunda:**
   * {{ciudad_id}} proviene de Gestión contractual crud /lugares-ejecucion

### Formatos especiales:
- **Cláusula tercera:** _de la totalidad de programas y proyectos de nombre dependencia_ ❌ (POSIBLEMENTE EL MID DEBA CONSULTAR ESTOS DATOS ADICIONALES) @cjgonzalezp :interrobang: -> No requiere variable dado que lo diligencian ellos mismos.
- **Cláusula decimo octava:** _Tabla_ de amparos (sólo si aplica)
- **Cláusula vigésimo novena:** _Día de la semana y fecha_ actual en la que se crea la minuta


## Contrato de Suministro:
- **Cláusula primera:** 
   * {{nombre_contratista}} ❌ Proveedores (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid)
   * {{nit_contratista}} ❌ Proveedores (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid)
- **Cláusula segunda:** {{objeto}} proviene de Sicapital
- **Cláusula tercera:** {{actividades}} proviene de Sicapital
- **Cláusula cuarta:** 
    * {{valorPesos}} proviene de Gestión contractual crud /contratos-generales **en números**, en letras habría que transformarlo.
    * {{numero_cdp_id}} proviene de Gestión contractual crud /cdp
    * {{vigencia_cdp}} proviene de Gestión contractual crud /cdp
    * {{rubro_cdp}} ❌
- **Cláusula quinta:** {{modoPago}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula séptima:** 
   * {{plazoEjecucion}} proviene de Gestión contractual crud /contratos-generales
   * {{unidadEjecutoraId}} proviene de Gestión contractual crud /contratos-generales
- **Cláusula vigésimo séptima:**
   * {{ordenadorId}} proviene de Gestión contractual crud /contratos-generales
   * {{cargo_ordenador}} ❌ :memo: se consultará mediante el servicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)
   * {{sede_id}} proviene de Gestión contractual crud /lugares-ejecucion
   * {{telefono_oficina}} ❌ @cjgonzalezp :interrobang: 
   * {{correo_ordenador}} ❌ :memo: se consultará mediante el servicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid)
   * {{representante}} ❌Proveedores (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid)
   * {{direccion_contratista}} ❌Proveedores (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid)
   * {{telefono_contratista}} ❌Proveedores (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid)
   * {{correo_contratista}} ❌Proveedores (?) :memo: información proveedor ms [proveedores_mid](https://github.com/udistrital/proveedores_mid)
- **Cláusula vigésimo octava:** {{oficina_supervisora}} ❌ @cjgonzalezp :interrobang: 
- **Cláusula trigésimo segunda:**
   * {{ciudad_id}} proviene de Gestión contractual crud /lugares-ejecucion
  
### Formatos especiales:
- **Cláusula decimo quinta:** _Tabla_ de amparos (sólo si aplica)

**Comment by Lau2ri** [comment]
Se implementa la función que convierte cualquier valor numérico en texto en el microservicio de gestión contractual mid, debido a una situación con la base de datos, queda pendiente la prueba con una llamada al endpoint de un contrato, pero por el momento se muestra la funcionalidad con un dato numérico quemado: 

![image](https://github.com/user-attachments/assets/77897a2f-98bd-4237-83de-2097b469fcdc)

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelven las fuentes de los datos pendientes en tú mismo comentario ( :memo: ). Se encuentran unos datos pendientes de revisar con @cjgonzalezp ( :interrobang: ).
Cambiar nombre de la función (convierte número a texto).

**Comment by edwargl7** [comment]
**Rubro**
![image](https://github.com/user-attachments/assets/65ffaf6c-ffd6-47b2-a5a7-4b894b634e79)

**Comment by edwargl7** [comment]
Se requiere revisar con funcionamiento la fuente de teléfonos oficina y correo del ordenador.
