### ISSUE TITLE
Implementación manejo de roles vista de registro de contrato y consulta

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#201]
Se requiere realizar la implementación de manejo de roles basado en los roles del usuario de la sesión basado en la matriz de roles y permisos. Para esto emplear variables de entorno que faciliten el manejo de las comparaciones de roles en caso de ser necesario cambiar alguna (los roles a emplear son los manejados en WSO2).
[Gestión de Usuarios - Módulos y Permisos (1).pdf](https://github.com/user-attachments/files/17902879/Gestion.de.Usuarios.-.Modulos.y.Permisos.1.pdf)

**Sub Tareas**

- [x] Implementación obtención de roles del usuario de la sesión.
- [x] Implementación control de acciones vista de consulta del contrato.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
- Estado anterior protección de roles. Aunque la ruta correspondiente no aparecía en el menú (Registrar Contrato) para el usuario, si este ingresaba la URL directamente, se permitía el acceso: 

![Image](https://github.com/user-attachments/assets/241e3bdd-bdc1-41f2-a9d0-789332897ed7)

![Image](https://github.com/user-attachments/assets/0b4c4f08-9f8d-421d-9618-79ae4f71a06e)

![Image](https://github.com/user-attachments/assets/375d8ebc-cb04-4312-9703-e0e6cebbc7fd)

- Se implementa una validación que garantiza que el usuario solo pueda acceder a las rutas autorizadas según las asociadas a su menú: 

![Image](https://github.com/user-attachments/assets/d4571708-1157-4a33-9f1e-5692e39366f5)

![Image](https://github.com/user-attachments/assets/47e0748e-3ed6-4c55-beda-b626d71527cd)

Si se ingresa a una ruta no correspodiente (que no aparezca en el menú), se muestre una ventana emergente indicando dicha información:

![Image](https://github.com/user-attachments/assets/800c0da8-0ec2-45c5-808b-09813119eef7)

![Image](https://github.com/user-attachments/assets/6df404ce-1d5b-4908-97ee-7c0ac6299cec)

De lo contrario, si permite el ingreso (que aparezca en el menú):

![Image](https://github.com/user-attachments/assets/8de4e35a-3fca-40cd-8e22-547d6ab185fb)

![Image](https://github.com/user-attachments/assets/6431f0de-b110-480d-a2bd-de66b3d4c0e8)

**Comment by edwargl7** [comment]
Muy buen trabajo y documentación, por favor resolver conflictos en el PR.

**Comment by edwargl7** [comment]
Resuelto PR muchas gracias.
