### ISSUE TITLE
Integración especificaciones técnicas con microcliente gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#202]
Se requiere realizar la implementación de los nuevos botones basado en el diseño del analista de la Issue #229.
![image](https://github.com/user-attachments/assets/a8ad5cb3-0d14-445e-a1b1-fed8490ec86f)

**Sub Tareas**

- [x] Implementación botones de Cargue masivo y Añadir especificación en el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).
- [x] Integración entre [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf) y [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud) para el registro de nueva especificación desde el botón "Añadir Especificación".
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en implementación y resultados pruebas funcionales

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se añaden capturas del desarrollo realizado: 

![image](https://github.com/user-attachments/assets/1d455f43-79a2-4100-ae2f-f6ca91e97711)

![image](https://github.com/user-attachments/assets/d46ca6a1-4c6c-47f7-b63e-6db55d1a5967)

![image](https://github.com/user-attachments/assets/076ad22c-809f-4daa-86ee-3aa0b9ae03a1)

![image](https://github.com/user-attachments/assets/8beeaf7c-ea06-41a4-807d-5339e6406079)

![image](https://github.com/user-attachments/assets/a8ca620c-3b84-4cac-8ba2-6c1de7d1117b)

**Comment by edwargl7** [comment]
Se resuelve PR, muy buen trabajo.
