### ISSUE TITLE
Mockup vista contratrista

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#205]
Se requiere realizar el diseño del mockup de las diferentes vistas que involucra al rol del contratista en los módulos de aprobación de contrato y aprobación del acta de inicio 

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos
- [x] Presentar el mockup al equipo SoS
- [x] Realizar ajustes según comentarios del equipo SoS
- [x] Presentar al equipo el mockup definitivo 

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS
- [x] Diseño documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño de mockup de revisión, aprobación y firma de contrato desde el rol contratista.

![Image](https://github.com/user-attachments/assets/2ff26aaa-11e1-4603-891f-c26618c3a348)


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp
