### ISSUE TITLE
Fecha de suscripción modificable, revisar con el usuario ARGO V2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#206]
Se requiere realizar la consulta al usuario sobre el manejo de fecha de suscripción dado que no se manejaría con el proceso de firma electrónica. 

**Sub Tareas**

- [x] Información sobre manejo de fecha de suscripción.

**Criterios de aceptación**

- [x] Detalle de información sobre manejo de fecha de suscripción.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se revisa con el usuario la posibilidad de implementar en ARGO V2 la opción de poder modificar la fecha de suscripción de los contratos en proceso de registro. Sin embargo, el usuario comenta que no sería necesaria la modificación de esta fecha.

**La revisión queda documenta sobre el acta de reunión No 155/2024 Presentación avances del sistema. A continuación, adjunto enlace del documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvqJhN55oI1FsypJ0s8X6ckBNMYIeSaAJT25708oITFyUw?e=wcIlEg

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp
