### ISSUE TITLE
Revisión estilos módulo de registro de contrato ambiente pruebas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#207]
Se requiere realizar la revisión del estado actual del registro de contrato y consulta de contrato (revisión parcial por falta del microservicio crud en ambiente de pruebas) y el apoyo en la creación de una Issue que permita al desarrollador ajustar los estilos teniendo presente no afectar implementaciones como los texto enriquecidos.

**Sub Tareas**

- [x] Revisión parcial del ambiente de pruebas submódulo de registro y consulta de contrato.
- [x] Apoyo creación de Issue de ajuste de estilos.

**Criterios de aceptación**

- [x] Creación de la Issue con las subtareas de ajustes de estilos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la revisión de estilos del módulo de registro de contrato, se crea documento con la lista de ajustes de estilos a realizar en la próxima issue que permita al desarrollador ajustar los estilos solicitados.

![Image](https://github.com/user-attachments/assets/248fea89-4c6e-4945-9e4f-b41027e7c3b1)


**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoJKIEZ0ey5MhXVQddrxxSgBAXcdJV9UQg3mcwixweC3dA?e=r79lOC


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la revisión de estilos del módulo de registro de contrato.

**Enlace documento guardado con la revisión realizada en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoJKIEZ0ey5MhXVQddrxxSgBAXcdJV9UQg3mcwixweC3dA?e=nVKi9U


Saludos.

**Comment by edwargl7** [comment]
Muchas gracias, se utiliza como insumo para el ajuste de estilos y diseño por parte del equipo de desarrollo.
