### ISSUE TITLE
Revisión y creación de plantillas minutas Idexud - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#214]
Se requiere realizar el diseño de las plantillas para parametrización de contratos según su tipo del Idexud.

**Sub Tareas**

- [x] Realizar la investigación según cada tipo de contrato.
- [x] Proyectar las diferentes plantillas.
- [x] Exponer al equipo SoS.

**Criterios de aceptación**

- [x] Plantillas construídas y aprobadas equipos SoS.
- [x] Plantillas documentadas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza revisión y parametrización plantillas de minutas para los tipos de contrato que se implementaran en el sistema ARGO V2 caja ejecutora Idexud. 

**Plantillas revisadas y parametrizadas**
Contrato de alquiler
Contrato de compraventa
Contrato de arrendamiento
Contrato de interventoría

**A continuación enlace de las plantillas guardadas en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EiQZdAFWDDxLmA7uL6VAZ-EBf-8I29ILRsBxtN4HpEI9Lw?e=7vViBQ

Se continuará... con la segunda parte en el siguiente sprint

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp
