### ISSUE TITLE
Documentación módulo de registro de contratos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#216]
Se requiere realizar la documentación técnica del módulo de registro de contrato, incluyendo la información sobre los cambios en el modelo de datos del sistema actual y el nuevo que permitan identificar los cambios a tener presente en la migración. La identificación de las integraciones y las fuentes de datos del nuevo ARGO. Utilizar como guía los documentos compartidos.

**Sub Tareas**

- [x] Documentación repositorios.
- [x] Documentación arquitectura.
- [x] Documentación APIs y endpoints usados.
- [x] Documentación base de datos.

**Criterios de aceptación**

- [x] Documento actualizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Estructura base del documento
![Image](https://github.com/user-attachments/assets/4573c654-6395-4e07-9ca8-60d931c7dc5f)

**Comment by Lau2ri** [comment]
Se comienza el documento de gestión técnica con la redacción de la introducción, objetivos, arquitectura y con la referencia a los endpoints utilizados en el sistema. El archivo de gestión técnica se está trabajando en el siguiente enlace de One Drive

**Comment by Lau2ri** [comment]
Se continúa con la redacción del documento, agregando la documentación de varios de los endpoints y la comparación entre las bases de datos de ARGO v1 con la v2.

**Comment by Lau2ri** [comment]
Se termina la documentación requerida para el alcance de esta tarea.

**Comment by edwargl7** [comment]
Validada documentación inicial. Muchas gracias.
