### ISSUE TITLE
Creación plantillas HTML minuta de contratos e integración con microcliente

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#218]
Se requiere realizar el diseño HTML de las plantillas de la minuta de cada tipo de contrato que cuente con las variables basado en el modelo de datos del microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud). Este HTML debe contar con el manejo de condicionales según corresponda.

Por ejemplo:
![image](https://github.com/user-attachments/assets/ec6d0365-15c9-4032-83b7-7638b9096055)

**Sub Tareas**

- [x] Diseño de plantillas para cada contrato sin incluir las cláusulas.
- [x] Registro de plantillas aprobadas en [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless).
- [x] Integración con el microservicio [plantillas_mid](https://github.com/udistrital/plantillas_mid) para el renderizado de las plantillas.
- [x] Integración microservicio plantillas mid con microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).
![Image](https://github.com/user-attachments/assets/a672d080-15f9-4805-b139-3c4cee5601f5)
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación plantillas creadas y resultado del renderizado de las plantillas creadas.

**Requerimientos**

No aplica

**Material de apoyo**
- [Ejemplo plantillas-jinja2](https://codigofacilito.com/articulos/plantillas-jinja2)
- [Diseño de contratos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Elj4ywUkhIZNhCNu6uk40TwB3jBZ2Yx9INBpmjm762EOjA?e=SaZvBI)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se adjunta carpeta coorespondiente al progreso de las plantillas de contratos: 
[Plantillas.zip](https://github.com/user-attachments/files/17725480/Plantillas.zip)

**Comment by diegobauto** [comment]
Actualización de plantillas: 
[PLANTILLAS.zip](https://github.com/user-attachments/files/17742814/PLANTILLAS.zip)

**Comment by diegobauto** [comment]
- Diseño de la plantilla:

![image](https://github.com/user-attachments/assets/213451bf-d372-495f-8c2f-5b830b850d48)

- Registro de la plantilla: 

![image](https://github.com/user-attachments/assets/d931b9f2-7a0f-4fec-bbf2-22e35477875d)

- Renderizado de la plantilla:

![image](https://github.com/user-attachments/assets/bc8087d8-7dca-4b5a-988e-708cb771536b)

![image](https://github.com/user-attachments/assets/a1be739d-96e0-4016-8654-19527b36f8b2)

Carga de archivos:
[Plantillas.zip](https://github.com/user-attachments/files/17766380/Plantillas.zip)

**Comment by diegobauto** [comment]
- Visualización del contrato:
 
![Image](https://github.com/user-attachments/assets/f007bed2-554b-44f1-bc24-e9953e1670ac)

- Pruebas funcionales (se adjuta carpeta con los documentos pdf generados a partir de la plantilla): 
Carpeta: 
[Pruebas funcionales.zip](https://github.com/user-attachments/files/17782558/Pruebas.funcionales.zip)

EJemplo visualización:
![image](https://github.com/user-attachments/assets/53efe7a3-3ed0-4da9-a710-01750d6dad04)
![image](https://github.com/user-attachments/assets/bcce2bda-9a53-4673-a82d-cbac906ef425)

- Carpeta de archivos utilizados (plantillas, json, script...): 
[data.zip](https://github.com/user-attachments/files/17782563/data.zip)

**Comment by edwargl7** [comment]
Muy buen trabajo y documentación. Posteriormente se ajustará la vista de visualización de la minuta. 
@cjgonzalezp me ayudas con tu revisión por favor.
