### ISSUE TITLE
Inducción integrante nuevo sobre ARGO v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#219]
Se requiere realizar la inducción sobre ARGO al nuevo integrante abordando los cambios frente al sistema anterior, los diseños y funcionalidad proyectada para la nueva versión de ARGO.

**Sub Tareas**

- [x] Presentación de ARGO v2.

**Criterios de aceptación**

- [x] Documentación presentación ARGO v2.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con líder técnico y nuevo integrante para presentarle el alcance, diseños del sistema y los procesos que se llevaran dentro de la versión 2.0. Con el fin de darle un contexto del proyecto y lo que se requiere desde la parte de desarrollo.

**Adjunto relación enlace de la grabación**  
https://udistritaleduco-my.sharepoint.com/:v:/r/personal/cjgonzalezp_udistrital_edu_co/Documents/Grabaciones/Presentaci%C3%B3n%20proyecto%20ARGO%20V2-20241113_150529-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=9s28IP&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp!
