### ISSUE TITLE
Gestionar la actualización del flujo del proceso de vinculación contractual entre OC y OP

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#22]
Se requiere realizar la gestión para la actualización del flujo del proceso de vinculación contractual entre OC y OAP

**Sub Tareas**

- [x] Acompañar la programación de la sesión entre Oficina de Contratación y Oficina Asesora de Planeación 
- [ ] Participar en la sesión entre OC y OAP
- [ ] Apoyar la actualización del flujo del proceso
- [ ] Generar seguimiento de la aprobación del flujo actualizado por parte del SIGUD

**Criterios de aceptación**

- [ ] Acta de sesión
- [ ] Proyección de la actualización del flujo
- [ ] Envío de solicitud de actualización del flujo

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buenas tardes,

Se habla con la Jede de la Oficina de Contratación Diana Pirachican para programar reunión en conjunto con la oficina de planeación para actualizar los diagramas actuales cargados en SIGUD, la jefe me comenta que se tiene previsto realizarla la semana del 27 al 31 de junio según disponibilidad de las partes.


Saludos.

**Comment by jcmurilloa** [comment]
@cjgonzalezp recuerda realizar los comentarios recientes en esta issue para dar por cerrada esta tarea.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta nuevamente al cliente el día 13 de julio de 2024 para gestionar reunión de actualización de procedimientos en SIGUD con planeación. Quedaron de revisar tiempos disponibles, pero no se recibió respuesta concreta. Es decir, que no depende de nosotros.

Agradezco cerrar la issue y en dado caso que se programe la reunión se genere una nueva issue en el sprint que se desarrolle.


Saludos.

**Comment by jcmurilloa** [comment]
Se procede a cerrar la issue debido a que se adelantó la gestión, pero no fue psoible concretar el encuentro entre estas dependencias.
