### ISSUE TITLE
Preparación presentación estado de desarrollo ARGO v2 al usuario final

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#220]
Se requiere realizar la presentación de la comparación de las dos versiones de ARGO, el acompañamiento al equipo de desarrollo y la presentación al usuario.

**Sub Tareas**

- [x] Preparación presentación.
- [x] Presentación al usuario.

**Criterios de aceptación**

- [x] Presentación al usuario.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se crea una presentación en power point para poder presentar las novedades y avances que se tienen a la fecha y así darle un orden al desarrollo de la reunión.

https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EW0YhvofX1pJtyg7p5s-JhYBiEUlrWzXYfqhsnkrwj_iIw?e=eDRcf8


Saludos.

**Comment by edwargl7** [comment]
Se cumplió con el apoyo al usuario y la presentación al usuario.
