### ISSUE TITLE
Implementación reemplazo de variables en las cláusulas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#224]
Se requiere realizar la implementación de un endpoint en el microservicio [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid) usando una función que permita transformar y reemplazar los valores de las variables por el respectivo valor aplicando un color con el que se identifique los valores que el usuario no debe reemplazar y que si reemplaza no se tomaran dichos cambios.
Se requiere un endpoint que al realizar la actualización de cláusula o parágrafo valide si existe en el contenido la transformación para que revierta estos cambios y regrese el valor en el HTML a la variable original.

Ejemplo:
```html
Esto es <span style='color: red;' data-original-value='{{objeto}}'>un texto</span> con <span style='color: blue;'>color</span>.
```
![image](https://github.com/user-attachments/assets/2f35e9b0-2bde-4e25-9abb-9365e6dad9d2)

**Sub Tareas**

- [x] Implementar función que consulte los datos del contrato (usando la función [getContratoTransformed](https://github.com/udistrital/gestion_contractual_mid/blob/develop/src/contrato-general/contrato-general.service.ts#L71) y agregue los valores de variables requeridas en la cláusula (datos complementarios). Esta función será usada para la generación de la minuta también.
- [x] Implementación función de procesamiento de variables a span con estilo y etiqueta de identificación.
- [x] Implementación endpoint de consulta de cláusulas y parágrafos procesados para la vista del paso de cláusulas y parágrafos.
- [x] Implementación endpoint de actualización de cláusula que reemplace los span por el valor de variable nuevamente si aplica y actualice el contenido en el microservicio [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud).
- [x] Implementación endpoint de actualización de parágrafo que reemplace los span por el valor de variable nuevamente si aplica y actualice el contenido en el microservicio [clausulas_paragrafos_crud](https://github.com/udistrital/clausulas_paragrafos_crud).
- [x] Integración de nuevos endpoints con el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y resultados de pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se comienza con el análisis de la función getContratoTransformed y en general de los endpoints ya existentes del mid para poder comenzar con las implementaciones requeridas.

**Comment by Lau2ri** [comment]
Se crea la base del endpoint que se va a trabajar, sin embargo surgen una serie de preguntas que imposibilitan la continuación, en el daily del día de mañana se comentaran con el líder.

**Comment by edwargl7** [comment]
**Pruebas adicionales**
- Modificación parcial del valor de la variables desde el mf.
- Eliminación del texto de la variables desde el mf.


**Validaciones adicionales**
- Conteo de variables en el MID.

En revisión con el equipo se requiere realizar pruebas en el editor antes de continuar con la implementación.

**Comment by Lau2ri** [comment]
## Pruebas del editor de texto

### Clausula original:

<img src="https://github.com/user-attachments/assets/a382a33e-1a8c-4082-858e-0ec12ccb8019" width=500>

### Modificación parcial del texto: Falló ❌
Original:

<img src="https://github.com/user-attachments/assets/396f3f16-a168-4ff4-a639-65f3c423b908" width=350>

Edit:

<img src="https://github.com/user-attachments/assets/5ce854b7-275b-41dc-9e2d-6f285acb8559" width=350>

Al guardar, se crea el nuevo registro en base con los cambios realizados, además se borra el `data-original-value`, y se reemplaza la clausula original por la nueva en el contrato:

<img src="https://github.com/user-attachments/assets/b5cbce65-c030-42f2-8920-086f814b9d9b" width=550>

### Eliminación total del texto: Falló ❌
Original:

<img src="https://github.com/user-attachments/assets/396f3f16-a168-4ff4-a639-65f3c423b908" width=350>

Edit:

<img src="https://github.com/user-attachments/assets/17584324-4344-4047-8bd6-a0a433167a4b" width=350>

Al guardar, se crea el nuevo registro en base con los cambios realizados, además se borra el `data-original-value`, y se reemplaza la clausula original por la nueva en el contrato:

<img src="https://github.com/user-attachments/assets/66d494e4-f20e-488f-9819-44d28fc4c9d3" width=550>

### Esto también ocurre cuando la Clausula es no predeterminada, en vez de crear el registro nuevo, actualiza el registro existente con los cambios.

**Comment by edwargl7** [comment]
Dados los resultados obtenidos y que no se puede garantizar que no se modifique por parte del usuario, y que los cambios pueden afectar la información. Se procede a mantener el comportamiento actual y se continúa en está tarea la obtención de datos para las cláusulas que van a las minutas.

**Comment by Lau2ri** [comment]
Se comienza con realizar los llamados a los respectivos endpoints de dónde se van a sacar las variables, falta hacerles la transformación de los parámetros y filtrar sólo los valores requeridos.

https://github.com/user-attachments/assets/411393f6-2193-408f-9b4a-6ed3f6120706

![Image](https://github.com/user-attachments/assets/7d7b800b-8916-4d22-9f0f-3921a1f99634)

**Comment by Lau2ri** [comment]
Se organiza el json de resultado para dejar solo las variables necesarias para rellenar las clausulas, y muestra solo las variables que existen según el contrato solicitado.

<img src="https://github.com/user-attachments/assets/be4bf910-ca6a-4919-a8ec-5de70ba5abf1" width=400>

A continuación se muestran en morado las variables que faltan por mostrar en el endpoint debido a que no tengo la claridad de que endpoint se deben consultar exactamente.

<img src="https://github.com/user-attachments/assets/5c1fdb90-651b-40b9-bf7d-e15e44844ef8" width=400>

Por otro lado, actualmente el endpoint para consultar el proveedor sólo se puede consultar por número de documento del contratista, así que temporalmente este valor está quemado en código, pero hay que evaluar si para realizar la consulta para este endpoint se proporcionará el documento del contratista en cuestión además del id del contrato, o si se debe hacer de otra manera.

Por último, la función de transformación de variables de parámetros a su respectivo valor ya fue implementada también, sólo que debido a un fallo presentado con el endpoint de parámetros crud, no se pudo probar funcionalmente.

**Comment by edwargl7** [comment]
Objeto y actividades se toma de la información de contrato general.
Rubro se debe consultar mediante el mismo endpoint de consulta de CDP.

Se completará una vez se tengan los endpoints de información del ordenador.
