### ISSUE TITLE
Preparación despliegue microservicios CORE ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#226]
Se requiere realizar la actualización del script de creación de las tablas del microservicio 
[gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud). Actualización repositorio [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid).

**Sub Tareas**

- [x] Actualización modelo de datos agregando campos relacionados al consecutivo de elaboración y número de contrato.
- [x] Actualización con campos y faltantes.
- [x] Unificación script de creación de tablas del microservicio.
- [x] Actualización modelo de datos y variables de entorno en el README.
- [x] Actualización script unificado en el repositorio.
- [x] Agregar drone, entrypoint y Dockerfile al repositorio.

**Criterios de aceptación**

- [x] Actualización del repositorio.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/3444a9de-6da0-43fd-a92e-21f683d8623c)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/796f18b7-7f26-411a-a093-49a64fcbbca9)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/51faf31a-59d8-465f-842b-42e25a78125f)

**Comment by edwargl7** [comment]
Muy buen trabajo, pendiente entrypoint.

**Comment by edwargl7** [comment]
Completada Issue, muchas gracias.
