### ISSUE TITLE
Maquetación vista de aprobación jefe contratación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#227]
Se requiere realizar la maquetación del módulo de aprobación del jefe de contratación en el mf [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).
![image](https://github.com/user-attachments/assets/9b3499bf-9450-4aec-8f27-a4333f525bde)
![image](https://github.com/user-attachments/assets/efd2f611-bdd0-4904-9abe-129a8f041aea)
![image](https://github.com/user-attachments/assets/eff92432-e999-4446-b2a7-17154246278d)
![image](https://github.com/user-attachments/assets/5d295114-8818-400e-a4be-30a04d942143)
![image](https://github.com/user-attachments/assets/7c66a664-7ee6-47fe-8035-67656644f57a)
![image](https://github.com/user-attachments/assets/1a99df93-27af-442e-b81f-d9387cccdce0)
![image](https://github.com/user-attachments/assets/4aabe0db-adc6-41e9-a81e-f8ee9ef6f6f7)

Apoyarse con la implementación de la [Issue 258 de Sísifo](https://github.com/udistrital/sisifo_documentacion/issues/258) [Componente](https://github.com/udistrital/plan_anual_auditoria_mf/tree/develop/src/app/modules/programacion/revision-jefe).

**Sub Tareas**

- [x] Maquetación aprobación del jefe de contratación.
- [x] Integración microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud) para cambio de estado (si se rechaza agregar la observación en el campo motivo).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultado de la maquetación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
- Pantalla inicial: 
![image](https://github.com/user-attachments/assets/fae233b7-d3a8-411c-bc1a-d22f183f27a5)
![image](https://github.com/user-attachments/assets/3ef8c30c-5965-476e-a31c-53653ae25e72)

- Botón "Rechazar Contrato":
![image](https://github.com/user-attachments/assets/235c854c-3c9a-48d4-924a-dbb40dddfe5b)
![image](https://github.com/user-attachments/assets/a8e052a9-7f58-43e7-abcb-2b79579d20f5)

- Botón "Aprobar y Enviar a Ordenador":
![image](https://github.com/user-attachments/assets/4a227add-229a-4293-b3d8-513c9e6e958f)

**Comment by diegobauto** [comment]
Pruebas funcionales (Evidencia): 

- Rechazar Contrato:

Modal de observaciones:
![Image](https://github.com/user-attachments/assets/aad61eab-4e72-480f-9faa-5b81a07e5ae8)

Mensaje de alerta de confirmación de rechazo:
![Image](https://github.com/user-attachments/assets/99df6755-b005-4b50-8024-38a2047e95f1)

Al no ingresar observación (aparece una ventana que indica la revisión de los datos enviados):
![Image](https://github.com/user-attachments/assets/d5ce93a4-298b-4a69-9bb6-62626217fd41)

Al ingresar observación correctamente:
![Image](https://github.com/user-attachments/assets/4ac481c9-95ed-4701-982d-7c6b5f347fda)

Mensaje de alerta de confirmación de rechazo:
![Image](https://github.com/user-attachments/assets/6c8babd4-ce31-43a0-a727-a06b9f658470)

Solicitud correcta:
![Image](https://github.com/user-attachments/assets/54d068e6-784f-440c-a94f-d4101970bb76)

Validación creación de estado:
![Image](https://github.com/user-attachments/assets/62e1f5a9-050e-4244-b34a-9ad26ada2445)

- Apobar y Enviar a Ordenador: 

Mensaje de alerta de confirmación:
![Image](https://github.com/user-attachments/assets/959af753-1890-433f-9744-ce7cccd4d875)

Solicitud correcta:
![Image](https://github.com/user-attachments/assets/334d3934-1855-475d-b389-e302f0b8efa6)

Validación creación de estado:
![Image](https://github.com/user-attachments/assets/d4e19eaf-b388-4c7e-90ce-88b663f4fc0f)

**Comment by edwargl7** [comment]
Muy buena implementación y documentación, se resuelve el PR.
