### ISSUE TITLE
Maquetación vista de aprobación ordenador

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#228]
Se requiere realizar la maquetación del módulo de aprobación del ordenador en el mf [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).

![image](https://github.com/user-attachments/assets/0dbdff1d-19ea-446a-a2e6-cf5ed0584185)
![image](https://github.com/user-attachments/assets/b46148a5-7391-4f37-a50d-08cc2377c66c)
![image](https://github.com/user-attachments/assets/04eb9664-1bc2-4c04-bf4e-d8d942beba81)
![image](https://github.com/user-attachments/assets/e44c906b-c891-4208-a4ba-ce422d27d4a8)
![image](https://github.com/user-attachments/assets/03754457-0c26-4ea7-848e-2b14f41dafc5)
![image](https://github.com/user-attachments/assets/87af99ec-a24d-42b8-a266-af697c4942a0)

**Sub Tareas**

- [x] Maquetación aprobación del ordenador.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultado de la maquetación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
- Pantalla inicial: 
![image](https://github.com/user-attachments/assets/cff61b78-1542-463e-8bb5-bba1ac01f74c)
![image](https://github.com/user-attachments/assets/23deef17-5c22-4ff8-b231-647d6bfeab13)

- Botón "Rechazar Contrato":
![image](https://github.com/user-attachments/assets/03b11a0a-f88d-4d92-8afd-2fbc5ced8b5d)
![image](https://github.com/user-attachments/assets/3b4755dd-a559-4993-b1db-e786278c1748)

- Botón "Firmar y Enviar a Contratista":
![image](https://github.com/user-attachments/assets/3071d18e-2bcb-4011-99a0-a1a5b564944a)

**Comment by diegobauto** [comment]
Pruebas funcionales (Evidencia): 

- Rechazar Contrato:

Modal de observaciones:
![Image](https://github.com/user-attachments/assets/e2159f67-e867-4085-993a-c57343c4e84f)

Al ingresar información de observación:
![Image](https://github.com/user-attachments/assets/87295680-d1db-4651-9ffd-804ba6dd7936)

Mensaje de alerta de confirmación de rechazo:
![Image](https://github.com/user-attachments/assets/7821ef80-9545-40ed-9391-8078456d117b)

Solicitud correcta:
![Image](https://github.com/user-attachments/assets/8cf40917-abc4-4c38-afdd-478dc8dc3e3b)

Validación creación de estado:
![Image](https://github.com/user-attachments/assets/8adacf5a-5034-4abc-8590-ff2c12af16e0)

- Firmar y Enviar a Contratista: 

Mensaje de alerta de confirmación:
![Image](https://github.com/user-attachments/assets/60e1872d-6833-47de-a16c-b66605284541)

Solicitud correcta:
![Image](https://github.com/user-attachments/assets/5276fba7-3369-495f-a792-3b97666d6060)

Validación creación de estado:
![Image](https://github.com/user-attachments/assets/7942de50-e7d9-453a-ac39-daf5568a1f67)

**Comment by edwargl7** [comment]
Muy buena implementación y documentación, se resuelve el PR del desarrollo trabajado reutilizando los componentes de aprobación.
