### ISSUE TITLE
Ajuste diseño mockup especificaciones técnicas y minuta

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#229]
Se requiere realizar el ajuste del paso de especificaciones técnicas con el modal de creación de un registro o edición de una especificación, así como la eliminación.

![Image](https://github.com/user-attachments/assets/e8567f85-1999-44c4-a8ba-c0a42a73c864)

**Sub Tareas**

- [ ] Actualización del paso de especificaciones técnicas.

**Criterios de aceptación**

- [ ] Mockup actualizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza ajuste al mockup de registro de contrato step especificaciones técnicas según lo solicitado por el líder técnico.

![Image](https://github.com/user-attachments/assets/22b4f834-9898-43cd-881e-d44a4f6669ac)

**Enlace archivo actualizado y guardado en OneDrive en la carpeta del proyecto ARGO V2 Registro Contrato - Rol Abogado**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20Contractual/Subm%C3%B3dulo%20Contratos?csf=1&web=1&e=wHOrlw


Saludos.

**Comment by edwargl7** [comment]
Muchas gracias @cjgonzalezp muy buen trabajo.
