### ISSUE TITLE
Proyectar y socializar formato de historias de usuario con cliente y equipo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#23]
Se requiere realizar la proyección y socialización del formato de historias de usuario con cliente y equipo

**Sub Tareas**

- [x] Proyección del formato de historias de usuario
- [x] Socialización del formato de historias de usuario con el cliente
- [x] Socialización del formato aprobado por el cliente con el equipo
- [x] Refinamiento y aprobación del formato por parte del equipo SoS

**Criterios de aceptación**

- [x] Formato de historia de usuario aprobado por los interesados
- [x] Formato de historia de usuario documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día Julián, 

Relaciono avance de las historias de usuarios según requerimientos iniciales solicitados por el cliente para la implementación y parametrización del formulario de registro de contratos en el módulo de gestión contractual.


**Formato Historias Usuarios**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/fcb3283a-6a5e-4b56-a6fa-abe2a7365cf1)

**Link de archivo cargado en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkgXy3AxizNCpjJdxIxQ3S4BM5UCaqWmnxqisBwTlDhDDg?e=lUkrl3


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se completa formato de historias de usuario, según requerimientos del cliente.

**Link de archivo cargado en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkgXy3AxizNCpjJdxIxQ3S4BM5UCaqWmnxqisBwTlDhDDg?e=ucOPEl

Pendiente socializar formato de historias de usuario con el cliente y el equipo de desarrollo.

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

El día 31 de mayo se socializa con el cliente el formato Historias de Usuarios junto con el mockup con los requerimientos solicitados en la anterior sesión.

**Adjunto link grabación de la sesión con el cliente**
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cjgonzalezp_udistrital_edu_co/EUJd0decrSdChhrQHhiKqsoBUiqMbhPdNUzanWW1d_Huig?e=80ifKb&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


**Link de archivo cargado en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkgXy3AxizNCpjJdxIxQ3S4BM5UCaqWmnxqisBwTlDhDDg?e=9Wtb12


Saludos.
