### ISSUE TITLE
Construir diagrama modular y de procesos del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#230]
Se requiere realizar la construcción de los diagramas modulares y de procesos del sistema como complemento de la documentación técnica.

**Sub Tareas**

- [x] Revisar la inmersión del requerimiento según los siguientes enlaces: https://github.com/udistrital/polux_cliente/issues/832, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/ES7a6FEo7gFIvQXkuLrLJp8BwC2OkgrCL7OTdsrHmTVPfQ?e=lpuvxv, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/Ef8JZ-s9FXJBkRFKbsLcR2EBWG2yk5hAQ_qt7x0dcUo_sA?e=q9rxnW
- [x] Articular con líder técnico la información necesaria.
- [x] Proyectar los diagramas modulares y de procesos para equipo SoS.

**Criterios de aceptación**

- [x] Diagramas aprobados por equipo SoS
- [x] Diagramas referenciados en carpeta Documentación técnica

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la construcción del diagrama modular y de procesos del sistema.

![Image](https://github.com/user-attachments/assets/c34b5387-c050-4dd0-826b-c9c3020f76a0)


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la construcción del diagrama modular y de procesos del sistema.

![Image](https://github.com/user-attachments/assets/f3c89a7a-3eb9-451d-91c8-22584a99def4)

**Enlace carpeta guardada en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Diagramas/Diagrama%20Modular?csf=1&web=1&e=X44Pe5

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, estaremos a la espera de su presentación a funcionamiento al momento de compartir la documentación del sistema.
