### ISSUE TITLE
Revisión y creación de plantillas minutas Idexud - Parte 2

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#231]
Se requiere continuar con la realización del diseño de las plantillas para parametrización de contratos según su tipo del Idexud.

**Sub Tareas**

- [x] Realizar la investigación según cada tipo de contrato.
- [x] Proyectar las diferentes plantillas.
- [x] Exponer al equipo SoS.

**Criterios de aceptación**

- [x] Plantillas construídas y aprobadas equipos SoS.
- [x] Plantillas documentadas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la revisión y parametrización de las plantillas para las minutas que se implementaran en el sistema ARGO V2 para la oficina de extensión (Idexud)

**Tipos de contrato**
Contrato de Obra
Contrato de Suministro

**Pendientes**
Contrato de transporte
Contrato de prestación de servicios profesionales y de apoyo a la gestión
Contrato de prestación de servicios


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la revisión y parametrización de las plantillas compartidas por la Oficina de Extensión (Idexud). En una siguiente issue se podría concertar una reunión con cliente para revisar ajustes y estilos de las plantillas revisadas, para proceder con el desarrollo e implementación en el sistema ARGO V2.

**Enlaces plantillas guardadas en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Parametrizaciones/Plantillas%20Tipos%20de%20Contratos/
[Idexud](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20ARGO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Parametrizaciones/Plantillas%20Tipos%20de%20Contratos/Idexud?csf=1&web=1&e=b0DbXi)?csf=1&web=1&e=b0DbXi 


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, concuerdo en que se debe exponer al cliente el resultado con el ánimo de refinar la información recopilada y establecer versión final de las plantillas.
