### ISSUE TITLE
Apoyo revisión microcliente root - Despliegue

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#232]
Se requiere realizar ajustes para el correcto despliegue del microcliente [auditoria_plan_mejoramiento_root_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_root_mf) requerido para los microclientes de Sísifo [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).

https://pruebassisifomicroclientes.portaloas.udistrital.edu.co/

**Sub Tareas**

- [x] Ajustes para el despliegue del microcliente.
- [x] Despliegue.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación ajustes despliegue y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/24850391-d38e-4a3b-839a-bb0580250956)
Parece ser que el problema viene de no poder cargar estas configs.

**Comment by mau-oati** [comment]
No he podido enviar cambios, pues no tengo permisos en el repo. 👀

**Comment by edwargl7** [comment]
Agregados permisos

**Comment by mau-oati** [comment]
Se actualizaron dependencias y se hicieron cambios en las url para eviatr error de cors,

Actualmente se confirma que no quedan referencias de ARGO en el código, sin embargo https://pruebassisifomicroclientes.portaloas.udistrital.edu.co/ sigue generando error de cors con la url de ARGO, parece haber una caché o demora en el despliegue. 

![Image](https://github.com/user-attachments/assets/a71175e1-8327-441c-b225-1280a50ea02a)

**Comment by edwargl7** [comment]
Muchas gracias, se logra el correcto funcionamiento con los ajustes realizados en conjunto con infraestructura.
![image](https://github.com/user-attachments/assets/eddd2d59-9dc0-4ebd-9956-963f6f9677b1)
