### ISSUE TITLE
Implementación integración pasos de registro con el id del contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#233]
Se requiere realizar la integración de cada paso con el id del contrato y la organización del flujo de peticiones para garantizar que se lancen en el momento requerido, registro de cláusulas.

**Sub Tareas**

- [x] Integración pasos con id de contrato registrado.
- [x] Ajuste flujo de peticiones según sea requerido en cada paso.
- [x] Ajustes datos CDP.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se incian ajuste de limpieza en crud.

**Comment by edwargl7** [comment]
Adicional a lo revisado inicialmente por favor eliminar el check de ordenador encargado por favor y mantener visible el campo de resolución (se validará este campo con el analista @cjgonzalezp ).
![image](https://github.com/user-attachments/assets/b9a7a7a7-9307-4ead-bd1b-93c4dc12a378)

**Comment by edwargl7** [comment]
Se confirma con @cjgonzalezp para remover el campo de resolución también.

**Comment by mau-oati** [comment]
Se revisan y prueba el guardado de pasos en el modulo de registros. 

![Image](https://github.com/user-attachments/assets/4bec43e9-5337-44e5-9091-cb49a4fcfc5d)
![Image](https://github.com/user-attachments/assets/af5ac55c-dc9d-4555-8e86-89774071c5bd)

Se encuentran novedades a revisar:
- Requerido un endpoint para obtener unidad ejecutora.
- Revisar Flujo de nombre del Ordenador (Por ahora quemado).
- Revisar Forma de Pago (Campo Quemado).
- Revisar Inconsistencia de guardado en Lugar Ejecución (Departamento/Municipio).
- Revisar Endpoint con info correcta de CDP.
- Confirmar el Guardado del Paso Documentos (Uno o varios)

- Revisar la ruta /contratos que está cargando este componente:
![Image](https://github.com/user-attachments/assets/bcc5aec3-2ebf-49ab-8d98-9329de9d6f47)

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelven los PR asociados.

**Comment by edwargl7** [comment]
Revisando con @cjgonzalezp se requiere para CPS un valor predefinido en Forma de pago.

**Comment by edwargl7** [comment]
Revisar Inconsistencia de guardado en Lugar Ejecución (Departamento/Municipio). Revisar para migración.
