### ISSUE TITLE
Integración vista de consulta contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#234]
Se requiere realizar la integración de la vista de consulta implementada en la Issue #225, que permita consultar los contratos registrados basado en los filtros (sin filtrar el de estados por el momento).

Integración con microservicio [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid).
![Image](https://github.com/user-attachments/assets/875dddd2-9ccb-48b6-b029-dbac586fef7d)

**Sub Tareas**

- [x] Integración microcliente y microservicio mid.
- [x] Pruebas funcionales con cada filtro y combinados.

**Criterios de aceptación**

- [x] Documentación resultados de las pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se implementan las consultas faltantes para poder tener la lista de parámetros completa para comenzar con la implementación de la consulta del contrato.

**Comment by Lau2ri** [comment]
Se realiza la integración de los filtros de la consulta al crud para obtener los datos requeridos para la consulta de contratos en el micro cliente en el micro servicio mid, actualmente muestra la mayoría de los datos, queda pendiente transformar un par de datos de su valor en parámetros a su nombre en texto y queda por ajustar la búsqueda del nombre del contratista, ya que por el momento no funciona cuando el contratista no es una persona "natural" sino es a lo mejor una "jurídica" y su nombre está en un formato distinto por el cuál se realiza la consulta.  

https://github.com/user-attachments/assets/0d170080-8f30-437c-bc28-b80806f151b3

![Image](https://github.com/user-attachments/assets/65817ce0-3ec7-4fb0-b443-6a67a2757cac)

**Comment by Lau2ri** [comment]
https://github.com/user-attachments/assets/b0348b37-cac3-4680-bbbc-9a51e07ea3f8

![Image](https://github.com/user-attachments/assets/18fae870-fb43-4715-8b00-382e98e2fd74)

**Comment by edwargl7** [comment]
número elaboración es consecutivo elaboración que se asigna cuando pasa a suscrito, por el momento se puede asignar a los registros para poder realizar la validación.

**Comment by edwargl7** [comment]
Fecha creación filtrado con desde y hasta

**Comment by Lau2ri** [comment]
Se realizan las transformaciones que hacían falta de parámetros a su nombre para la consulta de contratos:

![Captura de pantalla 2024-11-30 181246](https://github.com/user-attachments/assets/d1beff01-849b-4975-b4fd-e631aa864419)

Por este sprint no se puede realizar el filtro de fechas desde y hasta debido a que por el momento dicho filtro no se está aplicando bien directamente en el endpoint (pruebas con el swagger) y además la lógica de filtrado de una fecha hasta otra supone una lógica relativamente compleja que habrá que evaluar si se hace directamente en el cliente o si se realiza en el servicio.

Acerca del consecutivo de elaboración, este dato actualmente no se trae en el contrato, habrá que actualizar los registros si es debido a que no lo tienen, o actualizar la respuesta del endpoint para incluir este dato para poder realizar el filtro.

Por le momento no se propone PR debido a la posibilidad de seguir trabajando los ajustes faltantes el siguiente sprint bajo la misma rama.

**Comment by edwargl7** [comment]
Muy buen trabajo, por favor realiza el PR bajando los cambios y resolviendo conflictos por favor.

**Comment by Lau2ri** [comment]
Se realizan los PR correspondientes.

**Comment by edwargl7** [comment]
Resueltos PR, muchas gracias.
