### ISSUE TITLE
Integración gestor documental para almacenamiento de minuta

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#235]
Se requiere realizar la integración con el registro de la minuta en la tabla de documento contrato y el registro del PDF en el gestor documental.

**Sub Tareas**

- [x] Integración registro del PDF en el gestor documental.
- [x] Integración documento contrato.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación integración registro de minuta.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se añade evidencia, funcionamiento:

[Grabación de pantalla desde 2024-11-25 21-34-26.webm](https://github.com/user-attachments/assets/acdf730e-a13e-4b13-8379-7ed4a9d554d4)

**Comment by diegobauto** [comment]
Se adjunta evidencias del funcionamiento: 

Visualización de la minuta: 
![Image](https://github.com/user-attachments/assets/fb8b7aa0-e5c0-4f85-8b14-7c5ee3c30b9e)

Guardado del documento en el gestor documental, y posteriormente en la tabla de documentos-contrato:
![Image](https://github.com/user-attachments/assets/f590f253-eeb5-4cd6-96f9-3eaf28ea3b76)

![Image](https://github.com/user-attachments/assets/aed2fcfc-4ba8-48c2-84ed-1abc44506c6f)

![Image](https://github.com/user-attachments/assets/53104359-e219-4acb-a860-8c6a886a2a72)

Al buscarlo por id, obtenemos:
![Image](https://github.com/user-attachments/assets/3db82074-ea73-43be-9ce8-65dfcb849455)

Verificamos contenido en base64, si se guardo correctamente el archivo:
![Image](https://github.com/user-attachments/assets/0d0677c3-af84-4a11-9705-3882022f01f2)

![Image](https://github.com/user-attachments/assets/ef5d1de5-6a1a-4935-a24b-ef3f24abda37)

![Image](https://github.com/user-attachments/assets/98e2461a-9bff-4ac3-9680-781df8d4d0e9)

**Comment by edwargl7** [comment]
Muy buen trabajo, resuelto PR.
