### ISSUE TITLE
Integración especificaciones técnicas y microservicio crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#238]
Se requiere realizar la integración del paso de especificaciones técnicas con el microservicio CRUD.

**Sub Tareas**

- [x] Integración de registro individual de especificación.
- [x] Implementación query params controlador find All (ejemplo: https://github.com/udistrital/gestion_contractual_crud/blob/feature%2Fenhancements-estados/src/estado-contrato/estado-contrato.service.ts) en el microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud).
- [x] Integración consulta de especificaciones asociadas a un contrato (filtrando activas).
- [x] Integración edición y eliminación de especificación.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

- Confirmar si es requerido paginado @cjgonzalezp .

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realizan pruebas de funcionamiento para la obtención, creación, actualización y eliminado de especificaciones técnicas:

- CREACIÓN Y OBTENCIÓN:

![Image](https://github.com/user-attachments/assets/6b4ee87e-6045-4baa-a088-2cd5e2ef8726)

![Image](https://github.com/user-attachments/assets/25ca7d67-b330-43b7-a901-78563138f57f)

![Image](https://github.com/user-attachments/assets/51a395bc-3dbe-42bf-b940-eee16dd22a05)

![Image](https://github.com/user-attachments/assets/2298928c-45fd-440b-b830-ab9642833c5a)

- ACTUALIZACIÓN Y OBTENCIÓN:

![Image](https://github.com/user-attachments/assets/536402de-e0c4-4e63-8766-00939ed70539)

![Image](https://github.com/user-attachments/assets/5e2486ae-f7bd-41b2-939a-81e9e415ab98)

![Image](https://github.com/user-attachments/assets/ba04a302-a34a-4b51-84b1-1d0d067b94da)

![Image](https://github.com/user-attachments/assets/ce8d4692-ac64-4273-960e-bfa0e5bffdb5)

- ELIMINACIÓN Y OBTENCIÓN:

![Image](https://github.com/user-attachments/assets/2d4894f2-172f-4fc3-83c4-d15ad5028864)

![Image](https://github.com/user-attachments/assets/4663b803-0768-4b5d-b16a-833b9d47fa8e)

![Image](https://github.com/user-attachments/assets/a4cfa128-48f3-4823-835c-69de2956bda5)

![Image](https://github.com/user-attachments/assets/b49a047d-eb00-48b9-a026-39fcd9d715fd)

![Image](https://github.com/user-attachments/assets/0cb5ea56-a83c-4fd6-b427-786972369975)

**Comment by diegobauto** [comment]
Además se realizan las siguientes validaciones en el formulario:
- Cantidad permite únicamente valores enteros
 
- Valor unitario y total permiten únicamente dos decimales
 
- No se permite actualizar si no se realizaron cambios

  ![Image](https://github.com/user-attachments/assets/3bed7782-caee-4235-988d-aae820ada796)

  ![Image](https://github.com/user-attachments/assets/5002df2f-f258-4900-91c0-2e172ed65a7d)

- No se permite crear si no están digitados los campos

  ![Image](https://github.com/user-attachments/assets/bfb01e55-82f5-456d-82d5-1e9e0932f224)

  ![Image](https://github.com/user-attachments/assets/9df66867-f52d-4726-b6a9-e20ea4f9d124)

**Comment by edwargl7** [comment]
Muy buena implementación y documentación, se valida con @cjgonzalezp si es necesario cantidades no enteras. Por favor resolver conflictos del PR.

**Comment by edwargl7** [comment]
Resuelto PR muchas gracias.
