### ISSUE TITLE
Preparación presentación estado actual desarrollo ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#239]
Se requiere realizar el montaje de los servicio requeridos para la presentación al usuario y la preparación de los registros requeridos para la presentación.

**Sub Tareas**

- [x] Montaje de servicios requeridos para la presentación (registro y consulta de contrato, registro de pólizas y acta de inicio, roles).
- [x] Organización de datos para la presentación.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Muy buen trabajo.

**Comment by mau-oati** [comment]
Antes de la presentación se revisó el avance integral de todo del proyecto:
- Se corrigieron elementos de ui en varios pasos.
- Se robustecieron validaciones de estado guardado/nuevo elemento.
- Se limpiaron elementos redudantes. 
- Se incluyó el nuevo componente búsqueda **(searchable-select)**
