### ISSUE TITLE
Revisión dependencias de datos del módulo de Gestión Orden de compras y servicios - Dependencia de y sobre ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#24]
Se requiere realizar el análisis detallado sobre cada uno de los datos requeridos en el módulo de Gestión Contractual y Orden de compras y servicios, identificando que campos son consumidos o se deben consumir de otros servicios y también identificar que datos registrados en ARGO son consumidos por otros servicios.

Esto con el fin de ver la viabilidad de:

1. Unificar el módulo de Gestión Contractual con el módulo de Orden de compras y servicios.
2. Diseñar e implementar un microservicio para la gestión de estos módulos con una base de datos diferente a la base de datos actual, sin afectar otros sistemas.

Para esto se debe crear una tabla con la lista de los campos requeridos en el registro de Contratos en estos módulos identificando las similitudes entre los dos módulos, el consumo de otros servicios para poder realizar el registro y que servicios requieren de estos datos.

**Sub Tareas**

- [x] Registrar todos los campos de los formularios de registro de contrato de los módulos de Gestión de Orden de compras y servicios.
- [x] Revisión de similitud en los campos de los dos módulos.
- [x] Revisión y registro de cada campo si su fuente es de otro sistema basado en el sistema actual ARGO apoyado con la base de datos del sistema actual. [Ver diagrama en la carpeta de ARGO](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EbS_rdklkDxDo33gYLJ79nkBqGjhDXQgrGdWLDvdNe1k6Q?e=qrdEBS).
- [x] Identificar cuales campos son consumidos por otros sistemas (tarea que se realizará con el apoyo de otros equipos).

**Criterios de aceptación**

- [x] Lista de campos de los formularios de los módulos de Gestión orden de compras y servicios en los que se especifique si la fuente es de otro sistema y si es fuente para otro sistema.

**Requerimientos**

- [ ] Usuario del ambiente de pruebas de ARGO.
- [x] Modelo de datos del sistema actual de ARGO.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Evidenciar el avance progresivo en cada sub tarea.
- [x] Listado de campos de los formularios de los módulos de Gestión orden de compras y servicios que especifiquen la dependencia de otros sistemas, tanto que sean consumidos por ARGO como desde otros sistemas.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Enlace del archivo donde podemos agregar los avances de esta Issue [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBcCUIhWwEqT5dYoDnjk1ZcQ?e=eAaliN). Muchas gracias.

**Comment by edwargl7** [comment]
Por el momento no se tiene usuario en ambiente de pruebas, se debe trabajar con el material disponible (manuales y capacitaciones).

**Comment by mau-oati** [comment]
Se agregó información del formulario de flujo de órdenes de compra en el documento.

**Comment by mau-oati** [comment]
Se continúa la inclusión de elementos de ordenes de compra en la tabla de dependencias.

**Comment by mau-oati** [comment]
**Dudas**: De donde puede estar llegando los datos de Información Presupuestal 1 y 2?, datos como Tipo de Moneda, Numero de Disponibilidad o Solicitud de Necesidad no termino de ubicar su origen.

**Comment by mau-oati** [comment]
### Los campos SIN marca de color, no han sido identificados plenamente.

<img src="https://github.com/udistrital/argo_documentacion/assets/163943201/9c84503e-a550-46a4-af61-02afa1cb9d59" width="300">

<img src="https://github.com/udistrital/argo_documentacion/assets/163943201/cae789a5-2437-479f-bca0-2f09f06dc523" width="300">

<img src="https://github.com/udistrital/argo_documentacion/assets/163943201/4a868a9d-a549-42b3-8e2b-bcbe4181ebea" width="300">

**Comment by edwargl7** [comment]
Se realiza la revisión preliminar en la que se observa la posibilidad de unificar el módulo de gestión contractual con el módulo de órdenes en la etapa de registro del contrato. Una vez recibidos los requerimientos por parte del usuario final se revisaran las secciones que puedan ser diferentes entre estos dos módulos en la etapa de registro del contrato. Buen análisis a nivel de base de datos. El origen de los campos se abordará en la tercera capacitación que permitirá tener mayor claridad de algunos campos identificados. Muy buen trabajo.
