### ISSUE TITLE
Implementación estados internos microservicio gestion_contractual_crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#242]
Se requiere realizar la implementación del manejo de estados internos en el microservicio [gestion_contractual_crud](https://github.com/udistrital/gestion_contractual_crud) que permita cambiar el estado actual del contrato con los cambios de estados internos manteniendo el estado externo del contrato.

[estado-contrato.service](https://github.com/udistrital/gestion_contractual_crud/blob/develop/src/estado-contrato/estado-contrato.service.ts)

**Sub Tareas**

- [x] Implementación cambio de estado interno.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avance implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/0f9b765a-2f59-4995-a973-7d1c211aaeb2)

**Comment by edwargl7** [comment]
Implementación completada y PR resuelto.
