### ISSUE TITLE
Implementación de acciones según rol y estado del contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#243]
Se requiere realizar la implementación de acciones en la vista de consulta del contrato según el rol del usuario y según el estado del contrato (estado interno y externo) en el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf), basado en el flujo de estados del contrato.

![Estados del Contrato](https://github.com/user-attachments/assets/cc24e560-fc74-4998-a313-a8d6352886cc)

[Mockup aprobación contratista](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EbrXmK4TtgtNjh9VB-3Yu4wBrk05hiEMEBJQMSuyVYsSaQ?e=BsGon9)

**Sub Tareas**

- [x] Implementación acciones en vista de consulta según rol y estado del contrato.
- [x] Implementación vista de aprobación contratista (Reutilizar vista de aprobación de jefe y ordenador).
- [x] Integración vistas de aprobación (Jefe contratación -> JEFE_DEPENDENCIA, ordenador del gasto -> ORDENADOR_DEL_GASTO, contratista -> CONTRATISTA).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avance implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza ajuste de rol para la visualización de contrato del contratista:
![1](https://github.com/user-attachments/assets/b1aa744a-44b5-40bf-b647-c2ee3c457355)
![2](https://github.com/user-attachments/assets/25d0bb54-9236-4a14-8f0f-adc403cf98ff)
![3](https://github.com/user-attachments/assets/7208e07b-ed1e-494f-81f4-8c8bd11ef90f)
![4](https://github.com/user-attachments/assets/64de6b5b-53a8-40ae-be3d-683c6d303281)
![5](https://github.com/user-attachments/assets/272aa312-94e7-4db4-8c68-01387737a9f1)
![6](https://github.com/user-attachments/assets/933c732b-95d3-44ff-a71a-895bdc898dec)
![7](https://github.com/user-attachments/assets/1fa9fb31-8bd3-4cf4-a147-1d34542411b3)

**Comment by diegobauto** [comment]
Se realiza validación de multiples usuarios, de acuerdo a las acciones en el modulo de Consulta de contrato:
Observación:  Tener en cuenta que falta realizar ajuste dependiendo de los estados generales e internos.
Además se realiza un estado de carga en el modulo de Revisión de contrato, debido a que mientras se visualizaba el contrato se veía el espacio en blanco.

JEFE DE DEPENDECIA:

![Image](https://github.com/user-attachments/assets/a396c1bc-8406-4f36-96f4-0d5b555e5184)

![Image](https://github.com/user-attachments/assets/67d7f607-7d00-4b3e-a838-fb7282cb5996)

![Image](https://github.com/user-attachments/assets/f04ded2b-51eb-4896-830c-00ba68812bf4)

![Image](https://github.com/user-attachments/assets/72146e61-3433-4a91-b69c-5a414ef7e644)

![Image](https://github.com/user-attachments/assets/786e9170-d4ff-4ca5-930d-667dd2b80a40)

CONTRATISTA:

![Image](https://github.com/user-attachments/assets/866acfc8-9b45-40a2-9c81-d60f17975a32)

![Image](https://github.com/user-attachments/assets/2e730bbc-5579-415b-942e-70a83cd72082)

![Image](https://github.com/user-attachments/assets/c670a34c-963d-4922-ac13-932e28888679)

![Image](https://github.com/user-attachments/assets/a0255f38-4792-4360-8207-ce45a048608d)

![Image](https://github.com/user-attachments/assets/e0e421c3-39da-45b1-8569-e36dc219af12)

![Image](https://github.com/user-attachments/assets/2900e420-9f7f-45c6-adbf-d1e80e27f89f)

![Image](https://github.com/user-attachments/assets/4ed4c330-bc9f-4bd6-8d83-4fbd12b40b79)

**Comment by edwargl7** [comment]
Buena documentación e implementación, resolver conflictos del [PR 63](https://github.com/udistrital/gestion_contractual_mf/pull/63) por favor.
