### ISSUE TITLE
Integración visualización de minuta en vistas de aprobación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#244]
Se requiere realizar la implementación de consulta al gestor documental para la visualización de la minuta almacenada asociada al contrato en cada vista de aprobación (jefe, ordenador y contratista).

**Sub Tareas**

- [x] Integración consulta documento con gestor documental.
- [x] Implementación vista de consulta de minuta en las vistas de aprobación.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza desarrollo y se adjunta evidencia del funcionamiento:

![Image](https://github.com/user-attachments/assets/1c751399-77e4-4f05-b4a6-d5e4699915a1)

![Image](https://github.com/user-attachments/assets/65a9a1c1-6d7d-43d6-a4d5-3b6122ac05ee)
