### ISSUE TITLE
Implementación vista de histórico de observaciones abogado - parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#245]
Se requiere realizar la implementación de visualización del histórico de observaciones de rechazo desde el rol de abogado que le permita identificar el motivo de rechazo. Esta opción solo será visible para el abogado siempre y cuando se tenga por lo menos un rechazo y se encuentré el contrato en el estado borrador.

**Sub Tareas**

- [x] Maquetación vista de histórico de observaciones.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza maqueteción historial de observación:

![image](https://github.com/user-attachments/assets/e7e98648-2288-4b36-9ea0-2dcc7baf05af)

![Image](https://github.com/user-attachments/assets/0ba54f24-b9f3-4d60-b78a-6d46c873f7f7)

**Comment by edwargl7** [comment]
Aprobado por @jcmurilloa y @cjgonzalezp para mostrar el histórico completo.
