### ISSUE TITLE
Implementación consulta de contrato por fecha de registro

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#246]
Se requiere realizar la implementación de la consulta de contratos en un rango de fechas por la fecha de creación e integrarla en el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf) en la vista de consulta.

**Sub Tareas**

- [x] Implementación consulta entre rango de fechas en el microservicio CRUD.
- [x] Integración consulta por fecha.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se requiere resolver conflictos por favor en el [PR 64](https://github.com/udistrital/gestion_contractual_mf/pull/64)

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/c02737ea-f331-4626-9375-5ac6999a10b3

**Comment by edwargl7** [comment]
Finalizada la Issue con las pruebas. Muchas gracias.
