### ISSUE TITLE
Implementación endpoint de consulta de estados en microservicio mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#247]
Se requiere realizar la implementación del endpoint de consulta de estados de un contrato en el microservicio [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid) que retorne la información del estado general (id y nombre de parámetros crud), información del usuario que realiza el cambio (usuario_id y nombre de terceros) y demás datos del estado (fecha, motivo). Y también agregar el filtro para identificar si tiene más de un registro de borrador que indica que cuenta con rechazo.

**Sub Tareas**

- [x] Implementación controlador de estados de un contratos.
- [x] Integración con terceros y parámetros crud para resolver las referencias.
- [x] Implementación filtro de rechazo.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se comienza con la creación de la base para el endpoint de estados.

**Comment by Lau2ri** [comment]
Se implementa el endpoint de consulta de estado de un contrato mostrando todos los datos requeridos, sólo queda por realizar el filtro de rechazo:

https://github.com/user-attachments/assets/10ccd507-0552-40b4-9035-1ac2783757e3

![Image](https://github.com/user-attachments/assets/8e51a85d-6d61-448a-9573-bdf1f34a9725)

**Comment by Lau2ri** [comment]
No se pudo realizar la prueba del filtro de rechazo debido a un error en el mid, no se sabe si en parámetros crud o una caída en la vpn pero en general el mid no está funcionando correctamente (como venía haciendo) en el llamado de los contratos:

![image](https://github.com/user-attachments/assets/6d74ab44-8d68-4397-8352-c34ccba47c94)

![image](https://github.com/user-attachments/assets/6703e793-b3b0-40fe-8a8e-fd3495e22273)

**Comment by edwargl7** [comment]
Se pueden reemplazar en las variables de entorno ENDP por SERVICIO dado que cada variable de entorno almacena el HOST del servicio y según el caso permite realizar peticiones a varios endpoints.
![image](https://github.com/user-attachments/assets/dc9810d5-f795-4003-9bfa-5ca8b819364e)

Se resuelve el PR buena implementación. Se crea nueva tarea para resolver los errores mencionados y culminar las pruebas funcionales.
