### ISSUE TITLE
Implementación vista de histórico de observaciones abogado - parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#249]
Se requiere realizar la integración e implementación entre el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf) y el microservicio  [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid) para la visualización del histórico de cambios de estados de un plan donde se observe el cambio de estado, la observación si existe, el usuario que realiza el cambio (nombre) y el rol registrado al momento de realizar la acción.

![image](https://github.com/user-attachments/assets/72d60099-fbab-4cf3-a046-46152df9dad8)

**Sub Tareas**

- [x] Implementación validación de observación de rechazo para activación de acción en la vista de consulta.
- [x] Integración estados entre microservicio MID [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid) y microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Material de apoyo**
```html
<mat-icon>info</mat-icon>
```

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se adjunta evidencia de prueba funcional: 

![Image](https://github.com/user-attachments/assets/fc336786-2470-4b0b-9b42-43c3a722a901)

![Image](https://github.com/user-attachments/assets/f8bb4a21-7dfa-45bc-a534-8b29a5afd0be)

![Image](https://github.com/user-attachments/assets/7d5a5fd9-4b21-4975-965e-dc51f424d883)

Observación: Dado que el comportamiento de la tabla de consulta presenta algunas fallas de carga al navegar entre paginas, de la misma manera se esta presentando para el modal del historial.

**Comment by diegobauto** [comment]
PR: https://github.com/udistrital/gestion_contractual_mid/pull/8

**Comment by diegobauto** [comment]
Para realizar merge, primero realizar el merge de: https://github.com/udistrital/gestion_contractual_mf/pull/65

**Comment by edwargl7** [comment]
Resuelto PR https://github.com/udistrital/gestion_contractual_mid/pull/8, pendiente resolver conflictos del PR del microcliente por favor. Buen trabajo.
