### ISSUE TITLE
Implementación de acciones según estado del contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#250]
Se requiere realizar la implementación de acciones en la vista de consulta del contrato según el rol del usuario y según el estado del contrato (estado interno y externo) en el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf), basado en el flujo de estados del contrato.

![Estados del Contrato](https://github.com/user-attachments/assets/cc24e560-fc74-4998-a313-a8d6352886cc)

**Sub Tareas**

- [x] Actualización modelo de datos agregando campo rol como string a la tabla estado_contrato.
- [x] Actualización controlador [estado_contrato](https://github.com/udistrital/gestion_contractual_crud/tree/develop/src/estado-contrato) para agregar el nuevo campo de rol.
- [x] Implementación de obtención de persona_id o id del tercero que se encuentra logeado basado en la implementación realizada en este [ejemplo](https://github.com/udistrital/plan_anual_auditoria_mf/blob/develop/src/app/core/services/user.service.ts).
- [x] Implementación registro de estado "SUSCRITO" al momento de ser aprobado por el usuario JEFE de contratación.
- [x] Implementación registro de rol del usuario al momento de realizar cambios en los estados internos.
- [x] Implementación acciones en vista de consulta según rol y estado del contrato.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avance implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Por medio de @mau-oati, se relizo la actualización controlador para agregar el nuevo campo de rol

**Comment by diegobauto** [comment]
Además se realizo la actualización del modelo de datos: 
![modelo-basedatos-core-Argo](https://github.com/user-attachments/assets/0c0b8541-841c-4ff0-8d9f-e90f9ddbd66a)

**Comment by diegobauto** [comment]
Se realiza con @mau-oati ajustes en la tabla de estado_contrato:
- Eliminación de campo fecha_ejecucion_estado
- Ajuste en campo 'actual' para dejarlo como true en el ultimo registro (estaba tomando activo)
- AJuste fecha_creacion
- Ajuste fecha_modificacion

Queda pendiente actualizar modelo de datos

**Comment by diegobauto** [comment]
Actualización modelo de datos, tabla estado_contrato: 
![modelo-basedatos-core-Argo](https://github.com/user-attachments/assets/a9a0e6b6-9afb-4fc6-a2c9-dd78abc40cab)

**Comment by diegobauto** [comment]
Implementación acciones en vista de consulta según rol y estado del contrato:

![Image](https://github.com/user-attachments/assets/8e7e6544-9eb1-4e95-a679-8e65d344aeba)

![Image](https://github.com/user-attachments/assets/58d39c40-73e9-4bce-8396-e67fd2db5d09)

**Comment by diegobauto** [comment]
Implementación de obtención de persona_id o id del tercero que se encuentra logueado:

![Image](https://github.com/user-attachments/assets/626fb42c-5093-44cc-9525-d9a1a917c6ab)

![Image](https://github.com/user-attachments/assets/994b17f3-d7b9-4e58-b346-8b522351b876)

![Image](https://github.com/user-attachments/assets/13c9cffc-3727-4490-b621-b5f90a394b01)

**Comment by diegobauto** [comment]
Rechazo de contrato

Se observa que se añade un registro con:
- estado_parametro_id: 6773 *(POR_SUSCRIBIR)*
- estado_interno_parametro_id: 6803 *(RECHAZADO)*

Además se añade el rol de quien realizó la acción dependiendo del estado (CONTRATISTA)

![Image](https://github.com/user-attachments/assets/2a4d45e6-d6a0-4f1f-bae4-ccd20dce406b)

![Image](https://github.com/user-attachments/assets/1fd6dbad-8d55-4753-9601-ef1b1a7baf58)

![Image](https://github.com/user-attachments/assets/7a7225ee-c313-4d1e-a979-841c4418f6f1)

![Image](https://github.com/user-attachments/assets/b7064c6d-0d52-43d5-aa65-4624d3ab5659)

![Image](https://github.com/user-attachments/assets/411fc6ec-3560-4bec-bec1-a3ce8597fb12)

**Comment by diegobauto** [comment]
Aprobación del contrato

Se observa que se añade DOS registros con:

- Primer registro (cambio automatico):
 
  - estado_parametro_id: 6773 *(POR_SUSCRIBIR)*
  - estado_interno_parametro_id: 6809 *(APROBADO_JEFE)*

- Segundo registro:
 Implementación registro de estado "SUSCRITO" al momento de ser aprobado por el usuario JEFE de contratación.
  - estado_parametro_id: 6774 *(SUSCRITO)*
  - estado_interno_parametro_id: 6801 *(EN_FIRMA_ORDENADOR)*

Además:
- Se añade el rol de quien realizó la acción dependiendo del estado (JEFE_DEPENDENCIA)
- Se verifica que los estados anteriores queden con el campo actual en 'false'


![Image](https://github.com/user-attachments/assets/5f99880d-769d-42af-97ce-cb3c463ead5e)

![Image](https://github.com/user-attachments/assets/cecafece-a6b4-45c6-aaf5-d14c2de3ddac)

![Image](https://github.com/user-attachments/assets/74d0519e-3d80-41f9-9fe2-a6e7a2133fca)

![Image](https://github.com/user-attachments/assets/4be9f465-a533-4471-97fa-eb09606cba7c)

![Image](https://github.com/user-attachments/assets/eba2c139-04d2-40f6-904e-bc2feb48e9bf)

**Comment by diegobauto** [comment]
Aprobación del contrato

Se observa que se añade un registro (ya que esta en estado de Firmar por Contratista) con:
- estado_parametro_id: 6774 *(SUSCRITO)*
- estado_interno_parametro_id: 6804 *(FIRMADO_CONTRATISTA)*

Además:
- Se añade el rol de quien realizó la acción dependiendo del estado (CONTRATISTA) 
- Se verifica que los estados anteriores queden con el campo actual en 'false'
- Se verifica que como no fue aprobado por el usuario JEFE de contratación sigue estando el estado general en SUSCRITO

![Image](https://github.com/user-attachments/assets/2f3cb30a-f76c-4c88-b747-de9713062cc8)

![Image](https://github.com/user-attachments/assets/aaa9700f-2d0f-4cbc-b1ad-6f438c18e42c)

![Image](https://github.com/user-attachments/assets/f9e7ddb3-6496-44ec-b790-353554f74956)

![Image](https://github.com/user-attachments/assets/a37bab11-4b6d-48d4-bc3a-6c2c397b7a7c)

![Image](https://github.com/user-attachments/assets/dafeda34-051c-42e9-9ea9-fbc5135477e0)

**Comment by diegobauto** [comment]
Se adjuntan imagenes de referencia: 
![Estados Internos-Externos drawio](https://github.com/user-attachments/assets/3d48754e-f56d-4a2b-a74b-d77a31ebec4a)
![acciones estados_roles](https://github.com/user-attachments/assets/4b5f0f6c-e841-4217-a479-23ee8577043e)

**Comment by edwargl7** [comment]
Muy buena documentación e implementación, resolver conflictos por favor.
