### ISSUE TITLE
Ajuste errores y Pruebas endpoint de consulta de estados en microservicio mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#251]
Se requiere realizar la revisión y ajustes al error en el microservicio  [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid) reportado en la Issue #247 

**Sub Tareas**

- [x] Resolver fallos en el microservicio mid.
- [x] Realizar las pruebas funcionales al endpoint de estados.

**Criterios de aceptación**

- [x] Documentación ajustes realizados y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Encontramos cambios en la forma de trabajar del cluster de postgreSQL con la VPN activa, ahora no permite dos conexiones al tiempo, por lo que generamos diferentes usuarios para mitigar el error de conexión que se reflejaba como un 500. Con eso volvió a funcionar la conexión local entre mid y crud.

**Comment by Lau2ri** [comment]
Pruebas funcionales endpoint de estados más filtro de estado "Rechazado" (id 6803):

https://github.com/user-attachments/assets/f8c514a7-bffe-4382-808f-b933824ca798

![Image](https://github.com/user-attachments/assets/bd35a952-790a-4b0a-aca2-e93686c7e138)

Se observa que hay un par de casos muy específicos que el contrato trae más de un estado en vez de traer el último, puede deberse a algún ajuste en el crud:

![Captura de pantalla 2024-12-09 194254](https://github.com/user-attachments/assets/8b3349ec-582e-4c5a-bb31-10c2c894d353)

Mientras que el resto si traen el último estado permitiendo así la transformación de los parámetros: 

![Captura de pantalla 2024-12-09 194309](https://github.com/user-attachments/assets/9a2392a5-fbe9-4414-b888-38d2b5f6c5f4)

**Comment by edwargl7** [comment]
Finalizados los ajustes y pruebas completas.
