### ISSUE TITLE
Implementación búsqueda en selectores por número en el submódulo de registro de contratos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#252]
Se requiere realizar el ajuste en los datos y la implementación de la búsqueda por código numérico en los selectores del submódulo de registro de contrato similar al ARGO v1.
![image](https://github.com/user-attachments/assets/6fc75a3f-4abe-47dc-9cf2-f1447076e7db)

El sistema actual almacena estos códigos en el campo "codigo contraloria".
![image](https://github.com/user-attachments/assets/1e68f073-041a-48c4-beda-172a3251536b)

**Sub Tareas**

- [x] Ajuste registro de datos paramétricos basado en los códigos del sistema actual.
- [x] Implementación búsqueda en los selectores y selección al tabular en el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Inicio revisión de documentación para la implementación local de un selector como prueba incial.

**Comment by mau-oati** [comment]
Se revisa la posibilidad de cambiar la descripción en la db parámetros, para evitar la concatenación en las APIs o el cliente.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/a70a2b6c-bc80-44d2-a267-ad3d3d959ab0)

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/d09a42a7-c148-4ab0-8bc6-41b190d9087c

**Comment by edwargl7** [comment]
Buen trabajo, resuelto el PR. Muchas gracias.
