### ISSUE TITLE
Implementación e integración consulta y asignación de ordenador en el registro de contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#253]
Se requiere realizar la implementación de los endpoints de consulta de cargo ordenador y ordenador basado en el cargo en el microservicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid) y la integración en el microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf)

**Sub Tareas**

- [x] Implementación consulta de cargo de ordenadores.
- [x] Implementación consulta información del ordenador.
- [x] Integración consulta ordenador en el microcliente.
- [x] Integración registro en el microservicio crud.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Pruebas funcionales del endpoint de Ordenadores (faltantes en la tarea [#198](https://github.com/udistrital/argo_documentacion/issues/198)):

https://github.com/user-attachments/assets/56ac5772-ac8f-472b-ace1-0a2bf1093083

![Image](https://github.com/user-attachments/assets/68900d19-4c98-41ee-b7c6-015c6d76712f)

**Comment by edwargl7** [comment]
Formato fecha a enviar "DD-MM-YYYY" en la consulta del ordenador.

**Comment by Lau2ri** [comment]
Se actualiza el endpoint de consulta de ordenadores en el mid para que traiga todos los ordenadores desde el crud, se procede con el filtrado de estos ordenadores por rol. 

https://github.com/user-attachments/assets/eb51554c-9bbd-424d-8cda-56dd36d9c4f8

![Image](https://github.com/user-attachments/assets/91daf0b2-ff40-4315-a88b-8209d2db24a1)

**Comment by Lau2ri** [comment]
Debido a un problema desconocido, al parecer asociado a la vpn no me están funcionando las consultas a los servicios que requieren de la vpn activa, por lo tanto no se podrán mostrar las pruebas de funcionalidad de las implementaciones realizadas:
- Endpoint de consulta de Roles de ordenador
- Endpoint de consulta de Ordenador actual por rol
- Endpoint de consulta de Ordenador por rol
- Integración consulta endpoint de roles en el microcliente
- Integración consulta de ordenador por rol actual seleccionado por el usuario

![image](https://github.com/user-attachments/assets/6082c877-f584-4d5f-a767-9427f441fd1d)

![image](https://github.com/user-attachments/assets/6f710842-9afc-434e-a261-b9cf478fa58f)

**Comment by edwargl7** [comment]
Se resuelven los PR, pendiente ajustar a snake case todos los campos de los endpoint y ajuste para no requerir la conversión de XML. Buen trabajo.
