### ISSUE TITLE
Ajuste modelo de datos tabla supervisor

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#254]
Se requiere realizar el ajuste al diseño de la tabla de supervisores para mantener la referencia de sede y dependencia del sistema actual tanto para la migración como la integración temporal con este parámetro. Campos legados sede supervisor, dependencia supervisor, cargo, documento, estado, digito de verificación y las referencias al OIKOS actual (sede y dependencia).

![image](https://github.com/user-attachments/assets/c1358880-83b9-4604-8520-42fb38977e3b)

**Sub Tareas**

- [x] Actualización modelo de datos.
- [x] Creación y ajuste SQL de creación de base de datos.

**Criterios de aceptación**

- [x] Modelo y SQL actualizado en el repositorio.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se actualiza la tabla de supervisores con los campos solicitados:

![image](https://github.com/user-attachments/assets/6858d57b-78b8-4df4-941c-81c16c310c2b)

**Comment by edwargl7** [comment]
Se debe actualizar los campos relacionados al OIKOS nuevo como tipo entero similar a como se maneja lugar de ejecución.
