### ISSUE TITLE
Revisión y ajuste de la documentación ténica del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#255]
Se requiere realizar el apoyo en la revisión y ajuste de la documentación ténica con base a la elaborada en Pólux: [documentación tecnica](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EbJ-FyQnHu1IqMFJJg_1SpsBVO193db6c_rNPMBPD-tWkQ) que se presenta a funcionamiento 

**Sub Tareas**

- [x] Establecer listado de documentos a proyectar,
- [x] Apoyar en la actualización de la documentación técnica.
- [x] Exponer documentos a equipos SoS

**Criterios de aceptación**

- [x] Lista de chequeo proyectada.
- [x] Documentación realizada y almacenada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cjgonzalezp** [comment]
Buen día,

A continuación, relaciono listado de documentos necesarios para la entrega del sistema

**LISTADO DOCUMENTOS ENTREGABLES**
1.	Diagrama modular - OK
2.	Diagrama de proceso general - Pendiente pasarlos a esta carpeta
3.	Formato Aceptación de entregables - Se crea documento en Word para documentar
4.	Documento descripción técnica del desarrollo - Se crea documento en Word para documentar

Adicionalmente, se crea una carpeta en OneDrive para consolidar la documentación y se organizó cada uno de los documentos para alimentar la información requerida. 

**Adjunto enlace**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsRW9WipyidAhLJ-rYy_OfwB5BfqIeU-pD4Z4vBD327HeQ?e=OaU5p1


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, pendiente creación de espacio para la documentación de manuales e instructivos del sistema.
