### ISSUE TITLE
Actualizar los mockups del sistema según comentarios del cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#256]
Se requiere realizar la actualización de los mockups según comentarios sugeridos por el cliente

**Sub Tareas**

- [x] Actualiza diseño de mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [ ] Presentar al equipo y cliente el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo y cliente.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se actualizan los mockups del sistema según comentarios del cliente realizados en la última reunión de presentación de avances.

Se agrega el campo para agregar la fecha de la TRM registrada en el formulario.
<img width="445" alt="Image" src="https://github.com/user-attachments/assets/27e225ed-2ad1-4e02-8d01-0ee21ba35ce6" />

Se retira del mockup la opción de visualizar la justificación, objeto del contrato, actividades cuando se relaciona mas de un CDP.
<img width="337" alt="Image" src="https://github.com/user-attachments/assets/a6ef7c7d-e60c-4826-a372-3f921b71c4e7" />

Se agrega la acción para que el abogado pueda cargar la minuta generada en el sistema con su firma.
1. <img width="410" alt="Image" src="https://github.com/user-attachments/assets/3c71d1f1-2563-4b4a-90d2-cdc81f42ade0" />

2. <img width="413" alt="Image" src="https://github.com/user-attachments/assets/1c06cea1-68b3-400b-a54b-e3d3ec518aa1" />

3. <img width="401" alt="Image" src="https://github.com/user-attachments/assets/735a7a62-ede9-4095-9869-5b6b44607086" />

4. <img width="407" alt="Image" src="https://github.com/user-attachments/assets/962161db-3241-48fc-8b2e-b940a1cda12e" />

**Las modificaciones se realizaron en todos los roles involucrados en la aprobación y firma del contrato. Adjunto enlace archivos actualizados en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtRHNMKONftNgfh2dqvpRgYB1KiebyZ2TqkenPrwjw7p8g?e=NtjDOL


Saludos.

**Comment by jcmurilloa** [comment]
Muy buenos diseños @cjgonzalezp , se terminarán de revisar por parte de desarrollo en el próximo daily
