### ISSUE TITLE
Actualización matriz de roles y permisos y flujo de estados internos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#257]
Se requiere realizar la actualización de la matriz de roles y permisos basado en los cambios efectuados por los estados. También se requiere actualizar el flujo de estados.

**Sub Tareas**

- [x] Actualizar matriz de roles y permisos.
- [x] Actualizar diagrama de máquina de estados.

**Criterios de aceptación**

- [x] Actualización de matriz y diagrama de flujos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza actualización de la matriz de roles y permisos. Adicionalmente, se proyecta diagrama de flujo manejo de estados generales y estados internos para el proceso de contratación.

1.
![Image](https://github.com/user-attachments/assets/2824df43-589a-4dc7-a4e7-8154d152188a)

**Enlace documento matriz de roles y permisos guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ElVi0FHYxEJLnQpPNp3VZSMBovgyYQvaHEE0giygn-1wzQ?e=d9akdA

2.
![Image](https://github.com/user-attachments/assets/a84f1913-6122-4d62-9371-0d93d4785ed5)

**Enlace diagrama de flujo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ejp1TnJuT6NGgMTuy7I0GpsBu5djrQ8-Sfs3VfkmHf7dTA?e=zZSTgz


Saludos.

**Comment by edwargl7** [comment]
Actualizado muchas gracias.
