### ISSUE TITLE
Revisión dependencias de datos del módulo de Gestión Actas de inicio y pólizas - Dependencia de y sobre ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#26]
Se requiere realizar el análisis detallado sobre cada uno de los datos requeridos en el módulo de Gestión Actas de inicio y pólizas, identificando que campos son consumidos o se deben consumir de otros servicios y también identificar que datos registrados en ARGO son consumidos por otros servicios.

Esto con el fin de ver la viabilidad de:

1. Diseñar e implementar un microservicio para la gestión de estos módulos con una base de datos diferente a la base de datos actual, sin afectar otros sistemas. O la necesidad de reutilizar la base de datos actual.

Para esto se debe crear una tabla con la lista de los campos requeridos en el registro de Actas de inicio y pólizas en estos módulos identificando el consumo de otros servicios para poder realizar el registro y que servicios requieren de estos datos.

**Sub Tareas**

- [x] Revisión reuniones y explicación de la lógica de negocio de ARGO.
- [x] Registrar todos los campos de los formularios de registro de contrato de los módulos de Gestión Actas de inicio y pólizas.
- [x] Revisión y registro de cada campo si su fuente es de otro sistema basado en el sistema actual ARGO apoyado con la base de datos del sistema actual. [Ver diagrama en la carpeta de ARGO](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EbS_rdklkDxDo33gYLJ79nkBqGjhDXQgrGdWLDvdNe1k6Q?e=qrdEBS).
- [x] Identificar cuales campos son consumidos por otros sistemas (tarea que se realizará con el apoyo de otros equipos).

**Criterios de aceptación**

- [x] Lista de campos de los formularios de los módulos de Gestión Actas de inicio y pólizas en los que se especifique si la fuente es de otro sistema y si es fuente para otro sistema.

**Requerimientos**

- [ ] Usuario del ambiente de pruebas de ARGO.
- [x] Modelo de datos del sistema actual de ARGO.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Evidenciar el avance progresivo en cada sub tarea.
- [x] Listado de campos de los formularios de los módulos de Gestión Actas de inicio y pólizas que especifiquen la dependencia de otros sistemas, tanto que sean consumidos por ARGO como desde otros sistemas.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Enlace del archivo donde podemos agregar los avances de esta Issue [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBcCUIhWwEqT5dYoDnjk1ZcQ?e=eAaliN). Muchas gracias.

**Comment by jucastro94** [comment]
se realiza revision de grabaciones de capacitacion e induccion ARGO v1

**Comment by edwargl7** [comment]
Se puede complementar la información con el manual de Gestión de Actas pagina 16.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/841c9d6c-a29e-44d1-a05a-4b9d2a4630f0)

**Comment by edwargl7** [comment]
Por el momento no se tiene usuario en ambiente de pruebas, se debe trabajar con el material disponible (manuales y capacitaciones).

**Comment by jucastro94** [comment]
se termina de revisar documentacion y se realiza identificacion inicial de datos requeridos para cada uno de los modulo:
MODULO POLIZA

- descripcion
- fecha de registro
- usuario
- fecha inicio
- fechafin
- numero contrato
- vigencia
- numero de poliza
- entidad aseguradora
- fecha de aprobacion
- fecha expedicion

- unidad de amparo
- amparo
- tipo valor amparo 

ACTA INICIO

- contrato
- fecha inicio
- fecha fin
- plazo ejecucion
- observaciones

**Comment by jucastro94** [comment]
se inserta informacion obtenida en tabla de modulos y dependencias

![Image](https://github.com/udistrital/argo_documentacion/assets/107083834/9396ad7c-c585-4ce7-b66b-d0b81d71d70a)



![Image](https://github.com/udistrital/argo_documentacion/assets/107083834/2ec2e488-3be3-4c9f-b9f4-e53b6fcdfa43)

**Comment by edwargl7** [comment]
Pendiente con el líder validar las tablas donde se almacenan las actas de inico.

**Comment by edwargl7** [comment]
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/c46a4bd6-db02-4604-a5cb-3cb81e1b439c)

**Comment by edwargl7** [comment]
Se realiza la revisión en la que se observa completos los campos basado en la documentación del sistema actual. Revisando con ayuda del arquitecto y la explicación de la gestión de actas de inicio para CPS se identifica que el sistema Titan que actualmente consume las fechas de las actas de inicio no cuenta con un consumo directo si no que se realiza por una ETL lo que permite tener una mayor independencia en el manejo de módulo de gestión de actas de inicio. Muy buen trabajo.
