### ISSUE TITLE
Ajustes endpoint de ordenadores

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#260]
Se requiere realizar el ajuste a snake case en los campos del endpoint de consulta de ordenadores implementado en la Issue #253. Además, completar la integración para el registro en el CRUD de gestión contractual.

**Sub Tareas**

- [x] Ajuste endpoints de ordenadores.
- [x] Integración microcliente y microservicio para el registro del ordenador seleccionado.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza el ajuste en los campos del endpoint de ordenadores de camelCase a snake_case, se ajustan estos cambios primero en el crud (para que quede acorde con el modelo de datos) y luego si en el mid de ordenadores para que se mantenga la coherencia.

**Comment by Lau2ri** [comment]
Se comienza la integración para el guardado del ordenador en el crud, pero todavía hay datos que faltan por clarificar:
![image](https://github.com/user-attachments/assets/e96edad5-7a61-4433-8fc6-28ccc0aab453)
