### ISSUE TITLE
Ajuste selectores en el submódulo de registro de contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#261]
Se requiere realizar el ajuste en los selectores del submódulo del registro de contrato manteniendo el orden alfabético o numérico según sea el caso. Además, en la selección de vigencia de CDP se debe permitir solamente elegir la vigencia actual.

**Sub Tareas**

- [x] Apoyo en la actualización de los parámetros CRUD para agregar en el nombre los números de consulta.
- [x] Ajuste filtros de consulta a parámetros CRUD para organizarlos por número o alfabeticamente.
- [x] Ajuste vigencia de consulta de CDP.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se incian validaciones de las tablas de parámetros.

**Comment by edwargl7** [comment]
Me ayudas actualizando por favor los siguientes:

1. Modalidad de Selección
2. Régimen de Contratación
3. Procedimiento
4. Tema Gasto Inversión

**Comment by mau-oati** [comment]
Ajustes aplicados en Modalidad Selección:

![Image](https://github.com/user-attachments/assets/0a3008ea-1a3c-4476-b310-2a1fa8de50b0)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/6e31c116-bb48-4f11-ac15-dbd9790a9173)

**Comment by mau-oati** [comment]
Orden Alfabético:

<img width="600" src="https://github.com/user-attachments/assets/45772949-aa8a-485a-b887-48965177691e" />

**Comment by mau-oati** [comment]
<img width="362"  src="https://github.com/user-attachments/assets/e187e0cb-22d0-4a77-88b6-d1c62a2b333e" />

Ajuste a Vigencia actual.

**Comment by edwargl7** [comment]
Muy buena implementación. Se revisa para realizar cambios en el orden. Se realiza despliegue en ambiente de pruebas y se valida el desarrollo.

![image](https://github.com/user-attachments/assets/27b9752c-0cf9-43ba-a0cd-e02f9070a30c)
![image](https://github.com/user-attachments/assets/59caec0d-7845-4240-ba61-174a96d77e3e)

Se iniciará validación con @cjgonzalezp para garantizar que se cuenta con todos los registros correctos, dado que unos registros de tipología parecen presentar registros que podría ser necesarios revisar en la BD de parámetros.
![image](https://github.com/user-attachments/assets/7c0149a9-d22c-4915-aea1-63b17e714daa)
