### ISSUE TITLE
Actualización roles y estado de finalización de firmantes

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#262]
Se requiere realizar el ajuste en los roles aplicando los roles nuevos de ARGO v2 teniendo presente los dos roles de ABOGADOS según unidad ejecutora.

**Sub Tareas**

- [x] Actualización roles y permisos con los nuevos roles compartidos.
- [x] Agregar flujo de estado de firmas completadas para la integración en el filtro de búsqueda para el acta de aprobación de póliza.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Evidencia modulo de consulta por roles:

- Si el usuario no se reconoce o los estados no se asocian a las acciones de los roles: 
![1](https://github.com/user-attachments/assets/aafd0048-2cdc-439a-8079-96d896bca25b)

- JEFE_CONTRATACION_RECTOR o JEFE_CONTRATACION_IDEXUD
![2](https://github.com/user-attachments/assets/326ed6fc-8a9b-447a-b52c-2892ba7bff30)
![3](https://github.com/user-attachments/assets/fe942db5-0290-417c-b316-6f9862dd31bf)

- ABOGADO_CONTRATACION_RECTOR o ABOGADO_CONTRATACION_IDEXUD
![4](https://github.com/user-attachments/assets/6e3e3b31-e564-4a8c-8148-8f79a048f64c)
![5](https://github.com/user-attachments/assets/0b05b7bd-dca3-4c41-ac89-47761c107416)

- PROVEEDOR
![6](https://github.com/user-attachments/assets/16b2ebc3-0340-4a91-93eb-0143e5d1a24a)
![7](https://github.com/user-attachments/assets/a3524283-82cb-4c0a-8abb-027c28b20858)

- ORDENADOR_DEL_GASTO
![8](https://github.com/user-attachments/assets/1212e0f4-d778-4c5a-b3df-6672d1e6634b)
![9](https://github.com/user-attachments/assets/99ba95a8-dfcf-4a0a-9aac-6d9e7d4cd2e7)

**Comment by diegobauto** [comment]
Adición de nuevo estado FIRMAS_COMPLETAS, cuando el PROVEEDOR (Contratista) realiza la firma del contrato:
Observación: Se realizan dos registros, el de FIRMADO_CONTRATISTA (6804) y FIRMAS_COMPLETAS (6817) para mantener la trazabilidad (historial)  del contrato.

![Image](https://github.com/user-attachments/assets/fe04d703-5e3e-4076-a774-2ea7f8bb17be)

![Image](https://github.com/user-attachments/assets/b43e1621-0cf8-4433-8bdc-db29882de1c6)

![Image](https://github.com/user-attachments/assets/0294b1c5-f299-493f-a69c-0c8fa8d79c42)

![Image](https://github.com/user-attachments/assets/2e136430-5796-4fca-935c-818ac86a40f0)

**Comment by diegobauto** [comment]
Se realiza ajuste adicional en el componente para cargar el *estado actual* del contrato tomado de la *url* que trae desde el modulo de *Consultar Contrato*.
