### ISSUE TITLE
Actualización estilos en ARGO v2 basado en los ajustes realizados en Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#264]
Se requiere realizar la actualización de la paleta de colores y ajuste en los estilos del formulario de registro de contrato de ARGO basado en los ajuste realizados en Sísifo para mantener un diseño y paleta de colores similar en estos dos sistemas que hacen parte de GAIA. Realizar los ajustes identificados en la Issue #207.

**Sub Tareas**

- [x] Montaje del microcliente 
- [x] Actualización de paleta de colores.
- [x] Actualización del diseño del stepper y formulario de registro (tener precaución con el componente de texto enriquecido y la funcionalidad de búsqueda de los selectores).
- [x] Prueba funcionales.

**Criterios de aceptación**

- [x] Documentación pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Actualización estilos en ARGO v2 basado en los ajustes realizados en Sísifo v2**

>[!NOTE]
> Cambio de estilo en stepper

![image](https://github.com/user-attachments/assets/47e7ea7d-3e5e-416c-ba45-af5de8cfe261)

---

![image](https://github.com/user-attachments/assets/8992ab32-d2cb-441f-99e0-4f3554038d93)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Puntos desarrollados del documento
 
---

[ x ]

![image](https://github.com/user-attachments/assets/b28d10d0-2c30-4454-94ec-36b8c4fb8e8e)

---

[ x ]

![image](https://github.com/user-attachments/assets/5536c05a-2ca6-47fe-b2de-87928aaaf9ae)

---

[ x ]

![image](https://github.com/user-attachments/assets/770b70f4-9696-44b9-b69a-8ac0d47bb59b)

---

[ x ]

![image](https://github.com/user-attachments/assets/d922901b-626b-4757-ae14-cc59ac68346a)

---

[ x ]

![image](https://github.com/user-attachments/assets/4a833692-98af-438d-b04e-fc7b7e93935a)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Diseño  tabla

![image](https://github.com/user-attachments/assets/88d46c2b-6d5c-4b7a-8e34-0326d2e8d628)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Cambio de colores para las alertas

![image](https://github.com/user-attachments/assets/b05d4e90-6edc-44e5-91ca-3c56a1c6cb3c)

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR y se realiza el despliegue. Se puede revisar con @cjgonzalezp la posibilidad de ajustes dado un alto contenido de rojo.
![image](https://github.com/user-attachments/assets/c34ccfcd-8d35-430d-8f10-f6d7fa5bce70)
