### ISSUE TITLE
Actualización documento de avances de Argo v2

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#265]
Se requiere realizar la actualización del módulo de avances de Argo agregando columnas relacionadas a las diferentes fases y documentos requeridos en cada uno para la identificación de avances en cada ambiente y lo requerido para los pasos en cada ambiente.

**Sub Tareas**

- [x] Documentación avances generales en documentación y manuales.

**Criterios de aceptación**

- [x] Actualización del documento.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la actualización del documento de avances de ARGO V2.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU6xVqCteLtMgMZWGApXvAUBeglYsir8Rz7xdZaHWRPemg?e=GeVfbb

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se actualiza el documento de avances del proyecto Argo V2. Junto con el líder técnico haremos una reunión el día 19 de diciembre a las 11:00 am para complementar el documento desde la parte técnica.

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU6xVqCteLtMgMZWGApXvAUBeglYsir8Rz7xdZaHWRPemg?e=GeVfbb

Saludos.

**Comment by edwargl7** [comment]
Se finaliza la actualización con el avance actual,
