### ISSUE TITLE
Construir acta de entregable para el primer alcance del sistema Argo V2

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#267]
Se requiere realizar la proyección del acta de entregables para el primer alcance del sistema Argo V2

Subtareas**

- [x] Recopilar la información técnica de cada modalidad
- [x] Construir el acta de entregables del sistema
- [x] Exponer acta de entregables a funcionamiento

**Criterios de aceptación**

- [ ] Acta de entregables documentada
- [ ] Acta de entregables aprobada por funcionamiento

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Está refinada y estimada en puntos de historia por el equipo.
- [X] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] Las dependencias están identificadas y resueltas.
- [X] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la construcción del documento acta de entregable para el primer alcance del sistema ARGO V2

**Enlace documento guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EZvbbCPfGj9Fu2J6WhEVVRMBwxpsYh1el0sNWZqOpK5UWA?e=ohWzTj

Saludos.

**Comment by edwargl7** [comment]
Buen día se revisa y se complementará una vez se culminen los despliegues y la preparación para la entrega a finales de enero 2025.
