### ISSUE TITLE
Implementación flujo de aprobación por unidad ejecutora

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#268]
Se requiere realizar el análisis e implementación para el flujo de aprobación de la unidad ejecutora Rectoría e IDEXUD. Dado que el flujo de aprobación de estos cambia se requiere realizar la implementación en el cambio de estados que cambia en el ordenador entre los dos flujos.
Además, dado que el ordenador del IDEXUD tiene un paso adicional que es revisar, luego lo envía al contratista y luego de la firma del contratista procede a firmarlo. Este cambio genera que sea necesario manejar de cara al usuario en el primer paso de revisión del ordenador un cambio en el botón de aprobación. Y para el momento en que lo firma ya no puede rechazarlo.

**Sub Tareas**

- [x] Ajuste registros de contratos en base de datos para identificar la unidad ejecutora.
- [x] Ajuste flujo de aprobación implementado actualmente para aplicarlo a los contratos de la unidad ejecutora de Rectoría.
- [x] Pruebas funcionales unidad de Rectoría.
- [x] Implementación flujo de aprobación de la unidad ejecutora Idexud.
- [x] Pruebas funcionales unidad Idexud.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza analisis previo del desarrollo de tal manera que el código tenga mejor adapación para los diferentes flujos del sistema en base a la unidad.

**Comment by diegobauto** [comment]
PR: https://github.com/udistrital/gestion_contractual_mf/pull/73

**Comment by diegobauto** [comment]
Unidad RECTORIA:

- EN_REVISION_JEFE

![Image](https://github.com/user-attachments/assets/dd667620-24bb-4f11-afc0-04ce2bd5e054)

![Image](https://github.com/user-attachments/assets/b04c09aa-26a4-4cc9-b908-1e93c0e01595)

![Image](https://github.com/user-attachments/assets/e52c0ee9-ef2e-4a22-a28e-57bd1b5b8c65)

![Image](https://github.com/user-attachments/assets/9b62164a-8470-479f-82fc-3a5cebf0eb11)

![Image](https://github.com/user-attachments/assets/9f8c9b2e-8671-4fad-b911-314c3587fb58)

- EN_FIRMA_ORDENADOR

![Image](https://github.com/user-attachments/assets/77a501e9-3818-49da-bf2e-f30f748022b2)

![Image](https://github.com/user-attachments/assets/cbd0d904-149b-4081-829b-da8c39265f14)

![Image](https://github.com/user-attachments/assets/928c8f83-efa1-43a2-b86a-5fb7f8164e43)

![Image](https://github.com/user-attachments/assets/e92f3453-c9b0-49b6-80f4-5dfbe043c4e6)

![Image](https://github.com/user-attachments/assets/8bc5505a-74a5-4302-94a4-5fcaff1fc7ec)

- EN_FIRMA_CONTRATISTA

![Image](https://github.com/user-attachments/assets/5593bae3-8ba3-4042-9f04-445dc8945604)

![Image](https://github.com/user-attachments/assets/c16dc6a3-9622-45d8-b2fa-38fcaefdf45c)

![Image](https://github.com/user-attachments/assets/b80dbdfd-d7d1-4a2d-b061-bd85cb45c4b5)

![Image](https://github.com/user-attachments/assets/9387bb2c-79c8-46ae-abd2-9650a121f0c3)

![Image](https://github.com/user-attachments/assets/c6a9018d-abb7-445c-84fc-2100b607c564)

**Comment by diegobauto** [comment]
Unidad IDEXUD:

- EN_REVISION_JEFE

![Image](https://github.com/user-attachments/assets/42736eea-55ef-4bb4-ae82-b31a451b63f9)

![Image](https://github.com/user-attachments/assets/91a1aff4-d6ef-4336-9b8e-8448066a2edb)

![Image](https://github.com/user-attachments/assets/ae56b779-5a0a-4744-8ed0-b87dad9ccdb9)

![Image](https://github.com/user-attachments/assets/b5429f5b-f590-4778-81d1-bcd289bc3b4b)

![Image](https://github.com/user-attachments/assets/980e79d7-f454-408f-a245-b8fa68da1211)

- EN_REVISION_ORDENADOR

![Image](https://github.com/user-attachments/assets/0e211c92-d0e8-4013-91e9-62961ae8d248)

![Image](https://github.com/user-attachments/assets/89882ca8-0f35-45ba-b5fe-9e4c1fce13f5)

![Image](https://github.com/user-attachments/assets/560e2af5-34c3-4f82-9589-6cb9cb41aa9a)

![Image](https://github.com/user-attachments/assets/df03017b-a91f-48a2-baf9-f65516c9d5cb)

![Image](https://github.com/user-attachments/assets/26c2010a-cf30-45f8-8740-dceae1cbd9c5)

- EN_FIRMA_CONTRATISTA

![Image](https://github.com/user-attachments/assets/047248d1-823f-4b7b-90d7-6610bcfee250)

![Image](https://github.com/user-attachments/assets/44ade8eb-53f6-46e9-a46e-507159c9366e)

![Image](https://github.com/user-attachments/assets/a3b6e4a3-3259-4755-b573-6cb326dd8935)

![Image](https://github.com/user-attachments/assets/03b5d7f8-e848-4471-a93d-88481e428d85)

![Image](https://github.com/user-attachments/assets/2bd61c59-747a-4146-832f-d294511b5a31)

- EN_FIRMA_ORDENADOR

![Image](https://github.com/user-attachments/assets/a52be86b-1d88-48bd-9d38-1cdd4768460e)

![Image](https://github.com/user-attachments/assets/0133bc87-9021-4861-aec6-309dfddc0a57)

![Image](https://github.com/user-attachments/assets/2b698eaf-5a82-4065-a241-aebdf9ccfc69)

![Image](https://github.com/user-attachments/assets/17dc14af-2e90-46fb-a583-dd54f050a39a)

![Image](https://github.com/user-attachments/assets/18000790-7887-4231-9186-19f3b8e743c3)

**Comment by edwargl7** [comment]
Muy buen diseño, implementación y documentación de pruebas. Cubre el escenario solicitado y permite realizar cambios en flujos para futuras nuevas unidades ejecutoras o cambios en los flujos actuales minimizando la complejidad de los cambios. Tener presente esta implementación para documentarla en el documento técnico para futuras necesidades.

Resolver conflictos del PR por favor.
