### ISSUE TITLE
Apoyo validación integración de ordenadores con el microcliente

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#269]
Se requiere realizar las pruebas de la integración entre el microservicio de ordenadores mid, el microcliente y el microservicio CRUD. Para validar que se consulte de forma correcta el rol/cargo y la información del ordenador. También realizar las pruebas de integración con el CRUD para validar el correcto registro de la información del ordenador.

**Sub Tareas**

- [x] Pruebas funcionales integración consulta de rol e información del ordenador.
- [x] Pruebas funcionales integración registro de ordenador asociado al contrato.

**Criterios de aceptación**

- [x] Documentación resultado de pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/eaee7d43-2679-426f-912d-ba7f939877cd

**Comment by edwargl7** [comment]
Resueltos PR. Muchas gracias por el apoyo en las pruebas. Se completa correctamente.
