### ISSUE TITLE
Revisión dependencias de datos del módulo de Gestión Ordenadores del gasto - Dependencia de y sobre ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#27]
Se requiere realizar el análisis detallado sobre cada uno de los datos requeridos en el módulo de Gestión ordenadores del gasto, identificando que campos son consumidos o se deben consumir de otros servicios y también identificar que datos registrados en ARGO son consumidos por otros servicios.

Esto con el fin de ver la viabilidad de:

1. Diseñar e implementar un microservicio para la gestión de estos módulos con una base de datos diferente a la base de datos actual, sin afectar otros sistemas. O la necesidad de reutilizar la base de datos actual.

Para esto se debe crear una tabla con la lista de los campos requeridos en el registro de ordenadores del gasto en estos módulos identificando el consumo de otros servicios para poder realizar el registro y que servicios requieren de estos datos.

**Sub Tareas**

- [x] Revisión reuniones y explicación de la lógica de negocio de ARGO.
- [x] Registrar todos los campos de los formularios de registro de contrato de los módulos de Gestión ordenadores del gasto.
- [x] Revisión y registro de cada campo si su fuente es de otro sistema basado en el sistema actual ARGO apoyado con la base de datos del sistema actual. [Ver diagrama en la carpeta de ARGO](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EbS_rdklkDxDo33gYLJ79nkBqGjhDXQgrGdWLDvdNe1k6Q?e=qrdEBS).
- [x] Identificar cuales campos son consumidos por otros sistemas (tarea que se realizará con el apoyo de otros equipos).

**Criterios de aceptación**

- [x] Lista de campos de los formularios de los módulos de Gestión ordenadores del gasto en los que se especifique si la fuente es de otro sistema y si es fuente para otro sistema.

**Requerimientos**

- [ ] Usuario del ambiente de pruebas de ARGO.
- [x] Modelo de datos del sistema actual de ARGO.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Evidenciar el avance progresivo en cada sub tarea.
- [x] Listado de campos de los formularios de los módulos de Gestión ordenadores del gasto que especifiquen la dependencia de otros sistemas, tanto que sean consumidos por ARGO como desde otros sistemas.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Enlace del archivo donde podemos agregar los avances de esta Issue [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBcCUIhWwEqT5dYoDnjk1ZcQ?e=eAaliN). Muchas gracias.

**Comment by alexhrr** [comment]
Se está llevando a cabo la revisión del material suministrado para comprender la lógica de negocio y el funcionamiento del sistema para poder llevar a cabo el análisis solicitado.

**Comment by edwargl7** [comment]
Por el momento no se tiene usuario en ambiente de pruebas, se debe trabajar con el material disponible (manuales y capacitaciones).

**Comment by edwargl7** [comment]
Se puede apoyar la revisión con el siguiente manual. Muchas gracias.
[ADMINISTRACIÓN GENERAL (SOPORTE 1er Y 2do NIVEL) - ARGO.pdf](https://github.com/udistrital/argo_documentacion/files/15392111/ADMINISTRACION.GENERAL.SOPORTE.1er.Y.2do.NIVEL.-.ARGO.pdf)

**Comment by alexhrr** [comment]
Se realiza el registro de los campos solicitados para el módulo de gestión de ordenadores de contrato en el documento dispuesto para registrar los avances.
Según la información suministrada, los servicios del modulo son independientes y no requiere consumir otro servicio, pero los registros si son consumidos por otros servicios que se encuentran en el documento.

**Comment by edwargl7** [comment]
Se completa, se va a revisar más detallado el archivo con los campos encontrados.

**Comment by edwargl7** [comment]
Se realiza la revisión en la que se observa por el momento completos los campos basado en el modelo de datos y el sistema actual. Por medio del resultado se plantea la posibilidad de mantener este submódulo en microservicios y microcliente separado del core de ARGO. Es posible que se refine este submódulo con requerimientos del usuario. Se va a revisar más detallado los puntos de mejora de este submódulo. Muy buen trabajo.
