### ISSUE TITLE
Actualización estilos en ARGO v2 basado en los ajustes realizados en Sísifo v2 - Póliza MF

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#270]
Se requiere realizar la actualización en los estilos del formulario de registro de póliza que consta:
1. Búsqueda de contrato al que se realiza la asociación.
2. Visualización del formulario de asociación de póliza.

Se agregan las imágenes del mockup en el que se observa el diseño y comportamiento esperado. 

**Mockup**
![image](https://github.com/user-attachments/assets/2e8950b3-9cc0-4b68-8a28-f4804ef817cb)
![image](https://github.com/user-attachments/assets/490d7e34-acc7-46f3-9d62-524390f36f2a)
![image](https://github.com/user-attachments/assets/e2f65d55-2e5c-4be2-aeee-52b759adf374)
![image](https://github.com/user-attachments/assets/58dd6bb3-e6c4-43c0-8d6c-8143d8917bc8)
![image](https://github.com/user-attachments/assets/a8de1fe0-f47f-429d-84a0-81f1723d3751)

**Sub Tareas**

- [x] Actualización vista de consulta de contrato.
- [x] Ocultar los botones de acciones cuando no se tiene seleccionado ni se visualiza el formulario de póliza.
- [x] Actualización del formulario de registro de póliza.
- [x] Implementación interceptor.
- [x] Implementación spinner.
- [x] Ajuste diseño de alertas.

**Criterios de aceptación**

- [x] Documentación de ajustes del diseño.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Actualización estilos en ARGO v2 basado en los ajustes realizados en Sísifo v2 - Póliza MF**

>[!NOTE]
> - Cambio de estilos 
> - Implementación de spinner
> - Implementación de inputs responsive

![image](https://github.com/user-attachments/assets/f01b6a59-79b8-42c5-ac21-c07f8a9ae10c)

**Comment by edwargl7** [comment]
Resuelto PR finalizada. Muchas gracias.
