### ISSUE TITLE
Actualización estilos en ARGO v2 basado en los ajustes realizados en Sísifo v2 - Acta Inicio MF

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#271]
Se requiere realizar la actualización en los estilos del formulario de registro de acta de inicio.

1. Búsqueda de contrato al que se realiza la asociación.
2. Visualización del formulario de registro de acta de inicio.

Se agregan las imágenes del mockup en el que se observa el diseño y comportamiento esperado. 

**Mockup**

![image](https://github.com/user-attachments/assets/2e6eedb5-1327-495c-975c-ab93524a38b0)
![image](https://github.com/user-attachments/assets/6f9fed26-01c1-41fc-829b-9942154106d9)
![image](https://github.com/user-attachments/assets/c4c8bdde-ecf2-417c-b94a-efce39ef6026)
![image](https://github.com/user-attachments/assets/bab88e6f-bfd7-4b62-92cb-f36ef7da48e2)

**Sub Tareas**

- [x] Actualización vista de consulta de contrato.
- [x] Actualización del formulario de registro de póliza.
- [x] Implementación interceptor.
- [x] Implementación spinner.
- [x] Ajuste diseño de alertas.

**Criterios de aceptación**

- [x] Documentación de ajustes del diseño.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Actualización estilos en ARGO v2 basado en los ajustes realizados en Sísifo v2 - Acta Inicio MF**

>[!NOTE]
> - Cambio de estilos en el formulario
> - Implementación de inputs responsive
> - Implementación de spinner (servicio - interceptor - componente)

https://github.com/user-attachments/assets/e892871f-6a5b-45ed-9972-a2407f2e0af5

**Comment by edwargl7** [comment]
Resuelto PR, finalizada implementación.
