### ISSUE TITLE
Documentación técnica roles y permisos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#273]
Se requiere realizar la documentación técnica de los roles en la vista de consulta y registro de contrato.

**Sub Tareas**

- [x] Documentación roles y permisos.

**Criterios de aceptación**

- [x] Documento actualizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza actualización de documento técnico incluyendo apartado de Roles y permisos

[Documentación Técnica registro de contrato](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdfjoP3Phv1HkJz_rWNb83EBuCb-w1YHyrt4OV4IvsW3Xw?e=bkmOi0)

![Image](https://github.com/user-attachments/assets/41995b1f-0626-41c5-b6ee-495fd3f18809)

![Image](https://github.com/user-attachments/assets/ae62291c-0d60-4b23-82d2-2d05da7d5d5f)

![Image](https://github.com/user-attachments/assets/ea16309e-b3d6-40d7-a1fb-fbacea87f487)

![Image](https://github.com/user-attachments/assets/12490fa4-47ca-4f68-9b03-115eb41a2505)

**Comment by edwargl7** [comment]
Buen trabajo, se realizará la revisión con @cjgonzalezp.
