### ISSUE TITLE
Implementación unidad ejecutora registro de contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#274]
Se requiere realizar agregar en el mf [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_mf) un selector de unidad ejecutora que por defecto deje preseleccionado la unidad ejecutora que tenga el usuario (en caso de tener un solo rol de unidad ejecutora, en caso de tener más de uno no se selecciona ninguno). El campo será obligatorio y se debe agregar en el primer paso del formulario.

**Sub Tareas**

- [x] Implementación selector en el paso 1.
- [x] Implementación buscador por número.
- [x] Implementación lógica preselección.
- [x] Integración registro, actualización y consulta en el MID y CRUD.
- [x] Pruebas funcionales.
- [x] Implementar buscador en número de disponibilidad paso 2.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/154998af-0b34-4588-917e-61334faccf95)

**Comment by mau-oati** [comment]
## Dos opciones: 

![Image](https://github.com/user-attachments/assets/5291ab53-112a-4feb-9e2e-79d336e2b14d)

## Única Opción:
![Image](https://github.com/user-attachments/assets/402d173a-df30-4d72-9599-9b932faacb98)

**Comment by mau-oati** [comment]
### Selector de búsqueda en CDPs:
![Image](https://github.com/user-attachments/assets/a064d1c6-2f99-4dba-b749-3fe8b12c569d)

**Comment by edwargl7** [comment]
Revisado y aprobado el PR, pero es necesario resolver conflictos por favor para completarlo.
Muy buen trabajo.
