### ISSUE TITLE
Ajustes cambio de estado contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#276]
Se requiere realizar el ajuste en el motivo para los casos aprobados para no enviar un string " ". Ajustes flujo basado en tipo de unidad ejecutora del contrato.

**Sub Tareas**

- [x] Ajuste motivo en los casos aprobados.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza ajuste con @mau-oati para tomar como nulo el motivo de un estado de contrato, en dado caso de aprobación

**Comment by diegobauto** [comment]
Prueba funcional:

![Image](https://github.com/user-attachments/assets/8597c04c-ee4a-4157-ac97-14a50fa59f93)

![Image](https://github.com/user-attachments/assets/c0b34156-a324-4f60-b86a-0cc6a568b0ca)

**Comment by diegobauto** [comment]
Pruebas funcionales. obtención de unidad ejecutora con respecto al contrato:

Unidades ejecutoras:
![Image](https://github.com/user-attachments/assets/2872e3d8-159c-44be-9356-862c4f903a89)

Contratos:
![Image](https://github.com/user-attachments/assets/a34d60f2-b12c-424a-bf6f-1d99136ccd87)

![Image](https://github.com/user-attachments/assets/d88e79f7-adbc-4dfb-ab3e-fedb0a01a405)

![Image](https://github.com/user-attachments/assets/cc1e5a5b-f24d-426b-838d-90696e0d4120)

![Image](https://github.com/user-attachments/assets/e582bfcb-5b60-4cfa-8af5-6f4eb50f43ed)
