### ISSUE TITLE
Integración cargue masivo especificaciones técnicas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#277]
Se requiere realizar la integración del cargue masivo en el paso de especificaciones técnicas basado en la plantilla XLSX.

**Sub Tareas**

- [x] Crear plantilla XLSX.
- [x] Integración cargue masivo creando endpoint en el MID [gestion_contractual_mid](https://github.com/udistrital/gestion_contractual_mid).
- [x] Implementación botón de descarga de la plantilla XLSX.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Creación de Plantilla XLSX: 
[plantilla cargue masivo especificaciones.xlsx](https://github.com/user-attachments/files/18264750/plantilla.cargue.masivo.especificaciones.xlsx)

**Comment by diegobauto** [comment]
Pruebas funcionales:
- Se añade estado de carga mientras se procesan las especificaciones y barra de deslizamiento para facilitar la visualización cuando hayan muchas especificaciones.
- Queda pendiente actualizar tabla al finalizar el proceso, y ajustar modal para manetener estilos actuales del sistema.
- Observación: Cuando la petición en alguna de las filas  aparece una parte del mensaje que dice: "Error al preparar el payload". Sería recomendable ajustar este mensaje para que sea más claro y menos técnico para el usuario final.

Todas las filas están de forma correcta:

![Image](https://github.com/user-attachments/assets/25d66a5c-1f44-4d33-b484-7d551732f356)

![Image](https://github.com/user-attachments/assets/de44481d-530b-469c-8a2f-1495c9f60a97)

![Image](https://github.com/user-attachments/assets/48aa0d92-6e3b-4b0f-a642-bdd6417b5f0b)

![Image](https://github.com/user-attachments/assets/7d7a52bc-7a9f-4e2e-9218-dea2a6c94692)

![Image](https://github.com/user-attachments/assets/220c7eb2-e557-4d41-b244-91a84dc4677d)

Faltan valores por ingresar en las filas: 

![Image](https://github.com/user-attachments/assets/c4fe5233-dfe2-40f4-ad7e-bd5ca05c3477)

![Image](https://github.com/user-attachments/assets/e052856c-6cef-4c51-bab6-0d323055e22f)

![Image](https://github.com/user-attachments/assets/bda1e79b-710e-4222-9068-93aed3061716)

![Image](https://github.com/user-attachments/assets/e29982dd-ebcd-4c9b-acf0-d36f67e2f6ec)

![Image](https://github.com/user-attachments/assets/d3433f46-41c6-4647-9b8f-b5d735a939b8)

**Comment by edwargl7** [comment]
Buen trabajo, se resuelven PR. Ajustar lo siguiente:

- Cambiar serverlessUrl por un nombre de variable específico al servicio
![image](https://github.com/user-attachments/assets/1e976074-f1a0-4b1e-af13-964561bfe146)
