### ISSUE TITLE
Implementación firma con cargue de documento

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#278]
Se requiere realizar el ajuste en el flujo de firma en las vistas de aprobación (jefe, ordenador y contratista) para al momento de aprobar y firmar o firmar (ordenador del IDEXUD) se muestre un modal para cargar la minuta firmada.

![image](https://github.com/user-attachments/assets/b36ccaea-0b37-414d-9265-920fac47e690)

**Sub Tareas**

- [x] Implementación modal para cargue de minuta en PDF.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza la implementación del modal que permite subir el archivo de la minuta firmada en los casos en los que ésta acción sea permitida respetando los roles y el estado del contrato seleccionado.

https://github.com/user-attachments/assets/66f28977-3b91-4962-be25-34332801e84e

![Image](https://github.com/user-attachments/assets/0a927696-a614-459d-b62f-f6412a9f78a5)

**Comment by edwargl7** [comment]
Buen trabajo, se resuelve el PR y se ajusta la referencia del servicio de gestor documental por error detectado en el despliegue.
![Image](https://github.com/user-attachments/assets/2b8d62ec-8d4b-4d5b-a8b9-d3211502ff29)
