### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión requerimientos con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#28]
Se requiere realizar la concertación, desarrollo y levantamiento acta de sesión de requerimientos con cliente

**Sub Tareas**

- [x] Concertar reunión de requerimientos con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Diligenciamiento del formato de historias de usuario con el cliente
- [x] Aprobación del formato de historias de usuario
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes con anexo de historias de usuario

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se agenda reunión para el día viernes 31 de mayo de 2024 a las 9:30 am con la Oficina de Contratación para continuar con el levantamiento de requerimientos.



Cordial saludo.

**Comment by cjgonzalezp** [comment]
Buen día,

Se levanta acta de reunión #039/2024 requerimientos con cliente. Pendiente recolección de firmas por los participantes.

**Link del documento cargado en OneDrive en la carpeta del proyecto correspondientes**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnGlMAuAzARKldo30_NunLYBB2z9KbL8jvmw_ko_WOjtKQ?e=KZboTi

Cordial saludo

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta a cliente Jhon Henry Arenas, para concertar reunión para el día viernes 07 de junio de 2024. Pendiente confirmación de la hora.

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los ajustes sugeridos y se vuelve a cargar el documento a la carpeta de proyecto correspondiente. Queda pendiente recolectar firmas de los participantes.

**Link del documento cargado en OneDrive en la carpeta del proyecto correspondientes**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnGlMAuAzARKldo30_NunLYBB2z9KbL8jvmw_ko_WOjtKQ?e=Ztyy7Y

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza con la recolección de firmas de los participantes presentes en la reunión. 

**Adjunto link del documento cargado en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnGlMAuAzARKldo30_NunLYBB2z9KbL8jvmw_ko_WOjtKQ?e=Ztyy7Y

Saludos

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp
