### ISSUE TITLE
Revisión estilos y parámetros del ambiente de pruebas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#280]
Se requiere realizar la revisión del ajuste de estilos aplicados al microcliente de gestión contractual y los parámetros del formulario. También revisar si es requerido agregar la funcionalidad de búsqueda en algún otro selector.

**Sub Tareas**

- [x] Revisión estilos.
- [x] Revisión parámetros de los selectores.
- [x] Revisión funcionalidad de búsqueda en los selectores (se requiere en algún otro selector?)

**Criterios de aceptación**

- [x] Documentación de la Issue con los resultados de la revisión.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza revisión de estilos y parámetros del ambiente de pruebas al microcliente de gestión contractual registro de contrato.

1. Agregar lista de tipos de contratos para convenios los cuales fueron actualizados en el documento de datos paramétricos 
![Image](https://github.com/user-attachments/assets/c1a1e9cf-db29-4aa6-9169-d8b1e3c5defe)
![Image](https://github.com/user-attachments/assets/e1389390-5464-4b90-a7cc-e5b7c40846ee)

2. Agregar a la lista de perfil contratista, el perfil asesor 3 como se menciona en el documento datos paramétricos 
![Image](https://github.com/user-attachments/assets/df978ff7-9028-40c9-beb1-59c710b7779f)
![Image](https://github.com/user-attachments/assets/6d1a4cd6-2467-4e7a-843c-bd57d56e6513)

3. Revisar la lista para el campo tipología especifica, la información no corresponde a lista suministrada en en el documento datos paramétricos
![Image](https://github.com/user-attachments/assets/f7008658-f825-4f15-8f2a-882d49b00b84)
![Image](https://github.com/user-attachments/assets/790b6d2e-28c7-41a4-88dc-476bec6ea6fa)

4. Revisar el campo valor del contrato, este lo debería traer el sistema automaticamente
![Image](https://github.com/user-attachments/assets/921f2a00-acd3-4bc0-a0f3-65a0ddffbec5)

5.  El nombre del ordenador debería ser un campo de búsqueda, sugiero agregar el símbolo de la lupa
![Image](https://github.com/user-attachments/assets/e263c02e-3ec4-4621-85ae-79f6ac029569)
 
6. Dar orden numérico de menos a mayor a la lista del campo origen de recurso
![Image](https://github.com/user-attachments/assets/cf31fc25-f842-49f1-a55f-7c5acf4b5008)

7. Dar orden numérico de menos a mayor a la lista del campo tema gasto inversión
![Image](https://github.com/user-attachments/assets/4bb5cdd9-d46e-4e74-a1ad-6eb9f7f73a43)

8.  Cambiar color del título **forma de pago** y dejarle el mismo color del menú
![Image](https://github.com/user-attachments/assets/0600210c-cd61-4c2e-8a3c-f380e2480c0f)

**Comment by cjgonzalezp** [comment]
9. Pendiente revisar el step **información solicitante y supervisor**
![Image](https://github.com/user-attachments/assets/c69b9760-165a-4eb6-93d4-007422cfdfab)

10. Es posible dejar en negrita los títulos de la información![Image](https://github.com/user-attachments/assets/a443a57f-47b7-46e0-9783-11bbc282b7e6)

11. No se visualiza el step de **amparos y mecanismos de garantías**
![Image](https://github.com/user-attachments/assets/74b967c9-22e9-44f0-88be-44b30e4d4aea)


Por favor revisar los comentarios y realizar los ajustes pertinentes de estilos y parámetros del ambiente de pruebas revisados en la presente issue para dar por finalizada y aprobar el formulario de registro de contrato.

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente @edwargl7 de estos ajustes para generar con el equipo de desarrollo.
