### ISSUE TITLE
Integración cargue masivo especificaciones técnicas - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#284]
Se requiere realizar la implementación de actualización de tabla de especificaciones técnicas.

**Sub Tareas**

- [x] Implementación actualización paso de especificaciones técnicas.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Validación unicamente archivos xlsx:

![Image](https://github.com/user-attachments/assets/e6f0ece6-90d5-4e5b-a74e-20933c689726)

Actualización de tabla al realizar cargue masivo:

![Image](https://github.com/user-attachments/assets/d8c991b0-f63a-4a8c-8d20-7bcf9a1793ee)

![Image](https://github.com/user-attachments/assets/cec61c86-6e67-41a2-9383-3cd504d9f1d3)

![Image](https://github.com/user-attachments/assets/95f83e2c-eb81-4127-a2c0-d20429de93c6)

![Image](https://github.com/user-attachments/assets/e55ee6cc-93f1-4a8b-81b3-6789d23dc883)

**Comment by edwargl7** [comment]
Buen trabajo, se revisará la actualización de la carga nuevamente junto con el spinner y el interceptor implementado en la Issue #283 .
