### ISSUE TITLE
Revisión Lineamientos aplicativos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#3]
Se requiere realizar la revisión del "Manual de identidad visual subsistemas de información" para seguir las recomendaciones en el uso de logotipos, tipografías, estilos y distribución de la interfaz.

**Sub Tareas**

- [x] Revisión Manual de identidad visual subsistemas de información [Lineamientos aplicativos v2](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EVWLVk3colNNlAs6ExWXQfcB7LJ0JS_Xnido3CPXP5Tn7w?e=RWpoe6)

**Criterios de aceptación**

- [x] Descripción elementos importantes a tener en cuenta para el desarrollo del Argo v2

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Breve descripción de elementos importantes para el desarrollo del Argo v2.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
ARGO hace parte de Gaia en el esquema de estilos.

El esquema de colores es: 

Tonos basados en Pantone 1815C: 

#731514
#863028
#98483C
#AA5F52
#BC7669
#CD8E81
#DEA69A
#EFBEB4
#FFD7CE
#FFEAE6
#FFFFF



![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/26e68fcc-f121-4247-bf70-e39ec328d4b5)

**Comment by mau-oati** [comment]
Tipografía Principal: **Cocogoose regular**
Texto principal de los logotipos.

Tipografía Secundaria: **For the love of hate bold**
Texto secundario de los logotipos.

Tipografía Adicional: **Titilium semibold**
Texto de logotipos para la página web de la Dependencia.



![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/2c2a4013-84b8-4a0f-8490-0c560141bdbb)

**Comment by mau-oati** [comment]
![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/cc9a0d7b-42d9-462f-89bc-54a651c1cfda)


1. **Header**: Encabezado de los sistemas de información. Este ocupa el 10% del total de la pantalla y tiene un fondo color blanco (#FFFFFF). En él se encuentran los siguientes elementos:
1.1. **Logotipo**: ubicado en la parte superior derecha de la pantalla. En este caso, debe ir en su versión original.
1.2. **Barra de búsqueda**: ubicada en la parte central superior de la pantalla.
1.3. **Botones de usuario**: Esta sección, ubicada en la parte superior derecha de la pantalla, se compone por tres botones: Mensajes, notificaciones y usuario, donde podrá consultar la información de la cuenta. En esta sección también encontrará el usuario que está trabajando en el aplicativo (la tipografía utilizada para este texto es Open Sans Bold).

2. **Espacio de trabajo**: En este espacio el usuario podrá realizar la gestión correspondiente al proceso que está ejecutando. Este debe ocupar el 66,25% de la pantalla.


3. **Menú**: En esta sección se muestran las distintas funciones que tiene habilitado el usuario enel sistema. Este debe ocupar el 13,75% de espacio de la pantalla.
3.1. **Íconos y texto del menú**: Aquí se encuentran varias secciones. La primera son los tres íconos dispuestos en forma vertical que corresponden a los accesos a preguntas frecuentes, videotutoriales y manuales. En la parte inferior de estos íconos se encuentran los menús y sus respectivos íconos y los submenús propios del aplicativo con el que se está trabajando. La fuente a utilizar para los textos de los menús es Open Sans Bold y para los submenús se utiliza Open Sans Semibold.

4. **Footer**: En esta sección se encuentra la información general de la dependencia y debe ocupar el 10% del espacio de la pantalla.
4.1. En la parte inferior izquierda, se encuentra el escudo y logotipos horizontales de la universidad, cumpliendo los lineamientos para su uso, seguido por una línea vertical y el nombre de la Oficina Asesora de Sistemas (la tipografía utilizada para este texto es
Open Sans Bold).

**Comment by Lau2ri** [comment]
Para finalizar, el isotopo que corresponde al Sistema Argo se muestra en la siguiente imagen:
<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/d530719f-d8b1-40b9-a1ff-3ddb9482e563" width="180" >

Este istopo debe ubicarse al lado izquierdo de el nombre del aplicativo escrito en mayúsculas y justo debajo del nombre una descripción del objetivo del aplicativo, en este caso esa descripción es "Gestión de contratación y compras" en combinación de mayúsculas y minúsculas, ambos textos cumpliendo los parámetros de color y tipografía.

Esta disposición nos da como resultado el logotipo del Sistema Argo, mostrado a continuación:

 <img src="https://github.com/udistrital/argo_documentacion/assets/133523053/3c8e00aa-d839-4b9c-8ef6-aec0e0cb10c6" width="550">

Para finalizar, el logotipo de alto contraste sobre el fondo color rojo característico de Argo, tanto el isotopo como el texto que lo acompaña deben estar en color blanco para así resaltar sobre su fondo, de la siguiente manera:

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/e1f40ede-713e-487e-9258-a7ed70c1f063" width="550">

**Comment by edwargl7** [comment]
Excelente trabajo. Tener presente estos lineamientos en el desarrollo de los microclientes.
