### ISSUE TITLE
Culminar el diseño del mockup del submódulo Gestión de contratos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#30]
Se requiere culminar el diseño del mockup del submódulo Gestión de contratos acorde a lo indicado en la reunión cliente. 

**Sub Tareas**

- [ ] Diseñar mock up con base en los requerimientos.
- [ ] Presentar el mockup al cliente.
- [ ] Realizar ajustes según comentarios del cliente.
- [ ] Presentar al equipo el mock definitivo para el desarrollo.

**Criterios de aceptación**

- [ ] Mockup aprobado por cliente y equipo.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza avance en el mockup de los submódulos faltantes del módulo de gestión contractual.

![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/03cbdf97-84ac-4d4e-9c1f-60e199f0b4a2)

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza avance de mockup del módulo de gestión contractual.

**Submódulo Registro Contrato Mejorado**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/71c7a0d1-66b6-402f-a288-d959d5cdddbe)

**Link del archivo cargado en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmJYcbb4P51Jr7bcXo-TadIBeAozStHKnipweAoG8VWYYw?e=MntxgY


Cordial saludo.

**Comment by cjgonzalezp** [comment]
Adicional, se hace una segunda sesión de revisión con el líder técnico del proyecto el 30 de mayo de 2024 para hacer ajustes antes de presentarlo al cliente.

**Link grabación de sesión**
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cjgonzalezp_udistrital_edu_co/ETKws8HLMUxIsOPSq4fCe-IBrq7cwapwxCHzYB-KL-miyw?e=bPHKQi&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


Cordial saludo

**Comment by jcmurilloa** [comment]
Muy buen trabajo, adicionar por favor opciones para proyectar acta de aprobación y de inicio en el módulo de Gestión contractual
