### ISSUE TITLE
Diseño modelo de datos de cada módulo de ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#32]
Se requiere realizar el diseño inicial del modelo de datos para cada módulo propuesto de ARGO v2. Este modelo de datos se divide en cada módulo lo cual permite proponer el uso de bases de datos relacional y no relacional según sea el caso. Además, tener una división de base de datos identificando parcialmente los microservicios.
Es importante identificar los datos paramétricos y los datos que son obtenidos de otros sistemas. En caso de ser una base de datos relacional tener presente los lineamientos [Modelo de datos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md). En caso de ser una base de datos no relacional agregar notas de los campos que son obtenidos de otros servicios para una mayor claridad.

**Sub Tareas**

- [x] Diseño modelo de datos del módulo de actas de inicio.
- [x] Diseño modelo de datos del módulo pólizas y amparos.
- [x] Diseño modelo de datos del módulo de gestión contractual y órdenes de compras y servicios.
- [x] Actualización documento [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s) con los tipos y restricciones evidenciados en el progreso del diseño del modelo de datos.

**Material**
- [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s)

**Criterios de aceptación**

- [x] Diseño modelo de datos del módulo de actas de inicio, teniendo presente los lineamientos.
- [x] Diseño modelo de datos del módulo pólizas y amparos, teniendo presente los lineamientos.
- [x] Diseño modelo de datos del módulo de gestión contractual y órdenes de compras y servicios, teniendo presente los lineamientos.
- [x] Actualización documento [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s) con los datos aclarados en el diseño del modelo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Modelos de datos de actas de inicio, pólizas y amparos y gestión contractual y órdenes de compra y servicio.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Borrador incial tabla contrato:



![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/e06ca6bd-90d2-4b7c-8d08-d796bb7110a2)

**Comment by mau-oati** [comment]
Avance del Borrador:

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/7160c5d9-3c89-464a-b436-0504ae1dae63)

**Comment by mau-oati** [comment]
En color <span style="color:orange">naranja</span>tenemos los elementos que deberían ser paramétricos, y en color <span style="color:purple">morado</span> los casos particulares que vale la pena revisar. 


Con **numero_constancia**: Es opcional y se llena de manera trivial. Correcto?
Con **cargo** en supervisor: Es un campo paramétrico o es el id de una tabla cargo?

**Comment by edwargl7** [comment]
Se realiza la revisión en base de datos del sistema actual y no es claro el uso de numero_constancia. El cargo es paramétrico.

**Comment by mau-oati** [comment]
![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/f9b75ea9-8f8b-4cdc-ab8f-032516012e32)

**Comment by edwargl7** [comment]
Se realiza una revisión inicial. Se observa un buen trabajo. Pendiente el diseño del modelo de datos para actas de inicio. Pendiente complementar el documento [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s) las columnas Requiere de (tablas propias) y Requiere de (otros servicios) con lo identificado desde esta vista.

**Comment by mau-oati** [comment]
**Propuesta Inicial:**


![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/44876099-667e-453a-9bcf-434476c87924)


Separada por Micro Servicios, basado en la tarea #33 


**MS - Supervisor Contrato:**

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/f753fff4-baac-44a1-a8da-c5785b36d9d1)

**MS - Acta de Inicio:**

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/bd2a298e-9d9c-4e68-b65b-c4e9d1386069)

**MS - Pólizas y Amparos:**


![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/67a04139-d553-405b-8c38-36bcdf377a21)


**MS - Ordenador:**


![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/f0a6aa19-95b2-4739-b7c0-ad5f925a11ea)

**Comment by edwargl7** [comment]
Pendiente entrega de actualización del documento y cambio de estado en review para su revisión completa.

**Comment by mau-oati** [comment]
Ajustes completados en el documento Módulos y Dependencias.

**Comment by edwargl7** [comment]
Se realiza la revisión y se identifica la necesidad de agregar los siguientes campos basado en los mockups suministrados para el sprint actual.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/714acc66-1687-4eef-a524-b48021c23db0)

**Comment by mau-oati** [comment]
Ajuste al Modelo Propuesto

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/2a60caaa-56f7-4cef-bb64-3f272bbe71f1)
