### ISSUE TITLE
Diseño diagrama de microservicios de ARGO

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#33]
Se requiere realizar el diseño inicial de la arquitectura descriptiva de cada módulo propuesto de ARGO v2. Este diagrama debe ser diseñado basado en la vista de módulos y vista de componentes/conectores en una capa general, donde permita visualizar los principales componentes de cada módulo y las interfaces, principalmente de los microservicios con otras fuentes de suministro de datos.
Es importante identificar los datos paramétricos y los datos que son obtenidos de otros sistemas para representarlos en el diagrama.
Ejemplo:
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/89344063-3ecb-4c35-8252-2b8ddc57f5f9)

**Sub Tareas**

- [x] Diseño diagrama del módulo de supervisores y ordenadores del gasto (microservicios separados).
- [x] Diseño diagrama del módulo de actas de inicio.
- [x] Diseño diagrama del módulo pólizas y amparos.
- [x] Diseño diagrama del módulo de gestión contractual y órdenes de compras y servicios.
- [x] Actualización documento [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s) con los tipos y restricciones evidenciados en el progreso del diseño de arquitectura descriptiva.

**Material**
- [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s)

**Criterios de aceptación**

- [x] Diseño diagrama del módulo de supervisores y ordenadores del gasto (microservicios separados).
- [x] Diseño diagrama del módulo de actas de inicio.
- [x] Diseño diagrama del módulo pólizas y amparos.
- [x] Diseño diagrama del módulo de gestión contractual y órdenes de compras y servicios.
- [ ] Actualización documento [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s) con los datos aclarados en el diseño de la arquitectura.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama con los módulos de actas de inicio, pólizas y amparos y gestión contractual y órdenes de compra y servicio, supervisores y ordenadores del gasto.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se inicia la tarea con la creación de un documento Draw.io que contendrá los diagramas solicitados y con la revisión e investigación a profundidad del formato sugerido para realizar dichos diagramas.

**Comment by Lau2ri** [comment]
Se inicia el boceto del diseño del diagrama de microservicios en el archivo draw.io siguiente: https://app.diagrams.net/#G1EZdCWDhC_zdefNretdiviIeV12-rq6BG#%7B"pageId"%3A"XKyjC68PPlrllvAJt4zl"%7D 
El boceto se encuentra en la pestaña de "Microservicios ARGO".

**Comment by Lau2ri** [comment]
Se presenta a continuación la versión 1 del diagrama de microservicios del sistema Argo v2.

![ARGO-Microservicios ARGO drawio](https://github.com/udistrital/argo_documentacion/assets/133523053/4182ebe4-fefd-451c-a566-b7d2d6156ff0)

**Comment by edwargl7** [comment]
Se realiza la revisión y se observa el diagrama terminado y ajustado con lo comentado anteriormente.
Se revisa el archivo y se ajusta modifica lugar_ejecución por Dependencias (OIKOS) que sería el servicio que nos suministra la información de dependencias, y sedes.
