### ISSUE TITLE
Diseño modelo de datos de cada módulo de ARGO - Revisión parámetros

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#35]
Se requiere realizar la revisión de los parámetros identificados en la [Issue #32](https://github.com/udistrital/argo_documentacion/issues/32). Actualmente ARGO cuenta con una tabla de parámetros propia. Por lo tanto, se requiere revisar las tipologías requeridas identificadas y un planteamiento inicial sobre si almacenarlas en el nuevo ARGO o en el servicio de parametros_crud. Para esto se debe identificar cada tipología si es propia del sistema o puede ser compartida con otros sistemas.

**Sub Tareas**

- [x] Clasificación de cada tipología identificada en la [Issue #32](https://github.com/udistrital/argo_documentacion/issues/32) si es propia de ARGO o puede ser compartida con otros sistemas. Agregar una hoja nueva en [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYOta-0AZYdBmhFlseX1vRcBn6bkKhV9OgWs2E4gAYPWJQ?e=xAgF8s)
- [ ] Presentación al equipo DBA del modelo de datos completo.
- [ ] Ajustes sugeridos por el equipo DBA

**Criterios de aceptación**

- [x] Tabla que clasifique cada tipología para revisión con DBAs y elección del manejo de estos.
- [ ] Presentación y ajustes al modelo de datos sugeridos por el equipo DBA.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Clasificación de tipologías.
- [ ] Actualización del modelo de datos basado en las sugerencias del equipo DBA.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Cambiar de estado la Issue y documentar avances por favor.

**Comment by mau-oati** [comment]
Se crea la pestaña clasificación de Dependencias, para tener un vistazo general de los parametros propios y los transversales.

**Comment by mau-oati** [comment]
Se recomienda almacenar los parámetros propios en una colección parametros, con una relación similar a la que se encuentra en argo v1.

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/7a1d3c10-711c-452e-a442-2304c5e05bbb)

**Comment by edwargl7** [comment]
Se realiza la revisión y presentación al equipo DBA donde indican que plantear esa división es la adecuada separando los parámetros generales de los propios del core del sistema. Se da por finalizada esta Issue. Muy buen trabajo.
