### ISSUE TITLE
Creación microservicio gestión contractual y órdenes de compras y servicios - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#36]
Se requiere realizar la creación del microservicio de gestión contractual y órdenes de compras y servicios basado en el modelo de datos de la [Issue #32](https://github.com/udistrital/argo_documentacion/issues/32).

**Especificaciones técnicas**

1. Repositorio de este nuevo microcliente [gestion_contractual_compras_contrato_crud](https://github.com/udistrital/gestion_contractual_compras_contrato_crud)
2. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos microservicios definidos por la OATI.
3. Revisión de tecnología a usar para el modelo no relacional. Recomendado MongoDB.

**Sub Tareas**

- [x] Revisión tecnología a usar para el modelo de datos no relacional.
- [ ] Implementación del microservicio core de gestión del contrato para el módulo de gestión contractual y órdenes de compras y servicios.
- [ ] Documentación del README siguiendo los lineamientos [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Criterios de aceptación**

- [ ] Creación de la rama con el desarrollo indicado.
- [ ] Documentación del README siguiendo los lineamientos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Tener presente también los lineamientos [Lineamiento Para Repositorios Institucionales](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md) que presenta el Gitflow.

**Comment by mau-oati** [comment]
Se propone un stack de Typescript (NestJS Framework) junto con Mongoose (Comunicación con Mongo).

**Comment by mau-oati** [comment]
Se crea Fork del Repo para una implementación incial. https://github.com/mau-oati/gestion_contractual_compras_contrato_crud

**Comment by edwargl7** [comment]
Se debe ajustar el alcance de esta tarea dado que es prioridad culminar [ajustes y presentar el modelo de datos al equipo DBA (Issue 41)](https://github.com/udistrital/argo_documentacion/issues/41) ya que es insumo para esta tarea.

**Comment by edwargl7** [comment]
Se debe terminar de definir el modelo de datos, el tipo de base de datos a usar. Y examinar la posibilidad de utilizar la base de datos actual o planes alternos de migración que eviten mantener los dos sistemas ejecutándose al tiempo (punto sugerido por el equipo DBA). Por lo que se requiere complementar la investigación y establecer un documento que permita evidenciar los puntos y criterios tenidos en cuenta a la hora de tomar la decisión. Por lo que esta tarea se retoma una vez culminado este proceso.
