### ISSUE TITLE
Diseñar submódulos relacionados con acta de aprobación de pólizas

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#37]
Se requiere actualizar el diseño del mockup del modulo de Gestión contractual, relacionado con acta de aprobación de pólizas y de inicio, acorde a lo indicado en la reunión cliente. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [ ] Presentar el mockup al cliente.
- [ ] Realizar ajustes según comentarios del cliente.
- [ ] Presentar al equipo el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [ ] Mockup aprobado por cliente y equipo.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avance en el diseño del mockup para actas de inicio.


**Page Módulo Gestión Actas de Inicio**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/49ab5181-94db-4cd1-839e-96d9796ee6b4)

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen avance @cjgonzalezp! Recuerda que el submódulo de acta de aprobación de póliza es anterior a este de actas de inicio.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla el mockup para el módulo de gestión de pólizas. Pendiente presentar el diseño al líder técnico para revisar ajustes. Seguido, presentar al cliente la propuesta de diseño para revisar ajustes y nuevamente presentar el diseño definitivo al líder técnico y equipo de desarrollo.

**Módulo Gestión de Pólizas**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/fac6241c-001e-475a-87bf-f270151d97d3)

**Enlace del diseño cargado en OneDrive en la carpeta del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmJYcbb4P51Jr7bcXo-TadIBeAozStHKnipweAoG8VWYYw?e=wphQxk


Saludos.

**Comment by jcmurilloa** [comment]
Buen día @cjgonzalezp 

Las fechas de la póliza pueden diferir de cada amparo, es decir, cada amparo genera una fecha de cubrimiento diferente, por tal razón estas fechas se deberían ingresar por cada uno de los amparos.

Asimismo, se deben añadir los espacios correspondientes al valor total de la póliza, así como para cada amparo, pues estos valores pueden cambiar de acuerdo al porcentaje que dicte cada amparo.

En consultar póliza, se debería contar con la posibilidad de corregir todos los valores que se ingresan al momento del registro, es decir incluir los amparos. 

En la próxima sesión revisamos en equipo SoS estas observaciones.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los ajustes sugeridos en el anterior comentario por Julián Murillo

**Mockup Modulo Gestión de Polizas**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/1707e4d6-9495-45ec-849c-343f7558972f)


Saludos.

**Comment by jcmurilloa** [comment]
Gracias por atender las sugerencias @cjgonzalezp, revisaremos al detalle en la sesión planning del 28/06!

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp!
