### ISSUE TITLE
Ajustes modelo de datos de ARGO v2 -Módulos gestión contractual y órdenes, pólizas y amparos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#41]
Se requiere realizar los ajustes evidenciados en la [Issue 32](https://github.com/udistrital/argo_documentacion/issues/32) y los sugeridos por el equipo DBA al modelo de datos propuesto para ARGO v2.

Lista de ajustes a realizar:

- Agregar **_id** al final de los campos de tipos identificados y resaltados de color amarillo en la Issue 32.
- Agregar el campo de perfil del contratista, aplica póliza y fecha Suscripción Estudios y documentos previos (abreviando el nombre para no dejarlo tal cual como en la interfaz gráfica).
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/e10113bd-d410-44df-900c-ea6fe7f3609d)

- Ajustar la tabla de amparos:
> - Agregando el campo valor y descripción
> - Agregando los id de la tabla de contrato y póliza al amparo
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/43e7a9d6-f585-4cb5-86a9-fbca2d28b5c1)

- Agregar a la tabla lugar de ejecución país, departamento, municipio los ids. Revisar con DBA la posibilidad o existencia de la tabla divipolas.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/335987db-8c4c-47cd-be3c-d0000cdc2495)

- Agregar medio de pago y modo de pago a la tabla contrato general.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/1abba098-4aa9-49ef-ba4c-07f0f654a08b)

**Sub Tareas**

- [x] Realizar los ajustes identificados y descritos en esta Issue.
- [x] Presentación a DBAs
- [x] Realizar ajustes sugeridos por el equipo DBA.

**Criterios de aceptación**

- [x] Modelo de datos revisado por el equipo DBA y ajustado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Modelo de datos actualizado y cargado en la carpeta de documentos de ARGO.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Ajuste al Modelo Propuesto

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/9e9f9693-e44d-49f4-9ab3-c1c3bb8183d6)

**Comment by edwargl7** [comment]
Se ajustan los puntos de historia basado en los ajustes sugeridos. Se debe realizar una revisión detallada frente a la posibilidad de utilizar la misma base de datos, o alternativas que permitan no tener en funcionamiento dos sistemas. Se realizará un análisis adicional al trabajado actualmente para concretar los puntos críticos del sistema y las soluciones.
Tener presente en los resultados que manejo se puede dar al servicio de ARGO actual, conservando la base de datos.

**Comment by mau-oati** [comment]
Se comparte propuesta actualizada con los cambios solicitados en la reunion:

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/1e37d112-b5fd-4828-8184-2ada9c5bdd93)

**Comment by edwargl7** [comment]
Se realiza la revisión del modelo de datos actualizado con las recomendaciones dadas por los DBAs y los ajustes descritos en la Issue. Se observa que cuenta con lo solicitado. Muy buen trabajo.

Se realiza una comparación entre las tablas y colecciones abordadas para este modulo de gestión contractual y órdenes empleando el mockup, el modelo de datos actual y el modelo de datos propuesto. En los que se identifican de color azul los evidenciados actualmente en el mockup y de morado los presentes en el modelo de datos actual, resaltados en el modelo propuesto.

**Tabla/colección principal contrato**
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/d0b90493-498a-44eb-8e42-fff350477427)

**Tabla/colección Póliza y amparo**
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/87250356-ca80-46ad-8078-a7999a8e7c6e)

**Tabla/colección Lugar ejecución**
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/65b9864a-d3b0-4e24-a01b-25d668b8de63)

**Tabla/colección supervisor**
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/b1e8daa0-4873-4b72-aba6-a6b23960b204)

**Tabla/colección contratista**
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/dc422c0c-e253-498d-afb4-d4f8d6c03765)

Se realiza dicha revisión con el fin de recolectar los puntos de diferencia y establecer un mejor panorama para la definición del modelo de datos a usar y la necesidad de partir de un modelo de datos nuevo.

Se observan otros ajustes requeridos al modelo actual que se trabajaran en una siguiente tarea.
