### ISSUE TITLE
Se requiere realizar la concertación, desarrollo y levantamiento acta de sesión de refinamiento con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#42]
Se requiere realizar la concertación, desarrollo y levantamiento acta de sesión de refinamiento con cliente

**Sub Tareas**

- [x] Concertar reunión de refinamiento con el cliente
- [x] Desarrollar la reunión de refinamiento
- [x] Diligenciamiento del formato de historias de usuario con el cliente
- [x] Aprobación del formato de historias de usuario
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes con anexo de historias de usuario

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se acuerda reunión con el cliente para levantamiento de requerimientos el día 18 de junio de 2024 Hora: 9:00 am.


Cordial saludo.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con el cliente hoy 18 de junio de 2024 para refinamiento de requerimientos en horario de 9:00 am a 11:30 am. Pendiente de terminar el acta de reunión 045/2023 para revisión y aprobación del líder y recolección de firmas de los participantes presentes.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla acta de reunión 045/2024 levantamiento de requerimientos para revisión y visto bueno de Julián Murillo. Está pendiente enviar a firmar por los participantes en la reunión.

Enlace del documento cargado en OneDrive en la carpeta del proyecto ARGO V2
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpkHkAlomHRDonIgN1Gqeo8BE8fCeAyjsmCZzw3Zg_7wjg?e=YpALcc


Saludos.

**Comment by jcmurilloa** [comment]
El acta cumple con lo solicitado @cjgonzalezp, ahora a recoger firmas, gracias!

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza recolección de firmas de todos los participantes presentes en la reunión del pasado 18 de junio de 2024 acta No 045/2024.

**Enlace del documento cargado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpkHkAlomHRDonIgN1Gqeo8BE8fCeAyjsmCZzw3Zg_7wjg?e=Spoutl

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp!
