### ISSUE TITLE
Revisión estilos para el microcliente gestión contractual y órdenes de compras y servicios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#43]
Se requiere realizar la revisión y creación de los estilos requeridos para el formulario del módulo de gestión contractual y órdenes de compras y servicios, ya que los estilos actuales no cubren lo requerido para el formulario base implementado en la [Issue 34](https://github.com/udistrital/argo_documentacion/issues/34). Además, en la revisión de otros microclientes se observa que cuentan cada uno con estilos adicionales propios para cada sistema [sga_cliente_root](https://github.com/udistrital/sga_cliente_root/tree/develop/src/assets/styles), [sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf/tree/develop/src/assets/styles), [planeacion_construccion_mf](https://github.com/udistrital/planeacion_construccion_mf/tree/develop/src/assets/styles) y [planeacion_root_mf](https://github.com/udistrital/planeacion_root_mf/tree/develop/src/assets/styles).

**Lineamientos a tener presente**
- [Lineamiento Para Repositorios Institucionales](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en Comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)

**Sub Tareas**

- [x] Ejecución de los microclientes root y [gestion_contractual_compras_contrato_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) en ambiente local.
- [x] Revisión estilos de los proyectos mencionados en la descripción de la Issue.
- [ ] Creación de los estilos requeridos en una rama nueva en el repositorio [root](https://github.com/udistrital/gestion_contractual_compras_root_mf).
- [ ] Pruebas de visualización correcta de los estilos con el desarrollo de la rama develop.

**Criterios de aceptación**

- [ ] Pruebas de visualización correcta de los estilos con el desarrollo de la rama develop.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se incia la revisión del manejo de estilos para complementar la issue #34 , se incia con la configuración del cliente local.

**Comment by mau-oati** [comment]
En otros servicios la fuente tipográfica usada en el body y el contenido en general es **Helvetica**, sin embargo siguiendo el manual de lineamientos debería ser **Open Sans**, en ese caso el modelo actual está correcto por el tema tipográfico, solo que se nota diferente por las tipografías aplicadas en otros sistemas.

**Comment by mau-oati** [comment]
Se encontraron ajustes que son necesarios revisar en [core_mf_cliente](https://github.com/udistrital/core_mf_cliente) , se aplicaron ajustes de **tipografias** en el root, para el manejo general de los diferentes clientes: 

![image](https://github.com/udistrital/argo_documentacion/assets/163943201/c91184f2-bdfb-461a-a750-affc04726706)

**Comment by edwargl7** [comment]
Se revisa los avances en la daily del día 14 de junio las dudas y avances, se requiere una revisión y apoyo de los equipos que actualmente tienen mayores avances en el manejo de estos estilos, ya que se observan diferencias entre la forma de abordar los estilos en los microclientes existentes actualmente, incluso un comportamiento y visualización diferente entre estos que no es claro el porque dado que usan el mismo core (sisgplan y sga).
Adicional en la Issue #38 se evidencia que usando una etiqueta diferente (mat-raised-button) si aplica estilo, por lo que se requiere también apoyo de los otros equipos para conocer donde se manejan estos estilos y que etiquetas tienen asignado que estilos para un manejo más fácil y eficiente de lo requerido en los mockups.
