### ISSUE TITLE
Ajustes modelo de datos de ARGO v2 -Módulos gestión contractual y órdenes, pólizas y amparos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#44]
Se requiere realizar ajustes al modelo de datos propuesto para ARGO v2 trabajado en las Issues #32 y #41. Estos ajustes surgen basado en la revisión realizada entre mockups, modelo de datos del actual ARGO y el propuesto. Se puede observar el resultado de la comparación en la Issue #41.

**Ajustes requeridos**
- [x] Remover los campos: póliza, supervisores, acta_inicio, cdp de la colección contrato_general. Ya que la póliza tiene la referencia del contrato, la tabla/colección supervisores almacena la relación de uno a muchos, tener presente una revisión de posibilidad mucho a muchos, o establecer si es una lista de ids de los supervisores y cada supervisor almacena el resto de información propia del mismo. La tabla/colección acta_inicio y cdp almacenan la referencia del contrato.
- [x] ¿La tabla/colección supervisor_contrato es de "rompimiento" con el servicio que se consumirá de información de supervisores o en el modelo propuesto hace referencia a la misma tabla del modelo actual?
- [x] De la tabla/colección contrato_general el campo ordenador del gasto debe ser un id de referencia a la tabla/colección de ordenadores.
- [x] Evaluar la posibilidad de eliminar la tabla/colección contratista y agregar dicho id de referencia con el identificador de ágora.
- [x] Evaluar y/o agregar el campo usuario_id o para mayor seguimiento los campos creado_por_id y modificado_por_id o creado_por y modificado_por, los cuales almacenen el id del usuario que realizó el registro y modificaciones.
- [x] Agregar la referencia del contrato a la tabla/colección póliza.
- [x] Modificar el campo entidad_aseguradora por entidad_aseguradora_id en la tabla/colección póliza.
- [x] Agregar a la tabla/colección amparo el campo de unidad_amparo_id que permite almacenar, por ejemplo, porcentaje o SMLV.
- [x] Evaluar la adición de los campos _fecha_suscripcion, fecha_cancelacion, motivo_cancelacion_ dada la unificación de las tablas que almacenaban eso en el modelo actual, o si estos campos deben ser parte del módulo de novedades.
- [x] Agregar los siguientes campos o mencionar del modelo propuesto cuales son.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/5fe931da-aabc-4708-9b9b-4f8224493881)
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/bd9d39fe-f8d9-4903-b939-df5fa3073705)
- [x] En la tabla/colección modificar la unidad_ejecucion a unidad_ejecucion_id dado que es una referencia.
- [x] En la tabla/colección supervisor el campo digito_verificacion_id cambiarlo a digito_verificacion, dado que es un valor numérico y no una referencia.
- [x] En la tabla/colección cdp remover el campo registro_presupuestal dado que el rp depende del cdp. Por lo tanto, se requiere agregar en la tabla/colección del rp la referencia del cdp.
- [x] De los campos propuestos no se identifica claramente el consecutivo de elaboración.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/1a5c4682-272c-4cb7-8418-0fcf85c9a5ca)

**Sub Tareas**

- [x] Cargar el archivo con la versión actual y en el mismo crear una nueva pestaña con la nueva versión generada.
- [x] Realizar los ajustes indicados al modelo de datos actual, documentando las observaciones respectivas en cada campo en caso que se identifiquen otras opciones.

**Criterios de aceptación**

- [x] Creada nueva versión del modelo de datos propuesto.
- [x] Cargado el archivo con las versiones diseñadas del modelo en la carpeta Gestión técnica/Documentos ARGO v2.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Modelo de datos actualizado y cargado en la carpeta de documentos de ARGO.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se ajusta el modelo eliminando campos de doble referencia, se continúa con los demás ajustes, 

El avance actual (WIP) es: 



![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/5ee04a0e-8a55-493b-81ea-7c1c9be6982b)

**Comment by mau-oati** [comment]
Se comparte propuesta actualizada: 

### Leyenda:

- Color **Azul**: ObjectId de relaciones entre colecciones.
- Color **Rojo**: Campos Obligatorios en cada tabla, para control y auditoría básica.
- Color **Morado**: ObjectId que guardan parámetros de la colección **parámetro**.
- Color **Amarillo**: Elementos traídos de Parámetros CRUD. 
- En **Negrilla** campos para revisar y confirmar su rol en el modelo de datos.

### Preview:

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/dcc285e0-0537-4bf8-aaba-aa574fd3e4ed)

**Comment by mau-oati** [comment]
![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/77f49a75-405b-448a-95bb-cdac6c508fb6)

**Comment by mau-oati** [comment]
## Poliza MS 

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/5dfcb4d8-f502-4dc7-9522-1541708e7c39)

## Supervisor MS

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/2d87c464-41ea-4ca9-945d-6be6e785c36a)

## Auditoria ARGO MS

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/e4506936-907e-4af2-afed-c1d0e1ce5f67)

## Parametros ARGO MS

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/f7cc1054-a4e4-4e77-baaa-18ceb49d48c8)

## CDP MS

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/70346737-d9d6-4724-b20d-bd02c6f9338f)

**Comment by mau-oati** [comment]
## Acta Inicio MS

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/741722b3-a415-4393-bfeb-7fa9038eb4eb)

## Contratista MS

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/9f0727f3-c2a5-4bb6-8b92-45f45e1fb103)

## Ordenador MS

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/492f93c5-a9a3-4e13-9179-c0c0d7d8536e)

**Comment by edwargl7** [comment]
Realizada una revisión parcial de las divisiones y principales observaciones, pendiente validación del líder técnico campos específicos de la tabla/colección contrato_general y revisar los campos resaltados de color negro sobre su uso actualmente. En general muy buen trabajo, se observa una buena propuesta para el registro de cambios y usuario que realiza los cambios del microservicio propuesto como auditoría, se revisará en más detalle con el fin de llevarlo a que pueda ser utilizado por diferentes microservicios y sistemas, por lo que se adicionaran campos que permitan identifcar el microservicio o sistema al que pertenece para un agrupamiento por sistema, y un posible campo para almacenar metadata que pueda ser relevante para el cambio realizado (descripción, causa, ...).

**Comment by mau-oati** [comment]
![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/5388b4b6-aa12-4419-b61f-ac33daf11f14)

**Comment by edwargl7** [comment]
Se validan los ajustes y cumplen con los ajustes requeridos.
