### ISSUE TITLE
Revisión estilos para el microcliente gestión contractual y órdenes de compras y servicios - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#46]
Se requiere continuar con la revisión y creación de los estilos requeridos (abordada inicialmente en #43) para el formulario del módulo de gestión contractual y órdenes de compras y servicios, ya que los estilos actuales no cubren lo requerido para el formulario base implementado en la Issues #34 y #38. Además, en la revisión de otros microclientes se observa que cuentan cada uno con estilos adicionales propios para cada sistema [sga_cliente_root](https://github.com/udistrital/sga_cliente_root/tree/develop/src/assets/styles), [sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf/tree/develop/src/assets/styles), [planeacion_construccion_mf](https://github.com/udistrital/planeacion_construccion_mf/tree/develop/src/assets/styles) y [planeacion_root_mf](https://github.com/udistrital/planeacion_root_mf/tree/develop/src/assets/styles) y un comportamiento diferente al expandir el menú, y diferencias en el header y footer. Posiblemente por integración de [web-components](https://github.com/udistrital/web-components/tree/develop).

Para este Issue se requiere la revisión con los otros equipos para tener una mayor claridad de los pasos a seguir y complemento de la información revisada de los lineamientos.

**Lineamientos a tener presente**
- [Lineamiento Para Repositorios Institucionales](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en Comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)

**Sub Tareas**

- [x] Revisión de estilos con integrantes de los proyectos mencionados en la descripción de la Issue.
- [x] Creación de los estilos requeridos en una rama nueva en el repositorio [root](https://github.com/udistrital/gestion_contractual_compras_root_mf).
- [x] Pruebas de visualización correcta de los estilos con el desarrollo de la rama develop paso 1 del formulario.

**Criterios de aceptación**

- [x] Pruebas de visualización correcta de los estilos con el desarrollo de la rama develop.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Revisando las anotaciones y las recomendacionea dadas por el equipo experto, iniciamos la creaci'on de un PR para ajustar los estilos del root con los avances encontrados.

**Comment by edwargl7** [comment]
Información importante para el manejo de estilos en microclientes según lo conversado con varios líderes y desarrolladores que han guiado este proceso en la OATI, adicional de la revisión de varios microclientes :test_tube:.

## 1. Definición estilos :memo: 
En resumen, cada microcliente parcel complementa y maneja estilos para angular material y los que sean pertinentes agregando el siguiente script en la ruta src/assets/styles/<nombre-archivo>.scss

```
@use '@angular/material' as mat;

@include mat.core();

$md-primary: (
  50 : var(--md-primary-50),
  100 : var(--md-primary-100),
  200 : var(--md-primary-200),
  300 : var(--md-primary-300),
  400 : var(--md-primary-400),
  500 : var(--md-primary-500),
  600 : var(--md-primary-600),
  700 : var(--md-primary-700),
  800 : var(--md-primary-800),
  900 : var(--md-primary-900),
  A100 : var(--md-primary-A100),
  A200 : var(--md-primary-A200),
  A400 : var(--md-primary-A400),
  A700 : var(--md-primary-A700),
  contrast: (50 : var(--md-primary-contrast-50),
    100 : var(--md-primary-contrast-100),
    200 : var(--md-primary-contrast-200),
    300 : var(--md-primary-contrast-300),
    400 : var(--md-primary-contrast-400),
    500 : var(--md-primary-contrast-500),
    600 : var(--md-primary-contrast-600),
    700 : var(--md-primary-contrast-700),
    800 : var(--md-primary-contrast-800),
    900 : var(--md-primary-contrast-900),
    A100 : var(--md-primary-contrast-A100),
    A200 : var(--md-primary-contrast-A200),
    A400 : var(--md-primary-contrast-A400),
    A700 : var(--md-primary-contrast-A700),
  )
);

$md-accent: (
  50 : var(--md-accent-50),
  100 : var(--md-accent-100),
  200 : var(--md-accent-200),
  300 : var(--md-accent-300),
  400 : var(--md-accent-400),
  500 : var(--md-accent-500),
  600 : var(--md-accent-600),
  700 : var(--md-accent-700),
  800 : var(--md-accent-800),
  900 : var(--md-accent-900),
  A100 : var(--md-accent-A100),
  A200 : var(--md-accent-A200),
  A400 : var(--md-accent-A400),
  A700 : var(--md-accent-A700),
  contrast: (50 : var(--md-accent-contrast-50),
    100 : var(--md-accent-contrast-100),
    200 : var(--md-accent-contrast-200),
    300 : var(--md-accent-contrast-300),
    400 : var(--md-accent-contrast-400),
    500 : var(--md-accent-contrast-500),
    600 : var(--md-accent-contrast-600),
    700 : var(--md-accent-contrast-700),
    800 : var(--md-accent-contrast-800),
    900 : var(--md-accent-contrast-900),
    A100 : var(--md-accent-contrast-A100),
    A200 : var(--md-accent-contrast-A200),
    A400 : var(--md-accent-contrast-A400),
    A700 : var(--md-accent-contrast-A700),
  )
);

$md-warning: (
  50 : var(--md-warning-50),
  100 : var(--md-warning-100),
  200 : var(--md-warning-200),
  300 : var(--md-warning-300),
  400 : var(--md-warning-400),
  500 : var(--md-warning-500),
  600 : var(--md-warning-600),
  700 : var(--md-warning-700),
  800 : var(--md-warning-800),
  900 : var(--md-warning-900),
  A100 : var(--md-warning-A100),
  A200 : var(--md-warning-A200),
  A400 : var(--md-warning-A400),
  A700 : var(--md-warning-A700),
  contrast: (50 : var(--md-warning-contrast-50),
    100 : var(--md-warning-contrast-100),
    200 : var(--md-warning-contrast-200),
    300 : var(--md-warning-contrast-300),
    400 : var(--md-warning-contrast-400),
    500 : var(--md-warning-contrast-500),
    600 : var(--md-warning-contrast-600),
    700 : var(--md-warning-contrast-700),
    800 : var(--md-warning-contrast-800),
    900 : var(--md-warning-contrast-900),
    A100 : var(--md-warning-contrast-A100),
    A200 : var(--md-warning-contrast-A200),
    A400 : var(--md-warning-contrast-A400),
    A700 : var(--md-warning-contrast-A700),
  )
);

$light-theme: mat.define-light-theme((color: (primary: mat.define-palette($md-primary, 500),
        accent: mat.define-palette($md-accent, 500),
        warn: mat.define-palette($md-warning, 500),
      ),
      typography: mat.define-typography-config($font-family: 'Open Sans',
      ),
      desity: 0,
    ));

@include mat.all-component-themes($light-theme);
```

Donde,
```
/* Importación de Angular Material */
@use '@angular/material' as mat;
```
Permite usar las funciones del módulo de Angular Material y mixins en el archivo de estilos.

```
/* Inclusión del Núcleo de Angular Material */
@include mat.core();
```
Este mixin incluye los estilos básicos necesarios para Angular Material. Debe incluirse al menos una vez en su aplicación para que los componentes de Angular Material se rendericen correctamente.

```
/* Definición de Paletas de Colores */

/* Paleta primaria */
$md-primary: (...}

/* Paleta acento*/
$md-accent: (...}

/* Paleta Advertencia */
$md-warning: (...}
```
Se definen las paletas de colores _primary_, _warning_ y _accent_, para cada tonalidad del color, desde 50 hasta A700 basado en los estilos proporcionados en [assets](https://github.com/udistrital/assets) . Las variantes de contraste (contrast) también se definen para asegurar que el texto sobre el color primario sea legible.

```
/* Definición del tema claro */
$light-theme: mat.define-light-theme(
...
);
```

```
/* Asignación colores a Angular Material */
@include mat.all-component-themes($light-theme);
```
Finalmente, se aplica el tema definido a todos los componentes de Angular Material. Este mixin asegura que todos los componentes utilicen los colores, tipografía y densidad definidos en _light-theme_.

### Material adicional :book: 
- lineamientos [Estilos de Angular Material](https://github.com/udistrital/lineamientos_oas/blob/master/single_spa/core.md#estilos-de-angular-material)
- [Theming Angular Material](https://material.angular.io/guide/theming)

## 2. Uso de estilos :pushpin:
Para poder usar los estilos se debe en cada microcliente referenciar los estilos en el script _angular.json_ en:
```
...,
"styles": [
  "src/assets/styles/<nombre-archivo>.scss",
  ...
],
...
```

## Nota :warning: :rotating_light:
Según la información recopilada con otros equipos de desarrollo de la OATI, se busca usar principalmente iconos y estilos de angular.

**Comment by mau-oati** [comment]
![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/a32752bb-cc3a-43eb-8b6c-b1d1e0982537)

**Comment by edwargl7** [comment]
Realizar ajustes al PR de estilos del root siguiendo lineamientos en el título del commit. En general se observa todo correctamente.

**Comment by edwargl7** [comment]
Se observa una buena sincronización de los ajustes de la rama develop.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/31238e50-619b-4571-b0c8-d45118ac8876)

**Comment by edwargl7** [comment]
Se resuelve el PR y se finaliza esta Issue. Buen trabajo. Se seguirán ajustando los estilos según sea necesario en cada microcliente y en el root.
