### ISSUE TITLE
Pruebas y ajustes de estilos formulario del microcliente gestión contractual y órdenes de compras y servicios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#47]
Se requiere realizar la revisión y ajustes de los estilos requeridos a los pasos del 1 al 8 del formulario trabajados en las Issue #34, #38 y #39. Y los estilos definidos en la Issue #46.

**Sub Tareas**

- [x] Revisión de los estilos definidos y aplicación en cada paso del formulario.
- [x] Ajustes de estilos requeridos de cada paso.
- [x] Ajustes de estilos requeridos en el modal al momento de dar clic en el botón de guardar.

**Criterios de aceptación**

- [x] Correcta visualización de estilos en el formulario de registro del microcliente gestión contractual y órdenes de compras y servicios.

**Requerimientos**

- [x] Definición de estilos base en la Issue #46.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
## Avances
En la Issue #39 ya se ha venido trabajando con el root al día con los cambios realizados por mi compañero en la Issue #46, se ha evidenciado una mejora en los siguientes campos:

- Input y Select en dónde ya no se ve el error de tapar el texto que describe lo que es el campo

![Captura de pantalla 2024-06-20 205530](https://github.com/udistrital/argo_documentacion/assets/133523053/5bb73cb0-946b-4028-97e3-3f4dcf392903)

![Captura de pantalla 2024-06-20 205546](https://github.com/udistrital/argo_documentacion/assets/133523053/078e00f8-0eca-4c92-b369-052a80e28a0e)

- La fuente ya es la correcta en todo el formulario
- Los botones se muestran con el color y forma adecuado.

![Captura de pantalla 2024-06-20 205607](https://github.com/udistrital/argo_documentacion/assets/133523053/21275bc3-e037-4a13-89f6-bc15a3a6bac4)

- Input y Select dentro de la tabla también se ven de manera correcta.

![Captura de pantalla 2024-06-20 205621](https://github.com/udistrital/argo_documentacion/assets/133523053/0db40b01-292d-4f07-954c-01c8619daba1)

**Comment by edwargl7** [comment]
Se observa la aplicación de estilos e integración con los ajustes realizados por @mau-oati. Se seguirán realizando ajustes a los estilos en cada componente, microcliente y root según corresponda. Buen trabajo.
