### ISSUE TITLE
Continuar con el refinamiento del mockup del modulo de Gestión contractual, relacionado con actualizar contrato, constratos suscritos y contratos por vigencia, acorde a lo indicado en la reunión cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#48]
Se requiere continuar con el diseño del mockup del modulo de Gestión contractual, relacionado con actualizar contrato, constratos suscritos y contratos por vigencia, acorde a lo indicado en la reunión cliente. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al cliente.
- [x] Realizar ajustes según comentarios del cliente.
- [x] Presentar al equipo el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan primeros ajustes al módulo de registro de contrato según requerimientos del cliente.


![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/e23f800e-c0be-4d37-bb5a-3f49d881b7c3)


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

De acuerdo con las observaciones y sugerencias del cliente se continúa trabajando en el refinamiento del mockup.

![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/ca37c458-58bd-4a1b-bf72-8d6f18eed970)

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los ajustes en el formulario de registro de contrato de acuerdo con lo conversado en reunión con el equipo. Para su revisión y comentarios @jcmurilloa @edwargl7.

![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/01036184-c069-4b7e-84b0-061cd28e733f)


Saludos

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente aprobación por parte del cliente

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta el diseño del mockup submódulo registro de contrato con el cliente y se recibe aprobación para el desarrollo del módulo dentro del sistema ARGO V2

**Enlace del archivo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmqVFSYpNa9OoZQfXWTrsm0B6O_4aRQrkxfUf5BgvjC1Jg?e=HTz3PM


Saludo.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp, pendiente recolección de firmas en la issue correspondiente.
