### ISSUE TITLE
Revisión documentación Argo v1 - Segunda etapa

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#5]
Se requiere realizar la revisión de la documentación disponible del sistema Argo v1, para comprender el funcionamiento y los diferentes roles y módulos que tiene el sistema actual.

**Sub Tareas**

- [x] Revisión manual de usuario [MANUAL DE USUARIO DE GESTIÓN DE ACTAS DE INICIO EN EL SISTEMA DE GESTIÓN CONTRACTUAL](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXESNhvxH3ZOqIfTXBrNk08BoIsxYagWJnUfVCEqbpxffA?e=52xXdm)
- [x] Revisión manual de usuario [INSTRUCTIVO PARA LA GESTIÓN DEL MÓDULO DE NOVEDADES](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EV8FQs1yZSdLuRj6K2gR39UBVBNh32EpJQrunaYsuxtkhQ?e=D6DTrs)
- [x] Revisión manual de usuario [Instructivo para la modificación de contratos suscritos - argo](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZpf4dDGxg1HmotFODXDz8ABMGjWnWcZBs2nySc5OI3L9A?e=9dl5fV)
- [x] Complementar la Identificación de los módulos y roles involucrados en el actual sistema.

**Criterios de aceptación**

- [x] Complementar lista de los roles y módulos del sistema Argo v1

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Comentario en el issue con la lista de módulos y roles identificados en la revisión de la documentación.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se encontraron dudas sobre el flujo que tendrán los funcionarios (supervisores), para el control de actas de inicio. Actualmente se hace desde el SGA.

**Comment by mau-oati** [comment]
### - Módulo de Actas de Inicio
**Rol:** Supervisores (Funcionarios)

**Acciones:**

Registrar Acta de Inicio.

Actualizar Acta de Inicio.

Consultar Contrato.

Gestión de Actas de Novedades. 

### - Módulo de Nodedades
**Rol**: Personas autorizadas de la Oficina Asesora Jurídica.

**Acciones**:

Crear novidad de prórroga.

Crear novedad de suspención.

Crear novedad de reinicio.

Crear novedad de cesión.

Crear novedad de terminación anticipada.


### - Módulo de Modificaciones

**Rol**: Servidores públicos y contratistas (Definidos por Oficina Asesora Jurídica)

**Acciones**:

Consulta de Constratos Suscritos.

Modificación de Contratos Suscritos.

**Comment by mau-oati** [comment]
Nota: Conexiones actuales descritas para ARGO. Con SGA y ÁGORA.

**Comment by mau-oati** [comment]
Duda: En caso de mantener el módulo de novedades, migraremos para que concuerde con los modelos de bases de datos nuevos o usaremos los modelos existentes como una regla y guia para el montaje de los nuevos?

**Comment by edwargl7** [comment]
Excelente trabajo. Muchas gracias por las dudas presentadas.

- Sobre el manejo de las actas de inicio se consultará el 07/05/2024 sobre el manejo en otro sistema actualmente.
- Se está consultando las conexiones con otros sistemas (ÁGORA, SICAPITAL, SGA).
-  Sobre el módulo de novedades que es nuevo, se seguirá revisando el estado actual de ese sistema y la posibilidad de crear un microcliente que permita integrar todo el desarrollo realizado sin necesidad de desarrollarlo nuevamente. Este módulo dado que para el desarrollo actual de ARGO es de los últimos requeridos en la integración permite ir evaluando las integraciones posibles.
