### ISSUE TITLE
Diseño modelo de datos ARGO v2 (gestión contractual, acta de inicio, pólizas, amparos, supervisores, ordenadores) con migración ARGO v1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#50]
Se requiere realizar el análisis y diseño complementario al modelo de datos propuesto actualmente teniendo presente que se debe contemplar la migración del modelo de datos actual. Por lo que se hace necesario realizar el diseño contemplando las tablas de gestión contractual (contrato_general, estados, CDP, RP, contratista) junto con las tablas de pólizas, amparos, supervisores y ordenadores.

**Sub Tareas**

- [ ] Complemento modelo de datos con las tablas de estados del modelo actual (contrato_suscrito, contrato_cancelado y contrato_estado)
- [x] Revisión tabla orden y la compatibilidad con el nuevo ARGO v2.
- [x] Contemplar la creación de un campo que permita identificar los registros legados de los nuevos para una trazabilidad más clara con el ARGO actual.
- [x] Revisión unificación tablas de amparos del modelo actual al nuevo ARGO v2 (tablas amparo_contrato y amparo_poliza).
- [ ] Revisión tablas de ordenadores y supervisores dada la migración se debe identificar las fuentes de estos datos y la nueva estructura requerida para la integración con ARGO v2.
- [ ] Identificación puntos críticos de la migración.

**Criterios de aceptación**

- [ ] Matriz comparación de los modelos contemplando la necesidad de la migración de datos del modelo actual.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Matriz de comparación modelos de datos contemplando migración sistema ARGO actual.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se inicia la identificación y creación de tablas de correlación entre los modelos de ARGOv1 y ARGOv2.

**Comment by mau-oati** [comment]
Se unifican las tablas de estado (WIP), se dificulta el acceso a los datos por problemas de conexi'on con la VPN.

**Comment by mau-oati** [comment]
Se agrega al documento tabla de relación de parámetros, se sigue actualizando la tabla principal. 

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/10aed87e-e474-46b1-95b2-3c2e373eaa19)

En la matriz de correlación se relacionan los campos antiguos con los nuevos, junto con un ejemplo en cada versión, si la migración es transparente, se resalta de color verde, en caso de llevar cambios de relación, tipo de dato o contenido, va en naranja.

**Comment by mau-oati** [comment]
**Duda**: En la tabla contrato_suscrito existe un campo **numero_contrato_suscrito**. No me queda muy claro para qué se usa.

**Comment by mau-oati** [comment]
Número_contrato_suscrito === consecutivo_tipo_dato

**Comment by mau-oati** [comment]
Existe un **consecutivo_contrato_suscrito** y **numero_contrato_suscrito**, queda la duda de la diferencia de ambos, ambos son consecutivos. Pero ninguno se relaciona con el **numero_contrato**, que relaciona el numero de registro cuando se crea en _contrato_general_.

**Comment by mau-oati** [comment]
Duda: Si un contrato, tiene un supervisor A, B, C, pero el supervisor A se retira por cualquier razón, se mantiene el registro de todos los supervisores, siendo el principal A, aunque no esté disponible, o se debe actualizar para mantener los supervisores: B, C, D, por ejemplo.

**Comment by edwargl7** [comment]
Pendiente consultar con funcionamiento la diferencia entre consecutivo_contrato_suscrito y numero_contrato_suscrito de la tabla contrato_suscrito.

Pendiente la consulta al usuario con ayuda de @cjgonzalezp sobre la duda de cambios de supervisores si afecta en algo el proceso que se llevaría en ARGO. Dado que principalmente esa afectación estaría en cumplidos y posiblemente en novedades.

**Comment by mau-oati** [comment]
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/emrianoa_udistrital_edu_co/EW4nmJOIHr9Es76eualJ0JMB0eGKzep4j_Dyd4Ft_FXhgg?e=4dipuK

**Comment by edwargl7** [comment]
Se realiza la revisión, cuenta con una correcta división por submódulos y un análisis riguroso de cada campo, se agregan algunas observaciones y se toma nota de los campos que se requiere revisar con funcionamiento para tener una mayor claridad sobre el funcionamiento y uso de algunos campos identificados, esto es bastante importante para la migración.

Dentro de estos es importante consultar el consecutivo_elaboracion y su importancia en el ARGO actual y la necesidad de este campo en el nuevo sistema, y otros consecutivos propios de algunos estados del contrato.
