### ISSUE TITLE
Revisión Integración Ágora - Datos contratista

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#53]
Se requiere realizar la revisión de la integración con Ágora, los datos requeridos del contratista que se deben consultar y la creación de un microservicios MID que permita ser el intermediario entre Ágora y ARGO v2, con el fin de mantener una interfaz entre este MID y los microservicios de ARGO v2 garantizando una mantenibilidad, reusabilidad e interoperabilidad dado que por medio de este MID se desacopla el nuevo ARGO y permite que en futuras migraciones de Ágora a un nuevo sistema o cambios en las fuentes de datos, o web services solo sea necesario realizar los ajustes en dicho MID conservando las interfaces entre ARGO v2 y el MID.

**Sub Tareas**

- [x] Identificación campos requeridos de Ágora.
- [x] Revisión endpoints de Ágora con información del contratista.
- [x] Identificación de campos faltantes o sobrantes.
- [ ] Actualización diagrama de microservicios agregando el microservicio MID.

**Criterios de aceptación**

- [x] Identificación campos requeridos de Ágora y campos faltantes o sobrantes de los endpoints actuales.
- [ ] Actualización diagrama de arquitectura.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Análisis intefaz requerida con los datos del contratista para ARGO v2.
- [ ] Actualización diagrama de arquitectura ARGO v2.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Endpoints relacionados.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/bd98f2fe-2600-4c3d-99dd-981d27ce60a3)
[informacion_persona_natural](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=administrativa_amazon_api&version=v1&provider=admin&tenant=carbon.super#!/informacion_persona_natural/InformacionPersonaNaturalController_Get_All)

![image](https://github.com/udistrital/argo_documentacion/assets/50187485/6fc6d489-d854-4022-9165-ce8c776a9854)
[informacion_persona_juridica](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=administrativa_amazon_api&version=v1&provider=admin&tenant=carbon.super#!/informacion_persona_juridica/InformacionPersonaJuridicaController_Get_All)

**Comment by edwargl7** [comment]
Modelo de datos persona natural.
![udistrital - agora - informacion_persona_natural](https://github.com/udistrital/argo_documentacion/assets/50187485/65e80613-4fab-475f-a5d2-e791c0453c74)

**Comment by edwargl7** [comment]
Imagen base con la que se consulta información del contratista.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/715f4ee5-ec29-447c-bfd8-717aaec96b5a)

**Comment by mau-oati** [comment]
En la interface de ARGO - Informaci'on del contratista:

1. Se consulta el endpoint **informacion_persona_natural** o **informacion_persona_juridica** dependiendo el caso (segun el dropdown).
2. Se muestra en pantalla a informaci'on re retorno. 
3. Al dar en Siguiente, se crea un registro en **contrato_general_crud** en la coleccion **contratista**, que relaciona un **numero_identificacion_id** con el contrato actual.


```mermaid
sequenceDiagram
    ARGO-->>+AGORA: GET informacion_persona_natural
    ARGO-->>+AGORA: GET informacion_persona_juridica
    AGORA->>+ARGO: RESPONSE
    ARGO->>+contrato_general_crud: SAVE numero_identificacion_id
```

En ARGO, la 'unica informaci'on guardada, es el numero de indentificaci'on de la persona juridica o natural, el resto de la informaci'on, ser'a obtenida de 'AGORA.

**Comment by mau-oati** [comment]
Existirá un **contratistas_mid** que se encargue de consultar la información en ÁGORA y que se encargue del guardado de la relación en contrato_general_crud.

Dependencias:
**ÁGORA**: La única fuente de verdad es ágora, no se mantendrán copias o información del parte de ARGO, por ende, si el servicio de ágora no está disponible, cualquier proceso que requiera obtener el nombre, contacto, dirección, teléfono, etc, para cualquier flujo, no será posible ejecutarse hasta que esté nuevamente ágora en funcionamiento.

**Comment by edwargl7** [comment]
Buen trabajo, actualmente ARGO cuenta con un filtro que permite presentar tanto personas naturales como jurídicas por medio del mismo filtro, se debe consultar con más detalle el endpoint o lógica empleada para este funcionamiento.
 
![Filtro contratista](https://github.com/udistrital/argo_documentacion/assets/50187485/0d949ea2-d6ba-47db-9aec-048b97aa01fd)
