### ISSUE TITLE
Revisión plantillas para generación de minutas ARGO actual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#55]
Se requiere realizar la revisión del modelo de datos actual de las plantillas para minutas las tablas parametro_minuta, parametro_minuta_tipo_contrato y plantilla_minuta. En el modelo actual se almacenan las plantillas en HTML con una separación de estilos en otra columna, y el almacenamiento de la plantilla en HTML.

Actualmente se realizan actualizaciones a las plantillas periódicamente, en la que se modifica el contenido de dichas plantillas según el tipo de contrato y este se genera para todos los contratos de ese tipo durante dicho periodo, en caso de requerir realizar ajustes se solicita el cambio y este se aplica en la plantilla generando que este nuevo ajuste sea aplicado en los nuevos contratos que se generen. En algunos casos el usuario requiere agregar cláusulas o editar parágrafos para casos especiales de contratos, sin que estos cambios deban ser replicados en otros contratos del mismo tipo. Actualmente cuentan con un proceso manual de edición. Por lo que se requiere desacoplar estos registros del modelo actual proponiendo un nuevo modelo donde se pueda gestionar las cláusulas y/o parágrafos de forma independiente.

**Material de apoyo**
Tablas empleadas para almacenar parámetros y elementos requeridos para la generación de las minutas por medio de plantillas.

![image](https://github.com/udistrital/argo_documentacion/assets/50187485/25cbfcbc-4ea4-4da3-9417-3e65406595f3)

![image](https://github.com/udistrital/argo_documentacion/assets/50187485/28119c84-fd2f-4159-85c0-f02a7347aa4d)

![image](https://github.com/udistrital/argo_documentacion/assets/50187485/09448c97-037e-46de-921f-c27a2c420554)

**Sub Tareas**

- [x] Revisión del modelo de datos actual.
- [x] Revisión de estructura de plantillas actual.
- [x] Diseño modelo de datos que cuente con un control de versiones de plantillas.
- [x] Análisis de microservicio MID que permita una estructuración de los datos que componen la plantilla para su renderizado.
- [x] Diseño diagrama microservicios que involucre el microservicio de plantillas, el de cláusulas y parágrafos y el MID de estructuración de datos.

**Criterios de aceptación**

- [x] Revisión modelo de datos del ARGO actual y plantillas.
- [x] Diagrama de microservicios empleados para el módulo de Minuta.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de microservicios involucrados en el módulo de minuta.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Se comenzó con la revisión general de todas las subtareas y se tienen las siguientes dudas:
- La primera duda es saber en dónde se puede encontrar la estructura de la plantilla actual para su revisión
- La segunda es saber así mismo en cuál repositorio se puede hacer la revisión de la generación de documentos pdf que maneja el sistema Argo actualmente para tenerlo como base de comparación con la investigación que se realizará a continuación
- La tercera duda es que las subtareas dan a entender que se necesita el diseño de dos modelos de datos, pero se asume que debe ser un solo modelo que cumpla las tres características pedidas (gestión de cláusulas y parágrafos, y control de versiones)

Por último se sugiere la opción de replantear el alcance de la tarea bajo la consideración de dividir en dos partes la tarea principal, una con las subtareas relacionadas con el modelo de datos (diseño e investigación) y otra con las subtareas relacionadas con los microservicios (las últimas dos)

**Comment by Lau2ri** [comment]
Ya se realizó la revisión y entendimiento del modelo de datos actual y la forma en la que estas 3 tablas indicadas interactúan entre sí para crear la minuta. También se revisó y se entendió la estructura de varias de las plantillas HTML que se guardan en la tabla de plantilla_minuta junto con una minuta ya creada en formato pdf para ver el resultado real actual.

Se procede con el diseño del modelo de datos y el de microservicios.

**Comment by Lau2ri** [comment]
### Propuesta

Se presenta el modelo de datos actualizado en dónde se incluye la propuesta de un control de versiones para las plantillas de minuta:

![Minuta_argo_v2-Control_versiones drawio](https://github.com/udistrital/argo_documentacion/assets/133523053/39062642-d550-46a0-8925-dc966a84fd06)

Este sería el modelo como se encuentra actualmente (para referencia):

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/d8611ee3-3f69-4a58-8795-fbf49698b2f3" width="550">

Este modelo fue diseñado en Draw.io y ya se encuentra subido en la carpeta de One Drive del proyecto en el directorio:
Gestión técnica/Documentos ARGO v2/Modelo de Datos/Minuta

**Comment by edwargl7** [comment]
Pendiente consultar con funcionamiento el uso de los campos tipo_plantilla y fecha_vigencia de la tabla plantilla_minuta, sobre el uso y posibilidad de remover.

Unificar las tablas del versionado, agregando:

- Campo de version como numérico y en el microservicio se manejará la lógica para que incremente según el tipo de contrato.
- Campo version_actual, booleano que en la lógica del microservicio se manejara que solo exista uno en true el resto en false.

**Comment by Lau2ri** [comment]
Se unifican las tablas del versionado como se solicitó:

![Minuta_argo_v2-Control_versiones drawio (2)](https://github.com/udistrital/argo_documentacion/assets/133523053/aeedb08a-8c88-4741-b48d-bdc4ba8b6a99)

**Comment by Lau2ri** [comment]
Como propuesta inicial del diagrama de microservicios se presenta el siguiente:

![Minuta_argo_v2-Microservicios drawio (2)](https://github.com/udistrital/argo_documentacion/assets/133523053/bc011ab3-1e32-40f9-b4df-0c94e49cf644)

**Comment by edwargl7** [comment]
Se observa una buena propuesta para modelo de datos de plantillas con versionado, para los requerimientos comprendidos hasta la fecha. El diagrama de microservicios se actualizará una vez se unifique con el modelo de ARGO, dado que parte de la información de la minuta es recopilada en el core de ARGO. Buen trabajo.
