### ISSUE TITLE
Modelo de datos Cláusulas y Parágrafos ARGO v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#56]
Se requiere realizar el análisis y diseño del modelo de datos para el microservicio de cláusulas y parágrafos basado en la Issue #55. Dado que en el sistema actual, las cláusulas se almacenan dentro de la plantilla en el campo que guarda el HTML, se requiere la separación y creación de un modelo de datos nuevo para darle un manejo a posibles ediciones al momento de generar la minuta por parte del usuario (agregar parágrafos).

**Sub Tareas**

- [x] Diseño de modelo de datos que permita gestionar las cláusulas y parágrafos de forma independiente a la plantilla.

**Criterios de aceptación**

- [x] Diseño modelo de datos para microservicio de gestión de cláusulas y parágrafos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de modelo de datos de cláusulas y parágrafos.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se comenzó con la revisión del modelo de datos actual para comprender la estructura manejada y así seguir con el diseño del modelo de datos solicitado.

**Comment by Lau2ri** [comment]
### Propuesta
Se presenta la propuesta del modelo de datos el cual permitiría gestionar las cláusulas y parágrafos de forma independiente a la plantilla:

![Minuta_argo_v2-Cláusulas_Parágrafos drawio](https://github.com/udistrital/argo_documentacion/assets/133523053/af754896-210d-4b93-8f9c-4864ec046625)

Este modelo fue diseñado en Draw.io y ya se encuentra subido en la carpeta de One Drive del proyecto en el directorio:
Gestión técnica/Documentos ARGO v2/Modelo de Datos/Minuta

**Comment by Lau2ri** [comment]
Se corrigió el modelo conectando en una relación uno a muchos las tablas de clausula_minuta y paragrafo_minuta, debido a que una clausula puede tener relacionados varios parágrafos y, así mismo, un parágrafo específico debido a su contexto estará asignado a una clausula específica, y posteriormente, con la tabla plantilla_minuta habría una relación de muchos a muchos con clausula_minuta, el cuál ya traería cada clausula con sus respectivos parágrafos asignados.

![Minuta_argo_v2-Cláusulas_Parágrafos drawio (2)](https://github.com/udistrital/argo_documentacion/assets/133523053/060115a3-a4ea-4ff3-b8f2-80001d714d5e)

**Comment by edwargl7** [comment]
Buen trabajo, corregir la relación entre paragrafo_minuta y clausula_minuta. Se observa otro repositorio con una gestión similar se validará el funcionamiento del mismo y se realizaran ajustes en caso que ese sistema no se encuentre en funcionamiento. Se ajustará el modelo propuesto según sea el caso para agrupar las cláusulas según el tipo de contrato, aunque existan cláusulas similares en los tipos de contrato principalmente observadas en las cláusulas que almacenan información de los formularios de registro como el objeto del contrato y actividades.
