### ISSUE TITLE
Investigación generación de minuta desde la plantilla

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#57]
Se requiere realizar la investigación para generar el documento de la minuta, actualmente se genera desde el HTML y CSS almacenado en la tabla plantilla_minuta de ARGO. Se requiere realizar la investigación para replicar el funcionamiento basandolo en HTML y CSS para permitir un manejo similar desde el equipo de funcionamiento. Esta tarea se generó desde la Issue #55.

**Material de apoyo**
- Repositorio de ARGO versión actual [argo_desarrollo](https://github.com/udistrital/argo_desarrollo).
- Script de generación de la minuta para gestión contractual [documentoPdfContratoPrestacionServicios1](https://github.com/udistrital/argo_desarrollo/blob/master/blocks/gestionContractual/contratos/modificarContrato/funcion/documentoPdfContratoPrestacionServicios1.php#L295)

**Sub Tareas**

- [x] Investigación generación de documentos PDF a partir del HTML y CSS similar a como se crea en el sistema actual de ARGO.
- [x] Análisis almacenamiento para el correcto renderizado de la plantilla con la información de las cláusulas, de tal forma que consumiendo las fuentes de datos se generé el documento PDF de la minuta. Esto dado que van a existir cláusulas que van a tener la referencia a datos registrados en el contrato (por ejemplo: objeto del contrato, actividades).

**Criterios de aceptación**

- [ ] Investigación tecnología que se puede implementar para replicar la generación de documentos a partir de plantillas HTML.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Investigación tecnología y librerías para generar documento PDF desde la plantilla HTML y CSS.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se comenzó con la revisión y el análisis del material de apoyo dado.

**Comment by Lau2ri** [comment]
## Análisis previo:
Del Script de generación de la minuta para gestión contractual [documentoPdfContratoPrestacionServicios1](https://github.com/udistrital/argo_desarrollo/blob/master/blocks/gestionContractual/contratos/modificarContrato/funcion/documentoPdfContratoPrestacionServicios1.php#L295) se analizó lo siguiente:

1. Define una clase `EnLetras` para convertir números a su representación en letras.

2. Define una clase `RegistradorOrden` que maneja la lógica principal:
   - Realiza múltiples consultas a bases de datos para obtener información del contrato, contratista, ordenador, supervisor, etc.
   - Formatea la información obtenida.
   - Carga una plantilla de contrato basada en el tipo de contrato y la fecha.
   - Reemplaza marcadores en la plantilla con la información recopilada.

3. Crea una instancia de `RegistradorOrden` y llama al método `documento()` para generar el contenido del PDF.

4. Utiliza la biblioteca mPDF para generar el PDF:
   - Establece el tamaño de página, márgenes, fuente, etc.
   - Añade encabezados y pies de página.
   - Escribe el contenido HTML generado en el PDF.
   - Genera el archivo PDF para descargar.

**Comment by Lau2ri** [comment]
# Propuestas generación de PDF a partir del HTML y CSS

## 1. WeasyPrint:

WeasyPrint es una biblioteca de Python para convertir HTML y CSS a PDF.

### Funcionamiento:

- Renderiza HTML y CSS a PDF con alta fidelidad.
- Soporta la mayoría de las características de CSS para impresión.

### Pros:

- Excelente soporte para CSS, incluyendo estilos de impresión.
- Resultados de alta calidad y fidelidad al diseño original.

### Contras:

- Es una biblioteca de Python, por lo que requeriría integración adicional con Node.js.
- Puede ser más lenta que las alternativas basadas en JavaScript.

## 2. mPDF:

### Funcionamiento:

- Convierte HTML y CSS a PDF directamente en PHP.
- Soporta una amplia gama de características HTML y CSS, incluyendo tablas complejas, imágenes, y estilos avanzados.

### Pros:

- Alta fidelidad: Excelente rendimiento en la conversión de HTML y CSS complejos a PDF.
- Soporte UTF-8: Maneja bien textos en múltiples idiomas y caracteres especiales.
- Manejo de documentos largos: Está diseñado para manejar eficientemente documentos extensos.

### Contras:

- Basado en PHP: Dado que el proyecto actual está basado en Node.js y Angular, la integración directa de mPDF podría ser un desafío.
- Consumo de recursos: Para documentos muy grandes o complejos, puede consumir bastante memoria.
- Velocidad: Puede ser más lento que algunas alternativas basadas en JavaScript para documentos simples.

## 3. Puppeteer

Puppeteer es una biblioteca de Node.js desarrollada por Google que proporciona una API de alto nivel para controlar Chrome o Chromium.

### Funcionamiento:

- Permite renderizar páginas web y convertirlas a PDF con alta fidelidad.
- Puede ejecutar JavaScript en la página, lo que permite manipular el contenido antes de la generación del PDF.

### Pros:

- Excelente renderización de HTML y CSS complejos.
- Buena integración con Node.js.
- Permite la generación de PDFs con contenido dinámico.

### Contras:

- Puede ser más lento que algunas alternativas debido al uso de un navegador headless.
- Requiere más recursos del servidor.

## 4. PDFKit:

PDFKit es una biblioteca de generación de PDF para Node.js. Aunque no está diseñada específicamente para convertir HTML a PDF, se puede usar en combinación con otras librerías para lograr este objetivo.

### Funcionamiento:

- Permite crear documentos PDF desde cero o modificar PDFs existentes.
- Ofrece una API de bajo nivel para un control preciso sobre el contenido del PDF.
- Se puede integrar con librerías de parsing HTML para convertir HTML a comandos PDFKit.

### Pros:

- Gran flexibilidad y control sobre el resultado final.
- Buena integración con Node.js.

### Contras:

- Requiere más trabajo para convertir HTML a PDF, ya que no lo hace nativamente.
- La curva de aprendizaje puede ser más pronunciada.

**Comment by Lau2ri** [comment]
Propuesta de diagrama de microservicios dónde se evidencian los tres microservicios dados además del manejo de clausulas y parágrafos:

![Minuta_argo_v2-Microservicios drawio (1)](https://github.com/udistrital/argo_documentacion/assets/133523053/1338fe20-ea6e-4f16-b5ea-c657e691ec4d)

Además, dada la experiencia obtenida de los otros sistemas con el uso de gofpdf se propone esta tecnología como primera opción para la futura generación de minutas en Argo, quedarían pendientes las pruebas de concepto de dicha tecnología para confirmar su funcionalidad y rendimiento con nuestro caso particular.

**Comment by edwargl7** [comment]
Se requieren ajustes en el diagrama de microservicios dado que el microservicio que recopila la información es quien consume los servicios que almacenan la información y la plantilla y envía estos al microservicio que realiza el renderizado.
Se continuará con la revisión de las opciones y la prueba de concepto. Buen trabajo.
