### ISSUE TITLE
Crear y refinar la parametrización de datos para el sistema Argo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#58]
Se requiere realizar la creación y refinación la parametrización de datos para el sistema cumplidos proveedores

**Sub Tareas**

- [x] Construir el documento de parametrización de datos.
- [x] Refinar el documento con el equipo el documento.

**Criterios de aceptación**

- [x] Documento de parametrizaciín de datos definido

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza avance en la parametrización inicial de la minuta del contrato CPS para estructuración y desarrollo dentro del sistema ARGO V2. Y actualmente se está construyendo el documento de parametrización de datos del submódulo registro de contrato.

Enlace del documento minuta de contrato CPS cargado en OneDrive en la carpeta del proyecto ARGO V2.
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsP2qMRf4k9Cow_wvk06oewBW3r1nqjW1SU_idYoLv0XxA?e=v8dfRj


Saludos.

**Comment by jcmurilloa** [comment]
Muy bien @cjgonzalezp, en la próxima review revisamos!

**Comment by jcmurilloa** [comment]
Pendiente parametrización en documento editable y revisión

**Comment by cjgonzalezp** [comment]
Buen día,

Se proyecta información paramétrica del sistema ARGO V2 en documento editable como lo solicita el equipo SoS.

**Enlace del documento minuta de contrato CPS cargado en OneDrive en la carpeta del proyecto ARGO V2.**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsP2qMRf4k9Cow_wvk06oewBW3r1nqjW1SU_idYoLv0XxA?e=WKdcCC


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, documento valiosos para desarrollo @edwargl7
