### ISSUE TITLE
Actualizar los diagramas de flujo del sistema según novedades y refinamiento de mockups

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#59]
Se requiere realizar la actualización de los diagramas de flujo del sistema según refinamiento de mockups

**Sub Tareas**

- [x] Repasar diagramas de flujo actuales del sistema
- [x] Generar las modificaciones según refinamiento de mockups
- [x] Presentar al equipos SoS diagramas actualizados

**Criterios de aceptación**

- [ ] Diagramas de flujo actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diagrama de flujo del proceso de registro y aprobación de contrato en el sistema teniendo en cuenta los estados en cada actividad y los responsables involucrados en el proceso.

**Diagrama Estados de Contrato**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/ced47f5a-0763-45c1-b782-f5c9f1655aea)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsTyLCE3MAJGiEluHJ1P5hcB7WXrIE7oOmrf6vBRsR_wVA?e=7eJ1Ip


Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp, revisaremos el flujo al detalle la próxima SoS.

**Comment by jcmurilloa** [comment]
Por favor ajustar según las sugerencias realizadas en la sesión SoS y revisar en el próximo review

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes en el diagrama de flujo de acuerdo a sugerencias propuestas por el equipo SoS. Agradezco su revisión @jcmurilloa @edwargl7 quedo atento a comentarios adicionales. Pendiente presentar al cliente.

**Diagrama Estados de Contrato**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/a36b13b2-feba-48a6-8afe-c306e51b6ee7)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Esgeh5qXPhBPupCkX3BoGtsBmE0mu-ryfH57TuNoDgMheA?e=z7FNWI


Saludos.

**Comment by jcmurilloa** [comment]
Se ve bien @cjgonzalezp, en la Daily de mañana lo revisamos al detalle con el equipo SoS.

**Comment by jcmurilloa** [comment]
Pendiente realizar modificaciones respecto al cliente y generar flujo definitivo.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes en el diagrama de flujo estados del contrato de acuerdo a revisión con el cliente.

**Diagrama Estados de Contrato**
![Image](https://github.com/udistrital/argo_documentacion/assets/167805282/1234b90f-ed59-4cf4-91a6-30f57cd122b5)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Esgeh5qXPhBPupCkX3BoGtsBmE0mu-ryfH57TuNoDgMheA?e=ol0E7r


Saludos.

**Comment by jcmurilloa** [comment]
Excelente diagrama el consolidado finalmente con todos los aportes @cjgonzalezp. Muestra claramente la ruta para comprender la lógica del negocio.
