### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión exploratoria con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#6]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buenas tardes,

Se concertó una primera sesión de exploración del proceso que desarrolla en el sistema la oficina de contratación para determinar una base de posibles requerimientos para el desarrollo del sistema Argo V 2.0.

**La sesion fue desarrollada: **
Dia: 30 de abril de 2024
Hora: 09:00 am a 10:40 am
Lugar: Presencial - Sede Paiba

**Asistentes a la sesión:** 
OATI (Carlos Julián González Pérez - Heiner Edwar Granados Leal)
Oficina Contratación (Diva Conde Rueda - Luisa Fernanda Marín Ballen - Beatriz Cecilia Manrique Muñoz - Andrés Felipe Mercado Argel - Ximena Montealegre)

**Link Acta**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eqi1NapZzvlBua2xv02o9XEBKhdaFSBlTS7vUufsdFu0Ig?e=cTS3VM

**Link Grabación Sesión**
https://udistritaleduco-my.sharepoint.com/personal/cjgonzalezp_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fcjgonzalezp%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FLevantamiento%20requerimietos%20sistema%20ARGO%2D20240430%5F091540%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E3cbd2444%2Da2f8%2D456c%2Db317%2Da8800b546af3&ga=1

**Documentos Acta 019/2024 Argo - Levantamiento de Requerimientos**
[Acta 019-2024 Argo - Levantamiento de Requerimientos.pdf](https://github.com/udistrital/argo_documentacion/files/15205338/Acta.019-2024.Argo.-.Levantamiento.de.Requerimientos.pdf)

Saludos,

Carlos Julián González Pérez
Analista de Requerimientos OATI

**Comment by jcmurilloa** [comment]
Hola Carlos Julian.

El acta esta conforme a lo requerido, por favor adjuntar al documento, las respectivas firmas por parte de los asistentes, y adjuntar a su vez a la carpeta del one drive

**Comment by cjgonzalezp** [comment]
Buen día Julián,

El documento ya fue firmado por todos los participantes y la misma fue cargada el OneDrive en la carpeta del proyecto.

**Link Acta Reunión Firmada**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eqi1NapZzvlBua2xv02o9XEBKhdaFSBlTS7vUufsdFu0Ig?e=mWVDrD


Cordial saludo.
