### ISSUE TITLE
Revisión Integración Ágora - Datos contratista - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#60]
Se requiere realizar la revisión de la integración con Ágora basado en los últimos ajustes del Mockup en el que se eliminan unos campos y se agregan campos relacionados al representante legal. Esta Issue es la continuación de la Issue #53.
Se debe realizar la revisión de los endpoints del API administrativa_amazon_api que cumplan con los campos requeridos si es persona natural o jurídica.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/6d34db3c-c4e6-49d6-bf87-611e8d39e68b)

**Material de apoyo**
- Repositorio [administrativa_amazon_api](https://github.com/udistrital/administrativa_amazon_api)
- Controlador de [informacion_proveedor](https://github.com/udistrital/administrativa_amazon_api/blob/develop/controllers/informacion_proveedor.go)
- Endpoint de la API en el store [informacion_proveedor](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=administrativa_amazon_api&version=v1&provider=admin&tenant=carbon.super#/informacion_proveedor)
- Repositorio de ARGO versión actual [argo_desarrollo](https://github.com/udistrital/argo_desarrollo).
- Script con información sobre [proveedores en el ARGO actual](https://github.com/udistrital/argo_desarrollo/blob/master/blocks/gestionContractual/contratos/registrarContrato/Sql.class.php#L866). 

**Sub Tareas**

- [x] Revisión endpoints con campos requeridos según el Mockup.
- [x] Identificación campos faltantes (si aplica).
- [x] En caso que no se cuente con los endpoints que cubran lo requerido se debe crear la estructura requerida para evaluar la posibilidad de solicitar un endpoint que suministre los datos completos.
- [x] Detallar los datos que se consultaran de cada endpoint (en caso de requerir más de uno mencionar el orden de consulta), para esta sub tarea es importante agregar la estructura JSON de respuesta del endpoint y su correspondiente ruta (sin el HOST).
- [x] Actualización diagrama de microservicios agregando el microservicio MID que permite la consulta de información del contratista.

**Criterios de aceptación**

- [x] Identificación endpoints que suministren la información requerida sobre el contratista.
- [x] Actualización diagrama de arquitectura ARGO v2.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Identificación endpoints que suministren la información requerida sobre el contratista.
- [ ] Actualización diagrama de arquitectura ARGO v2.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Actualmente la información de expedición del documento solo está disponible en el endpoint de persona_natural.

**Comment by mau-oati** [comment]
Se requiere un endpoint que nos retorne la información relacionada al representante legal, basado en el endpoint de [informacion_persona_juridica](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=administrativa_amazon_api&version=v1&provider=admin&tenant=carbon.super#!/informacion_persona_juridica)
necesitamos incluir también:

- Nombre Representante Legal
- Documento Representante Legal
- Lugar de Expedición del Documento

**Comment by mau-oati** [comment]
El flujo de objentción de constratistas:
 
En **contratistas_mid**: 
- Solicitar info de endpoint **persona_natura**
- Solicitar infor de **persona_juridica**
- Combinar en un solo listado de objetos, retornar un listado de ids y tipo de contratista.

En el Frontend:
Se recibe el objeto combinado, para hidratar el dropdown del listado.
Cuando el usuario busque, filtrará entre las opciones en memoria. 
Al escoger uno, se enviará una petición a **contratistas_mid** para obtener el detalle individual del contratista seleciconado.

**Comment by mau-oati** [comment]
Se actualizó el diagrama de Microfrontends dejando la diferenciación del contratistas-mid.

**Comment by edwargl7** [comment]
Se requiere solicitar los campos adicionales, se revisa con el arquitecto la solución requerida y se solicita el apoyo al equipo de funcionamiento para identificar de donde tomar los campos adicionales requeridos.
Se valida el diagrama actualizado correctamente. Buen trabajo.
