### ISSUE TITLE
Implementación microservicio Ágora MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#61]
Se requiere realizar la implementación del microservicio MID ágora para ARGO v2 basado en los endpoints validados en la Issue #60 que permita la comunicación de los datos requeridos de Ágora a ARGO. La creación de este MID se genera con el fin de desacoplar el core de la nueva versión de ARGO con la fuente de datos de Ágora manteniendo una interfaz que permita a este microservicio mantener la estructura de datos hacía el CORE y encargándose de gestionar la lógica necesaria y consumo de endpoints requeridos para recopilar dicha información.

**Especificaciones técnicas**

1. Repositorio de este nuevo microservicio [proveedores_mid](https://github.com/udistrital/proveedores_mid).
2. El API debe cumplir con los siguientes lineamientos:
> a. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
> b. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
> c. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/40d6f40d-86f2-49e5-9e60-fc8d740749e0)
3. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang.

**Sub Tareas**

- [x] Creación API REST siguiendo los lineamientos.
- [x] Creación endpoint del servicio basado en [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/40d6f40d-86f2-49e5-9e60-fc8d740749e0)

**Criterios de aceptación**

- [x] API REST con los endpoints requeridos por el ARGO v2.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se trabaja en las consultas requeridas para la creación del endpoint requerido con ayuda del arquitecto y el equipo de funcionamiento.

**Comment by mau-oati** [comment]
Se revisa la necesidad de un endpoint que retorne la cantidad de numeros de disponibilidad para completar el flujo que existirá mas adelante en el frontend, dicho endpoint filtrado por vigencia y unidad_ejecutora.

**Comment by edwargl7** [comment]
Pendiente el endpoint, se revisa el comportamiento requerido ya que si se requiere la posibilidad de búsqueda en tiempo real se requiere usar cache con la lista de proveedores (documento identidad y nombres).

**Comment by edwargl7** [comment]
Se revisa con @cjgonzalezp y se aborda para evitar errores del usuario trabajar con la digitación del documento completo para realizar la búsqueda.

**Comment by edwargl7** [comment]
Se realiza el ajuste de la consulta SQL para el nuevo endpoint, pendiente la confirmación y creación del mismo con el apoyo del equipo de funcionamiento y arquitectura.

**Comment by mau-oati** [comment]
Se avanza el API CRUD con retorno de respuestas mocks, para continuar su desarrollo en cuanto tengamos disponible en endpoint definitivo.

**Comment by edwargl7** [comment]
Se realiza la revisión del repositorio cuenta con un buen avance, pendiente el endpoint para completar el desarrollo. Se trabajará finalizar este desarrollo una vez se cuente con el endpoint requerido.
