### ISSUE TITLE
Implementación microservicio Sicapital MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#62]
Se requiere realizar la implementación del microservicio MID Sicapital para ARGO v2 basado en los endpoints validados en la Issue #52  que permita la comunicación de los datos requeridos de Sicapital a ARGO. La creación de este MID se genera con el fin de desacoplar el core de la nueva versión de ARGO con la fuente de datos de sicapital manteniendo una interfaz que permita a este microservicio mantener la estructura de datos hacía el CORE y encargándose de gestionar la lógica necesaria y consumo de endpoints requeridos para recopilar dicha información.

**Especificaciones técnicas**

1. Repositorio de este nuevo microservicio [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid).
2. El API debe cumplir con los siguientes lineamientos:
> a. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
> b. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
> c. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/40d6f40d-86f2-49e5-9e60-fc8d740749e0)
3. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang.

**Sub Tareas**

- [x] Creación API REST siguiendo los lineamientos.
- [x] Creación endpoint del servicio basado en [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/40d6f40d-86f2-49e5-9e60-fc8d740749e0)

**Criterios de aceptación**

- [x] API REST con los endpoints requeridos por el ARGO v2.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se crea el endpoint de consulta de información del CPD basado en Script con información sobre [proveedores en el ARGO actual](https://github.com/udistrital/argo_desarrollo/blob/master/blocks/gestionContractual/contratos/registrarContrato/Sql.class.php#L926). Confirmar si se requieren más campos adicionales a los abordados en dicha consulta, por favor.

**Comment by mau-oati** [comment]
Se inicia el proceso de desarrollo local, probando librerías de conversión de XML a JS, al final se usó **xml2js**, se iniciaron pruebas de modelado con el endpoint nuevo.

**Comment by mau-oati** [comment]
Se revisa la necesidad de un endpoint que retorne la cantidad de numeros de disponibilidad para completar el flujo que existirá mas adelante en el frontend, dicho endpoint filtrado por vigencia y unidad_ejecutora.

**Comment by mau-oati** [comment]
Se encuentra que el endpoint nuevo retorna una lista de CDPs todos iguales, pero se esperaría que debería llegar solo 1.

**Comment by mau-oati** [comment]
Se ajusta para retornar el primer CDP, se evalúa la posibilidad de agregar un filtro adicional de **facultad** para asegurar el retorno del CDP adecuado, se prueba en local el retorno unitario.

**Comment by edwargl7** [comment]
Se realiza la revisión del desarrollo realizado, se puede usar de guía el proyecto [espacios_academicos_crud](https://github.com/udistrital/espacios_academicos_crud).
Además, se observa el uso del HOST directamente en el service y no como variable de entorno. Se debe realizar el ajuste.

**Comment by mau-oati** [comment]
Ejemplo de Response del API MID
```json
[
  {
    "vigencia": "2024",
    "descripcion": "Cesantías",
    "rubro_interno": "123",
    "estado": "APROBADA",
    "justificacion": "LA FACULTAD ABCDEF",
    "id_sol_cdp": "123",
    "nombre_dependencia": "FACULTAD DEL DERECHO",
    "fecha_registro": "2024-02-05T00:00:00.000+00:00",
    "observaciones": "SUELDO BÁSICO",
    "numero_disponibilidad": "1234",
    "num_sol_adq": "1234",
    "valor_contratacion": "123",
    "estadocdp": "VIGENTE"
  },
]
```

**Comment by mau-oati** [comment]
Se hizo el ajuste del host para completar la tarea.

**Comment by mau-oati** [comment]
Se hizo el ajuste del host y response para completar la tarea.

**Comment by edwargl7** [comment]
Se realiza la revisión y cumple con el ajuste pendiente, se trabajará al finalizar el sprint la revisión del desarrollo en una sesión para complementar las pruebas y evitar exponer en la prueba datos de los CDP.
Se trabajará en la Issue #73 el ajuste de primer letra mayúscula en la respuesta del endpoint.
