### ISSUE TITLE
Revisión y refinamiento modelo de datos módulo de parámetros

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#63]
Se requiere realizar el ajuste al modelo de datos propuesto en la Issue #44 donde se define el módulo de parámetros para la parametrización exclusiva de ARGO.

**Sub Tareas**

- [x] Revisión [modelo de datos del microservicio de parámetros CRUD](https://raw.githubusercontent.com/udistrital/parametros_crud/a51107771482e4dee3f76511bc18fd048a93866e/database/parametros.svg) para complementar el modelo propuesto.
- [x] Ajuste del modelo de datos propuesto agregando relación de la tabla parametro con si misma, que permita el registro de parámetros con niveles (padre-hijo) similar al manejado en parametros_crud.

**Criterios de aceptación**

- [x] Modelo de datos separados con los ajustes requeridos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza el ajuste al modelo agregando una relación de parámetro consigo mismo para permitir el registro de parámetros con niveles (padre-hijo) como se solicitó:

![image](https://github.com/udistrital/argo_documentacion/assets/133523053/a76bf76b-c6d2-464d-adba-37f78cbd8918)

Por el momento no se observan más ajustes al modelo de datos propuesto.

**Comment by edwargl7** [comment]
Me ayudas a actualizar los nombres de los tipos de datos de las tablas siguiendo los lineamientos de [modelo_de_datos] por favor.(https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Comment by Lau2ri** [comment]
Se realizan los cambios a los tipos de datos para ajustarlos a los lineamientos de modelo de datos dados por la OATI:

![image](https://github.com/udistrital/argo_documentacion/assets/133523053/70404da9-4169-44a1-aa70-41f3739ee09f)

**Comment by edwargl7** [comment]
Buen trabajo, ajustado según los lineamientos. Actualizar por favor el nombre del campo que almacena la relación de padre de la tabla parametro por favor, similar al modelo de datos de parametros_crud.
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/b1e0b717-5251-487f-ad25-4a073480c0a5)

**Comment by Lau2ri** [comment]
Se realiza el ajuste al nombre del campo parametro_padre_id 

![Image](https://github.com/udistrital/argo_documentacion/assets/133523053/c52617fb-a701-4193-8f37-5ad4648dbd0c)

**Comment by edwargl7** [comment]
Muchas gracias por el ajuste, se culmina la revisión de la Issue. Se crea ticket en el que se envía a revisión el modelo propuesto.
