### ISSUE TITLE
Diseñar mockup de vista consulta contrato de módulo de gestión contractual

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#64]
Se requiere realizar el diseño de vista consulta contrato de módulo de gestión contractual

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipos SoS.
- [x] Realizar ajustes según comentarios del equipo.
- [x] Presentar al cliente el mockup definitivo.

**Criterios de aceptación**

- [x] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño del submódulo consultar contrato del módulo gestión contractual.

Mockup Submódulo Consultar Contrato
![Image](https://github.com/user-attachments/assets/4acff552-1625-482d-b47f-0163dc814566)


Saludo.

**Comment by jcmurilloa** [comment]
Gracias por compartir el avance del diseño del mockup @cjgonzalezp, por favor comentar la issue con el mockup definitivo para revisar en el próximo review SoS.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza el diseño del submódulo consultar contrato del módulo gestión contractual. Pendiente revisar con el equipo SoS

**Enlace diseño cargado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmJYcbb4P51Jr7bcXo-TadIBeAozStHKnipweAoG8VWYYw?e=20s07a


Saludos.

**Comment by jcmurilloa** [comment]
Tener en cuenta las recomendaciones realizadas por el equipo SoS y exponer al equipo de desarrollo. Buen trabajo @cjgonzalezp

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los ajustes solicitados por el equipo SoS.

**Enlace diseño cargado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmqVFSYpNa9OoZQfXWTrsm0B6O_4aRQrkxfUf5BgvjC1Jg?e=woZ9un


Saludos.

**Comment by jcmurilloa** [comment]
Exelente trabajo @cjgonzalezp, pendiente aprobar por parte del cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta diseño mockup submódulo consulta de contrato al cliente y se recibe aprobación para su desarrollo en el sistema ARGO V2.

**Enlace archivo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtRHNMKONftNgfh2dqvpRgYByaohlPba34JGRwWKxxRaeA?e=msgcup

**Acta de reunión No. 103/2024 - Aprobación mockup submódulo consulta de contrato**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo4dvlEBnrxHqXWAgtJZQmUBR1zCMGrGE1p1qsDJ3EI_1A?e=BHQaoI

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp
