### ISSUE TITLE
Pruebas generación de minuta desde la plantilla

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#65]
Se requiere realizar la prueba de concepto de las alternativas investigadas en la Issue #57 para generar la minuta desde la plantilla HTML y el estilo CSS, basado en la generación actual de minutas de ARGO. Donde se busca desarrollar un microservicio independiente de generación de PDF basado en las plantillas y datos requeridos.

**Especificaciones técnicas**
1. Repositorio de almacenamiento de las pruebas de concepto [Prueba_concepto_plantillas_html](https://github.com/udistrital/Prueba_concepto_plantillas_html)

**Sub Tareas**

- [x] Copia de una plantilla para uso en pruebas locales.
- [x] Modificación de la plantilla del ambiente local de minuta de _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_ removiendo las variables y reemplazando por datos de prueba.
- [x] Desarrollo de scripts con las opciones que permitar renderizar esa plantilla de prueba sin variables y documentación de resultados.
- [x] Modificación de plantilla agregando variables a la plantilla para prueba con variables.
- [x] Modificación de scripts para que cuenten ahora con la posibilidad de pasar variables en un objeto con los datos requeridos que puede dejarse quemado en el mismo script para la prueba de renderizado con variables.
- [x] Documentar los resultados obtenidos.

**Criterios de aceptación**

- [x] Documentación de la prueba de concepto realizada con cada alternativa investigada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se comenzó la prueba de concepto con la librería WeasyPrint de Python y se obtuvo el siguiente [PDF](https://github.com/udistrital/Prueba_concepto_plantillas_html/blob/develop/WeasyPrint/pruebaWP.pdf) de la plantilla de minuta de Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión con vigencia más reciente encontrada en la base de datos.

Cabe mencionar que se hizo una prueba preliminar reemplazando uno de los parámetros, en este caso el parámetro de NOMBRE_ORDENADOR, reemplazándolo por ABC, y el cambio se hace correctamente sin mayor dificultad:

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/96e74bf0-e94d-449c-99a1-fa62b77a900f" width="500">

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/5a26898a-71db-426e-888e-c06e1494f62c" width="500">

El resultado obtenido con esta librería es muy bueno.

## Observaciones sobre el HTML

- Lo primero que se observó es que en el HTML guardado en la base de datos se encuentra un error, y es que la etiqueta de negrilla ( b ) no se encuentra cerrada en un momento específico (después de INFO CONTRATISTA), haciendo que a partir de ahí todo el texto quede en negrilla:

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/36b348f5-a72b-480f-87d6-86045e1d021b" width="400">

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/c5909daf-8a05-4cde-a33c-03e2cdfe7aa7" width="300">

Problema que se soluciona pues añadiendo el cierre de la negrilla ( /b ):

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/baf72f19-fe06-4995-afdf-7850b1a1e272" width="400">

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/464aaeee-fbc4-427c-999a-3a671f81f692" width="400">

- Y lo segundo que se observó que en cuanto a estilos no se está tomando el tamaño de letra situado en el HTML, es por eso que en el [PDF](https://github.com/udistrital/Prueba_concepto_plantillas_html/blob/develop/WeasyPrint/pruebaWP.pdf) se ve tan grande el texto.

**Comment by Lau2ri** [comment]
## Puppeteer
Se siguió con la prueba de concepto de la biblioteca Puppeteer, después de un buen rato de intentos y errores, se llegó a la conclusión de que no es viable utilizar esta biblioteca debido a que es necesario el uso de Chromium-browser para el funcionamiento de la biblioteca y, al parecer, en el entorno virtual WSL que estoy manejando (y que la mayoría de los desarrolladores de la OATI utilizan) está limitado en cuanto al uso y ejecución de estas aplicaciones:

![Captura de pantalla 2024-07-09 194749](https://github.com/udistrital/argo_documentacion/assets/133523053/dc47e59e-9bf4-42be-8b27-5185e6036e6d)

Este error indica que está utilizando Windows Subsystem for Linux (WSL) versión 1, que tiene algunas limitaciones, especialmente en lo que respecta a la ejecución de aplicaciones gráficas como Chromium:

![Captura de pantalla 2024-07-09 194800](https://github.com/udistrital/argo_documentacion/assets/133523053/e2153396-8b1a-4e82-beec-9b4e38d34b37)

Así que por el momento esta biblioteca deberá ser descartada.

**Comment by Lau2ri** [comment]
## Html2pdf
Se siguió con la prueba de concepto de la biblioteca Html2pdf, similar a la anterior, después de un buen rato de intentos y errores, se llegó a la conclusión de que no es viable utilizar esta biblioteca debido a un error encontrado, aparentemente, referente a que Node.js, o por lo menos mi versión, no es compatible con dicha biblioteca:

![Captura de pantalla 2024-07-09 205608](https://github.com/udistrital/argo_documentacion/assets/133523053/5daba93e-b4ad-4a34-9528-e6973fe84bfe)

![Captura de pantalla 2024-07-09 205625](https://github.com/udistrital/argo_documentacion/assets/133523053/b516dc57-63ab-40c8-90a7-0af4b831bd8c)

![Captura de pantalla 2024-07-09 210623](https://github.com/udistrital/argo_documentacion/assets/133523053/8221cd4c-19fc-4c38-b0aa-2fdfb446b02e)

Así que por el momento esta biblioteca deberá ser descartada.

**Comment by Lau2ri** [comment]
# Wkhtmltopdf
## En Python
En primera instancia se trabajo esta librería en Python, este fue el [pdf](https://github.com/udistrital/Prueba_concepto_plantillas_html/blob/develop/Wkhtmltopdf/pruebaWK.pdf) resultado. Una cosa por mencionar es que en este pdf si toma el tamaño de la fuente expresado en el HTML que es de 1px y es por esto que la letra se ve tan diminuta, habría que ajustarlo.

Se realizó la prueba de reemplazo de un parámetro como, en este caso el parámetro de NOMBRE_ORDENADOR, reemplazándolo por ABC, y el cambio se hace correctamente sin mayor dificultad:

![Captura de pantalla 2024-07-11 210236](https://github.com/user-attachments/assets/8ad66f1b-cf0f-4e36-b956-97f2ee82c9e6)

## En Node.js

Esta biblioteca también se podía trabajan en Node.js, así que se hizo la respectiva prueba, siendo el resultado prácticamente el mismo [pdf](https://github.com/udistrital/Prueba_concepto_plantillas_html/blob/develop/WkhtmltopdfNode/pruebaWKn.pdf), para esta prueba no se alcanzó a probar el reemplazo de parámetros, quedaría pendiente, por lo demás considero que es una opción viable. Se mantiene la observación del ajuste del tamaño de letra que se encuentra en 1px.

**Comment by Lau2ri** [comment]
## PDFKit
Esta es una librería que hace uso de Wkhtmltopdf, pero además tiene la desventaja que por si misma no está diseñada para interpretar HTML a texto, es por esto que la prueba que se hizo con esta biblioteca dio como resultado un texto HTML impreso literalmente sobre el pdf:

<img src="https://github.com/user-attachments/assets/f2cda526-7fb5-4d63-bc39-e6b7db933a6c" width="400">

Situación que claramente no nos es útil para nuestro objetivo. Además que para corregir esto se deben implementar otras bibliotecas extras (entre las cuales se encuentra Wkhtmltopdf), y no considero que esto sea funcional.

## jsPDF

Revisando la documentación de esta biblioteca en diferentes lugares como [este](https://www.codexworld.com/convert-html-to-pdf-using-javascript-jspdf/) encontré que esta biblioteca lo que hace principalmente es tomar como "pantallazos" del HTML e imprimirlos en el PDF, situación que consideré que no nos es útil debido a que se busca que el documento de Nomina sea de texto plano y no de imágenes de texto, debido a esto no se realizó la prueba de concepto porqué no resulta pertinente.

**Comment by edwargl7** [comment]
Se realiza una revisión de los resultados obtenidos presentados durante el sprint, se revisa el repositorio con las pruebas de concepto realizadas. Se observa una investigación y prueba de concepto con una buena variedad de alternativas validadas.
Además, con varias posibilidades que lograron alcanzar el resultado esperado.

**Comment by edwargl7** [comment]
Cumple con lo requerido, se cuenta con la opción de **mPDF** que es la librería que funciona actualmente en ARGO actual.
Buen trabajo.
