### ISSUE TITLE
Ajuste modelo de datos core ARGO v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#66]
Se requiere realizar el ajuste de modelo de datos del core de ARGO v2, donde se asigne el tipo de datos adecuado a los campos cuyo tipo de dato es _old_ del modelo de datos propuesto. Si son campos paramétricos tener presente que estos microservicios cuentan con un modelo de datos relacional. Además, se requiere remover del diagrama propuesto la tabla de paramétros dado que se manejará en otro microservicio.

**Sub Tareas**

- [x] Ajustes tipos de datos en el modelo de datos propuesto.
- [x] Remover tabla de parametro del modelo de datos propuesto para el core de ARGO v2.
- [x] Presentación modelo de datos al equipo DBA.

**Criterios de aceptación**

- [x] Modelo de datos actualizado con la observación sugerida por el equipo DBA.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se requiere presentar el modelo core de ARGO v2 separado como se trabajo en la Issue #44.
Para esta Issue se aborda:
![image](https://github.com/udistrital/argo_documentacion/assets/50187485/6ceac51e-e83a-4c4f-87f2-af699804a7ad)

**Comment by mau-oati** [comment]
Se adjunta propuesta actualizada del modelo de datos para el core de ARGO V2.

![Image](https://github.com/udistrital/argo_documentacion/assets/163943201/a55da977-9b14-43cb-b876-43b062f8f0f5)

**Comment by edwargl7** [comment]
Cuenta con los ajustes requeridos, se revisará en la Daily si cuenta con alguna modificación requerida contemplando la revisión de migración realizada en la Issue #50 .

**Comment by mau-oati** [comment]
Se hizo al actualización de la propuesta, la versión más reciente es:

![Propuesta-Migracion drawio (1)](https://github.com/udistrital/argo_documentacion/assets/163943201/13a5b647-1bc2-482b-a2d8-97935953ba12)

**Comment by edwargl7** [comment]
Se procede a presentar la última versión al equipo DBA. Buen trabajo.
