### ISSUE TITLE
Crear script de creación de base de datos microservicio de parametros_crud - registros no transversales

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#68]
Se requiere realizar la creación del script de creación de la base de datos del modelo datos de parametros_crud trabajado en la Issue #63. Se genera este borrador y se ajusta basado en las observaciones dadas al modelo de datos propuesto.

**Sub Tareas**

- [x] Creación de script para creación de microservicio de gestión de parametros_crud no transversales a otros sistemas.

**Criterios de aceptación**

- [x] Script creado basado en el modelo de datos propuesto (sujeto a cambios).

**Requerimientos**

- Ajuste mencionado en la Issue #57.

**Material de apoyo**
- Script de creación de base de datos de [inscripcion_crud](https://github.com/udistrital/inscripcion_crud/blob/develop/database/scripts/20190713_140607_crear_tablas_inscripciones.up.sql)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se crea el Script preliminar de creación del modelo de datos de parametros_argo según modelo diseñado en la issue #63:
```
BEGIN;


CREATE TABLE IF NOT EXISTS "parametros_argo".parametros
(
    id serial NOT NULL,
    nombre character varying NOT NULL,
    activo boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    fecha_modificacion timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "parametros_argo".tipo_parametro
(
    id serial NOT NULL,
    nombre_categoria character varying NOT NULL,
    activo boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    fecha_modificacion timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "parametros_argo".parametros
    ADD FOREIGN KEY (id)
    REFERENCES "parametros_argo".tipo_parametro (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "parametros_argo".parametros
    ADD FOREIGN KEY (id)
    REFERENCES "parametros_argo".parametros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
```

Quedo atenta si se requieren ajustes adicionales.

**Comment by edwargl7** [comment]
Pendiente confirmar con DBA el ajuste de si se dejan o no las fechas de creación y modificación.

**Comment by edwargl7** [comment]
Pendiente confirmar si se agrega los permisos como el ejemplo de inscripciones crud.

**Comment by edwargl7** [comment]
Se revisa con el arquitecto y se debe cancelar el desarrollo de un parámetros crud adicional. Se debe seguir usando solamente el parametros_crud actual. Se debe almacenar, sin embargo, los avances alcanzados el este modelo dado que se baso la tarea en las propuestas planteadas que permitieran desacoplar la dependencia de cada microservicio con parametros_crud.
