### ISSUE TITLE
Implementación microservicio MID ordenadores y supervisores

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#70]
Se requiere realizar la implementación base del microservicio MID para la consulta de ordenadores y supervisores.

**Sub Tareas**

- [x] Implementación microservicio base.
- [x] Implementación endpoint healthcheck.
- [x] Prueba integración healthcheck
- [ ] #190
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avance implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza el commit inicial creando toda la base del microservicio [ordenadores_supervisores_contratacion_mid](https://github.com/udistrital/ordenadores_supervisores_contratacion_mid) y se realiza la implementación del endpoint healthcheck con sus respectivas pruebas de integración:

![image](https://github.com/user-attachments/assets/58220226-c87c-4b42-966f-8fa1cd4d4c5e)

**Comment by edwargl7** [comment]
Muy buen trabajo, se complementa el endpoint de consulta de ordenador en el siguiente sprint dado que los endpoints consultados no contaron con los datos requeridos.
