### ISSUE TITLE
Pruebas Unitarias microservicio MID de Sicapital

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#71]
Se requiere realizar la creación de pruebas unitarias al endpoint de consulta de CDP por vigencia, numero disponibilidad y unidad ejecutora del microservicio MID de Sicaptial realizado en la Issue #62 .

**Sub Tareas**

- [x] Crear prueba unitaria del endpoint de consulta CDP revisando la posibilidad de usar un Mock para la consulta al servicio.

**Escenarios de pruebas**
- [x] Prueba unitaria función de consulta al servicio Mock para validar el correcto funcionamiento, escenario con una respuesta.
- [x] Prueba unitaria función de consulta al servicio Mock para validar el correcto funcionamiento, escenario con varias respuestas.
- [x] Prueba unitaria función de consulta al servicio Mock para validar el correcto funcionamiento, escenario sin ningún resultado de CDP.
- [x] Prueba unitaria función de consulta al servicio Mock para validar el caso que no se cuente con respuesta de la fuente de información (petición no respondida).

**Criterios de aceptación**

- [x] Escenarios mínimo de pruebas cubierto, se pueden agregar pruebas unitarias adicionales que sean identificadas.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Pendiente confirmar con el arquitecto si al enviar en el HEADER de la petición el ContentType con application/json retorna JSON y de esta forma evitamos tener que convertir XML. Revisado por @mau-oati .

**Comment by edwargl7** [comment]
Se confirma la posibilidad de obtener un JSON por medio de los HEADERS, por lo tanto, se remueve de la Issue las pruebas unitarias para la función de conversión XML2JSON.

**Comment by mau-oati** [comment]
Pruebas exitosas

<img src="https://github.com/user-attachments/assets/90de95ce-ce35-4802-a86e-ad08c10564d3" width="400" />

**Comment by edwargl7** [comment]
Se realiza la revisión del código, cuenta con pruebas unitarias solicitadas usando mock, son claras, completas y cuenta con el mock lo cual permite un trabajo de pruebas unitarias independiente del uso del servicio del ambiente real. Buen trabajo.
Tener presente la etiqueta apropiada para las pruebas (_test_) y realizar por favor el PR.

**Comment by edwargl7** [comment]
Pendientes resueltos. Finalizada completamente esta Issue :checkered_flag:
