### ISSUE TITLE
Agregar endpoint HealthCheck microservicio 

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#72]
Se requiere realizar el desarrollo del endpoint HealthCheck en el microservicio MID [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid), ejemplo de implementación en Beego [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md). Este endpoint debe poder ser consumido en el root del servicio. 

Estructura de respuesta del endpoint:
```
{
  "Status": "Ok",
  "checkCount": 22797
}
```

**Sub Tareas**

- [x] Creación endpoint health check
- [x] Pruebas del corrector funcionamiento del endpoint.

**Criterios de aceptación**

- [x] Implementación del endpoint, junto con el PR y pruebas realizadas al endpoint en ambiente local.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
- [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/5ac24694-0717-4d71-ba9d-d73674310715" width="250" />

**Comment by edwargl7** [comment]
Se ve un buen avance, pendiente ajustar el nombre de la función getHello y adicional actualizar por favor el README (tarea adicional a las documentadas en la Issue). Para la sección de pruebas unitarias en el lineamiento de README no se observa la documentación de ejemplo, por lo tanto, se debe guiar en la forma en la que se documento el Dockerfile y docker-compose.

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/7af2c1ba-8732-4e0a-b5e1-ba95a2c69246" width="250" />

**Comment by edwargl7** [comment]
Revisado y confirmado los ajustes pendientes. Buen trabajo.
