### ISSUE TITLE
Ajustes microservicio MID de Sicapital - Excepciones

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#73]
Se requiere realizar el desarrollo que cubra los casos erróneos en la consulta al servicio fuente de datos del CDP. Que garanticen en caso de fallos en la petición una respuesta controlada del MID o el caso en el que no sea posible la conversión del XML a JSON.

Tener presente el formato de respuesta de los endpoints.
![image](https://github.com/user-attachments/assets/4ffc0bb0-2e75-49ff-8321-4a098d2f0231)
Ese formato debe aplicarse tanto en respuestas correctas como en las excepciones.

**Sub Tareas**

- [x] Implementación de captura de excepciones para los casos requeridos, cumpliendo con el formato de respuesta.
- [x] Ajuste formato de respuesta para caso de respuesta correcta.

**Criterios de aceptación**

- [ ] Cumplir con la implementación de las subtareas y la respectiva evidencia de las pruebas realizadas.

**Requerimientos**

No aplica

**Material de apoyo**
- [Formato de respuesta](https://github.com/udistrital/utils_oas/blob/138b3a53e7b16c31813130c11aed9cf924ecd0e0/requestresponse/responses_format.go#L10)
- [Formato respuesta usado para excepciones](https://github.com/udistrital/utils_oas/blob/master/customerrorv2/custom_errorv2.go)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/3dc42386-edfd-47f8-ac86-b0e5388f755c" width="450" />

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/3108203b-cb32-46d6-97be-9d89fe806dbf" width="450" />

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/f3c09310-92f4-413f-a73f-1b0b2db1a95c" width="350" />

**Comment by edwargl7** [comment]
Se realiza la revisión del código y se observa una completa implementación. Cuenta la documentación apropiada para las pruebas requeridas. Buen trabajo.
