### ISSUE TITLE
Implementación microservicio Ágora MID - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#74]
Se requiere continuar con el desarrollo del endpoint de consulta de proveedor por documento de identidad trabajada inicialmente en la Issue #61, siguiendo el formato de respuesta.
![image](https://github.com/user-attachments/assets/4ffc0bb0-2e75-49ff-8321-4a098d2f0231)

**Sub Tareas**

- [x] Implementación del endpoint de consulta de proveedor por documento de identidad.
- [x] Implementación del endpoint de consulta del representante legal por id del proveedor, que se relaciona al id proveedor retornado por el endpoint anterior, que en caso de ser persona jurídica suministra la información del representante legal.
- [x] Implementación endpoint Health Check.
- [x] Pruebas del correcto funcionamiento del endpoint.

**Criterios de aceptación**

- [x] Implementación de los endpoints siguiendos los lineamientos requeridos para el nombre de los endpoints y el desarrollo del health check (se encuentran al final de este Issue), con sus respectivas evidencias de las pruebas realizadas.

**Requerimientos**

- Endpoints y consulta a base de datos compartida.

**Material de apoyo**
- Relación entre las tablas que almacenan la información del proveedor y del representante legal.
![udistrital - agora - proveedor_representante_legal](https://github.com/user-attachments/assets/ff85690b-43a2-4049-948e-ee0e0da270d1)

**Especificaciones técnicas**

1. Repositorio de microservicio [proveedores_mid](https://github.com/udistrital/proveedores_mid).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Duda:

La respuesta del primer endpoint, cuando trae datos de proveedor de persona natural, no deja muy claro si la ciudad de expedicion est'a presente. Es **ciudad_contacto**?



<img src="https://github.com/user-attachments/assets/ab7e93cc-c907-4bfa-8775-23f928907cd5" width="400" />

**Comment by mau-oati** [comment]
En el caso de **persona juridica**, esa informaci'on se obtiene del segundo endpont. 😁

**Comment by edwargl7** [comment]
:boom: Pendiente ajuste consulta para agregar ciudad de expedición.

**Comment by edwargl7** [comment]
La solución planteada para obtener el lugar de expedición se planteo usando el mismo endpoint de datos de representante legal, sin embargo, se replantea para complementar ese dato en el endpoint de proveedor que aplica solo para persona natural.

**Comment by edwargl7** [comment]
Actualizado el endpoint con el campo de ciudad_expedicion_documento que aplica para persona natural.
![image](https://github.com/user-attachments/assets/df23fb2b-e1af-4c54-a0aa-de8cf8427810)
En caso de ser persona jurídica se retorna vacio.
![image](https://github.com/user-attachments/assets/923ab761-0b0b-4e9f-8057-2909bc60310e)

**Comment by edwargl7** [comment]
Se comparte por interno los datos de pruebas que se pueden usar.

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/bea82573-e35e-4f63-be0f-ccd30fe594c0" width="500" />

**Comment by mau-oati** [comment]
**Persona Natural:**

<img src="https://github.com/user-attachments/assets/68de1c0e-dd90-489f-9591-86306a7f3f99" width="500" />

**Persona Juridica:**

<img src="https://github.com/user-attachments/assets/65724528-9442-4083-b116-ad41878d4f39" width="500" />

**Comment by mau-oati** [comment]
Caso: No Encontrado:

![Image](https://github.com/user-attachments/assets/2ed4243b-be82-4b52-a47e-92fde5d88ed5)

**Comment by edwargl7** [comment]
Muy buen trabajo, cumple con el desarrollo solicitado siguiendo los lineamientos y una implementación clara.
