### ISSUE TITLE
Registrar datos paramétricos de ARGO en parametros_crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#75]
Se requiere realizar el registro de los parámetros requeridos por ARGO organizados en el [Mockup](https://github.com/user-attachments/assets/4ffc0bb0-2e75-49ff-8321-4a098d2f0231) manteniendo la agrupación con la que cuentan algunos de los parámetros.

![image](https://github.com/user-attachments/assets/21439a21-530a-46f5-9f64-9a4dcfbdf49f)

**Sub Tareas**

- [x] Revisión modelo de datos de [parametros_crud](https://github.com/udistrital/parametros_crud) para organizar los datos que se requieren crear teniendo presente los parámetros que tienen agrupación.
- [x] Revisión de registro de los parámetros requeridos usando el API [API de parametros_crud](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=Parametros&version=v1&provider=admin&tenant=carbon.super)
- [x] Registro de Tipo de Compromiso -> Área tipo gestión contractual -> Id: 25.
- [x] Registro Tipo de Contrato -> Área tipo gestión contractual -> Id: 25
- [x] Registro Perfil del Contratista -> Área tipo gestión contractual -> Id: 25
- [x] Registro Tipología Específica -> Área tipo gestión contractual -> Id: 25
- [x] Registro Modalidad de Selección -> Área tipo gestión contractual -> Id: 25
- [x] Registro Régimen de Contratación -> Área tipo gestión contractual -> Id: 25
- [x] Registro Procedimiento -> Área tipo gestión contractual -> Id: 25
- [x] Registro Amparo -> Área tipo gestión contractual -> Id: 25
- [x] Registro Tipo de Control -> Área tipo gestión contractual -> Id: 25
- [x] Registro Clase Contratista -> Área tipo gestión contractual -> Id: 25
- [x] Registro Vigencia -> Área tipo gestión contractual -> Id: 25
- [x] Registro Tipo de Moneda -> Transversal -> Tipo Moneda -> Id: 26
- [x] Registro Tipo de Gasto -> Área tipo gestión contractual -> Id: 25
- [x] Registro Origen Recursos -> Área tipo gestión contractual -> Id: 25
- [x] Registro Origen Presupuesto -> Área tipo gestión contractual -> Id: 25
- [x] Registro Tema Gasto Inversión -> Área tipo gestión contractual -> Id: 25
- [x] Registro Medio de Pago -> Área tipo gestión contractual -> Id: 25
- [x] Validar la creación de los parámetros, realizando la petición filtrando por tipo. Ejemplo ".../v1/parametro?query=TipoParametroId:10".

**Criterios de aceptación**

- [x] Cumplir con las subtareas y la correspondiente evidencia de los registros realizados.

**Requerimientos**

No aplica

**Material de apoyo**
- [API de parametros_crud](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=Parametros&version=v1&provider=admin&tenant=carbon.super)
- Repositorio [parametros_crud](https://github.com/udistrital/parametros_crud)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Pendiente confirmar con @cjgonzalezp la relación de este tipo de contrato:
![image](https://github.com/user-attachments/assets/645b7dd2-b8ee-49ca-8101-0ba629df278c)

**Comment by Lau2ri** [comment]
## Registro de TIPOS PARÁMETRO por cada tabla:

<img src="https://github.com/user-attachments/assets/e4a05cf6-ec0f-4e27-ae9c-2ca937407268"  width=170>
<img src="https://github.com/user-attachments/assets/dedc77f8-d11f-4eea-9dd8-d0af0b25721e"  width=170>
<img src="https://github.com/user-attachments/assets/0af61e23-0ab3-4d4f-bee5-b335ffc85ac9"  width=170>
<img src="https://github.com/user-attachments/assets/0d9c186c-0fee-4219-9ab5-76cc4d6d5eb9"  width=170>
<img src="https://github.com/user-attachments/assets/a9537c27-1198-4ecd-869f-9854ff641bc7"  width=170>
<img src="https://github.com/user-attachments/assets/ee18019d-ca85-484f-b277-44e517e90991"  width=170>
<img src="https://github.com/user-attachments/assets/13a62c94-818d-4bf3-a6b9-dd7e516c1208"  width=170>
<img src="https://github.com/user-attachments/assets/a4f43c40-b850-4af2-892a-8ee32cae9fa0"  width=170>
<img src="https://github.com/user-attachments/assets/86b84738-d2a8-4677-82ea-ff9350bc2177"  width=170>
<img src="https://github.com/user-attachments/assets/b2a470b1-cd50-414b-86f8-3309f4c856f2"  width=170>
<img src="https://github.com/user-attachments/assets/84bf8906-c639-403c-b473-8b08df9a6159"  width=170>
<img src="https://github.com/user-attachments/assets/1c92e331-5911-441c-817a-75b9eb2e649c"  width=170>
<img src="https://github.com/user-attachments/assets/6babb85c-123d-4238-9010-c940df2c0746"  width=170>
<img src="https://github.com/user-attachments/assets/0f180a43-fda3-4c92-b10d-60e94b467c70"  width=170>
<img src="https://github.com/user-attachments/assets/1760477f-3c3e-4a6d-b825-eec867325339"  width=170>
<img src="https://github.com/user-attachments/assets/bb8d7b48-528f-4de1-a81b-904fddff0fc0"  width=170>
<img src="https://github.com/user-attachments/assets/3c758ba8-d572-4f42-ad94-0b02ac546b8c"  width=170>

## Registro de PARÁMETROS por cada tipo: 

<img src="https://github.com/user-attachments/assets/a689432d-4ac6-4d39-b202-622c1c4bcf83"  width=170>
<img src="https://github.com/user-attachments/assets/7a960c4a-cfb3-4d27-981b-cc87bdc24428"  width=170>
<img src="https://github.com/user-attachments/assets/f02304ed-bd8c-4cbe-b246-1625cf9c1462"  width=170>
<img src="https://github.com/user-attachments/assets/ef110c51-9b90-4c97-bbf5-1a71c94dc37e"  width=170>
<img src="https://github.com/user-attachments/assets/4b70b27e-3959-4771-8feb-8dcb9ecc09a7"  width=170>
<img src="https://github.com/user-attachments/assets/96125367-43ef-4c2b-9028-8fe4ba90f94f"  width=170>
<img src="https://github.com/user-attachments/assets/b51aba87-6af8-4e5a-8443-8e733f47394c"  width=170>
<img src="https://github.com/user-attachments/assets/7a71e695-cb23-4489-abf6-b68ca6f54407"  width=170>
<img src="https://github.com/user-attachments/assets/8a368294-8c7d-450c-b9ad-26a17733f115"  width=170>
<img src="https://github.com/user-attachments/assets/57972b0f-7171-4445-8bb2-12458074d8a5"  width=170>
<img src="https://github.com/user-attachments/assets/74559ca5-cba2-4b62-98ac-2cbf69e4c4cb"  width=170>
<img src="https://github.com/user-attachments/assets/cf81f7cc-fba6-496b-a263-ce08a6464a99"  width=170>
<img src="https://github.com/user-attachments/assets/325c2edb-da80-42b1-b767-e102bdef7c09"  width=170>
<img src="https://github.com/user-attachments/assets/fde920f0-926c-4717-91b2-d7fc6d1e0269"  width=170>
<img src="https://github.com/user-attachments/assets/be4344fc-3a3e-4651-ba54-206bcca8e51a"  width=170>
<img src="https://github.com/user-attachments/assets/4d702d97-6f42-4914-9ef7-590be118dae9"  width=170>

Sólo quedan faltando los parámetros de la tabla de Perfil del Contratista.

**Comment by edwargl7** [comment]
Ya se encuentra actualizado el Mockup con el ajuste de la agrupación de Perfil del contratista.
![image](https://github.com/user-attachments/assets/e7ced596-d574-423e-8df6-11a1aeaa2a10)

**Comment by Lau2ri** [comment]
Se realizan los registros de los parámetros de la tabla de Perfil del Contratista que faltaban:
<img src="https://github.com/user-attachments/assets/030db247-da97-49d3-8392-4c20dcd8528d"  width=400>

**Comment by edwargl7** [comment]
Se realiza la revisión y se debe ajustar los registros del perfil de contratista para solo el tipo de contrato **Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión**.
![image](https://github.com/user-attachments/assets/db27c025-e692-4d08-a9c7-e0bf679e3b46)

**Comment by edwargl7** [comment]
Confirmado el registro de los datos paramétricos abordados en está Issue.
Buen trabajo.
Se carga una lista resumen de registros a la carpeta de documentos de ARGO.
