### ISSUE TITLE
Integración de parametros_crud con el microcliente de gestión contractual - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#76]
Se requiere realizar la integración del microservicio [parametros_crud](https://github.com/udistrital/parametros_crud) con el microcliente de [gestión contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) en cada uno de los campos paramétricos del formulario trabajados basado en el [Mockup](https://github.com/user-attachments/assets/4ffc0bb0-2e75-49ff-8321-4a098d2f0231).

![image](https://github.com/user-attachments/assets/0db91171-f901-41ed-82df-e2d0dafeb606)
![image](https://github.com/user-attachments/assets/bcf67c72-e61d-49c1-a559-526598e5aea4)

**Sub Tareas**

- [x] Implementación integración con el microservicio [parametros_crud](https://github.com/udistrital/parametros_crud).
- [x] Implementación de integración en los selectores respectivos relacionado al registro de parámetros trabajado en la Issue #75, empleando variables de entorno para cada identificador que agrupa las opciones de cada selector.

**Criterios de aceptación**

- [x] Documentación de las pruebas realizadas con la integración de parámetros crud.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realizaron todos los pasos iniciales necesarios para hacer la integración con el microservicio de parametros_crud, lo cual es la creación del servicio y de sus respectivos managers.

![image](https://github.com/user-attachments/assets/ee371a67-875f-4d04-a0f7-c2f1536f1149)
![image](https://github.com/user-attachments/assets/3baab96f-6536-4a2c-89eb-13764c32f020)

## Problema:
A la hora re realizar la primera integración en el primer selector de todos que es el de Compromisos de la siguiente manera:

![image](https://github.com/user-attachments/assets/e92ef9e7-67ac-4daf-8139-a46ce64f3068)
![image](https://github.com/user-attachments/assets/66632f45-7e7a-479c-ad65-b2c83597272c)
![image](https://github.com/user-attachments/assets/f3a9d1de-0b24-4881-a0fb-5ef5d7021a3f)

Sucede que de repente no funciona el microcliente, por la consola no sale ningún error pero al completar la url http://localhost:4200 con la dirección /registrar-contrato, simplemente no carga.

Se hizo una exhaustiva revisión de todos los posibles factores que pudieran afectar, sin embargo no se tuvo éxito, y dicho error impide continuar con la tarea con normalidad.

Como sospecha se tiene que puede haber una incompatibilidad con los componentes Standalone, sin embargo no se pudo encontrar una solución a esto.

**Comment by Lau2ri** [comment]
Se realizaron una serie de cambios, principalmente se quitó el Standalone a todos los componentes que lo tenían y se hicieron las modificaciones necesarias para que funcionaran de nuevo con el cambio.

Se logró llegar a un punto en el que ya la ventana carga con normalidad, pero al darle inspeccionar elemento, en la consola se encuentra el siguiente error con respecto a la conexión con parametros_crud:

![image](https://github.com/user-attachments/assets/3ce31d3f-a5f7-4850-ac61-475549acc280)

**Comment by Lau2ri** [comment]
Se logra arreglar el error cambiando el Endpoint y ya se muestra un correcto funcionamiento:

<img src="https://github.com/user-attachments/assets/59e981a4-2ce7-4af5-959f-fd2df1748790" width=400>

Y se procede a añadir todos los identificadores de los registros necesitados en primera instancia como variables de entorno.

**Comment by edwargl7** [comment]
Se observa una refactorización del código realizada en búsqueda de encontrar el fallo en el consumo de _parametros_crud_, al igual que la integración con tipo de compromiso empleando variables de entorno, y la implementación del tipo de contrato planteando el uso de la variable del tipo de compromiso elegido. Cuenta con lo requerido para esta primera etapa, y dado que al final del sprint se logró encontrar una solución para el consumo del API se plantea la segunda parte de integración.
