### ISSUE TITLE
Implementación endpoint consulta de número de disponibilidad por vigencia y unidad ejecutora - micromid sicapital

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#77]
Se requiere realizar el desarrollo del endpoint de consulta de lista de números de disponibilidad por vigencia y unidad ejecutora requeridos para la selección de CDP en el microcliente requerido como se observa en la siguiente imagen: 

![image](https://github.com/user-attachments/assets/7ef4949e-a13d-4cef-befe-5971467dd440)

Tener presente el formato de respuesta de los endpoints.
![image](https://github.com/user-attachments/assets/4ffc0bb0-2e75-49ff-8321-4a098d2f0231)

**Sub Tareas**

- [x] Implementación del nuevo endpoint siguiendo las especificaciones técnicas. 
- [x] Pruebas funcionales del correcto funcionamiento del endpoint.
- [x] Implementar pruebas de integración endpoint de consulta de lista de números de disponibilidad por vigencia y unidad ejecutora.

**Escenarios de pruebas**
- [x] Prueba consulta de números de disponibilidad al servicio Mock para validar el correcto funcionamiento.
- [x] Prueba de consulta de números de disponibilidad al servicio Mock para validar consulta no encontrado.
- [x] Prueba de consulta de números de disponibilidad al servicio Mock para validar consulta sin respuesta de la fuente de información (petición no respondida).

**Criterios de aceptación**

- [x] Implementación del nuevo endpoint siguiendo las especificaciones técnicas y el formato de respuesta.
- [x] Pruebas de integración implementadas.

**Requerimientos**

- Depende de la creación del endpoint con apoyo del arquitecto.

**Especificaciones técnicas**

1. Repositorio de este nuevo endpoint [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid).
2. El API debe cumplir con los siguientes lineamientos:
> a. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
> b. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
> c. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/40d6f40d-86f2-49e5-9e60-fc8d740749e0)
3. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang.

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Ajustado el endpoint con el arquitecto y compartido por interno para el desarrollo.

**Comment by mau-oati** [comment]
Respuesta del Endpoint

![Image](https://github.com/user-attachments/assets/180151ae-b93e-4674-9c3a-cfef1078ea0e)

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/beb4fdab-0dd2-4d4f-b996-54b659e1e370)

**Comment by edwargl7** [comment]
Buen trabajo, agregar más detalle en la descripción de los controladores de este microservicio mid.

- Este endpoint es de consulta de la información de los CDP filtrando por vigencia, número de disponibilidad y unidad ejecutora.
![image](https://github.com/user-attachments/assets/0451f472-3a44-41b9-82a1-602f1438efc9)
- Este endpoint lista la información del número de disponibilidad filtrando por vigencia y unidad ejecutora.
![image](https://github.com/user-attachments/assets/37a0ff57-0d63-4fa0-9477-e56ac5a4f12c)

**Comment by mau-oati** [comment]
Se revisa la acualización de nombres y pruebas para ser más claras.

**Comment by edwargl7** [comment]
Se deben ajustar los nombres de los endpoints siguiendo los lineamientos Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)

**Comment by edwargl7** [comment]
Buen trabajo se resuelve el PR, pendiente realizar el ajuste mencionado.
