### ISSUE TITLE
Ajuste modelo de datos cláusulas y parágrafos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#78]
Se requiere realizar el ajuste del modelo de datos de Cláusulas y parágrafos requerido para la creación del microservicio CRUD que se encargue del almacenamiento de la parametrización de cláusulas que puede existir en cada contrato. Se debe tomar como partida el último modelo que contempla estas tablas en la Issue https://github.com/udistrital/argo_documentacion/issues/100.

**Sub Tareas**

- [x] Se debe contemplar una tabla para plantillas de cláusulas, las cuales serán creadas por tipo de contrato según sea requerido.
- [x] Dado que se desea permitir que el usuario para un contrato específico pueda reordenar las cláusulas y parágrafos es importante tener un campo que almacene este orden tanto en la plantilla como en el registro final.
- [x] Las cláusulas y parágrafos pueden modificarse para un contrato en específico (remover/adicionar cláusula o parágrafo).
- [x] Evaluar el tipo de base de datos para este modelo.

**Criterios de aceptación**

- [ ] Modelo de datos para gestión de cláusulas y parágrafos.

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
1. Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)
2. Lineamientos [Modelos de Datos en Mongo](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/lineamientos_mongo.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
## Primera propuesta
Se propone ajustar el modelo creando un sistema de plantillas por tipo de contrato, permitir reordenar cláusulas y parágrafos, y dar flexibilidad para modificarlos en contratos específicos.

Se añadirían dos nuevas tablas: una para las plantillas generales y otra para las cláusulas de cada plantilla. Las tablas existentes de cláusulas y parágrafos se actualizarían para incluir un campo de orden y uno que indique si se han modificado.

Con estos cambios, se podría manejar plantillas por tipo de contrato, reordenar fácilmente las cláusulas y parágrafos, y hacer modificaciones específicas para cada contrato según sea necesario.

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/87ea8d3e-1de1-475b-a504-335e685ae264)
![image](https://github.com/user-attachments/assets/eaa1d6f5-efcb-492d-8aae-760fcbdf73e7)
![image](https://github.com/user-attachments/assets/a0efb0cb-22db-40fe-a241-ec74faf0c8b8)

**Comment by Lau2ri** [comment]
## Modelo propuesto:
![image](https://github.com/user-attachments/assets/d14a6a36-c18f-4aec-90cd-4a66d732b687)
### Explicación de los cambios:
- Se añadió la tabla `plantilla_clausulas` para almacenar las plantillas por tipo de contrato.
- Se creó la tabla `clausula_especifica_plantilla` para almacenar las cláusulas específicas de cada plantilla.
- Se agregó el campo **_orden_** en `clausula` y `paragrafo` para permitir el reordenamiento.
- Se añadió el campo **_modificado_** en `clausula` y `paragrafo` para indicar si se han modificado respecto a la plantilla original.

**Comment by edwargl7** [comment]
Se realiza la revisión inicial, y se aborda parte de la sesión del daily para entre el equipo realizar la revisión de ajustes al modelo de datos agregando versionado. Este modelo de datos no existe actualmente en ARGO, por lo tanto, se revisa el impacto en la migración.
En la revisión particparon @Lau2ri @mau-oati y @cjgonzalezp.
Se requiere complementar los ajustes al modelo en el siguiente sprint en una sesión que se pueda participar el equipo completo.

Resultado de la sesión:
- Se plantea la posibilidad de eliminar la tabla clausula_especifica_plantilla.
- Agregar versionado en la tabla plantilla_clausula, y la referencia del tipo_contrato_id.
- Posiblemente se almacene tanto la plantilla como el registro de cada contrato en las mismas tablas de cláusula y parágrafo.

Ejemplo de posibles registros en las tablas.
```JSON

# Plantilla_clausula
{
    "_id": "",
    "nombre": "Plantilla CPS",
    "descripción": "Plantilla CPS",
    "clausulas": ["qweqeqwe", "asqwea"],
    "contrato_general_id": "iuyuyuyutyut",
    "version": 1,
    "tipo_contrato_id": 344
}

# Clausula_especifica
{
    "_id": "",
    "nombre": "Plantilla CPS",
    "descripción": "Plantilla CPS",
    "clausulas": ["qweqeqwe", "asqwea"],
    "contrato_general_id": "iuyuyuyutyut",
    "version": 1,
    "tipo_contrato_id": 344
}


# Clausula
{
    "_id": "qweqeqwe",
    "nombre": "Objeto contrato",
    "descripción": "{objeto_contrato}",
    "orden": 1,
    "activo": true,
    "fechas": "YYYY-MM-DD"
}
{
    "_id": "asqwea",
    "nombre": "Actividades",
    "descripción": "{objeto_contrato}",
    "orden": 2,
    "activo": true,
    "fechas": "YYYY-MM-DD"
}
```
