### ISSUE TITLE
Pruebas de integración microservicio MID de Ágora - Proveedores

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#79]
Se requiere realizar la implementación de pruebas unitarias los endpoints desarrollados en la Issue #74 de consulta de información de los proveedores, representante legal y Health Check.

**Sub Tareas**

- [x] Implementar pruebas endpoint de consulta de proveedor por documento de identidad.
- [x] Implementar pruebas endpoint de consulta de representante legal por id del proveedor (caso de persona jurídica).
- [x] Implementar pruebas endpoint Health Check.

**Escenarios de pruebas**
- [x] Prueba consulta de proveedores al servicio Mock para validar el correcto funcionamiento.
- [x] Prueba de consulta de proveedores al servicio Mock para validar consulta proveedor no encontrado.
- [x] Prueba de consulta de proveedores al servicio Mock para validar consulta sin respuesta de la fuente de información (petición no respondida).
- [x] Prueba consulta representante legal al servicio Mock para validar el correcto funcionamiento.
- [x] Prueba consulta representante legal al servicio Mock para validar consulta proveedor no encontrado.
- [x] Prueba consulta representante legal al servicio Mock para validar consulta sin respuesta de la fuente de información (petición no respondida).
- [x] Prueba Health Check.
- [x] Resultado del coverage de las pruebas implementadas.
- [x] Actualización del README agregando la sección de _Ejecución de pruebas_.

**Criterios de aceptación**

- [x] Escenarios mínimo de pruebas cubierto, se pueden agregar pruebas unitarias adicionales que sean identificadas.

**Requerimientos**

- Completar la Issue #74 

**Material de apoyo**
- Pruebas implementadas en la Issue #71.

**Especificaciones técnicas**

1. Repositorio de este nuevo microservicio [proveedores_mid](https://github.com/udistrital/proveedores_mid).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Terminar de revisar por favor los nuevos [lineamientos de Nestjs](https://github.com/udistrital/lineamientos_oas/tree/master?tab=readme-ov-file#6-apis-nestjs-new-)

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/973c8fa4-19be-406e-9832-3383e98540e5" width="550" />

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/778fbd7c-697a-47ac-8968-507072ab2703" width="400" />

**Comment by edwargl7** [comment]
Buena implementación de pruebas, muy útil este desarrollo para complementar los escenarios de pruebas de integración en los lineamientos. Buen coverage cubierto con las pruebas implementadas.
