### ISSUE TITLE
Integración de parametros_crud con el microcliente de gestión contractual - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#81]
Se requiere continuar con la integración del microservicio [parametros_crud](https://github.com/udistrital/parametros_crud) con el microcliente de [gestión contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) en cada uno de los campos paramétricos del formulario de registro de contrato. Se requiere continuar con la integración iniciada en la Issue #76.

**Sub Tareas**

- [x] Implementación integración con el microservicio [parametros_crud](https://github.com/udistrital/parametros_crud).
- [x] Implementación de integración en los selectores respectivos relacionado al registro de parámetros trabajado en la Issue #75, empleando variables de entorno para cada identificador que agrupa las opciones de cada selector.
- [x] Pruebas de la correcta integración de parámetros en el microcliente, contemplado los selectores que cambian dependiendo de la selección de otro selector. Por ejemplo: Tipo de compromiso y Tipo de contrato.

**Escenarios de pruebas**
- [x] Prueba correcta visualización de opciones de Tipo de Compromiso.
- [x] Prueba correcta visualización de opciones de Tipo de Contrato al seleccionar _Orden_ como Tipo de Compromiso.
- [x] Prueba visualización _Aplica Póliza_ al seleccionar _Orden_ como Tipo de Compromiso.
- [x] Prueba correcta visualización de opciones de Tipo de Contrato al seleccionar _Contrato_ como Tipo de Compromiso.
- [x] Prueba correcta visualización de opciones de Tipo de Contrato al seleccionar _Convenio_ como Tipo de Compromiso.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Arrendamiento_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Arrendamiento_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Compra-Venta_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato Interadministrativo_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Comisión de Estudios_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Obra_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Suministro_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Prestación de Servicios_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Perfil del Contratista al seleccionar _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Consultoría_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Tipología Específica al seleccionar _Contrato de Mutuo_ como Tipo de Contrato.
- [x] Prueba correcta visualización de opciones de Régimen de contratación.
- [x] Prueba correcta visualización de opciones de Modalidad de Selección.
- [x] Prueba correcta visualización de opciones de Procedimiento.
- [x] Prueba correcta visualización de opciones de Unidad de ejecución.

**Criterios de aceptación**

- [x] Documentación de las pruebas realizadas con la integración de parámetros crud.

**Requerimientos**

No aplica

**Material de apoyo**
- [Mockup registro de contrato](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=rzyr4B).
- Paso de información del contrato con los selectores a integrar con parametros_crud y el comportamiento de algunos selectores según la selección:
![image](https://github.com/user-attachments/assets/b031843f-6eed-4e46-a4d7-9f161fc14ccf)
![image](https://github.com/user-attachments/assets/b62a7b14-47f2-498e-89cf-51c55750a299)
- Lista en csv de parámetros registrados en parametros_crud (ver modelo de datos/listado_parametros_argo_v2_21_07_2024.csv) para una visualización más fácil de los ids de tipo parámetro, parámetro padre y parámetro.

**Especificaciones técnicas**
1. Repositorio microcliente de [gestión contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).
2. Repositorio microservicio [parametros_crud](https://github.com/udistrital/parametros_crud).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
3. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
4. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se da comienzo a la tarea.

**Comment by Lau2ri** [comment]
Se crean las demás funciones necesarias para cargar los datos desde parametros_crud con sus respectivos filtros, además de su llamado en el HTML para que se pueda visualizar correctamente:

![image](https://github.com/user-attachments/assets/671ff61e-a3ec-472b-b0bc-935121db5deb)

Los datos de las funciones generales ya se muestran correctamente en la interfaz.

Sin embargo queda pendiente el diseño de la lógica para el llamado de los datos que dependen del Id del tipo de compromiso y tipo de contrato.

**Comment by Lau2ri** [comment]
## Video de pruebas:

https://github.com/user-attachments/assets/fccd404e-3caa-4c44-8899-ae2830706e9e

![Image](https://github.com/user-attachments/assets/64c9860b-4fb2-428f-b208-2bdcd10725d1)

## Ajustes faltantes
Como se puede observar en el video, queda por ajustar los campos de Tipología Específica y de Régimen de Contratación que quedan resaltados en amarillo, esto es porque por alguna razón a pesar de mostrar las opciones correctamente, no se seleccionan dichas opciones. 

Además, falta por ajustar la búsqueda de los parámetros de Unidad de Ejecución, debido a que se muestran todos los que existen y sólo se necesitan 3 de estos: Dias, Meses y Años.

**Comment by Lau2ri** [comment]
### Se ha terminado la tarea con todos los escenarios de pruebas funcionando correctamente:
## Convenio
https://github.com/user-attachments/assets/ee9f055d-ae3c-4266-90a3-8dafc664c6c3

![Image](https://github.com/user-attachments/assets/d8ac4ece-d7b2-44d8-8426-49dd79b00c50)

## Orden
https://github.com/user-attachments/assets/34ab1043-4f43-466a-aa06-a931ec27ee3d

![Image](https://github.com/user-attachments/assets/3f356a8a-89c2-43bd-8c42-d7b93d14eb97)

## Contrato
https://github.com/user-attachments/assets/9a4481f1-3a6c-495c-b8f1-211d7d5cca30

![Image](https://github.com/user-attachments/assets/92dd5ca0-db21-43f8-a176-9f639c54ad0f)

**Comment by edwargl7** [comment]
Buen trabajo, cumple con las pruebas funcionales. Se puede realizar el PR y las siguientes observaciones se trabajaran en una siguiente iteración junto con otros desarrollos.

**Observaciones**
- Se está realizando la consulta a _perfil del contratista_ al seleccionar tipo de compromiso _Orden_, esta consulta solo debe realizarse con tipo de compromiso _Contrato_ y tipo de contrato _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_.
![image](https://github.com/user-attachments/assets/b05415ea-68f4-45dd-87e8-eb2b580e96db)
- Mejora requerida, el campo _Fecha Suscripción Estudios y Documentos Previos_ solo debe mostrarse cuando se seleccione tipo de compromiso _Contrato_ y tipo de contrato _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_, igual que el campo _perfil del contratista_.
- Se debe confirmar con el analista @cjgonzalezp si el campo _Plazo Ejecución_ debe ser numérico o pueden digitar cualquier valor (actualmente el sistema actual tiene el mismo comportamiento).
![image](https://github.com/user-attachments/assets/eebf7472-20a8-4759-88ac-7babcb8ea79b)

**Comment by edwargl7** [comment]
Se aclara con @cjgonzalezp que el campo _Plazo Ejecución_ debe ser de tipo numérico.
