### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con el cliente para mockup consulta contrato, póliza y acta de inicio

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#85]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente para mockup consulta contrato, póliza y acta de inicio

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Hoy 24 de julio de 2024 se contacta con el cliente, pendiente por confirmar agenda por parte del cliente para concertar reunión.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se concreta reunión con el cliente para el día jueves 01 de agosto de 2024 hora: 10:00 am sede Paiba.


Cordial saludo.

**Comment by cjgonzalezp** [comment]
Buen día,

Se posterga reunión programada con el cliente, para el día jueves 01 de agosto de 2024 hora 2:00 pm por solicitud del cliente.

Saludos

**Comment by jcmurilloa** [comment]
Buen día @cjgonzalezp, se realizó la reunión?

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con cliente según lo establecido el día 01 de agosto de 2024 hora: 3:00 pm a 4:30 pm. Pendiente terminar de levantar acta de reunión y recolección de firmas.

Saludos.

**Comment by jcmurilloa** [comment]
Buen día @cjgonzalezp, te recomiendo no dejar pasar varios días sin la proyección del acta, esto puede llegar a sopesar su contenido, puesto que el paso de los días puede llevar a otro tipo de interpretaciones de los temas tratados en el encuentro, traduciendose en mayor tiempo de dedicación a la escucha de la respectiva grabación.

**Comment by cjgonzalezp** [comment]
Buen día,

Se proyecta acta de reunión No 103/2024 Argo - Levantamiento de requerimientos. Pendiente recolección de firmas de los participantes.

**Enlace documento cargado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo4dvlEBnrxHqXWAgtJZQmUBR1zCMGrGE1p1qsDJ3EI_1A?e=65I7cn


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se recolectan firmas de los usuarios presentes en la reunión, y se da por finalizada la issue #85.

**Enlace documento cargado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo4dvlEBnrxHqXWAgtJZQmUBR1zCMGrGE1p1qsDJ3EI_1A?e=9Vaupi


Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp
