### ISSUE TITLE
Diseñar mockup de vista consulta póliza de módulo de gestión contractual

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#87]
Se requiere realizar el diseño de vista consulta póliza de módulo de gestión contractual

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipos SoS.
- [x] Realizar ajustes según comentarios del equipo.
- [x] Presentar al cliente el mockup definitivo.

**Criterios de aceptación**

- [x] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño de mockup del submódulo consultar póliza.

**Enlace del diseño mockup del módulo consultar póliza**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ErwobuGGQsRLjDJofLUmDR8BXygCKwMTXUMIj1ci_oJlaA?e=S8Hewc


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, pendiente la culminación del diseño para repasar en el la proxima sesión Review SoS.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente generar los cambios sugeridos para aprobación por parte del cliente en ls sesión del 31/07.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes al mockup según cambios sugeridos por el equipo SoS. Pendiente presentar diseño al cliente el día 31 de julio.

**Mockup Módulo Pólizas >> Consultar Póliza** 
![Image](https://github.com/user-attachments/assets/2977d4e4-52c6-4682-ba1e-02601a32a571)

**Enlace archivo cargado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EcR5jmYvZYdOuI9_VE5SBOYBqAyiXFW931-1g2aRhCYFug?e=wYhOr0


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta diseño mockup submódulo consulta de póliza al cliente y se recibe aprobación para su desarrollo en el sistema ARGO V2.

**Enlace archivo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuPCWLOJsQFPpAGekdxLO-oBAxm2b5LnyKpkR6k0k7ZUyQ?e=SFnVCb

**Acta de reunión No. 103/2024 - Aprobación mockup submódulo consulta de póliza**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo4dvlEBnrxHqXWAgtJZQmUBR1zCMGrGE1p1qsDJ3EI_1A?e=BHQaoI


Saludos.

**Comment by jcmurilloa** [comment]
Diseños aprobados por equipo SoS y cliente, muy buen trabajo @cjgonzalezp
