### ISSUE TITLE
Reestructuración del Formulario de Registro de Contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#88]
Se requiere reorganizar los pasos del formulario de registro de contrato, para asegurar que la información se recolecte de manera lógica y secuencial basado en el [Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5). En este se incluyen secciones nuevas necesarias para un registro completo.

_Nuevo orden de los pasos:_
1. Información de contrato
2. Información Presupuestal
3. Información Solicitante y Supervisor
4. Información contratista
5. Obligaciones de Contrato
6. Especificaciones Técnicas
7. Garantía y Mecanismos de Cobertura del Riesgo
8. Cláusulas y Parágrafos

### **Subtareas**

**_- Organización del Formulario:_**
- [x] Reorganizar el formulario con el nuevo orden especificado.
- [x] Revisión nombre con numeración de los FormGroup (firstFormGroup, secondFormGroup, ...), dado que para tipo de contrato de arrendamiento se requiere un paso adicional. Estos nombres ayudan a identificar en el componente de registro-contracto, pero en cada componente de cada paso puede que no tengan la misma enumeración como actualmente se contemplaba en el Mockup.

**_- Paso de Información Presupuestal:_**
- [x] Agregar _Checkbox_ al paso de **Información Presupuestal** para reversar saldos.
![image](https://github.com/user-attachments/assets/81a09dec-cf4c-4525-9304-a024f130ff34)
- [x] Agregar border a las dos secciones de este paso. Se puede trabajar usando [Card de Angular Material](https://material.angular.io/components/card/examples)
![image](https://github.com/user-attachments/assets/3407ac4d-7265-4b0e-bfa7-4418d1201c6b)

**_- Paso de Obligaciones de Contrato:_**
- [x] Reorganización orden de los campos del paso y eliminación del campo _Condiciones_.
- [x] Agregar border a la sección completa del paso que agrupe los 3 campos.
- [x] Remover botón _Descargar_ (llevar esta implementación al último paso _Cláusulas y Parágrafos_).
![image](https://github.com/user-attachments/assets/07c06034-2f12-4eaf-ba7b-34d44751ef37)

**_- Estilos del Formulario:_**
- [x] Agregar border a la sección del paso _Información Solicitante y Supervisor_.
- [x] Agregar border a la sección del paso _Información Contratista_.
- [x] Agregar border a la sección del paso _Garantía y Mecanismos de Cobertura del Riesgo_.

### **Criterios de aceptación**

- [x] Formulario con todos los pasos en el orden requerido.
- [x] Pasos 1, 2, 3, 4, 5 y 7 cuenten con los campos, bordes y botones solicitados y detallados en el Mockup.

### **Requerimientos**

No aplica

### **Material de apoyo**
- [Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5)
- [Angular Material - Card](https://material.angular.io/components/card/overview)

### **Especificaciones técnicas**
- Repositorio de microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).

### **Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

### **Lineamientos Microclientes**
- [Arquitectura de aplicaciones - Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realiza la reestructuración de los pasos del formulario, agregando el sexto paso de Especificaciones Técnicas y el octavo paso de Cláusulas y Parágrafos.

![Captura de pantalla 2024-07-30 220244](https://github.com/user-attachments/assets/1c420742-12b9-4c5c-bc8c-fb5ed10b46a7)

Además se hace la respectiva organización de los nombres de FormGroup de cada paso en el componente de registro-contracto y directamente en cada uno de los pasos se reemplazo este nombre (firstFormGroup, secondFormGroup, ...), por simplemente "form" para hacerlo más cómodo.

**Comment by Lau2ri** [comment]
Se realizan todos los ajustes solicitados, a continuación se muestran los resultados:

https://github.com/user-attachments/assets/94b6b943-2174-45ca-8f8d-ce24f50649c2

![Image](https://github.com/user-attachments/assets/b60918a9-2be2-4b2e-9e5c-9d84f665380a)

Para los bordes y sus títulos se realizó el ajuste directamente en los estilos del root para poder tenerlos de forma global en el sistema.

**Comment by edwargl7** [comment]
Desarrollo completado correctamente, buen enfoque de estilos aplicados desde el root. Se recomienda separar estos estilos en otro archivo css similar a los aplicados en [sga cliente root](https://github.com/udistrital/sga_cliente_root/tree/develop/src/assets/styles).
![image](https://github.com/user-attachments/assets/2ec09027-f1f0-4966-92a1-4404adad3a3b)

**Comment by Lau2ri** [comment]
Se realiza la separación de los estilos en otro archivo como se solicitó, y se comprobó que siguen funcionando los estilos correctamente:

<img src="https://github.com/user-attachments/assets/e44d4480-fbb8-4329-b199-07eaff62ab00" width=500>

**Comment by edwargl7** [comment]
Se confirmar los ajustes solicitados y se realiza el PR. Muy buen trabajo.
