### ISSUE TITLE
Implementación pasos Especificaciones Técnicas y Cláusulas y Parágrafos del Formulario de Registro de Contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#89]
Se requiere implementar los pasos nuevos _Especificaciones Técnicas_ y _Cláusulas y Parágrafos_ en el formulario de registro de contrato basado en el [Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5).

_Orden de los pasos:_
1. Información de contrato
2. Información Presupuestal
3. Información Solicitante y Supervisor
4. Información contratista
5. Obligaciones de Contrato
6. **Especificaciones Técnicas**
7. Garantía y Mecanismos de Cobertura del Riesgo
8. **Cláusulas y Parágrafos**

**Sub Tareas**
- [x] Agregar paso _Especificaciones Técnicas_.
![image](https://github.com/user-attachments/assets/db4be806-3656-488f-bc43-b7e90921bd79)
- [x] Agregar paso _Cláusulas y Parágrafos_
![image](https://github.com/user-attachments/assets/b2b09f89-3f95-4475-b8bb-7ac287948ed4)

**Criterios de aceptación**

- [x] Formulario con todos los pasos en el orden requerido.
- [x] Pasos 6 y 8 cuenten con los campos, bordes y botones solicitados y detallados en el Mockup.

**Requerimientos**

No aplica

**Material de apoyo**
- [Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5)

**Especificaciones técnicas**
- Repositorio de microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- [Arquitectura de aplicaciones - Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
## Se añade el Paso 6 del formulario llamado Especificaciones Técnicas.
💡 Respecto a este paso se tiene la duda al respecto de la tabla debido a que por el mockup no me queda claro si la tabla sólo muestra datos, o es para ingresar textos, añadir filas, etc.

![Captura de pantalla 2024-08-01 214216](https://github.com/user-attachments/assets/24e5d474-13eb-4fb8-acdf-7cb5f9d4a33a)

**Comment by edwargl7** [comment]
Se debe revisar con más detalle el funcionamiento del paso 6, y se agrega la siguiente imagen de complemento para el paso de cláusulas y parágrafos, se detallará la posibilidad de agregar parágrafos en la creación de cláusulas nuevas.
![image](https://github.com/user-attachments/assets/e48575c2-3130-4f13-b9ff-c285c9ee8527)

**Comment by Lau2ri** [comment]
## Se añade la estructura lógica del paso 8 del formulario "Cláusulas y Parágrafos"
Sin embargo, queda pendiente ajustar el diseño de la ventana emergente para añadir los parágrafos que, aunque funciona, no está acorde con el mockup presentado.

https://github.com/user-attachments/assets/6e31eefc-e4bd-43b4-a3cc-f5054e16b31a

![Image](https://github.com/user-attachments/assets/ceb92032-2f83-49d0-89b1-f7cc2626be0f)

**Comment by edwargl7** [comment]
Muy buen desarrollo, pendiente realizar le PR.

**Comment by edwargl7** [comment]
Resuelto el PR. Finalizada por completa la Issue.
