### ISSUE TITLE
División del Cliente Argo v1 en Microfrontends - Microcliente Gestión contractual PT1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#9]
Se requiere realizar la planeación y estructuración para dividir el sistema Argo v1 en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI. 

Esta tarea contempla el módulo de Gestión contractual (creación, edición y suscripción sin incluir pólizas ni acta de inicio).

Tener presente que para la versión 2 de ARGO se debe tener presente agregar más de un supervisor.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

- [x] Análisis del sistema Argo v1 microcliente de Gestión Contractual
- [x] Crear diagrama de componentes de la arquitectura para Argo v2.
- [x] Listado de funcionalidades de cada microcliente basado en las funciones conocidas en el manual de usuario revisado en las tareas realizadas en el Sprint 0.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de componentes con la división clara el sistema en múltiples microclientes.
- [x] Listado de funcionalidades que componen cada microcliente.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
### Primer borrador
Propuesta diagrama gestión contractual:

<img src="https://github.com/udistrital/argo_documentacion/assets/133523053/ced2ae20-6522-4aef-802e-89d40f615337" width="550" >

**Comment by edwargl7** [comment]
Buen día, agregar por favor el componente de suscripción múltiple. Muchas gracias.

**Comment by edwargl7** [comment]
Excelente trabajo, para el microcliente de **Gestión de elementos y servicios** la funcionalidad de consulta de contratos es de contratos no suscritos. No se observan más ajustes.

**Comment by Lau2ri** [comment]
Se modifica en el Módulo de Gestión Contractual, en la sección de Gestión de elementos y servicios, se cambia la consulta de contratos por vigencia a consulta de contratos no suscritos.

![Image](https://github.com/udistrital/argo_documentacion/assets/133523053/c47e5833-996a-45ed-a99f-d346267de962)

**Comment by edwargl7** [comment]
Muchas gracias. Se da por terminada la tarea.
