### ISSUE TITLE
Ajustes paso Información de Contrato del Formulario de Registro de Contrato

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#90]
Se requiere realizar ajustes al paso _Información de Contrato_ relacionados a la Issue #81.

**Sub Tareas**

- [x] Realizar solamente la consulta de _perfil del contratista_ en _parametros_crud_ al seleccionar el tipo de contrato _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_.
![image](https://github.com/user-attachments/assets/1e3c9ed1-52cf-4e4e-80c7-072f21d77323)
- [x] El campo _Fecha Suscripción Estudios y Documentos Previos_ solo debe mostrarse cuando se seleccione tipo de contrato _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_.
- [x] Implementar restricción de fechas futuras al campo _Fecha Suscripción Estudios y Documentos Previos_.
- [x] Implementar restricción de solamente permitir valores numéricos en el campo de _Plazo Ejecución_.

**Criterios de aceptación**

- [x] Visualización de los campos _perfil del contratista_ y _Fecha Suscripción Estudios y Documentos Previos_ solo cuando se seleccione el tipo de contrato _Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión_.
- [x] Restricción de fechas futuras al campo _Fecha Suscripción Estudios y Documentos Previos_.

**Requerimientos**

No aplica

**Material de apoyo**
- [Angular Material - Datepicker -Date validation](https://material.angular.io/components/datepicker/overview#date-validation)

**Especificaciones técnicas**
- Repositorio de microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- [Arquitectura de aplicaciones - Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Lau2ri** [comment]
Se realizaron todos los ajustes correctamente:

https://github.com/user-attachments/assets/2a80fa5d-0e7f-496f-af70-066dfba219df

![Image](https://github.com/user-attachments/assets/8677bcf7-96b3-4735-a08d-8be63f08dcc6)

**Comment by edwargl7** [comment]
Se confirma el correcto funcionamiento de los ajustes aplicados. Muy buen trabajo.
