### ISSUE TITLE
Integración de presupuesto contractual MID con el microcliente de gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#91]
Se requiere realizar la integración del microservicio [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid) con el microcliente de [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) en el paso de _Información presupuestal_ la sección de _Disponibilidades Presupuestales Asociadas_ basado en el [Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5).

**Subtareas**

- [x] Basado en los cambios realizados en proveedores_mid en la Issue #97 realizar el ajuste de la consulta, por el cambio del nombre del endpoint.
- [x] Implementación de la integración con el microservicio de presupuesto contractual endpoint de consulta de números de disponibilidad filtrando por vigencia y unidad ejecutora.
- [x] Implementación de la integración con el microservicio de presupuesto contractual endpoint de consulta del detalle de la disponibilidad presupuestal.
- [x] Pruebas funcionales de la consulta de números de disponibilidad.
- [x] Pruebas funcionales de la consulta del detalle de la disponibilidad presupuestal.

**Escenarios de pruebas**
- [x] Consulta exitosa de números de disponibilidad por vigencia y unidad ejecutora.
- [x] Consulta exitosa del detalle de la disponibilidad presupuestal seleccionada.

**Criterios de aceptación**

- [x] Documentación de las pruebas realizadas con la integración del endpoint de consulta presupuesto contractual. 

**Requerimientos**

No aplica

**Material de apoyo**
- Imagen Mockup paso de _Información Presupuestal_.
![image](https://github.com/user-attachments/assets/7141561e-8132-4ae6-b1c2-fb73f8dbe7fa)

**Especificaciones técnicas**
1. Repositorio de microservicio [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid).
2. Repositorio de microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- Arquitectura de aplicaciones - Microclientes (https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/8ac29257-8d11-48e8-9ef6-9bf9b6b9f9e6

**Comment by mau-oati** [comment]
https://github.com/user-attachments/assets/4dd52db0-9921-438b-82bb-3d2207616aed

**Comment by edwargl7** [comment]
Buen trabajo, pendiente el PR y confirmar con @mau-oati que no se pueda elegir nuevamente un número de disponibilidad escogido previamente.

**Comment by edwargl7** [comment]
Se resuelve el PR y se finaliza la Issue.
