### ISSUE TITLE
Integración de proveedores MID con el microcliente de gestión contractual - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#92]
Se requiere completar la integración del microservicio [proveedores_mid](https://github.com/udistrital/proveedores_mid) con el microcliente de [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) iniciada en la Issue #80.

**Sub Tareas**

- [x] Ajuste en los campos visualizados de información del contratista basado en la imagen del Mockup (se remueven unos campos de información del contratista como información bancaria y se agrega información del representante legal).
Se debe visualizar para persona natural de la siguiente manera
![image](https://github.com/user-attachments/assets/5ec6c382-4b50-4cc0-8602-0f1d01c5158b)
Y persona Jurídica:
![image](https://github.com/user-attachments/assets/bd9bcba8-f959-42e1-9ced-12caca1ebb48)
- [x] Pruebas funcionales de la consulta de un proveedor (persona natural).
- [x] Pruebas funcionales de la consulta de un proveedor (persona jurídica).

**Escenarios de pruebas**
- [x] Consulta exitosa de un proveedor persona natural. Con la correcta visualización de los datos (sin visualizar los campos de representante legal).
- [x] Consulta exitosa de un proveedor persona jurídica. Con la correcta visualización de los datos (visualizando los campos de representante legal).

**Criterios de aceptación**

- [x] Documentación de las pruebas realizadas con la integración del endpoint de consulta de proveedor.

**Requerimientos**

No aplica

**Material de apoyo**
- Imagen Mockup paso de información del contratista.
![image](https://github.com/user-attachments/assets/ebed8329-e34d-434a-aa7d-e13138772a21)

**Especificaciones técnicas**
1. Repositorio de microservicio [proveedores_mid](https://github.com/udistrital/proveedores_mid).
2. Repositorio de microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- Arquitectura de aplicaciones - Microclientes (https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
**Contratista Persona Natural:**

![Image](https://github.com/user-attachments/assets/639af6ef-4b14-4d47-87d4-ae717c25f2b5)

**Contratista Persona Juridica:**

![Image](https://github.com/user-attachments/assets/cbf78e88-8d95-4293-b88f-3634a8f59704)

**Comment by edwargl7** [comment]
Se valida el correcto funcionamiento. Adicional cuenta con mensaje de error al consultar y no obtener respuesta. Muy buen trabajo.
![image](https://github.com/user-attachments/assets/7a8aa488-7996-4de6-8a69-aa57329d92de)
