### ISSUE TITLE
Ajuste modelo de datos de Gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#93]
Se requiere realizar ajustes en el modelo de datos general del sistema ARGO v2 que aborda la información del módulo de registro del contrato basado en las sugerencias dadas por el equipo DBA y otros ajustes requeridos para almacenar de manera lógica la información nueva en el [Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5).

**Subtareas**

- [x] Actualizar nombre de las colecciones a singular (aplica para estado_contrato, estado).
- [x] Ajustar el tipo de dato de los campos vigencia y fecha_ejecucion_estado en colección estado_contrato.
- [x] Validar si es necesario mantener los campos fecha_creacion y fecha_modificacion en la colección estado por sugerencia de no usar estos campos en tablas de tipo paramétrica.
- [x] Ajustar el tipo de dato de los campos municipio_id, dependencia_id, ciudad_id y sede_id de la colección lugar_ejecucion.
- [x] Ajustar el tipo de dato de los campos numero_constancia, dependencia_solicitante_id, sede_solicitante_id, tema_gasto_inversion_id, medio_pago_id en la colección contrato_general.
- [x] Agregar el campo perfil_contratista (paso 1 del formulario).
- [x] Evaluar la separación del campo fecha de estudios previos en otra colección.
- [x] Agregar el tipo de convenio en la colección de convenio.
- [x] Actualizar la tabla de información CDP que almacene los campos vigencia cdp y número de disponibilidad.
- [x] Separar los campos de información presupuestal en otra colección sin incluir los que se almacenan el la colección CDP ni campos asociados al ordenador (paso 2).
- [x] Evaluar la separación de los datos del solicitante (dependencia y sede) en otra colección (paso 3).
- [x] Agregar tabla/colección de cláusulas y parágrafos (paso 8).
- [x] Agregar nota de campos que vienen de otras fuentes (campos de parametros_crud) y actualizar o remover los colores (el rojo se cubre con el * de campos requeridos, unificar o remover colores paramétricos).
- [x] Agregar colección de contrato arrendamiento que cubra la migración del sistema actual.
- [x] Remover del modelo general la tabla creada para almacenar los parámetros propios de ARGO dado que se va a seguir usando parametros_crud.

**Criterios de aceptación**

- [x] Nueva versión del modelo de datos.

**Requerimientos**

No aplica

**Material de apoyo**
- Modelo de datos presentado al equipo DBA (modelo propuesto).
![modelo_datos_argo](https://github.com/user-attachments/assets/3d132296-cf90-4412-8cb8-b9b5ff44831a).
- Modelo de datos sistema actual.
![udistrital - argo-modelo-datos](https://github.com/user-attachments/assets/11909810-d732-480d-8c6c-399e2c529a4a)
- Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Modelos de datos**
- Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se comienza la actualización del modelo en drawio siguiendo los lineamientos de la tarea, eliminando la tabla de parámetros propios que no va y re organizado y unificando las referencias (amarillas y moradas) de parámetros. 

WIP

**Comment by mau-oati** [comment]
<img src="https://github.com/user-attachments/assets/ad6e0b88-b2cd-4aed-86b3-2f828ea5a695" width="600" />

**Comment by mau-oati** [comment]
**Duda:** Los campos de parámetros crud son campos string en su totalidad? (perfil_contratista_id, medio_pago_id, etc)

**Comment by mau-oati** [comment]
- Se unifican los parámetros (todos los campos que usan parámetros crud están en **amarillo**.) 
- Se asignan los mismos tipos de campo que la base de datos ARGO V1 para mantener compatibilidad cuando se cree el script de migración.

![Image](https://github.com/user-attachments/assets/498a46a0-bfbc-445e-90b7-d00ec6f388fe)

**Comment by mau-oati** [comment]
Modelo Unificado (Borrador)



![Image](https://github.com/user-attachments/assets/250fd9e4-d9fe-488d-892c-cf0dd15402f0)

**Comment by mau-oati** [comment]
Se contin'ua el avance en las tablas nuevas que permitan compatibilidad con el modelo antiguo. WIP

**Comment by mau-oati** [comment]
![Image](https://github.com/user-attachments/assets/eb0433a1-b7c0-4731-b785-8009454946f1)

**Comment by mau-oati** [comment]
Core ARGO V2

![Image](https://github.com/user-attachments/assets/1539d080-5257-4c63-8f5a-c4f9a29354c7)

**Comment by edwargl7** [comment]
Muy buen trabajo, buena documentación de avances y muy buena ayuda para la presentación seguir manteniendo el modelo general y el core separados.

**Observaciones**
- Ajustes en contrato_arrendamiento
> - cambiar _plaza_administracion_ por _plazo_administracion_
- Ajustes en estado_contrato
>- Remover campo vigencia
>- Remover campo numero_contrato
>- Ajustar nombre campo de referencia de _contrato_general_ 
>- usuario_id cambiar tipo string a number 
- Ajustes en convenio
>- Ajustar nombre campo de referencia de _contrato_general_
>- Ajuste en el campo de nombre_convenio por solo nombre y cambiar tipo.
- Ajustes en contratista
>- Ajustar nombre campo de referencia de _contrato_general_ 
- Ajustes en cdp
>- Ajustar nombre campo de referencia de _contrato_general_

**Comment by edwargl7** [comment]
Ajuste tipo de datos de campos paramétricos de:
![image](https://github.com/user-attachments/assets/9bcf6c8b-638e-4789-8d36-46167438ad71)

**Comment by edwargl7** [comment]
Se trabajaran estos ajustes en una nueva Issue. Se finalizará esta Issue una vez finalizados los ajustes.

**Comment by edwargl7** [comment]
Se cubren los ajustes en la Issue #100
