### ISSUE TITLE
Construir el diseño de las vistas según el rol y el avance del flujo de aprobación Parte 1

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#95]
Se requiere construir el diseño de las vistas según el rol y el avance del flujo de aprobación Parte 1

**Sub Tareas**

- [x] Diseñar mockups con base en los requerimientos.
- [x] Presentar el mockup al equipos SoS.
- [x] Realizar ajustes según comentarios del equipo.
- [x] Presentar al cliente el mockup definitivo.

**Criterios de aceptación**

- [x] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño de aprobación contrato en el módulo de gestión contractual>>Contratos

**Diseño Flujo Aprobación Contrato - Rol Jefe Oficina de Contratación**
![Image](https://github.com/user-attachments/assets/51ec12e3-61e9-4cb9-8395-8608345dee9c)

**Diseño Flujo Aprobación Contrato - Rol Ordenador del Gasto**
![Image](https://github.com/user-attachments/assets/4b323ad8-2b17-4144-87eb-aad4c4cde6ef)


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp, por favor tener en cuenta los comentarios realizados en la sesión SoS y exponer al cliente para su aprobación.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los ajustes sugeridos por el equipo SoS, se presentan los mockups al cliente y se recibe aprobación para el desarrollo en el sistema ARGO V2

**Diseño Flujo Aprobación Contrato - Rol Jefe Oficina de Contratación**
![Image](https://github.com/user-attachments/assets/37be8d7d-d39e-428a-9a7e-1c9434cc7034)

**Diseño Flujo Aprobación Contrato - Rol Ordenador del Gasto**
![Image](https://github.com/user-attachments/assets/973a4494-0396-47b6-972c-514e7b796d42)

**Enlace archivos guardados en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtRHNMKONftNgfh2dqvpRgYByaohlPba34JGRwWKxxRaeA?e=ebquVI

**Acta de reunión No 103/2024 aprobación mockups desarrollados en la issue #95**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo4dvlEBnrxHqXWAgtJZQmUBR1zCMGrGE1p1qsDJ3EI_1A?e=u6GZWg


Saludos.

**Comment by jcmurilloa** [comment]
Muy buenos diseños @cjgonzalezp !
