### ISSUE TITLE
Construir Diagrama de flujo general del proceso de contratación del Idexud

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/argo_documentacion#96]
Se requiere realizar la construcción del Diagrama de flujo general del proceso de contratación del Idexud

**Sub Tareas**

- [x] Generar la investigación e inmersión en el negcio con el cliente.
- [x] Construir diagrama de flujo según información.
- [x] Presentar diagrama de flujo a equipo SoS.
- [x] Realizar las modificaciones según observaciones

**Criterios de aceptación**

- [x] Diagrama de flujo definido
- [x] Diseño documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se solicita nuevamente documentación al cliente Jheshua Jared de la oficina de extensión. Pendiente envío de documentación para proyectar diagrama de flujo.


Saludos.

**Comment by jcmurilloa** [comment]
Por favor solicitar la información al correo institucional del IDEXUD, mediante cómputo.

**Comment by cjgonzalezp** [comment]
Buen día,

Según revisión previa con el cliente (Oficina de Extensión - Idexud) se construye diagrama inicial del flujo general del proceso de contratación. Sin embargo, el cliente revisará el diagrama a detalle para revisar si existen ajustes adicionales.

![Image](https://github.com/user-attachments/assets/b54d3b8e-2f20-4660-9f7e-40ccb17df880)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto ARGO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Esgeh5qXPhBPupCkX3BoGtsBmE0mu-ryfH57TuNoDgMheA?e=cUUgWc


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp, en el entendido, es posible anexar esta unidad administrativa a ARGO V2.
