### ISSUE TITLE
Ajustes endpoint de proveedor mid y presupuesto contractual mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#97]
Se requiere realizar ajustes en los nombres de los endpoint de [proveedores_mid](https://github.com/udistrital/proveedores_mid) y [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid) siguiendo los lineamientos de _Definición de endpoints para APIs REST_.

**Sub Tareas**

- [x] Ajuste endpoint contratista de [proveedores_mid](https://github.com/udistrital/proveedores_mid).
- [x] Ajuste endpoint de cdps de [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid).
- [x] Ajuste endpoint de número de disponibilidad de [presupuesto_contractual_mid](https://github.com/udistrital/presupuesto_contractual_mid).
- [x] Ajuste pruebas de integración.

**Escenarios de pruebas**
- [x] Pruebas funcionales de los endpoints ajustados.

**Criterios de aceptación**

- [x] Ajustes de los endpoints siguiendo los lineamientos.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
- Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
- Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
-  Guiarse en la construcción del microservicio basado en los lineamientos de [APIS NestJS ](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#6-apis-nestjs-new-)<img src="https://docs.nestjs.com/assets/logo-small.svg" alt="NestJS Icon" width="25"/>
- Guiarse en la construcción del microservicio basado en los lineamientos de [API FLASK :snake:](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#7-api-flask-new-snake)
- Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
- [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mau-oati** [comment]
Se ajustan los nombres de los endpoints a prural. Ajora se procede a ajustar pruebas de intregración con el micro frontend.

**Comment by mau-oati** [comment]
**Prueba proveedores_mid**

```json
// http://localhost:3000/contratistas?id=111111111

{
  "Success": true,
  "Status": 200,
  "Message": "Proveedor Encontrado",
  "Data": {
    "proveedor": {
      "id_proveedor": "21339",
      "ciudad_expedicion_documento": "Kabul",
      "id_ciudad_contacto": "3060",
      "direccion": "AVIAL 1 1 1  ",
      "numero_documento": "111111111",
      "nombre_estado": "ACTIVO",
      "numero_cuenta_bancaria": "11111111",
      "id_ciudad_expedicion_documento": "45",
      "id_estado": "1",
      "nombre_completo_proveedor": "1 1 1 1",
      "ciudad_contacto": "Puerto Narino",
      "web": "",
      "fecha_registro": "2023-06-30 - 12:15:21 PM",
      "correo": "sasa@gmail.com",
      "id_entidad_bancaria": "0",
      "tipo_persona": "NATURAL",
      "tipo_cuenta_bancaria": "AHORROS",
      "fecha_ultima_modificacion": "2023-06-30 - 12:15:21 PM"
    }
  }
}
```

**Comment by mau-oati** [comment]
Prueba Frontend, endpoint actualizado

![Image](https://github.com/user-attachments/assets/7600d6d1-f723-4cc2-a425-265ffe89f090)

**Comment by mau-oati** [comment]
Prueba Proveedor_contractual

```json
// http://localhost:3000/cdps/lista?vigencia=2024&unidadEjecutora=02

{
  "Success": true,
  "Status": 200,
  "Message": "Se encontraron CDPs",
  "Data": [
    {
      "vigencia": "2024",
      "numero_necesidad": "5",
      "estado_necesidad": "APROBADA",
      "numero_disponibilidad": "1",
      "estadocdp": "VIGENTE-AGOTADO",
      "nombre_dependencia": "IDEXUD",
      "id_necesidad": "4"
    }
]
}
```

**Comment by mau-oati** [comment]
**Duda**: Con Ajuste endpoint de número de disponibilidad de presupuesto_contractual_mid. Te refieres a cambiar el endpoint de "lista" o a otro ajuste?

**Comment by edwargl7** [comment]
Buen avance, pero no debemos usar _lista_, último punto de [Estrategia para el nombrado de recursos (definición de endpoints)](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md#estrategia-para-el-nombrado-de-recursos-definici%C3%B3n-de-endpoints) y primeros dos de [Ejemplos y aclaración](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md#ejemplos-y-aclaraci%C3%B3n)
![image](https://github.com/user-attachments/assets/08d5bafe-eb3f-43cf-80e0-e622dc2a7efc)
![image](https://github.com/user-attachments/assets/b9ec703d-9676-4391-b73e-25e526cc855b)

**Comment by edwargl7** [comment]
Resuelto PR del ajuste de proveedores, finalizado correctamente el ajuste en proveedores MID. Pendiente terminar ajustes en presupuesto.

**Comment by edwargl7** [comment]
Se realiza la revisión con @mau-oati donde se aclara que el ajuste se hizo siguiendo los lineamientos y se confirma en el PR solicitado. Se resuelve el PR y pendiente pruebas con nombres de endpoints actualizados.

**Comment by mau-oati** [comment]
Prueba **proveedor_contractual**

```json
// http://localhost:3000/cdps/numerosdisponibilidad?vigencia=2024&unidadEjecutora=02

{
  "Success": true,
  "Status": 200,
  "Message": "Se encontraron CDPs",
  "Data": [
    {
      "vigencia": "2024",
      "numero_necesidad": "5",
      "estado_necesidad": "APROBADA",
      "numero_disponibilidad": "1",
      "estadocdp": "VIGENTE-AGOTADO",
      "nombre_dependencia": "IDEXUD",
      "id_necesidad": "4"
    }
]
}
```

**Comment by edwargl7** [comment]
Finalizada la documentación de la Issue se da por finalizada.

**Comment by edwargl7** [comment]
Finalizados ajustes, se solicitan despliegues de los MIDs
