### ISSUE TITLE
Integración parámetros CRUD amparos microcliente de gestión contractual

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#99]
Se requiere realizar la integración del microservicio parámetros CRUD con el microcliente de [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) en el paso de _Garantía y Mecanismos de Cobertura del Riesgo_ basado en el [Mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdCjmD_A941CsLc_02iN66QBb5b5ehRT27kGZr1c6huaFg?e=fOdtS5).

**Sub Tareas**

- [x] Integración de amparos.
- [x] Ajuste unidad de medida según tipo de amparo seleccionado (solo para el tipo de amparo _Amparo de Responsabilidad Civil Extra- Contractual_ aplica SMLV (Cantidad)).
![image](https://github.com/user-attachments/assets/cfaf52f3-9c4a-4dd0-9684-8d4735b16410)

**Escenarios de pruebas**
- [x] Prueba correcta visualización de los amparos y la suficiencia según corresponda.

**Criterios de aceptación**

- [x] Documentación de las pruebas realizadas con la integración de parámetros crud.

**Requerimientos**

No aplica

**Material de apoyo**
- Imagen Mockup paso de Garantía y Mecanismos de Cobertura del Riesgo.
![image](https://github.com/user-attachments/assets/3e3ffe0e-b3fc-4a4d-8175-d34c338cdd13)

**Especificaciones técnicas**
1. Repositorio de microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
- [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
- Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microclientes**
- Arquitectura de aplicaciones - Microclientes (https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Adicional, por favor, agregar la validación para que porcentaje tenga la validación de mayor o igual a cero y menor o igual a cien y SMLV mayor a cero solamente @Lau2ri .

**Comment by Lau2ri** [comment]
Se realiza la integración de parámetros crud con Amparos, haciendo el llamado de estos parámetros en el select dentro de la tabla:

![image](https://github.com/user-attachments/assets/5bbabd54-b06d-4d7f-a815-4e0177a6d3b0)

Queda pendiente el ajuste de la unidad de medida según el tipo de amparo seleccionado y sus respectivas validaciones.

**Comment by Lau2ri** [comment]
Se hicieron los registros en parámetros crud de los dos parámetros de **Porcentaje** y **SMLV**, siendo éstos de tipo parámetro **Suficiencia Amparo** y de área tipo **Unidad de medida**

<img src="https://github.com/user-attachments/assets/9930fe43-7b2f-41d2-aa67-58359c16fb95" width=400>
<img src="https://github.com/user-attachments/assets/45007fa5-c555-45f4-87e8-495cae0c085c" width=310>

**Comment by Lau2ri** [comment]
Se realiza el ajuste para que se muestre en el input de suficiencia **Porcentaje** para cualquier selección de Amparo, y que para la selección de _Amparo de Responsabilidad Civil Extra- Contractual_ se muestre el input de **Cantidad de SMLV**, además se hicieron las validaciones para que en el porcentaje sólo deje ingresar números enteros del 1 al 100 y que para en salarios mínimos sólo deje ingresar valores enteros mayores a 0. 

https://github.com/user-attachments/assets/787ac74e-0a2b-4f47-a827-0e70b609341f

![Image](https://github.com/user-attachments/assets/cfd22a8f-b645-4727-b695-8c0dc69d08a8)

**Comment by edwargl7** [comment]
Buen trabajo, pendiente PR y validar si permite ingresar valores decimales.

**Comment by edwargl7** [comment]
Resuelto el PR.

**Comment by edwargl7** [comment]
Se confirma con @cjgonzalezp que el campo debe permitir agregar decimales.
